Repository canonical/ubuntu.com, pull requests merged in 2018-08, with the labels that each got.

#3845 Force all canonical tags as https
  templates/templates/base.html
Labels: Review: Code +1

#3786 eol d3 charts
  static/js/chart.js
  static/js/chartData.js
  static/sass/_pattern_chart.scss
  static/sass/styles.scss
  templates/info/release-end-of-life.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3853 Update for 16.04.5 release
  templates/download/alternative-downloads.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3854 BETA: Update for 16.04.5 release
  templates/download/alternative-downloads.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3856 Increase feed timeout to 2 seconds
  webapp/settings.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#3857 Make the alt download LTS link consistent
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#3858 Make the alt download LTS link consistent
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#3859 Update blog section styling on homepage
  templates/shared/_insights_news_strip.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3863 3838: Keep primary nav open on mobile screens
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3861 3839: Build German translated VMWare to OpenStack page
  navigation.yaml
  templates/cloud/contact-us.html
  templates/engage/de/vmware-to-openstack.html
  templates/shared/_cloud-contact-us-form-german.html
  templates/shared/forms/_country.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3868 Update image for production
  Dockerfile
  entrypoint
  package.json
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3869 Update image for production
  Dockerfile
  entrypoint
  package.json
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3876 3875: Remove reference to global-nav module in build script
  package.json
Labels: Review: Code +1, Review: QA +1

#3870 Keep URL parameters in link events
  static/js/navigation.js
Labels: Review: Code +1, Review: QA +1

#3872 Use 3 workers for beta
  .gitignore
  Dockerfile
  entrypoint
Labels: Review: Code +1, Review: QA +1

#3871 Use 3 workers
  Dockerfile
  entrypoint
Labels: Review: Code +1, Review: QA +1

#3864 Move release EOL page to /about/release-cycle and update copy
  navigation.yaml
  redirects.yaml
  templates/about/release-cycle.html
  templates/info/release-end-of-life.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3865 BETA: Update FCB datasheet link
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: QA +1

#3866 Update FCB datasheet link
  templates/cloud/foundation-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3867 3862: Remove global and primary navigation flyouts from print stylesheet
  static/sass/print.scss
Labels: Review: Code +1, Review: QA +1

#3898 Alternative Ubuntu Server installer download link with point
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#3899 Alternative Ubuntu Server installer download link with point
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#3896 3873: Add small padding to th and highlight cells
  static/sass/_pattern_table.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3900 Remove margin from search reset button
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: QA +1

#3890 Fix search error: Handle missing 'searchInformation'
  templates/500.html
  templates/search.html
  webapp/views.py
Labels: Review: Code needed, Review: QA needed

#3908 3889: Add opacity animation to primary nav overlay
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#3907 3902: Fix global nav overlay resize bug
  static/sass/_pattern_global-nav.scss
Labels: Review: Code +1, Review: QA +1

#3911 Fix search template
  templates/500.html
  templates/search.html
Labels: Review: Code +1, Review: QA +1

#3913 Fix overlay preventing interaction with page
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#3910 Added a landing page for the AI/ML webinar
  templates/engage/ai-ml-ubuntu.html
  templates/takeovers/_ai_webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3921 Mongoose no more!
  templates/ai/contact-us.html
  templates/containers/contact-us.html
  templates/core/contact-us.html
  templates/desktop/contact-us.html
  templates/download/server/s390x.html
  templates/download/server/thank-you-linuxone.html
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook_maas.html
  templates/kubernetes/contact-us.html
  templates/openstack/contact-us.html
  templates/server/contact-us.html
  templates/support/contact-us.html
  templates/templates/_navigation-developer-h.html
  templates/templates/global-nav.html
Labels: Review: Code needed, Review: QA needed

#3916 Redirect the most common 404 pages - part 1
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#3923 Add k8s datasheet and styling
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3924 Update the navigation menus for developer and enterprise
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3937 Point "Engage" heading at /resources
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#3936 Only use development Talisker settings in local development
  .env
  entrypoint
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3912 Update, move webinar embed
  templates/engage/de/vmware-to-openstack.html
  templates/engage/vmware-to-openstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3914 Add appstore whitepaper landing page
  templates/engage/iot-business-model.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3929 Build the Tackling the IoT takeover
  templates/index.html
  templates/takeovers/_tackling_iot.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3932 Copy updates to kubernetes index page
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3943 Update the appstore whitepaper return URL
  templates/engage/iot-business-model.html
Labels: Review: Code +1, Review: QA +1

#3947 Be more accurate about statsd requirement
  requirements.txt
Labels: Review: Code +1

#3944 Corrects conjure-up link
  templates/shared/_systems-management-tool.html
  templates/shared/_systems_management_tool.html
Labels: Review: Code +1, Review: QA +1

#3956 Update openstack packages pricing
  templates/shared/pricing/_openstack-packages.html
Labels: Review: Code +1, Review: QA +1

#3955 Update juju photo on public cloud page
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3946 Rotate takeovers
  templates/engage/ai-ml-ubuntu.html
  templates/index.html
  templates/takeovers/_ai_webinar.html
  templates/takeovers/_rigado_webinar.html
  templates/takeovers/_tackling_iot.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3909 3906: Hotfix for abbr styling
  static/sass/styles.scss
  templates/download/desktop/index.html
  templates/download/server/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3959 Removal of the Rigado takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3965 Set up D3 and create basic JS helper functions for desktop stats page
  static/js/desktopStatistics.js
  static/js/dummyData.js
  static/js/stickyNav.js
  static/sass/_pattern_desktop-statistics.scss
  static/sass/styles.scss
  templates/desktop/statistics.html
Labels: Review: Code +1, Review: QA +1

#3979 Moving the webinar up on the page EVEN HIGHER :)
  templates/engage/de/vmware-to-openstack.html
Labels: Review: Code +1, Review: QA +1

#3981 Update the content to the plans and pricing page
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-consulting.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#3987 3958: Build Financial Services Month takeover
  static/sass/styles.scss
  static/sass/takeovers/_financial-services.scss
  templates/index.html
  templates/takeovers/_financial-services.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX needed
