Repository canonical/ubuntu.com, pull requests merged in 2018-03, with the labels that each got.

#2767 Add ids for network installer and bittorrents on /download/alternate-downloads
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#2765 Minor updates to /download/cloud
  templates/download/cloud/index.html
Labels: Review: Code +1, Review: QA +1

#2758 Updated /info/release-end-of-life charts and tables
  templates/info/release-end-of-life.html
Labels: Review: Code +1, Review: QA +1

#2760 2754: Build /openstack/install/build-openstack page
  redirects.yaml
  templates/openstack/install/build-openstack.html
  templates/shared/contextual_footers/_cloud_bootstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2759 2753: Build openstack/install/try-openstack page
  redirects.yaml
  templates/openstack/install/try-openstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2757 2649: Build beta global nav
  static/sass/_pattern_global-nav.scss
  templates/templates/base.html
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2763 Update site with 16.04.4 point release
  templates/download/core/intel-nuc.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#2771 2651: Build beta.ubuntu.com secondary nav
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation-download.html
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2772 2755: Build /openstack/install page
  navigation.yaml
  templates/download/server/_other-ways.html
  templates/openstack/install/index.html
  templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2750 Updated Ubuntu Advantage service description
  static/sass/_pattern_lists.scss
  templates/legal/bootstack/2015-07-01-service-description.html
  templates/legal/bootstack/service-description.html
  templates/legal/shared/_appendix-management-escalation.html
  templates/legal/shared/_appendix-management-escalation_toc.html
  templates/legal/shared/_appendix-support-process.html
  templates/legal/shared/_appendix-support-process_toc.html
  templates/legal/shared/_appendix-support-scope.html
  templates/legal/shared/_appendix-support-scope_toc.html
  templates/legal/shared/_severity-levels.html
  templates/legal/ubuntu-advantage/service-description.html
Labels: Review: Code +1, Review: QA +1

#2774 Update OpenStack on /info/release-end-of-life
  templates/info/release-end-of-life.html
Labels: Review: Code +1, Review: QA +1

#2777 2664: Build /openstack section from /cloud section
  navigation.yaml
  redirects.yaml
  templates/cloud/index.html
  templates/desktop/snappy.html
  templates/juju/_base_juju.html
  templates/juju/index.html
  templates/openstack/_base_openstack.html
  templates/openstack/contact-us.html
  templates/openstack/foundation-cloud.html
  templates/openstack/index.html
  templates/openstack/install/build-openstack.html
  templates/openstack/install/index.html
  templates/openstack/install/try-openstack.html
  templates/openstack/managed-cloud.html
  templates/openstack/newsletter-thank-you.html
  templates/openstack/partners.html
  templates/openstack/shared/_events_overview.html
  templates/openstack/shared/_guest-list.html
  templates/openstack/shared/_openstack-aws-pie-chart.html
  templates/openstack/shared/_openstack-pie-chart.html
  templates/openstack/shared/_openstack_clients.html
  templates/openstack/storage.html
  templates/openstack/thank-you.html
  templates/openstack/training.html
  templates/public-cloud/index.html
  templates/shared/contextual_footers/_cloud_contact_us.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2778 Update copy in beta download tab
  templates/templates/_navigation-download.html
Labels: Review: Code +1, Review: QA +1

#2779 Bugfix/use correct styles on download menu third col
  templates/templates/_navigation-download.html
Labels: Review: Code +1, Review: QA +1

#2782 More resilient /resources
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#2792 Additional clean-ups to further reading feeds
  templates/cloud/index.html
  templates/download/server/_other-ways.html
  templates/index.html
  templates/shared/_insights_news_strip.html
  templates/shared/contextual_footers/_cloud_further_reading.html
  templates/shared/contextual_footers/_desktop_further_reading.html
  templates/shared/contextual_footers/_iot_further_reading.html
  templates/shared/contextual_footers/_security_further_reading.html
  templates/shared/contextual_footers/_telco_further_reading.html
  templates/templates/_further_reading_links.html
Labels: Review: Code +1, Review: QA +1

#2796 update the homepage takeover to iot business whitepaper
  templates/index.html
  templates/takeovers/_iot-business.html
  templates/takeovers/takeunders/_ubuntu-product-month.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2801 Add VirtIO Drivers to pricing page
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_ua-server-support.html
Labels: Review: Code +1, Review: QA +1

#2807 Service Description Header cleanup
  templates/legal/bootstack/service-description.html
  templates/legal/ubuntu-advantage/service-description.html
Labels: Review: Code +1, Review: QA +1

#2808 Updated strip color and added highlights
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_landscape.html
  templates/shared/pricing/_openstack-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_storage-support.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#2804 Remove ‘Ongoing enterprise support for Kubernetes after 30 days is optional.’
  templates/shared/pricing/_kubernetes-consulting.html
Labels: Review: Code +1, Review: QA +1

#2803 Add snapd installation instructions to BETA @ /openstack/install/try-openstack
  templates/openstack/install/try-openstack.html
Labels: Review: Code +1, Review: QA +1

#2812 Updated further reading links on /legal section
  templates/shared/contextual_footers/_cloud_further_reading.html
  templates/shared/contextual_footers/_further_reading.html
Labels: Review: Code +1, Review: QA +1

#2802 Add snap installation instructions on try-openstack
  templates/download/cloud/try-openstack.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2776 Update logo clouds to use links
  static/sass/_pattern_inline-images.scss
  templates/openstack/foundation-cloud.html
  templates/shared/_partner-logos.html
Labels: Review: Code +1, Review: QA +1

#2815 Removed max-width from footer content
  static/sass/_pattern_footer.scss
Labels: Review: Code +1, Review: QA +1

#2814 Fix insight spotlight posts with sticky ones
  templates/cloud/index.html
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#2822 Use a white bg for the build OpenStack instructions strip
  templates/download/cloud/build-openstack.html
Labels: Review: QA needed

#2819 Cleaned-up /pricing tables to look nicer
  templates/cloud/foundation-cloud/index.html
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_kubernetes-managed.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_storage-support.html
  templates/shared/pricing/_ua-desktop-support.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/shared/pricing/_ua-server-support.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#2832 Simplify _insights_news_strip include
  templates/cloud/index.html
  templates/index.html
  templates/shared/_insights_news_strip.html
Labels: Review: Code +1, Review: QA +1

#2821 Fixed aspect ratios on logo clouds
  static/sass/_pattern_inline-images.scss
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#2831 Build Kubernetes Month takeover
  static/sass/styles.scss
  static/sass/takeovers/_kubernetes-month.scss
  templates/index.html
  templates/takeovers/_kubernetes-month.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2820 White background for instructions on /download/server/provisioning
  templates/download/server/provisioning.html
Labels: Review: Code +1, Review: QA +1

#2835 Update kubernetes takeover copy
  templates/takeovers/_kubernetes-month.html
Labels: Review: Code +1, Review: UX +1

#2833 2740: Add animation to beta nav dropdown
  static/js/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation-community.html
  templates/templates/_navigation-developer.html
  templates/templates/_navigation-download.html
  templates/templates/_navigation-enterprise.html
  templates/templates/_navigation.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2841 Updated /resources to use correct insights url
  templates/resources/index.html
Labels: Review: Code +1, Review: QA +1

#2842 Update global nav version
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2851 Add trademarks page
  navigation.yaml
  templates/legal/trademarks/index.html
Labels: Review: Code +1, Review: QA +1

#2852 Added Snap Enterprise Proxy to /iot/appstore
  static/sass/_pattern_contribution.scss
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2844 Add initial copy for data protect section
  templates/contact-us/index.html
Labels: Review: Code +1, Review: QA +1

#2849 Link to data protection page in footer
  navigation.yaml
  templates/legal/data-protection/index.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1
