Repository canonical/ubuntu.com, pull requests merged in 2018-02, with the labels that each got.

#2687 Make feed requests timeout in 1.2 seconds
  webapp/settings.py
Labels: Review: Code +1, Review: QA +1

#2690 Basic prometheus metrics on ports 9090-9099
  .gitignore
  .sass-lint.yml
  package.json
  requirements.txt
  run
  webapp/settings.py
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#2691 Export prometheus metrics for feed requests
  requirements.txt
  webapp/settings.py
Labels: Review: Code +1, Review: QA +1

#2641 Replaced "live-migrate" to "copy" on /containers/lxd
  templates/containers/lxd.html
Labels: Review: Code needed, Review: QA needed

#2689 2668: Create /download/core/raspberry-pi-2-3 page
  static/sass/styles.scss
  templates/download/core/_boot-tips-strip.html
  templates/download/core/_first-boot-setup.html
  templates/download/core/_flash-image.html
  templates/download/core/_install-snaps-strip.html
  templates/download/core/_login.html
  templates/download/core/_setup-ubuntu-sso.html
  templates/download/core/raspberry-pi-2-3.html
  templates/download/shared/_get-ebook-security.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2692 2685: Update /community page
  redirects.yaml
  templates/about/about-ubuntu/flavours.html
  templates/community/_base_community.html
  templates/community/index.html
  templates/download/flavours.html
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1

#2710 2662: Move /about/about-ubuntu/licensing to /licensing
  redirects.yaml
  templates/licensing/_base_licensing.html
  templates/licensing/index.html
Labels: Review: Code +1, Review: QA +1

#2711 Upgrade to get-feeds v0.2.2 - more accurate timing
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2698 2654: Move /about/about-ubuntu/conduct to /community/code-of-conduct
  redirects.yaml
  templates/community/code-of-conduct.html
Labels: Review: Code +1, Review: QA +1

#2697 2655: Move /about/about-ubuntu/our-philosophy to /community/mission
  redirects.yaml
  templates/community/mission.html
Labels: Review: Code +1, Review: QA +1

#2705 2676: Create /download/core/kvm page
  templates/download/core/kvm.html
Labels: Review: Code +1, Review: QA +1

#2703 2674: Create /download/core/intel-nuc page
  templates/download/core/intel-nuc.html
Labels: Review: Code +1, Review: QA +1

#2702 2673: Create /download/core/qualcomm-dragonboard-410c page
  templates/download/core/qualcomm-dragonboard-410c.html
Labels: Review: Code +1, Review: QA +1

#2700 2670: Create /download/core/orange-pi-zero page
  templates/download/core/orange-pi-zero.html
Labels: Review: Code +1, Review: QA +1

#2701 2672: Create /download/core/samsung-artik-5-10 page
  templates/download/core/samsung-artik-5-10.html
Labels: Review: Code +1, Review: QA +1

#2704 2675: Create /download/core/intel-joule page
  templates/download/core/intel-joule.html
Labels: Review: Code +1, Review: QA +1

#2699 2669: Create /download/core/raspberry-pi-compute-module-3 page
  templates/download/core/raspberry-pi-compute-module-3.html
Labels: Review: Code +1, Review: QA +1

#2693 2660: Move /about/canonical-and-ubuntu to /community/canonical
  redirects.yaml
  templates/about/canonical-and-ubuntu.html
  templates/community/canonical.html
Labels: Review: Code +1, Review: QA +1

#2713 2688: Update /about page to reflect new /community pages
  templates/about/index.html
Labels: Review: Code +1, Review: QA +1

#2694 2659: Move /about/ubuntu-and-debian to /community/debian
  redirects.yaml
  templates/about/about-ubuntu/ubuntu-and-debian.html
  templates/community/debian.html
Labels: Review: Code +1, Review: QA +1

#2695 2657: Move /about/about-ubuntu/diversity to /community/diversity
  redirects.yaml
  templates/community/code-of-conduct.html
  templates/community/diversity.html
Labels: Review: Code +1, Review: QA +1

#2696 2656: Move /about/about-ubuntu/governance to /community/governance
  redirects.yaml
  templates/about/about-ubuntu/governance.html
  templates/community/governance.html
Labels: Review: Code +1, Review: QA +1

#2717 Upgrade to v2.7.0 of canonical-webteam tooling
  .gitignore
  .sass-lint.yml
  run
Labels: Review: Code +1, Review: QA +1

#2706 2671: Create /download/core/up-squared-iot-grove page
  templates/download/core/up-squared-iot-grove.html
Labels: Review: Code +1, Review: QA +1

#2712 Release new /download/core pages
  navigation.yaml
  static/sass/styles.scss
  templates/download/core/index.html
  templates/download/core/intel-joule.html
  templates/download/core/intel-nuc.html
  templates/download/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2719 Simpler prometheus buckets
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2716 Updated the BootStack service description
  templates/legal/bootstack/2015-07-01-service-description.html
  templates/legal/bootstack/service-description.html
  templates/legal/shared/_appendix-management-escalation.html
  templates/legal/shared/_appendix-support-process.html
  templates/legal/shared/_severity-levels.html
Labels: Review: Code +1, Review: QA +1

#2720 Build community section
  navigation.yaml
  redirects.yaml
  templates/about/about-ubuntu/flavours.html
  templates/about/about-ubuntu/governance.html
  templates/about/about-ubuntu/index.html
  templates/about/about-ubuntu/ubuntu-and-debian.html
  templates/about/canonical-and-ubuntu.html
  templates/about/index.html
  templates/community/_base_community.html
  templates/community/canonical.html
  templates/community/code-of-conduct.html
  templates/community/debian.html
  templates/community/diversity.html
  templates/community/governance.html
  templates/community/index.html
  templates/community/mission.html
  templates/download/flavours.html
  templates/download/index.html
  templates/licensing/_base_licensing.html
  templates/licensing/index.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2745 Moved ebook on /download/core/board pages
  navigation.yaml
  templates/download/core/intel-joule.html
  templates/download/core/intel-nuc.html
  templates/download/core/kvm.html
  templates/download/core/orange-pi-zero.html
  templates/download/core/qualcomm-dragonboard-410c.html
  templates/download/core/raspberry-pi-2-3.html
  templates/download/core/raspberry-pi-compute-module-3.html
  templates/download/core/samsung-artik-5-10.html
  templates/download/core/up-squared-iot-grove.html
  templates/download/shared/_get-ebook-security.html
Labels: Review: Code +1, Review: QA +1

#2747 Updated and moved contact-us pages
  navigation.yaml
  redirects.yaml
  templates/about/contact-us/index.html
  templates/about/index.html
  templates/contact-us/base_contact-us.html
  templates/contact-us/form/index.html
  templates/contact-us/form/thank-you.html
  templates/contact-us/index.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2727 2650: Build beta.ubuntu.com primary nav
  package.json
  static/sass/_global-settings.scss
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
  static/sass/_settings_colors.scss
  static/sass/styles.scss
  templates/templates/_global_nav.html
  templates/templates/_nav_community.html
  templates/templates/_nav_developer.html
  templates/templates/_nav_download.html
  templates/templates/_nav_enterprise.html
  templates/templates/_nav_global.html
  templates/templates/_navigation-community.html
  templates/templates/_navigation-developer.html
  templates/templates/_navigation-download.html
  templates/templates/_navigation-enterprise.html
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/templates/global-nav.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2761 Swap uappexplorer link for snap store.
  templates/desktop/snappy.html
Labels: Review: Code +1, Review: QA +1

#2752 2730: Update /download/cloud page
  navigation.yaml
  static/sass/_pattern_card.scss
  templates/download/cloud/index.html
  templates/shared/contextual_footers/_download_cloud_ubuntu_advantage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1
