Repository canonical/ubuntu.com, pull requests merged in 2018-09, with the labels that each got.

#3994 Align Talisker with other projects
  entrypoint
Labels: Review: Code +1

#3978 New finserv month landing page
  static/sass/styles.scss
  static/sass/takeovers/_financial-services.scss
  templates/engage/financial-services-month.html
  templates/index.html
  templates/takeovers/_financial-services.html
Labels: Priority: High, Review: Code +1, Review: Design +1, Review: UX +1

#3986 Update the content to the enterprise menu
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3985 Update the content to the service description page
  templates/legal/managed-services/2018-02-15-service-description.html
  templates/legal/shared/_appendix-management-escalation.html
  templates/legal/shared/_appendix-management-escalation_toc.html
  templates/legal/shared/_appendix-support-process.html
  templates/legal/shared/_appendix-support-scope.html
  templates/legal/shared/_appendix-support-scope_toc.html
  templates/legal/ubuntu-advantage/service-description-ja/2017-02-09.html
  templates/legal/ubuntu-advantage/service-description-ja/index.html
  templates/legal/ubuntu-advantage/service-description.html
Labels: Review: Code +1, Review: QA +1

#4002 Misc fixes on IoT takeover and Finserv lp
  templates/engage/financial-services-month.html
  templates/takeovers/_tackling_iot.html
Labels: Review: Code +1, Review: QA +1

#4006 Fix dropdown z-index
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#4009 UTMize de takeover
  templates/takeovers/_de-vmware-to-os.html
Labels: Review: Code +1

#4014 Cleanup UASD
  templates/legal/managed-services/service-description.html
  templates/legal/shared/_appendix-management-escalation.html
  templates/legal/shared/_appendix-management-escalation_toc.html
  templates/legal/shared/_appendix-support-process.html
  templates/legal/shared/_appendix-support-scope.html
  templates/legal/ubuntu-advantage/service-description.html
Labels: Review: Code +1, Review: QA +1

#4020 Support filtering search by site
  templates/search.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#3996 lp - multi-cloud guide
  templates/engage/multi-cloud-guide.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4021 Fix SD TOC link typo
  templates/legal/ubuntu-advantage/service-description.html
Labels: Review: Code +1, Review: QA +1

#4016 Multicloud operations takeover
  templates/index.html
  templates/takeovers/_multicloud-operations.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4030 Fix when articles are down
  templates/shared/_insights_news_strip.html
Labels: Review: Code +1, Review: QA +1

#4022 Create a standard include for landing page forms
  templates/engage/multi-cloud-guide.html
  templates/shared/forms/_landing_page_default.html
Labels: Review: Code +1, Review: QA +1

#4034 Rotate the DE takeover with Financial Services takeover
  templates/index_de.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4018 OpenStack Made Easy German Landing Page
  templates/engage/de/openstack-made-easy.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4013 Cleanup /support page
  templates/shared/_systems-management-tool.html
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4015 Updates/fixes to release-cycle page
  static/js/chart.js
  static/js/chartData.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4045 adding a u-no-print style to the print stylesheet
  static/sass/print.scss
  templates/shared/_feedback.html
Labels: Review: Code +1, Review: QA +1

#4028 Updated the text of /kubernetes/install
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4047 Change order of older versions on "Managed Services description" page
  templates/legal/managed-services/service-description.html
Labels: Review: Code +1

#4043 Vmware to openstack de
  templates/engage/de/vmware-to-openstack.html
Labels: Review: Code +1, Review: QA +1

#4035 New version of the multi-cloud landing page for AB testing
  templates/engage/multi-cloud-guide2.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4036 New version of IoT business model page for testing
  templates/engage/iot-business-model2.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4024 Created /about/packages page
  navigation.yaml
  templates/about/packages.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4011 Robot OS landing page
  templates/engage/robot-operating-system-choice.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4048 fixed display of card on /resources for topic tabs
  templates/resources/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4053 Update the Linkedin link in the footer
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#4055 Fix form id - Openstack Made Easy DE
  templates/engage/de/openstack-made-easy.html
Labels: Review: Code needed

#4054 Updates to the plans and pricing page content
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#4056 Update to ubuntu.com/about page
  templates/about/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4061 Added whitepaper resource on app store page
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: QA +1

#4063 Added ua datasheet to support page
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4064 “Plans and pricing”: Tweaks heading levels
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#4080 Use form include in existing (en) landing pages
  templates/engage/cloud-economics.html
  templates/engage/fingbox-case-study.html
  templates/engage/iot-business-model.html
Labels: Review: Code +1, Review: QA +1

#4085 Update text CTA on DE webinar page
  templates/engage/de/vmware-to-openstack.html
Labels: Review: Code +1, Review: QA +1

#4084 Add impression events for takeovers, switch to absolute URLs inside events
  static/js/navigation.js
Labels: Review: Code +1

#4076 Version of server download
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook_v1.html
  templates/download/shared/_get_ebook_v2.html
  templates/download/shared/_get_ebook_v3.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4092 Add custom ids to MAAS ebook sections versions
  templates/download/shared/_get_ebook_v1.html
  templates/download/shared/_get_ebook_v2.html
  templates/download/shared/_get_ebook_v3.html
Labels: Review: Code +1
