Repository canonical/ubuntu.com, pull requests merged in 2018-04, with the labels that each got.

#2848 Build data privacy form
  navigation.yaml
  static/sass/_pattern_contribution.scss
  templates/internet-of-things/appstore.html
  templates/legal/data-privacy-enquiry/index.html
  templates/legal/terms-and-policies/thank-you.html
Labels: Review: Code +1, Review: QA +1

#2856 One redirect for all USN URL versions
  .travis.yml
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#2863 Remove intel section from partners page
  templates/desktop/partners.html
Labels: Review: Code +1, Review: QA +1

#2898 Fix compact pull quote styling
  static/sass/_pattern_pull_quotes.scss
  static/sass/styles.scss
  templates/desktop/education.html
  templates/desktop/enterprise.html
  templates/desktop/government.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/index.html
  templates/internet-of-things/robotics.html
  templates/server/hyperscale.html
  templates/telecommunications/index.html
Labels: Review: Code needed, Review: Design needed, Review: QA needed

#2864 Revert "Update terms boxes"
  navigation.yaml
  templates/contact-us/index.html
  templates/legal/data-privacy-enquiry/index.html
  templates/legal/data-protection/index.html
  templates/legal/index.html
  templates/legal/terms-and-policies/thank-you.html
  templates/legal/trademarks/index.html
  templates/templates/footer.html
Labels: Review: Code +1

#2903 2861 short term pages
  navigation.yaml
  redirects.yaml
  templates/download/server/linuxone.html
  templates/download/server/thank-you-linuxone.html
  templates/legal/bootstack/index.html
  templates/legal/service-terms/2015-06-24.html
  templates/legal/service-terms/2015-09-09.html
  templates/legal/service-terms/2016-05-20.html
  templates/legal/service-terms/2016-06-24.html
  templates/legal/service-terms/index.html
  templates/legal/service-terms/ja.html
  templates/ubuntu-ia.csv
  templates/ubuntu-ia.txt
Labels: Review: Code +1, Review: QA +1

#2899 Fix styling issues with inline definition list
  static/sass/_pattern_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2915 copy updates to /server for 18.04
  templates/server/index.html
Labels: Review: Code +1, Review: QA +1

#2908 Remove gnome from flavours page
  templates/download/flavours.html
Labels: Review: Code +1, Review: QA +1

#2913 Update apps to snaps
  templates/desktop/features.html
Labels: Review: Code +1, Review: QA +1

#2919 2905 remove snappy page and redirect
  navigation.yaml
  redirects.yaml
  templates/desktop/snappy.html
Labels: Review: Code +1, Review: QA +1

#2906 453 move ebook
  templates/download/server/provisioning.html
Labels: Review: Code +1, Review: QA +1

#2923 Remove ebook section from server download thank you page
  templates/download/server/thank-you.html
Labels: Review: Code +1, Review: QA +1

#2917 Updated the kernel image and table for /info/release-end-of-life
  templates/info/release-end-of-life.html
Labels: Review: Code +1, Review: QA +1

#2925 conform p-code-snippet instances to correct vanilla markup
  templates/download/cloud/build-openstack.html
  templates/download/cloud/try-openstack.html
  templates/download/server/provisioning.html
  templates/support/esm.html
Labels: Review: Code +1

#2928 Fix resources tab alignment
  static/sass/_pattern_tabs.scss
  templates/resources/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2921 Update download page as per copy doc
  templates/download/desktop/_other-ways.html
  templates/download/desktop/index.html
Labels: Review: Code +1, Review: QA +1

#2933 Update Gateways page
  templates/internet-of-things/gateways.html
Labels: Review: Code +1, Review: QA +1

#2934 1675: Fix styling issues with bespoke heading + icon markup/scss
  static/sass/_pattern_heading-icon.scss
  static/sass/_pattern_link.scss
  static/sass/styles.scss
  templates/cloud/managed-cloud.html
  templates/desktop/1710.html
  templates/financial-services/index.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/robotics.html
  templates/kubernetes/index.html
  templates/kubernetes/managed.html
  templates/security/index.html
  templates/server/maas/index.html
  templates/shared/_resources_openstack.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2932 Ubuntu flavours
  templates/download/flavours.html
Labels: Review: Code +1, Review: QA +1

#2945 Build 18.04 release takeover
  static/sass/styles.scss
  static/sass/takeovers/_1804-release.scss
  templates/index.html
  templates/takeovers/_1804-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2941 Implement new download page design
  static/sass/_pattern_card.scss
  templates/download/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2943 Update kubernetes copy
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#2949 Updated download path for IBM X
  templates/download/server/index.html
  templates/download/server/linuxone-signup-thank-you.html
  templates/download/server/linuxone.html
  templates/download/server/thank-you-linuxone.html
  templates/ubuntu-ia.csv
  templates/ubuntu-ia.txt
Labels: Review: Code +1, Review: QA +1

#2940 Fix styles of bottom section of manage cloud page
  templates/cloud/managed-cloud.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2950 Fix table styling on /support/plans-and-pricing page
  static/sass/_pattern_table.scss
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_kubernetes-managed.html
  templates/shared/pricing/_landscape.html
  templates/shared/pricing/_openstack-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_storage-support.html
  templates/shared/pricing/_ua-desktop-support.html
  templates/shared/pricing/_ua-server-support.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2939 Rename BootStack legal section to managed-services
  navigation.yaml
  redirects.yaml
  templates/legal/bootstack/index.html
  templates/legal/index.html
  templates/legal/managed-services/2015-07-01-service-description.html
  templates/legal/managed-services/2018-02-15-service-description.html
  templates/legal/managed-services/index.html
  templates/legal/managed-services/privacy.html
  templates/legal/managed-services/service-description.html
  templates/legal/short-terms/2015-06-24.html
  templates/legal/short-terms/2015-09-09.html
  templates/legal/short-terms/2016-05-20.html
  templates/legal/short-terms/2016-06-24.html
  templates/legal/short-terms/index.html
  templates/legal/short-terms/ja.html
  templates/ubuntu-ia.csv
  templates/ubuntu-ia.txt
  test-redirects.pl
Labels: Review: Code +1, Review: QA +1

#2953 Update enterprise nav
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation-community.html
  templates/templates/_navigation-developer.html
  templates/templates/_navigation-download.html
  templates/templates/_navigation-enterprise.html
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#2954 Updated OpenStack section
  navigation.yaml
  redirects.yaml
  templates/openstack/consulting.html
  templates/openstack/developer.html
  templates/openstack/index.html
  templates/openstack/install.html
  templates/openstack/install/index.html
  templates/openstack/managed.html
  templates/shared/contextual_footers/_cloud_bootstack.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#2944 Update homepage screenshot
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2955 Bespoke styling fixes for Vanilla 1.7.0-beta
  package.json
  static/sass/_pattern_link.scss
  static/sass/_pattern_matrix.scss
  static/sass/_pattern_pull_quotes.scss
  static/sass/styles.scss
  templates/download/core/index.html
  templates/internet-of-things/appstore.html
  templates/resources/index.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2959 Add quotation to gateways page
  templates/internet-of-things/gateways.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2961 Update desktop overview page
  templates/desktop/index.html
  templates/shared/contextual_footers/_desktop_download.html
  templates/shared/contextual_footers/_desktop_flavours.html
  templates/shared/contextual_footers/_support-image.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2970 Update linuxone thankyou page
  navigation.yaml
  redirects.yaml
  templates/download/server/thank-you-linuxone.html
  templates/download/server/thank-you-s390x.html
Labels: Review: Code +1, Review: QA +1

#2969 Update urls for /download/iot and break to more detailed pages
  navigation.yaml
  redirects.yaml
  templates/download/core/index.html
  templates/download/iot/_boot-tips-strip.html
  templates/download/iot/_first-boot-setup.html
  templates/download/iot/_flash-image.html
  templates/download/iot/_install-snaps-strip.html
  templates/download/iot/_login.html
  templates/download/iot/_setup-ubuntu-sso.html
  templates/download/iot/index.html
  templates/download/iot/intel-joule-desktop.html
  templates/download/iot/intel-joule.html
  templates/download/iot/intel-nuc-desktop.html
  templates/download/iot/intel-nuc.html
  templates/download/iot/kvm.html
  templates/download/iot/orange-pi-zero.html
  templates/download/iot/qualcomm-dragonboard-410c.html
  templates/download/iot/raspberry-pi-2-3.html
  templates/download/iot/raspberry-pi-compute-module-3.html
  templates/download/iot/samsung-artik-5-10-server.html
  templates/download/iot/samsung-artik-5-10.html
  templates/download/iot/up-squared-iot-grove-server.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2951 Partners page
  templates/desktop/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2967 Update alternative downloads page
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2980 Fixes marketo redirect on linuxone download
  templates/download/server/linuxone.html
Labels: Priority: Critical, Review: Code +1, Review: QA +1

#2971 Update download desktop page
  templates/download/desktop/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2979 Update screenshot image
  templates/cloud/public-cloud.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2981 Update livepatch page
  templates/server/livepatch.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2983 Rebase from master
  navigation.yaml
  redirects.yaml
  templates/cloud/managed-cloud.html
  templates/download/cloud/build-openstack.html
  templates/download/cloud/try-openstack.html
  templates/download/core/index.html
  templates/download/iot/_boot-tips-strip.html
  templates/download/iot/_first-boot-setup.html
  templates/download/iot/_flash-image.html
  templates/download/iot/_install-snaps-strip.html
  templates/download/iot/_login.html
  templates/download/iot/_setup-ubuntu-sso.html
  templates/download/iot/index.html
  templates/download/iot/intel-joule-desktop.html
  templates/download/iot/intel-joule.html
  templates/download/iot/intel-nuc-desktop.html
  templates/download/iot/intel-nuc.html
  templates/download/iot/kvm.html
  templates/download/iot/orange-pi-zero.html
  templates/download/iot/qualcomm-dragonboard-410c.html
  templates/download/iot/raspberry-pi-2-3.html
  templates/download/iot/raspberry-pi-compute-module-3.html
  templates/download/iot/samsung-artik-5-10-server.html
  templates/download/iot/samsung-artik-5-10.html
  templates/download/iot/up-squared-iot-grove-server.html
  templates/download/server/index.html
  templates/download/server/linuxone-signup-thank-you.html
  templates/download/server/linuxone.html
  templates/download/server/provisioning.html
  templates/info/release-end-of-life.html
  templates/internet-of-things/gateways.html
  templates/kubernetes/index.html
  templates/legal/bootstack/index.html
  templates/legal/index.html
  templates/legal/managed-services/2015-07-01-service-description.html
  templates/legal/managed-services/2018-02-15-service-description.html
  templates/legal/managed-services/index.html
  templates/legal/managed-services/privacy.html
  templates/legal/managed-services/service-description.html
  templates/legal/short-terms/2015-06-24.html
  templates/legal/short-terms/2015-09-09.html
  templates/legal/short-terms/2016-05-20.html
  templates/legal/short-terms/2016-06-24.html
  templates/legal/short-terms/index.html
  templates/legal/short-terms/ja.html
  templates/support/esm.html
  templates/takeovers/_kubernetes-month.html
  templates/ubuntu-ia.csv
  templates/ubuntu-ia.txt
  test-redirects.pl
Labels: Review: Code +1

#2984 Update redirect url for linuxone download
  templates/download/server/linuxone.html
Labels: Review: Code +1, Review: QA +1

#2987 Copy updates on /download/cloud/build-openstack for 18.04
  templates/download/cloud/build-openstack.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2988 Update /containers/lxd page - 18.04
  templates/containers/lxd.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2989 Update /download/server page - 18.04
  templates/download/server/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2991 Update /download/server/s390x - 18.04
  navigation.yaml
  redirects.yaml
  templates/download/server/s390x.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2985 new /desktop/organisations page - 18.04
  navigation.yaml
  redirects.yaml
  static/sass/styles.scss
  templates/desktop/developers.html
  templates/desktop/organisations.html
  templates/desktop/ubuntu-in-organisations.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX needed

#3019 /cloud/storage copy update
  templates/cloud/storage.html
Labels: Review: Code +1, Review: QA +1

#3022 Legal/T&C'/contact-us - Remove bullet points in form
  templates/legal/terms-and-policies/contact-us.html
Labels: Review: Code +1, Review: QA +1

#3021 /download/cloud/try-openstack - update copy
  templates/download/cloud/try-openstack.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3025 Update copy on organisations page
  templates/desktop/organisations.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3027 Remove link as per copy doc
  templates/download/desktop/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3026 Update copy for provisioning page
  templates/download/server/provisioning.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3017 /desktop remove "benefits for all industry sectors" strip
  templates/desktop/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3028 Remove 1710 page
  deleted.yaml
  navigation.yaml
  templates/desktop/1710.html
Labels: Review: Code needed, Review: QA +1, Review: UX +1

#3030 Add related boxes to iot contact us page
  templates/internet-of-things/contact-us.html
  templates/internet-of-things/thank-you.html
  templates/shared/_cloud-contact-us-form.html
  templates/shared/forms/_desktop_help.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3015 Copy doc changes for /telecommunications for 18.04
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3036 Update livepatch copy
  templates/server/livepatch.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3034 changed hero link to use inverted style
  templates/support/esm.html
Labels: Review: Code +1, Review: QA +1

#3008 Copy doc changes for /cloud for 18.04
  templates/cloud/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3037 Download server 18.04
  templates/download/alternative-downloads.html
  templates/download/server/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2994 Add pages for each nav dropdown to be shown on mobile
  static/js/navigation.js
  static/js/scratch.js
  static/sass/_pattern_navigation.scss
  templates/nav-community.html
  templates/nav-developer.html
  templates/nav-download.html
  templates/nav-enterprise.html
  templates/templates/_navigation-download.html
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3040 Replace old Juju logo in cloud partners page
  templates/cloud/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3044 Added redirect from /cloud/openstack/autopilot to /openstack
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#3045 Update the issue template to help people filing Ubuntu OS bugs
  .github/ISSUE_TEMPLATE.md
Labels: Review: Code +1

#3042 Updated HP section on /server/hyperscale
  templates/server/hyperscale.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3046 Updated /Robotics contact link
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: QA +1

#3054 Rebase from master
  .github/ISSUE_TEMPLATE.md
  redirects.yaml
  templates/cloud/partners.html
  templates/download/server/thank-you-linuxone.html
  templates/internet-of-things/gateways.html
  templates/server/hyperscale.html
Labels: Review: Code +1

#3055 Replace "Canonical's Kubernetes" with better wording
  templates/containers/index.html
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#3051 Build k8s takeunder
  templates/takeovers/takeunders/_ubuntu-product-month.html
Labels: Review: Code +1, Review: Design +1, Review: UX +1

#3053 Update server page copy
  templates/download/server/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3057 3056 last minute fixes
  navigation.yaml
  templates/desktop/index.html
  templates/download/desktop/index.html
  templates/download/index.html
  templates/download/server/index.html
  templates/download/server/s390x.html
  templates/download/server/thank-you-s390x.html
  templates/server/index.html
  templates/takeovers/_1804-takeover.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3032 Update copy on desktop page
  templates/desktop/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3060 Update s390x in the download menu
  navigation.yaml
  redirects.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3061 Differentiate the two "Install Ubuntu Core" on raspi links
  templates/download/iot/index.html
Labels: Review: Code +1

#3062 Update server download links
  templates/download/server/index.html
  templates/download/server/thank-you.html
  templates/shared/contextual_footers/_download_more_info_enterprise.html
Labels: Review: Code +1, Review: QA +1

#3064 Remove Hastexo section
  templates/cloud/training.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3066 updated snap store image and link
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3067 Remove chevron from cta
  templates/download/desktop/index.html
  templates/download/server/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3071 Copy update
  templates/desktop/index.html
Labels: Review: Code +1, Review: QA +1

#3078 Remove br from title
  templates/download/cloud/build-openstack.html
Labels: Review: Code +1, Review: QA +1

#3081 Update documentation contextual footer
  templates/shared/contextual_footers/_download_documentation.html
Labels: Review: Code +1, Review: QA +1

#3082 Update to 18.04 on openstack
  templates/download/cloud/try-openstack.html
Labels: Review: Code +1, Review: QA +1

#3080 Make local link
  templates/download/cloud/build-openstack.html
Labels: Review: Code +1, Review: QA +1

#3084 Fix blurry logo
  templates/download/iot/index.html
Labels: Review: Code +1, Review: QA +1

#3086 Make browser image bigger
  templates/desktop/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3091 Updated the Ubuntu 16.04 LTS torrent links
  templates/download/alternative-downloads.html
Labels: Review: Code +1, Review: QA +1

#3096 Update resource link
  templates/resources/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
