Repository canonical/ubuntu.com, pull requests merged in 2018-06, with the labels that each got.

#3252 added rigado logo
  .travis.yml
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3232 Fixing global nav
  static/js/navigation.js
  static/sass/_global-settings.scss
  static/sass/_pattern_global-nav.scss
  static/sass/styles.scss
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3265 changed col size
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1

#3269 Change footer border
  static/sass/_pattern_footer.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3262 3256 nav content updates
  templates/shared/_insights_news_strip.html
  templates/templates/_navigation-developer-h.html
  templates/templates/global-nav.html
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3270 Add anchor for response times
  templates/legal/shared/_severity-levels.html
Labels: Review: Code +1, Review: QA +1

#3271 Content update for the NUC desktop install page
  templates/download/iot/intel-nuc-desktop.html
Labels: Review: Code +1, Review: QA +1

#3305 Cloud economics campaign landing page
  static/sass/styles.scss
  static/sass/takeovers/_private_cloud_economics.scss
  templates/engage/cloud-economics.html
Labels: Don't merge, Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3311 Removed the /juju page
  navigation.yaml
  redirects.yaml
  templates/desktop/developers.html
  templates/juju/_base_juju.html
  templates/juju/index.html
  templates/openstack/index.html
  templates/public-cloud/index.html
  templates/server/hyperscale.html
  templates/server/index.html
  templates/shared/contextual_footers/_maas-juju.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#3323 Takeover update
  static/sass/takeovers/_private_cloud_economics.scss
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3324 UTMize takeover link
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: QA +1

#3309 Update copy on managed services desc page
  templates/legal/managed-services/service-description.html
  templates/legal/shared/_appendix-management-escalation.html
  templates/legal/shared/_appendix-support-process.html
Labels: Review: Code +1, Review: QA +1

#3321 Remove docker ubuntu page
  navigation.yaml
  redirects.yaml
  templates/containers/docker-ubuntu.html
  templates/containers/index.html
  templates/templates/_navigation-enterprise-h.html
  templates/templates/_navigation-enterprise.html
Labels: Review: Code +1, Review: QA +1

#3325 Remove dead links
  .travis.yml
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#3310 Removed /server/maas page
  navigation.yaml
  redirects.yaml
  templates/openstack/index.html
  templates/server/index.html
  templates/server/maas.html
  templates/takeovers/_maas_may_2017.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#3320 3319 change icon size
  static/js/navigation.js
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-download-h.html
  templates/templates/_navigation-enterprise-h.html
  templates/templates/_navigation.html
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3326 remove lxd page
  navigation.yaml
  redirects.yaml
  templates/containers/index.html
  templates/containers/lxd.html
  templates/server/index.html
Labels: Review: Code needed, Review: QA needed

#3314 Add ebook to server download thank you page
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook.html
  templates/openstack/developer.html
  templates/openstack/install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3328 Update cloud-eco landing page design
  templates/engage/cloud-economics.html
Labels: Review: Code +1, Review: Design +1

#3330 Add common query params to context
  templates/engage/cloud-economics.html
  webapp/views.py
Labels: Review: Code +1

#3318 Add overlay and animation to products nav
  static/js/navigation.js
  static/sass/_pattern_global-nav.scss
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3368 Remove grid tool
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3375 Fix button spacing
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3374 Update copy of takeover
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: QA +1

#3329 Add beta feedback modal
  static/sass/_pattern_feedback.scss
  static/sass/styles.scss
  templates/shared/_feedback.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3371 Move global nav overlay to stop it overlapping global nav bar
  static/sass/_pattern_global-nav.scss
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3369 Remove hardcoded beta search results
  templates/search.html
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: QA +1

#3381 Remove rogue links download
  static/sass/styles.scss
  templates/openstack/install.html
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3395 Remove Suse OS
  templates/containers/lxd.html
  templates/download/server/index.html
  templates/download/server/thank-you.html
  templates/legal/trademarks/index.html
  templates/server/index.html
  templates/shared/pricing/_maas-support.html
Labels: Review: Code +1, Review: QA +1

#3399 Update NUC image listing as per Intel request
  templates/download/iot/intel-nuc-desktop.html
Labels: Review: Code +1, Review: Design +1

#3317 3273 nav anchors
  static/js/navigation.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3388 3356 kubernetes overview page
  static/sass/_pattern_matrix.scss
  templates/kubernetes/index.html
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3379 Add login menu
  static/js/navigation.js
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_matrix.scss
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3383 639 openstack managed page
  static/sass/styles.scss
  templates/openstack/managed.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3327 Removed docker section from /containers
  templates/containers/index.html
  templates/containers/shared/_whitepaper.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3438 3362 kubernetes install page
  navigation.yaml
  templates/kubernetes/_get_ebook.html
  templates/kubernetes/install.html
  templates/shared/contextual_footers/_cloud_bootstack.html
  templates/shared/contextual_footers/_cloud_further_reading.html
  templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3439 Add kubernetes partners page
  navigation.yaml
  templates/kubernetes/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3444 Add base template for ai pages
  templates/ai/base_ai.html
Labels: Review: Code +1

#3384 Update openstack consulting page
  static/sass/_pattern_card.scss
  templates/openstack/consulting.html
  templates/shared/_resources_openstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3442 3279 developer menu
  package.json
  templates/templates/_navigation-community.html
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-developer.html
  templates/templates/_navigation-download.html
  templates/templates/_navigation-enterprise.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3441 Update community menu
  templates/templates/_navigation-community-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3456 Create kubernetes contact-us and thank-you pages
  templates/kubernetes/contact-us.html
  templates/kubernetes/thank-you.html
Labels: Review: Code +1, Review: QA +1

#3458 Remove dead global nav link
  templates/templates/base.html
Labels: Review: Code +1

#3457 Update the openstack contact-us and thank-you pages
  redirects.yaml
  templates/legal/managed-services/index.html
  templates/openstack/contact-us.html
  templates/openstack/managed.html
  templates/openstack/storage.html
  templates/openstack/thank-you.html
  templates/openstack/training.html
  templates/support/plans-and-pricing.html
  test-redirects.pl
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#3461 Create the /ai contact-us and thank-you pages
  templates/ai/contact-us.html
  templates/ai/thank-you.html
Labels: Review: Code +1, Review: QA +1

#3268 Introducing canonical tags
  templates/cloud/thank-you.html
  templates/contact-us/form/thank-you.html
  templates/containers/thank-you.html
  templates/core/thank-you.html
  templates/desktop/thank-you.html
  templates/download/desktop/thank-you.html
  templates/download/server/thank-you-linuxone.html
  templates/download/server/thank-you-s390x.html
  templates/download/server/thank-you.html
  templates/internet-of-things/thank-you.html
  templates/openstack/index.html
  templates/server/index.html
  templates/server/maas/thank-you.html
  templates/server/thank-you.html
  templates/support/index.html
  templates/templates/base.html
  webapp/settings.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3450 k8s install copy updates
  templates/kubernetes/_get_ebook.html
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3446 Create the AI features page
  templates/ai/features.html
  templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3465 Livechat button
  static/sass/_pattern_feedback.scss
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3453 Create the AI install page
  static/sass/_pattern_lists.scss
  templates/ai/install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3470 Update card style
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3459 Create the OpenStack install page
  navigation.yaml
  redirects.yaml
  templates/openstack/developer.html
  templates/openstack/install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3455 3338 ai index page
  navigation.yaml
  templates/ai/index.html
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3472 Remove global-nav symlink
  static/global-nav
Labels: Review: Code +1

#3475 Update the k8s managed contact us link
  templates/kubernetes/managed.html
Labels: Review: Code +1, Review: QA +1

#3474 Use the K8s logo on the overview hero
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3469 3464 image updates
  templates/ai/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3477 Update the resource link on k8s overview
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#3480 Update homepage takeover h1
  templates/engage/cloud-economics.html
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: QA +1

#3488 Removed dup 'install' from openstack menu
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#3481 Update the containers page
  static/js/navigation.js
  templates/containers/index.html
  templates/containers/shared/_whitepaper.html
  templates/templates/_navigation-community-h.html
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-download-h.html
  templates/templates/_navigation-enterprise-h.html
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3491 3473 fix flavours menu
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#3487 Updated support page mentions of systems supported for Livepatch
  templates/server/livepatch.html
  templates/shared/_case-study-itstrategen.html
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#3478 Plans and pricing copy update
  templates/openstack/index.html
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/support/plans-and-pricing.html
Labels: Priority: High, Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3490 AI index K8's add-ons include
  templates/ai/index.html
Labels: Review: Code +1, Review: QA +1

#3493 Update plans and pricing page with pricing and services updates
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-consulting.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1
