Repository canonical/ubuntu.com, pull requests merged in 2018-12, with the labels that each got.

#4446 Updated enterprise nav
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4460 Updated 18.04.1 Server bittorrent link
  templates/download/alternative-downloads.html
  templates/download/server/index.html
Labels: Priority: Critical, Review: Code +1, Review: QA +1

#4477 Updating MicroK8s copy & links
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4480 Updated CTA and engage page for compliance
  templates/engage/ubuntu-compliance.html
  templates/takeovers/_compliance-webinar.html
Labels: Review: Code +1, Review: QA +1

#4450 Created templates for engage case study and webinar heros
  templates/engage/_heading-help.html
  templates/engage/shared/_header-case-study.html
  templates/engage/shared/_header.html
  templates/engage/ubuntu-18-10.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#4482 Update the webinar data privacy page
  templates/legal/data-privacy/webinar/2018-04-01.html
  templates/legal/data-privacy/webinar/index.html
Labels: Review: Code +1, Review: QA +1

#4457 Include siteSearch in next and previous links
  templates/search.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4478 Removed superfluous marketing material checkbox
  templates/download/server/s390x.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4485 Add microk8s takeover
  templates/index.html
  templates/takeovers/_microk8s-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4489 Changed Canonical Distribution of Kubernetes to Charmed Distribution …
  templates/ai/features.html
  templates/containers/contact-us.html
  templates/containers/thank-you.html
  templates/engage/ai-ml-ubuntu.html
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/base_docs.html
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/news.md
  templates/kubernetes/docs/overview.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/validation.md
  templates/kubernetes/features.html
  templates/kubernetes/partners.html
  templates/legal/shared/_appendix-support-scope.html
  templates/rfp/index.html
  templates/takeovers/_kubernetes-enterprise-takeover.html
  templates/takeovers/_kubernetes_takeover.html
  templates/takeovers/takeunders/_ubuntu-product-month.html
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#4490 More kubernetes name updates
  templates/kubernetes/features.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/partners.html
Labels: Review: Code +1, Review: QA +1

#4493 Fixed cropped inline images
  templates/openstack/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4487 Updated MicroK8s link
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4486 Support for case-insensitive URLs
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4494 Updates to the /kubernetes overview
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#4496 Added desktop developer takeover
  templates/index.html
  templates/takeovers/_desktop-developer-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1, Review: UX +1

#4505 Updated /kubernetes/partners with text updates
  templates/kubernetes/partners.html
Labels: Review: Code +1, Review: QA +1

#4499 Updated /kubernetes/features with SEO and text updates
  templates/kubernetes/features.html
Labels: Review: Code +1, Review: QA +1

#4501 Updated /kubernetes with SEO and text updates
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#4503 Updated /kubernetes/install with text updates
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: QA +1

#4495 Add docs for CDK 1.13 release
  templates/kubernetes/docs/certs-and-trust.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/troubleshooting.md
  templates/kubernetes/docs/using-vault.md
Labels: Copy update, Review: QA needed, Type: Maintenance

#4507 Update /kubernetes with copy doc changes
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#4513 Increase the z-index for the navigation
  static/sass/_pattern_gaming.scss
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#4515 Moving /engage/kubernetes-case-study to /engage/k8s-allan-gray
  redirects.yaml
  templates/engage/k8s-allan-gray.html
Labels: Review: Code +1, Review: QA +1

#4516 Updated takeover CTA links
  templates/engage/modern-cloud.html
  templates/takeovers/_spicule_takeover.html
  templates/takeovers/_trilio_takeover.html
Labels: Review: Code +1, Review: QA +1

#4518 Update the enterprise dropdown menu
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#4519 Apellix CS landing page
  templates/engage/industrial-drones-case-study.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4529 Remove the trilio & Spicule takeovers [19th December]
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#4532 "Openstack, un jeu d enfant" - French landing page + takeover
  templates/engage/fr/openstack-made-easy.html
  templates/index.html
  templates/takeovers/_french_takeover_openstack_made_easy.html
Labels: Review: Code needed, Review: Design +1, Review: QA needed, Review: UX +1

#4509 Update to the /core page
  static/js/stickyNav.js
  static/sass/_pattern_matrix.scss
  static/sass/_pattern_separator.scss
  static/sass/styles.scss
  templates/core/index.html
  templates/desktop/statistics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4525 Update /download/iot for core18
  navigation.yaml
  templates/download/iot/_flash-image.html
  templates/download/iot/index.html
  templates/download/iot/installation-media.html
  templates/download/iot/intel-nuc.html
  templates/download/iot/kvm.html
  templates/download/iot/qualcomm-dragonboard-410c.html
  templates/download/iot/raspberry-pi-2-3.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1
