Repository canonical/ubuntu.com, pull requests merged in 2018-07, with the labels that each got.

#3489 3476 design fix s390x page
  static/sass/styles.scss
  templates/download/server/s390x.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3503 Update K8s page copy
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3479 3392 mobile global nav
  static/js/navigation.js
  static/sass/_pattern_global-nav.scss
  templates/templates/_navigation-community-h.html
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3496 Merge beta
  templates/contact-us/form/thank-you.html
  templates/containers/lxd.html
  templates/containers/thank-you.html
  templates/core/thank-you.html
  templates/desktop/thank-you.html
  templates/download/desktop/thank-you.html
  templates/download/iot/intel-nuc-desktop.html
  templates/download/server/index.html
  templates/download/server/thank-you-s390x.html
  templates/download/server/thank-you.html
  templates/internet-of-things/thank-you.html
  templates/legal/trademarks/index.html
  templates/openstack/thank-you.html
  templates/server/index.html
  templates/server/livepatch.html
  templates/server/maas/thank-you.html
  templates/server/thank-you.html
  templates/shared/_case-study-itstrategen.html
  templates/shared/_insights_news_strip.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-consulting.html
  templates/support/index.html
  templates/takeovers/_private_cloud_economics.html
  templates/templates/base.html
  webapp/settings.py
  yarn.lock
Labels: Review: Code +1

#3533 Make hardcoded link relative
  templates/legal/data-privacy-enquiry/index.html
Labels: Review: Code +1, Review: QA +1

#3507 Update kubernetes pricing table
  templates/shared/pricing/_kubernetes-enterprise-support.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3506 Update kubernetes pricing table
  templates/shared/pricing/_kubernetes-enterprise-support.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3560 Update link on server page
  templates/server/index.html
Labels: Review: Code +1, Review: QA +1

#3546 3537 duplicated link
  templates/kubernetes/index.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
Labels: Review: Code +1, Review: QA +1

#3536 Fixed secondary and tertiary nav for mobile
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3535 3514 footer link bug
  templates/legal/terms-and-policies/index.html
Labels: Review: Code +1, Review: QA +1

#3547 added the top section back to the enterprise menu on mobile, fixed links
  static/sass/_pattern_lists.scss
  templates/templates/_navigation-enterprise-h.html
  templates/templates/footer.html
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: QA +1

#3570 Fix mobile list and image styling
  templates/server/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3572 Remove pictogram
  templates/server/hyperscale.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3523 Dynamic generation of navigation GA events
  static/js/navigation.js
Labels: Review: Code +1

#3534 Make absolute url relative
  templates/legal/terms-and-policies/livepatch-terms-of-service.html
Labels: Review: Code +1, Review: QA +1

#3538 Fix typo on page
  templates/openstack/features.html
Labels: Review: Code +1, Review: QA +1

#3569 Move hyperscale image
  templates/server/hyperscale.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3502 Add SSO data privacy notice
  templates/legal/dataprivacy/index.html
  templates/legal/dataprivacy/sso.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3552 Change spacing in footer links
  static/sass/_pattern_footer.scss
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3579 Update with sso policy
  templates/legal/dataprivacy/index.html
  templates/legal/dataprivacy/sso.html
Labels: Review: Code +1, Review: QA +1

#3582 IOT copy updates
  templates/internet-of-things/digital-signage.html
Labels: Review: Code +1, Review: QA +1

#3583 Hide picto on mobile /kubernetes/partners
  templates/kubernetes/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3495 Copy updates for openstack consulting
  static/sass/styles.scss
  templates/openstack/consulting.html
  templates/shared/_resources_openstack.html
  templates/shared/pricing/_openstack-consulting.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3585 Remove highlighted cards
  templates/kubernetes/managed.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3589 Update contact links on k8s partners page
  templates/kubernetes/partners.html
Labels: Review: Code +1, Review: QA +1

#3596 Livepatch page pictogram removal and card styling
  templates/server/livepatch.html
  templates/shared/_case-study-itstrategen.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3588 Hide logos on small screens
  templates/kubernetes/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3578 Fix breadcrumb - section title duplicated on large screens
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: QA +1

#3571 Wrap words in code tags
  templates/kubernetes/features.html
  templates/openstack/features.html
Labels: Review: Code +1, Review: QA +1

#3595 Fix link on download menu
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: QA +1

#3594 Change padding on download menu
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3587 Fix footer border width
  static/sass/_pattern_footer.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3602 Add more nav events, introduce content events
  static/js/navigation.js
Labels: Review: Code +1

#3603 Fix margins for takeunders
  static/sass/_pattern_takeunders.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3543 3528 fieldset border
  static/sass/styles.scss
  templates/shared/_cloud-contact-us-form.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3614 Change install media instructions link on the nuc desktop install page
  templates/download/iot/intel-nuc-desktop.html
Labels: Review: Code +1

#3557 Fix alignment of icons on matrix
  static/sass/_pattern_matrix.scss
  templates/desktop/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3617 Fix typo on about page
  templates/about/index.html
Labels: Review: Code +1, Review: QA +1

#3604 Add spacing under graph image
  templates/shared/_release_schedule.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3606 Move table on server page
  templates/server/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3607 Update videos link in global nav
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: QA +1

#3612 Fix table on mobile
  templates/shared/pricing/_kubernetes-enterprise-support.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3599 Add padding on mobile cards
  templates/server/hyperscale.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3586 Fix button spacing on k8s managed hero
  templates/kubernetes/managed.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3615 Change install media instructions link on the nuc desktop install page
  templates/download/iot/intel-nuc-desktop.html
Labels: Review: Code +1

#3598 Update takeover
  static/sass/takeovers/_private_cloud_economics.scss
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3613 Fix resource filters on mobile
  templates/resources/index.html
Labels: Review: Code +1, Review: QA +1

#3611 Update developer menu
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#3610 Update community menu
  templates/templates/_navigation-community-h.html
Labels: Review: Code +1, Review: QA +1

#3605 Center align card images
  templates/download/cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3608 Fix padding on developer menu on mobile
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#3621 Upgrade vanilla to latest version
  package.json
  static/sass/_pattern_lists.scss
  static/sass/_pattern_matrix.scss
  static/sass/_pattern_navigation.scss
  templates/desktop/features.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#3637 Remove pictogram and move text
  templates/openstack/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3626 Update image on openstack hero
  templates/openstack/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3639 Hide image on mobile
  templates/openstack/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3652 Fix the links to none existing pages
  templates/ai/index.html
  templates/kubernetes/features.html
  templates/openstack/features.html
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1

#3666 Fix telecominfraproject logo size
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3632 added new include for openstack packages
  templates/openstack/index.html
  templates/shared/pricing/_openstack-packages.html
Labels: Review: Code needed, Review: QA needed

#3663 Remove duplicated copy
  templates/ai/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3664 Hide kubeflow logo on mobile
  templates/ai/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3656 Update openstack managed page
  templates/openstack/managed.html
Labels: Review: Code +1, Review: QA +1

#3646 Udpate copy on openstack features page
  templates/openstack/features.html
Labels: Review: Code +1, Review: QA +1

#3662 Fix spacing on ai hero
  templates/ai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3665 Replace the install K8s bit.ly links with asset ones
  templates/ai/install.html
Labels: Review: Code +1, Review: QA +1

#3651 Fix spacing in hero
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3650 3645 spacing
  templates/openstack/managed.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3643 Fix spacing on openstack features
  templates/openstack/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3641 Fix table on mobile
  templates/shared/pricing/_openstack-consulting.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3633 Fix middots in footer
  static/sass/_pattern_lists.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3622 Update takeover
  static/sass/takeovers/_private_cloud_economics.scss
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1, Review: QA +1

#3674 Update marketo download forms to mongoose
  templates/download/iot/intel-joule.html
  templates/download/iot/intel-nuc.html
  templates/download/server/s390x.html
  templates/download/server/thank-you-linuxone.html
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook.html
  templates/download/shared/_get_ebook_maas.html
Labels: Review: Code +1, Review: QA +1

#3568 699 ai features
  templates/ai/features.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3677 Update links
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: QA +1

#3678 Fix typos of microk8s
  templates/ai/install.html
Labels: Review: Code +1

#3679 Fix typo in enterprise menu
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1

#3681 Add UTMs to takeover
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code +1

#3682 Add UTMs to takeover
  templates/takeovers/_private_cloud_economics.html
Labels: Review: Code needed

#3575 Add hover state to breadcrumb title
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3634 Update Google Optimize container ID
  templates/templates/_tag_manager.html
Labels: Review: Code +1

#3655 3638 update openstack page
  templates/openstack/index.html
  templates/shared/_resources_openstack.html
  templates/shared/contextual_footers/_cloud_contact_us.html
  templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3628 Update image on openstack training page
  templates/openstack/training.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3644 Increase speed on navigation transition
  static/js/navigation.js
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation-community-h.html
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-download-h.html
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3693 Update privacy notices copy
  templates/legal/dataprivacy/contact.html
  templates/legal/dataprivacy/newsletter.html
  templates/legal/dataprivacy/online-purchase.html
  templates/legal/dataprivacy/snap-store.html
  templates/legal/dataprivacy/sso.html
  templates/legal/dataprivacy/webinar.html
Labels: Review: Code +1, Review: QA +1

#3699 Remove autofocus on search field
  static/js/scratch.js
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3701 Privacy notice update
  templates/legal/dataprivacy/contact.html
  templates/legal/dataprivacy/newsletter.html
  templates/legal/dataprivacy/online-purchase.html
  templates/legal/dataprivacy/snap-store.html
  templates/legal/dataprivacy/sso.html
  templates/legal/dataprivacy/webinar.html
Labels: Review: Code +1, Review: QA +1

#3687 Fix incorrect link
  templates/ai/features.html
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: QA +1

#3685 Fix mobile menu state
  static/js/navigation.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3708 noindex thank-you pages
  templates/cloud/thank-you.html
  templates/contact-us/form/thank-you.html
  templates/containers/thank-you.html
  templates/core/thank-you.html
  templates/desktop/thank-you.html
  templates/download/desktop/thank-you.html
  templates/download/server/thank-you-linuxone.html
  templates/download/server/thank-you-s390x.html
  templates/download/server/thank-you.html
  templates/internet-of-things/thank-you.html
  templates/server/maas/thank-you.html
  templates/server/thank-you.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3709 Update developer menu
  static/js/navigation.js
  static/sass/_pattern_lists.scss
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3706 Use default vanilla pull quote pattern
  static/sass/_pattern_pull_quotes.scss
  static/sass/styles.scss
  templates/desktop/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3584 Add secondary nav to old policy page
  navigation.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3712 Update cookie notification markup
  static/js/scratch.js
Labels: Review: Code +1, Review: QA +1

#3714 Fix text alignment in download menu buttons
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3717 Change padding on header icon cards
  templates/download/desktop/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3718 Fix table horizontal scrolling on mobile
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-support.html
  templates/shared/pricing/_ua-desktop-support.html
  templates/shared/pricing/_ua-server-support.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3721 Change PR template URL syntax to avoid duplication
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code +1

#3715 Update card with footer pattern
  static/sass/_pattern_card.scss
  templates/download/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3722 Make login nav two cols on tablet
  static/sass/_pattern_global-nav.scss
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3720 Fix /download/cloud/ card images on mobile
  templates/download/cloud/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3723 Revert "Replace GSA with Google Custom Search"
  requirements.txt
  templates/search.html
  webapp/settings.py
  webapp/urls.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#3713 Update ai/install contextual footer
  templates/ai/install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3711 Fix caption styling on ai/features page
  templates/ai/features.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3710 Fix bare metal everywhere
  templates/ai/index.html
  templates/download/server/arm.html
  templates/kubernetes/features.html
  templates/kubernetes/index.html
  templates/kubernetes/managed.html
  templates/openstack/features.html
  templates/openstack/index.html
  templates/openstack/install.html
  templates/openstack/managed.html
  templates/server/hyperscale.html
  templates/shared/contextual_footers/_maas-faq.html
  templates/templates/global-nav.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3703 Update kubernetes managed copy
  templates/kubernetes/managed.html
  templates/shared/pricing/_kubernetes-managed.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3694 Update page Kubernetes features copy
  templates/kubernetes/features.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3740 Removed extra header block from s390x thank you page
  templates/download/server/thank-you-s390x.html
Labels: Review: Code +1, Review: QA +1

#3742 Update FCB datasheet
  templates/cloud/foundation-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3744 Update FCB datasheet on beta
  templates/openstack/consulting.html
Labels: Review: Code needed, Review: QA needed

#3754 Update PR template with QA steps practices
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code needed

#3752 Prevent white line under nav when closing enterprise menu in Firefox
  static/sass/_pattern_navigation.scss
Labels: Review: Code +1, Review: QA +1

#3739 Beta post release clean up
  static/js/forms.js
  static/sass/_global-settings.scss
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_card.scss
  static/sass/_pattern_contextual-footer.scss
  static/sass/_pattern_contribution.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_gaming.scss
  static/sass/_pattern_global-nav.scss
  static/sass/_pattern_hero.scss
  static/sass/_pattern_inline-images.scss
  static/sass/_pattern_link.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_matrix.scss
  static/sass/_pattern_sun-animation.scss
  static/sass/_pattern_table.scss
  static/sass/_pattern_tabs.scss
  static/sass/_pattern_testimonials.scss
  static/sass/_utility_full-width.scss
  static/sass/styles.scss
  templates/download/cloud/index.html
  templates/download/desktop/contribute.html
  templates/download/desktop/thank-you.html
  templates/download/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/gateways.html
  templates/openstack/consulting.html
  templates/openstack/managed.html
  templates/resources/index.html
  templates/shared/_insights_news_strip.html
  templates/shared/_systems-management-tool.html
  templates/support/index.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#3757 Fix position of livechat button
  static/sass/_pattern_feedback.scss
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3761 Fcb hardware req
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: QA +1

#3763 Update FCB requirements datasheet
  templates/cloud/foundation-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3760 Copy updates on plans and pricing page
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/support/plans-and-pricing.html
Labels: Review: Code +1, Review: QA +1

#3758 Plans and pricing update
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3772 Fix max-width issue on homepage heading
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3745 Update s390z download and thank you pages
  templates/download/server/s390x.html
  templates/download/server/thank-you-s390x.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3765 Add new takeover
  static/sass/_utility-animations.scss
  static/sass/styles.scss
  static/sass/takeovers/_private_cloud_economics.scss
  static/sass/takeovers/_rigado-webinar.scss
  templates/index.html
  templates/takeovers/_private_cloud_economics.html
  templates/takeovers/_rigado_webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3766 Add new takeover to beta site
  static/sass/_utility-animations.scss
  static/sass/styles.scss
  static/sass/takeovers/_private_cloud_economics.scss
  static/sass/takeovers/_rigado-webinar.scss
  templates/index.html
  templates/takeovers/_private_cloud_economics.html
  templates/takeovers/_rigado_webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3803 Kubernetes enterprise datasheet
  templates/kubernetes/index.html
  templates/kubernetes/managed.html
Labels: Review: Code +1, Review: QA +1

#3804 Enterprise kubernetes beta
  templates/kubernetes/managed.html
Labels: Review: Code +1, Review: QA +1

#3797 Update Enterprise kubernetes datasheet on beta
  templates/kubernetes/managed.html
Labels: Review: Code needed, Review: QA needed

#3808 Update Foundation Cloud Build datasheet
  templates/cloud/foundation-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3800 Replace snaps screenshot on /iot
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3810 BETA: Update Foundation Cloud Build datasheet links
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: QA +1

#3802 BETA: Update snap store screenshot on /iot
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3813 Re-add deleted datasheet button
  templates/cloud/foundation-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#3799 18.04.1 release for mongoose
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3798 Update for the 18.04.1 release
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3806 BETA: Add AI/ML webinar takeover
  static/sass/styles.scss
  static/sass/takeovers/_ai-webinar.scss
  templates/index.html
  templates/takeovers/_ai_webinar.html
  templates/takeovers/_rigado_webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3807 Add AI/ML webinar takeover
  static/sass/styles.scss
  static/sass/takeovers/_ai-webinar.scss
  templates/index.html
  templates/takeovers/_ai_webinar.html
  templates/takeovers/_rigado_webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#3826 Added Overview menu item back to secondary nav
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3825 BETA: Make takeover alternate on every new session
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3824 Make takeover alternate on every new session
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3833 Updated rancher webinar
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: QA +1

#3793 [HACKDAY] BETA: Add copy docs links to metadata
  templates/about/base_about.html
  templates/about/index.html
  templates/ai/base_ai.html
  templates/ai/contact-us.html
  templates/ai/features.html
  templates/ai/index.html
  templates/ai/thank-you.html
  templates/base_index.html
  templates/community/_base_community.html
  templates/community/canonical.html
  templates/community/code-of-conduct.html
  templates/community/debian.html
  templates/community/diversity.html
  templates/community/governance.html
  templates/community/index.html
  templates/community/mission.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#3843 3792: Remove word "physical" from desktop support
  templates/shared/pricing/_ua-desktop-support.html
Labels: Review: Code +1, Review: QA +1

#3829 Improvements to building of production image
  .gitignore
  .travis.yml
  Dockerfile
  package.json
  requirements.txt
  static/global-nav
Labels: Review: Code +1, Review: QA +1

#3832 Add animation to AI/ML takeover
  static/sass/takeovers/_ai-webinar.scss
  templates/takeovers/_ai_webinar.html
Labels: Review: Code needed, Review: Design +1, Review: QA needed
