Repository canonical/ubuntu.com, pull requests merged in 2019-12, with the labels that each got.

#6213 Fix bugs in eol charts
  static/js/chart.js
  static/js/release-chart.js
Labels: Review: Code +1, Review: QA +1

#6194 “Installation instructions” > “How to upgrade”
  templates/download/desktop/thank-you.html
Labels: Review: Code +1, Review: UX +1

#6216 Ubuntu AWS and Ubuntu pro pages
  navigation.yaml
  redirects.yaml
  static/sass/styles.scss
  templates/aws/base_aws.html
  templates/aws/contact-us.html
  templates/aws/index.html
  templates/aws/pro.html
  templates/aws/shared/_aws-pie-chart.html
  templates/aws/thank-you.html
  templates/shared/forms/interactive/_aws.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6217 update /public-cloud based on copy doc changes
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6124 Use MaxMind GeoIP database to calculate country
  requirements.txt
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#6220 Update link on the AWS pro page
  templates/aws/pro.html
Labels: Review: Code +1

#6226 Updated the public cloud page
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#6222 Build automotive page
  navigation.yaml
  templates/automotive/base_automotive.html
  templates/automotive/index.html
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6224 Update the datasheet
  templates/aws/pro.html
Labels: Review: Code +1, Review: QA +1

#6228 Remove mention of landscape from Ubuntu Pro
  templates/aws/pro.html
Labels: Review: Code needed, Review: QA needed

#6230 Apply image template to public cloud page
  package.json
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#6219 Changed the link to other sec takeover
  templates/security/index.html
Labels: Review: Code +1

#6232 Update image links for new raspberry pi image
  templates/download/raspberry-pi.html
Labels: Review: Code +1

#6231 Masters main
  static/sass/_utility_vertically-center.scss
  static/sass/styles.scss
  templates/masters-conference/_base-masters-conference.html
  templates/masters-conference/brendan-gregg.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6235 Build survey data privacy page
  navigation.yaml
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/survey.md
Labels: Review: Code +1, Review: QA +1

#6236 Masters main
  static/sass/_pattern_grid.scss
  templates/masters-conference/_base-masters-conference.html
  templates/masters-conference/contact-us.html
  templates/masters-conference/index.html
  templates/masters-conference/thank-you.html
  templates/shared/forms/interactive/_masters-conference.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6233 Build masters takeover
  templates/index.html
  templates/takeovers/_template.html
  templates/takeovers/_ubuntu-masters-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6234 Build SBI case study page
  templates/engage/index.html
  templates/engage/sbi-casestudy.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6237 Build WSLConf engage page
  navigation.yaml
  templates/engage/index.html
  templates/engage/wslconf.html
  templates/legal/data-privacy/events.md
  templates/legal/data-privacy/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6250 update /download/kvm copy
  templates/download/kvm.html
Labels: Review: Code +1, Review: QA +1

#6251 update /about copy
  templates/about/index.html
Labels: Review: Code +1, Review: QA +1

#6252 update /internet-of-things/robotics copy
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6258 update /automotive copy doc link
  templates/automotive/index.html
Labels: Review: QA +1

#6248 Fix the button padding in the footer
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#6259 add header illustration
  templates/automotive/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6260 Add automotive tile to IoT page
  static/sass/styles.scss
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6266 Remove the matrix image override
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#6268 add networking as a product to /internet-of-things contact us page
  templates/internet-of-things/contact-us.html
  templates/internet-of-things/thank-you.html
Labels: Review: Code +1, Review: QA +1

#6240 Add contract details to the expanding name
  static/sass/styles.scss
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#6242 Vmware engage update
  templates/engage/_base_engage_markdown.html
  templates/engage/index.html
  templates/engage/vmware-to-charmed-openstack.md
  templates/index.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6271 update cta copy on vmware takeover
  templates/takeovers/_vmware-to-charmed-openstack.html
Labels: Review: QA needed

#6272 Update the Lubuntu logo
  templates/download/flavours.html
Labels: Review: Code +1, Review: QA +1

#6283 Changed the takeovers in rotation
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#6275 Point to secure sites for other flavours
  templates/download/flavours.html
Labels: Review: Code +1

#6288 Cyberdyne engage
  templates/engage/cyberdyne.md
  templates/engage/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6296 convert engage entries to articles
  templates/engage/index.html
Labels: Review: Code +1, Review: QA +1

#6287 add multipass download info to /download/server
  templates/download/server/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6301 use article card template on engage index
  templates/engage/_article-card.html
  templates/engage/index.html
Labels: Review: Code +1, Review: QA +1

#6297 Added multipass download link to page
  templates/download/desktop/index.html
  templates/download/server/index.html
  templates/download/shared/_multipass-install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6302 add intro to microk8s takeover and engage page
  templates/engage/index.html
  templates/engage/intro-to-microk8s-webinar.md
  templates/index.html
  templates/takeovers/_intro-to-microk8s.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6303 add linux enterprise whitepaper engage page
  templates/engage/index.html
  templates/engage/linux-enterprise-whitepaper.md
  templates/index.html
  templates/takeovers/_linux-enterprise.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6276 Docs updates for k8s 1.17 release:
  navigation.yaml
  templates/kubernetes/docs/cis-compliance.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/snap-coherence.md
  templates/kubernetes/docs/storage.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#6304 fix typo
  templates/internet-of-things/networking.html
Labels: Review: Code needed, Review: QA needed

#6305 update meta description
  templates/engage/vmware-to-charmed-openstack.md
Labels: Review: Code +1, Review: QA +1
