Repository canonical/ubuntu.com, pull requests merged in 2019-08, with the labels that each got.

#5631 Add Suru background strip to desktop index page
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/desktop/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5633 Simplify /legal secondary menu
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#5634 Update iot index with new illustrations
  static/sass/_pattern_strip.scss
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5636 Add local rss feed
  redirects.yaml
  requirements.txt
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#5639 Rebuild /internet-of-things/robotics page
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5656 Revert blog module, hopefully itll fix things
  redirects.yaml
  requirements.txt
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#5659 Corrects Kubernetes “Contact us” page headings
  templates/kubernetes/contact-us.html
  templates/kubernetes/thank-you.html
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
  templates/shared/pricing/_kubernetes-consulting.html
Labels: Review: Code +1, Review: QA +1

#5661 5008 Maas automated hardware testing
  templates/engage/index.html
  templates/engage/maas-hardware-testing.html
  templates/index.html
  templates/takeovers/_maas-hardware-testing_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5658 Update version and checksums for 18.04.3
  releases.yaml
Labels: Review: Code +1, Review: QA +1

#5662 Replace Edge takeover with Maas
  templates/index.html
Labels: Review: QA +1

#5663 Add deepsense.ai webinar takeover and landing page
  templates/engage/data-pipelines-kubeflow.html
  templates/engage/index.html
  templates/engage/shared/_header.html
  templates/index.html
  templates/takeovers/_data-pipelines-kubeflow.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#5660 K8sdocs - remove conjure up
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/quickstart.md
Labels: Review: Code +1, Review: QA +1

#5657 Rebuild /iot/gateways page
  templates/internet-of-things/gateways.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5665 Update banner on /iot/robotics
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: QA +1

#5670 More text changes on the robotics page
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: QA +1

#5671 Update design of /download page
  static/sass/_pattern_strip.scss
  templates/download/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5675 Bump canonicalwebteam.blog to 2.3.0
  requirements.txt
Labels: Review: QA +1

#5667 Android on ubuntu takeover/engage page - due 14 August 2019
  templates/engage/_base_engage_markdown.html
  templates/engage/developing-android-on-ubuntu.md
  templates/engage/index.html
  templates/index.html
  templates/takeovers/_developing-android-on-ubuntu.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5678 k8s- change bundle ref
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: Code +1

#5681 Fix suru background on android takeover and engage page
  templates/engage/developing-android-on-ubuntu.md
  templates/takeovers/_developing-android-on-ubuntu.html
Labels: Review: Code +1, Review: QA +1

#5682 Add modal contact-us form for /openstack/storage
  templates/openstack/storage.html
  templates/shared/forms/interactive/_storage.html
Labels: Review: Code +1, Review: QA +1

#5692 New K8s release
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: Code +1, Review: QA +1

#5691 Copy update
  templates/security/certifications.html
Labels: Review: Code +1, Review: QA +1

#5693 Add feeds endpoints for authors, groups and topics
  redirects.yaml
  requirements.txt
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#5694 Change color on datapipelines takeover
  templates/engage/data-pipelines-kubeflow.html
  templates/takeovers/_data-pipelines-kubeflow.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5680 Add enterprise snap management whitepaper and takeover - 28 August 2019
  templates/engage/enterprise-snap-management.md
  templates/engage/index.html
  templates/index.html
  templates/takeovers/_enterprise-snap-management.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5699 Remove install commands and menu from /esm
  templates/esm/index.html
Labels: Review: Code +1, Review: QA +1

#5696 Update the /about/release-cycle
  static/js/chartData.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#5701 Reduce the blur on the Suru hero on download section
  static/sass/_pattern_strip.scss
Labels: Review: Code +1, Review: Design +1

#5700 Remove deprecated components
  static/js/scratch.js
  static/sass/_pattern_inline-images.scss
  static/sass/_vanilla-placeholders.scss
  static/sass/styles.scss
  templates/blog/topics/design.html
  templates/blog/topics/juju.html
  templates/blog/topics/maas.html
  templates/blog/topics/robotics.html
  templates/blog/topics/snappy.html
  templates/containers/index.html
  templates/desktop/developers.html
  templates/desktop/features.html
  templates/desktop/partners.html
  templates/legal/contributors/agreement.html
  templates/openstack/shared/_guest-list.html
  templates/server/index.html
  templates/shared/_call-sales-long.html
  templates/takeovers/_enterprise-kubernetes.html
  templates/takeovers/_maas_may_2017.html
Labels: Review: Code +1, Review: QA +1

#5706 Add learn more to all kubeflow section
  templates/kubeflow/consulting.html
  templates/kubeflow/features.html
  templates/kubeflow/index.html
  templates/kubeflow/install.html
  templates/kubeflow/shared/_learn-more.html
Labels: Review: Code +1, Review: QA +1

#5707 List feeds from most recent to oldest
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5704 Add microk8s to server download thankyou page
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook_maas.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5713 Fix the Hiri case study engage page
  templates/engage/hiri-case-study.html
Labels: Review: Code +1, Review: QA +1

#5712 Fix search error
  templates/search.html
Labels: Review: Code +1, Review: QA +1

#5716 Update kubeflow install instructions
  templates/kubeflow/install.html
Labels: Review: Code +1, Review: QA +1

#5717 GitHub not Github
  templates/core/index.html
  templates/embedded/index.html
Labels: Review: Code +1, Review: QA +1

#5718 Swap homepage takeovers
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5722 /search in Flask
  requirements.txt
  templates/search.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#5724 Engage pages in Markdown - removing extraneous bit of title
  templates/engage/_base_engage_markdown.html
Labels: Review: Code +1, Review: QA +1

#5726 Update developer dropdown
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#5728 Fix typo on iot/gateways
  templates/internet-of-things/gateways.html
Labels: Review: Code +1, Review: QA +1

#5730 escape html correctly on /pricing/infra
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#5731 /blog endpoints with Flask
  .circleci/config.yml
  navigation.yaml
  package.json
  redirects.yaml
  requirements.txt
  templates/blog/pagination.html
  templates/blog/topics/snapcraft.html
  webapp/app.py
  webapp/context.py
  webapp/testrunner.py
Labels: Review: Code +1, Review: QA +1

#5734 Remove resources
  .circleci/config.yml
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/templates/_navigation-developer-h.html
  templates/templates/_navigation-enterprise-h.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1
