Repository canonical/ubuntu.com, pull requests merged in 2019-11, with the labels that each got.

#6046 Fix broken link on K8s validation page
  templates/kubernetes/docs/validation.md
Labels: Review: Code +1

#6050 Add no-nav v2
  static/sass/styles.scss
  templates/engage/_base_engage_markdown.html
  templates/engage/base_engage.html
  templates/engage/shared/_header.html
  templates/templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6055 Add Ubuntu logo to all engage pages
  templates/engage/14-04-esm.html
  templates/engage/451-automotive.html
  templates/engage/ITstrategen-case-study.html
  templates/engage/_base_engage_markdown.html
  templates/engage/ai-gettingstarted.html
  templates/engage/ai-ml-ubuntu.html
  templates/engage/apparmor-intro.html
  templates/engage/base_engage.html
  templates/engage/casestudy-botsandus.html
  templates/engage/casestudy-commercetools.html
  templates/engage/cloud-economics.html
  templates/engage/deploy-ai-ml-model.html
  templates/engage/developer-desktop.html
  templates/engage/devops-cicd-webinar.html
  templates/engage/edge-month.html
  templates/engage/evolving-software.html
  templates/engage/financial-services-month.html
  templates/engage/fingbox-case-study.html
  templates/engage/future-proof-iot.html
  templates/engage/hiri-case-study.html
  templates/engage/index.html
  templates/engage/industrial-drones.html
  templates/engage/iot-business-model.html
  templates/engage/iot-disk-encryption.html
  templates/engage/k8s-allan-gray.html
  templates/engage/kernel-telco-nfv.html
  templates/engage/lxd-whitepaper.html
  templates/engage/modern-cloud.html
  templates/engage/multi-cloud-guide.html
  templates/engage/northstar.html
  templates/engage/robot-operating-system-choice.html
  templates/engage/shift-to-app-store-experience.html
  templates/engage/starting-with-ai.html
  templates/engage/ubuntu-18-10.html
  templates/engage/ubuntu-compliance.html
  templates/engage/ubuntu-core-and-kura.html
  templates/engage/ubuntu-lime-telco.html
  templates/engage/vmware-to-openstack.html
  templates/engage/whitepaper-iot-security.html
Labels: Review: Code +1, Review: QA +1

#6054 Kata containers engage page and takeover
  templates/engage/_base_engage_markdown.html
  templates/engage/index.html
  templates/engage/kata-containers-webinar.md
  templates/index.html
  templates/takeovers/_kata-containers.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6057 Check the nav exists before adding event listeners
  static/js/navigation.js
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#6063 Refactor to better handle expired tokens
  webapp/api/__init__.py
  webapp/api/advantage.py
  webapp/app.py
  webapp/auth.py
  webapp/login.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#6061 Typos and style in webinars paragraph
  templates/legal/data-privacy/index.html
Labels: Review: Code +1, Review: QA +1

#6058 Add welcome sanger engage page
  templates/engage/index.html
  templates/engage/wellcome-sanger-case-study.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6059 Ceph page
  templates/ceph/base_ceph.html
  templates/ceph/contact-us.html
  templates/ceph/index.html
  templates/ceph/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6064 Add tag name to /blog/tag/<tag_name> pages title
  templates/blog/tag.html
Labels: Review: Code +1, Review: QA +1

#6042 Update /iot page
  templates/internet-of-things/index.html
  templates/shared/pricing/_smart-start-prices.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6067 Capture advantage API exceptions in Sentry
  webapp/api/advantage.py
  webapp/views.py
Labels: Review: Code needed, Review: QA needed

#6075 Removed locale from kata takeover
  templates/takeovers/_kata-containers.html
Labels: Review: Code +1, Review: QA +1

#6074 Switch Ubuntu 19.10 takeover buttons
  templates/takeovers/_1910_takeover.html
Labels: Review: Code +1, Review: QA +1

#6076 [Docs] - minor updates to K8s pages
  templates/kubernetes/docs/cni-canal.md
  templates/kubernetes/docs/cni-flannel.md
Labels: Review: QA +1

#6080 add new suru type for featured blog posts section
  static/sass/_pattern_strip.scss
  templates/_docs/strips.html
  templates/blog/featured-articles.html
Labels: Review: Code +1, Review: Design +1

#6091 Update webinar link
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#6079 Create dell openstack reference architecture engage page
  templates/engage/dell-openstack-reference-architecture.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6077 New Dell k8s reference architecture engage page
  templates/engage/dell-k8s-reference-architecture.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6084 Display 11 blog posts per page
  requirements.txt
  templates/blog/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#6072 Tests changes
  .circleci/config.yml
Labels: Review: Code +1

#6065 Create Dell partner page and contact-form
  redirects.yaml
  templates/dell/base_dell.html
  templates/dell/contact-us.html
  templates/dell/index.html
  templates/dell/thank-you.html
  templates/internet-of-things/appstore.html
  templates/shared/forms/interactive/_partner-dell.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6094 Updated datasheet on /openstack/consulting
  templates/openstack/consulting.html
Labels: Review: Code +1, Review: QA +1

#6098 Add form for kubecon meetings
  templates/contact-us/form/index.html
Labels: Review: Code +1, Review: QA +1

#6102 add blog-header suru to /robotics
  static/sass/_pattern_strip.scss
  templates/_docs/strips.html
  templates/blog/topics/robotics.html
Labels: Review: Code +1, Review: Design +1

#6107 Add mirror list to dockerfile build
  Dockerfile
Labels: Review: Code +1, Review: QA needed

#6095 Update the messaging in the ESM drop down
  templates/advantage/index.html
Labels: Review: Code +1, Review: UX +1

#6112 Contact us illustration and column width updated
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#6113 Private cloud takeover
  templates/engage/_base_engage_markdown.html
  templates/engage/index.html
  templates/engage/private-cloud-build-webinar.md
  templates/index.html
  templates/takeovers/_private-cloud-build-takeover.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6108 Ensure forms in blog posts inherit URL UTM params
  static/js/navigation.js
Labels: Review: Code +1, Review: QA +1

#6117 fix typo
  templates/community/code-of-conduct.html
Labels: Review: Code +1, Review: QA +1

#6118 Add headers to advantage page
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#6121 add blog-header suru to /blog/press-center
  templates/blog/press-centre.html
Labels: Review: Code +1, Review: Design +1

#6096 Implement GeoIP directly on the /download/*/thank-you pages
  Dockerfile
  requirements.txt
  webapp/views.py
Labels: Don't merge, Review: Code +1, Review: QA +1

#6126 Fix feed issue with articles without category
  requirements.txt
Labels: Review: QA +1

#6119 Re-enable multistage builds to reduce docker image size
  .dockerignore
  Dockerfile
  config_list.txt
  scripts/generate_ia_csv.py
  scripts/generate_ia_txt.py
  sitemap.xml.gz
Labels: Review: Code +1, Review: QA +1

#6130 fix case inaccuracy on "private cloud builds"
  templates/engage/private-cloud-build-webinar.md
  templates/takeovers/_private-cloud-build-takeover.html
Labels: Review: QA +1

#6133 Update dell laptop image on /dell
  templates/dell/index.html
Labels: Review: Design +1, Review: QA +1

#6134 Port redirects from the legacy Apache frontend
  redirects.yaml
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#6132 Add ubuntu security takeover and engage
  templates/engage/index.html
  templates/engage/linux_security_webinar.md
  templates/index.html
  templates/takeovers/_linux-security_takeover.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#6085 Add links to advantage
  templates/esm/index.html
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#6083 Simplify row expansion and add FIPS + EAL warnings
  static/sass/styles.scss
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#6127 Update Kubernetes release chart
  static/js/chart.js
  static/js/chartData.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#6141 Add kubecon19 banner
  templates/index.html
  templates/takeovers/_kubecon19.html
Labels: Review: Code +1, Review: QA +1

#6142 Remove kata containers takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#6147 Stop automatically redirecting Chinese language users
  redirects.yaml
  templates/index.html
  templates/shared/_notice_default.html
Labels: Review: Code +1, Review: QA +1

#6151 Update the livepatch link
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#6149 Move device download pages to /download
  navigation.yaml
  redirects.yaml
  templates/download/intel-iei-tank-870.html
  templates/download/intel-joule-desktop.html
  templates/download/intel-joule.html
  templates/download/intel-nuc-desktop.html
  templates/download/intel-nuc.html
  templates/download/iot/index.html
  templates/download/kvm.html
  templates/download/orange-pi-zero.html
  templates/download/qualcomm-dragonboard-410c.html
  templates/download/raspberry-pi-2-3-core.html
  templates/download/raspberry-pi-compute-module-3.html
  templates/download/raspberry-pi.html
  templates/download/samsung-artik-5-10-server.html
  templates/download/samsung-artik-5-10.html
  templates/download/up-squared-iot-grove-server.html
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: QA +1

#6150 Add server documention
  navigation.yaml
  requirements.txt
  static/sass/_layout-documentation.scss
  templates/docs/base_docs.html
  templates/docs/document.html
  templates/templates/_navigation.html
  templates/templates/footer.html
  templates/templates/header_noscript.html
  webapp/app.py
  webapp/context.py
Labels: Review: Code +1, Review: QA +1

#6143 Update OSM section on /telecommunications page
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#6144 Update title of /internet-of-things/appstore page
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: QA +1

#6163 Fix the attached machine count
  webapp/views.py
Labels: Review: Code +1

#6158 [Docs] updates to k8s registry docs
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/operations.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#6159 Define of "free personal subscription" when logged in
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#6169 Update /pricing page
  templates/pricing/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6171 Redirect /aws/pro to /support
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#6170 Update /openstack/install command + update server docs links
  templates/openstack/install.html
  templates/shared/contextual_footers/_download_documentation.html
  templates/shared/contextual_footers/_download_server_guide.html
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#6181 Update /blog/topics/snapcraft hero section
  templates/blog/topics/snapcraft.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6172 Update /esm ITstrategen strip
  static/sass/_pattern_strip.scss
  templates/esm/index.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#6179 Update /blog/topics/design hero section
  templates/blog/topics/design.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6182 Remove kubcon19 notice
  templates/index.html
  templates/takeovers/_kubecon19.html
Labels: Review: Code +1, Review: QA +1

#6188 Add automotive to contact-us and thank-you
  templates/internet-of-things/contact-us.html
  templates/internet-of-things/thank-you.html
  templates/shared/_thank_you.html
Labels: Review: Code +1, Review: QA +1

#6189 Update enterprise dropdown
  templates/templates/_navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#6186 [Docs] Update links and notes for K8s ck2 release
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/release-notes.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#6180 update /blog/topics/maas hero section
  templates/blog/topics/maas.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6183 Update /blog/topics/juju hero section
  templates/blog/topics/juju.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6190 Update /blog/desktop hero
  templates/blog/desktop.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6191 Blog header updates
  static/sass/_pattern_strip.scss
  templates/_docs/strips.html
  templates/blog/cloud-and-server.html
  templates/blog/desktop.html
  templates/blog/internet-of-things.html
  templates/blog/press-centre.html
  templates/blog/topics/design.html
  templates/blog/topics/juju.html
  templates/blog/topics/maas.html
  templates/blog/topics/robotics.html
  templates/blog/topics/snapcraft.html
Labels: Review: QA +1

#6193 Fix spacing in code examples on the IOT installation media page
  templates/download/iot/installation-media.html
Labels: Review: Code +1, Review: QA +1

#6192 Add preconnect for Cloudinary
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#6197 Redirect old vmware landing page
  redirects.yaml
  templates/engage/index.html
Labels: Review: Code +1, Review: QA +1

#6106 Add mir engage page
  templates/engage/build-smart-devices-with-mir-whitepaper.md
  templates/engage/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#6195 Corrects STIG link
  templates/security/certifications.html
Labels: Review: Code +1
