Repository canonical/ubuntu.com, pull requests merged in 2019-01, with the labels that each got.

#4538 Update the k8s add-on pricing copy
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#4531 Remove news page from Kubernetes docs
  navigation.yaml
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/news.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1, Review: QA +1

#4543 Move UASD to markdown
  static/sass/_layout-documentation.scss
  static/sass/_layout-legal-pages.scss
  static/sass/styles.scss
  templates/legal/_base_legal_markdown.html
  templates/legal/shared/_appendix-management-escalation.md
  templates/legal/shared/_appendix-support-process.md
  templates/legal/shared/_appendix-support-process_toc.html
  templates/legal/shared/_appendix-support-scope.md
  templates/legal/shared/_appendix-support-scope_toc.html
  templates/legal/shared/_uasd_toc.html
  templates/legal/ubuntu-advantage-service-description/index.html
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/legal/ubuntu-advantage/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#4544 Remove takeovers to match the content tracker
  templates/index.html
Labels: Review: Code needed, Review: UX needed

#4548 Update esm 12 04
  static/js/chartData.js
  templates/legal/terms-and-policies/contact-us.html
Labels: Review: Code +1, Review: QA +1

#4554 Added microk8s takeover into rotation
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#4553 Remove the IBM message on the homepage
  templates/base_index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4557 Fixed bad anchor link on /legal/ubuntu-advantage-service-description
  templates/legal/shared/_appendix-support-scope_toc.html
Labels: Review: Code +1, Review: QA +1

#4565 Add GDPR compilance to the core contact us modal
  templates/core/index.html
Labels: Review: Code +1, Review: QA +1

#4567 Bump the global nav to 1.2.1
  package.json
  static/js/global-nav.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4561 Fix form validation on /legal/terms-and-policies/contact-us
  templates/legal/terms-and-policies/contact-us.html
Labels: Review: Code +1, Review: QA +1

#4558 Added noindex various thank you pages
  templates/ai/thank-you.html
  templates/kubernetes/thank-you.html
  templates/legal/contributors/thank-you.html
  templates/openstack/newsletter-thank-you.html
  templates/support/thank-you.html
Labels: Review: Code +1, Review: QA +1

#4560 Remove Mythbuntu from download dropdown
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: QA +1

#4559 Added border to tables and removed global nav links in print styles
  static/sass/print.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4570 Fixed use of greater thans and less thans in code examples
  templates/download/iot/installation-media.html
Labels: Review: Code +1, Review: QA +1

#4573 Removed non-Vanilla matrix
  static/sass/_pattern_matrix.scss
  static/sass/styles.scss
  templates/internet-of-things/robotics.html
  templates/openstack/storage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4576 Launch the core 18 takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#4578 Add modal contact us form to the IoT section of the site
  templates/core/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/robotics.html
  templates/shared/forms/_modal_form.html
Labels: Review: Code +1, Review: QA +1

#4580 Add a badge to display the Django version number
  README.md
Labels: Review: QA +1

#4583 Add UTM to the core 18 takeover
  templates/takeovers/_ubuntu-core-18-takeover.html
Labels: Review: Code needed, Review: QA needed

#4582 Update raspberry pi download instructions
  templates/download/iot/raspberry-pi-2-3.html
Labels: Review: Code +1, Review: QA +1

#4574 Build the brand store takeover
  templates/index.html
  templates/takeovers/_snapcraft-brand-store_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4585 Update to Django v1.11.18
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4584 Enable renovate with standard config
  renovate.json
Labels: Review: Code +1, Review: QA +1

#4581 Ubuntu Core: Remove caveat for older RPi kernel
  templates/download/iot/raspberry-pi-2-3.html
Labels: Review: Code +1

#4586 Build the broadsign-arrow takeover
  templates/takeovers/_broadsign-arrow_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#4603 Fix link to the partners contact-us on the ai overview
  redirects.yaml
  templates/ai/index.html
Labels: Review: Code +1, Review: QA +1

#4598 Add Kubernetes to release cycle page
  static/js/chart.js
  static/js/chartData.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4606 Split the dynamic contact functionality out
  static/js/dynamic-contact-form.js
  templates/shared/forms/_modal_form.html
Labels: Review: Code +1, Review: QA +1

#4608 Enable the brand store takeover
  templates/core/index.html
  templates/index.html
  templates/takeovers/_snapcraft-brand-store_takeover.html
Labels: Review: Code needed, Review: QA needed

#4612 Update Intel NUC desktop image link copy
  templates/download/iot/intel-nuc-desktop.html
Labels: Copy update, Review: Code +1, Review: QA +1

#4604 Cleaned up intel joule desktop install instructions
  templates/download/iot/intel-joule-desktop.html
Labels: Review: Code +1, Review: QA +1

#4613 Swap the core landing page takeover
  templates/core/index.html
Labels: Review: Code +1, Review: QA +1

#4605 Kubernetes docs updates
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/upgrading.md
Labels: Review: QA +1

#4618 Updated /support with ESM and general clean-ups
  templates/shared/_case-study-itstrategen.html
  templates/shared/_systems-management-tool.html
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#4621 Remove hidden ebook forms
  templates/download/server/thank-you.html
  templates/download/shared/_get_ebook_v1.html
Labels: Review: Code +1, Review: QA +1

#4617 Update ESM and add FAQ page
  navigation.yaml
  templates/esm/faq.html
  templates/esm/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4623 ESM landing page in french
  templates/engage/fr/esm.html
  templates/engage/fr/openstack-made-easy.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4609 Create general dynamic form
  package.json
  static/js/dynamic-contact-form.js
  static/sass/_pattern_contact-modal.scss
  static/sass/styles.scss
  templates/about/base_about.html
  templates/ai/base_ai.html
  templates/ai/features.html
  templates/ai/index.html
  templates/ai/install.html
  templates/community/_base_community.html
  templates/containers/base_containers.html
  templates/containers/index.html
  templates/core/index.html
  templates/desktop/base_desktop.html
  templates/desktop/organisations.html
  templates/download/_base_download.html
  templates/esm/base_esm.html
  templates/esm/index.html
  templates/financial-services/index.html
  templates/internet-of-things/base_things.html
  templates/kubernetes/base_kubernetes.html
  templates/kubernetes/docs/base_docs.html
  templates/kubernetes/features.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/livepatch/base_livepatch.html
  templates/livepatch/index.html
  templates/openstack/_base_openstack.html
  templates/openstack/consulting.html
  templates/openstack/features.html
  templates/openstack/index.html
  templates/openstack/install.html
  templates/openstack/managed.html
  templates/openstack/partners.html
  templates/openstack/storage.html
  templates/openstack/training.html
  templates/public-cloud/_base_public-cloud.html
  templates/rfp/_base_rfp.html
  templates/security/index.html
  templates/server/base_server.html
  templates/server/hyperscale.html
  templates/server/index.html
  templates/shared/forms/interactive/_general.html
  templates/support/base_support.html
  templates/support/plans-and-pricing.html
  templates/telecommunications/index.html
  templates/templates/base.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4625 Remove the bespoke suru background strip
  static/sass/styles.scss
  templates/internet-of-things/appstore.html
  templates/support/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4611 Embedded dynamic form
  templates/core/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/robotics.html
  templates/shared/forms/interactive/_embedded.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
