Repository canonical/ubuntu.com, pull requests merged in 2019-07, with the labels that each got.

#5402 Remove p-list-step__bullet
  templates/ai/install.html
  templates/download/iot/_flash-image.html
  templates/download/iot/_setup-ubuntu-sso.html
  templates/download/iot/installation-media.html
  templates/download/iot/intel-iei-tank-870.html
  templates/download/iot/intel-joule-desktop.html
  templates/download/iot/intel-joule.html
  templates/download/iot/intel-nuc-desktop.html
  templates/download/iot/intel-nuc.html
  templates/download/iot/kvm.html
  templates/download/iot/orange-pi-zero.html
  templates/download/iot/qualcomm-dragonboard-410c.html
  templates/download/iot/raspberry-pi-2-3-core.html
  templates/download/iot/raspberry-pi-2-3.html
  templates/download/iot/raspberry-pi-compute-module-3.html
  templates/download/iot/samsung-artik-5-10-server.html
  templates/download/iot/samsung-artik-5-10.html
  templates/download/iot/up-squared-iot-grove-server.html
  templates/download/server/provisioning.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/livepatch/index.html
  templates/openstack/install.html
  templates/openstack/managed.html
Labels: Review: Code +1, Review: QA +1

#5406 Update location of brandmark zip files
  templates/blog/cloud-and-server.html
  templates/blog/internet-of-things.html
  templates/blog/press-centre.html
  templates/engage/14-04-esm.html
  templates/legal/font-licence/differences.html
  templates/legal/font-licence/faq.html
  templates/legal/font-licence/index.html
  templates/legal/intellectual-property-policy/index.html
  templates/legal/ua-miracle-tc-ja.html
  templates/legal/ua-miracle-tc.html
  templates/legal/ubuntu-advantage-service-description/_base_legal_markdown.html
  templates/legal/ubuntu-advantage-service-description/ja/_base_legal_markdown_ja.html
  templates/legal/ubuntu-advantage-service-terms/2015-06-24.html
  templates/legal/ubuntu-advantage-service-terms/2015-09-09.html
  templates/legal/ubuntu-advantage-service-terms/2016-05-20.html
  templates/legal/ubuntu-advantage-service-terms/2016-06-24.html
  templates/legal/ubuntu-advantage-service-terms/ja.html
  templates/shared/contextual_footers/_download_enterprise_support.html
  templates/takeovers/_1710_takeover.html
  templates/takeovers/_advantage.html
  templates/takeovers/_openstack_security_takeover.html
  templates/takeovers/_takeover-help.html
Labels: Review: Code +1, Review: QA +1

#5407 Update links to insights.u.c to blog
  redirects.yaml
  templates/desktop/developers.html
  templates/desktop/partners.html
  templates/desktop/statistics.html
  templates/engage/14-04-esm.html
  templates/engage/events.html
  templates/engage/small-robot-company.html
  templates/financial-services/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/robotics.html
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/index.html
  templates/kubernetes/managed.html
  templates/openstack/features.html
  templates/public-cloud/index.html
  templates/security/index.html
  templates/shared/contextual_footers/_maas-faq.html
  templates/telecommunications/index.html
  templates/training/index.html
  templates/whitepapers/beta/robotics.html
  templates/whitepapers/robotics/index.html
Labels: Review: Code +1, Review: QA +1

#5408 Port redirects from blog.ubuntu.com
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5414 K8s Services datasheet + page changes
  templates/kubernetes/index.html
  templates/kubernetes/managed.html
  templates/pricing/consulting.html
Labels: Review: Code +1, Review: QA +1

#5404 K8s docs misc updates
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/overview.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/using-vault.md
Labels: Review: Code +1

#5412 Add buy.u.c cta back to /pricing and /pricing/infra
  templates/esm/index.html
  templates/livepatch/index.html
  templates/pricing/index.html
  templates/pricing/infra.html
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#5416 Update /advantage redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5418 Bump blog to v2.0.13
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5421 Bump blog to v2.0.14
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5420 K8s backups documentation updates
  navigation.yaml
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1

#5427 Fix-up /training page contact-us
  templates/training/_base_training.html
  templates/training/contact-us.html
  templates/training/index.html
  templates/training/thank-you.html
Labels: Review: Code +1, Review: QA +1

#5425 Update /support/thank-you page
  templates/support/thank-you.html
Labels: Review: Code +1, Review: QA +1

#5428 Remove un-needed front-matter
  .github/pull_request_template.md
Labels: Review: QA +1

#5423 Add training strips to /kubernetes and /openstack
  templates/kubernetes/index.html
  templates/openstack/index.html
  templates/shared/_training.html
Labels: Review: Code +1, Review: QA +1

#5426 Add anchor to on /download/iot for /core links
  templates/core/index.html
  templates/download/iot/index.html
  templates/takeovers/_ubuntu-core-18-takeover.html
Labels: Review: Code +1, Review: QA +1

#5429 Update Nuc and Tank870 UC18 images locations
  templates/download/iot/intel-iei-tank-870.html
  templates/download/iot/intel-nuc.html
Labels: Review: Code +1

#5433 Update badges
  README.md
Labels: Review: QA +1

#5432 Change 32M to 32m for macs
  templates/download/iot/installation-media.html
Labels: Review: Code +1, Review: QA +1

#5434 Links “Deb, snap, and charm packages” to Packages page
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#5437 Change text of edge month takeover
  templates/takeovers/_edge-month_takeover.html
Labels: Review: Code +1, Review: QA +1

#5438 Fix typo
  templates/takeovers/_edge-month_takeover.html
Labels: Review: QA +1

#5431 Update to product cards
  templates/blog/product-cards.html
Labels: Review: Code +1

#5441 Updated text on the lime takeover
  templates/takeovers/_ubuntu-lime-telco_takeover.html
Labels: Review: Code +1, Review: QA +1

#5442 Corrects PaddlePaddle link and text
  templates/templates/_navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#5456 Add City Network OpenStack cloud hosting case study engage page
  templates/engage/casestudy-city-network.html
Labels: Review: Code +1, Review: QA +1

#5447 Add 451 cloud economics engage page
  templates/engage/451-cloud-economics.html
Labels: Review: Code +1, Review: QA +1

#5455 Add essential guide for telecoms adopting big data solutions engage page
  templates/engage/essential-guide-big-data-solutions.html
Labels: Review: Code +1, Review: QA +1

#5449 Add OpenStack for telcos engage page
  templates/engage/openstack-telco-clouds.html
Labels: Review: Code +1, Review: QA +1

#5450 Add NVF and SDN on Openstack engage page
  templates/engage/nfv-sdn-openstack.html
Labels: Review: Code +1, Review: QA +1

#5451 Add CTO's guide to SDN, NFV & VNF engage page
  templates/engage/cto-guide-sdn-nfv-vnf.html
Labels: Review: Code +1, Review: QA +1

#5457 exclude kubeflow news from u.c/blog
  templates/shared/_insights_news_strip.html
  templates/shared/contextual_footers/_cloud_further_reading.html
  templates/shared/contextual_footers/_desktop_further_reading.html
  templates/shared/contextual_footers/_further_reading.html
  templates/shared/contextual_footers/_iot_further_reading.html
  templates/shared/contextual_footers/_security_further_reading.html
  templates/shared/contextual_footers/_telco_further_reading.html
  webapp/settings.py
Labels: Review: Code +1

#5453 Add low latency and real time kernels for telco and NFV engage page
  templates/engage/low-latency-report.html
Labels: Review: Code +1, Review: QA +1

#5454 Add Carrier Cloudification engage page
  templates/engage/telco-cloudification-ebook.html
Labels: Review: Code +1, Review: QA +1

#5448 Add OpenStack made easy engage page
  templates/engage/openstack-made-easy.html
Labels: Review: Code +1, Review: QA +1

#5446 Copyedits and changes “xzcat” to “gunzip”
  templates/download/iot/installation-media.html
Labels: Review: Code +1, Review: QA +1

#5444 Center align and max-width for wordpress figures
  static/sass/styles.scss
  templates/blog/article.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5467 Update edge month engage page to match the copy doc
  templates/engage/edge-month.html
Labels: Review: Code +1, Review: QA +1

#5476 [Engage] Add Rocket.Chat case study page
  templates/engage/casestudy-rocketchat.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5475 [Engage] Add IMS Evolve case study page
  templates/engage/casestudy-imsevolve.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5474 [Engage] Add Cinergy case study page
  templates/engage/casestudy-cinergy.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5472 [Engage] Add Nexiona case study page
  templates/engage/casestudy-nexiona.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5470 [Engage] Add Azlogica case study page
  templates/engage/casestudy-azlogica.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5465 [Engage] Add BotsAndUs case study page
  templates/engage/casestudy-botsandus.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5464 [Engage] Add Commercetools case study page
  templates/engage/casestudy-commercetools.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5459 Add How to escape from StuckStack ebook engage page
  templates/engage/stuckstack-ebook.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5461 Add ITstrategen case study engage page
  templates/engage/casestudy-itstratagen.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5481 Set a page_utms context var when links need inheritance of parent page UTMs
  templates/engage/edge-month.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5460 Add How to face the challenges of becoming a cloud operator engage page
  templates/engage/cloud-fray.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5480 [Engage] Add server provisioning eBook page
  templates/engage/ebook-maas.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5478 [Engage] Add private cloud eBook page
  templates/engage/private-cloud.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5473 [Engage] Add InnovaPOS case study page
  templates/engage/casestudy-innovapos.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5469 [Engage] Add containers whitepaper page
  templates/engage/whitepaper-containers.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5466 [Engage] azeti case study page
  templates/engage/casestudy-azeti.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5468 [Engage] Add IoT security whitepaper page
  templates/engage/whitepaper-iot-security.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5486 Add redirect from /IP to the legal page
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5482 Moved the verify checksum into an accordian
  static/sass/styles.scss
  templates/download/server/thank-you.html
  templates/download/shared/_verify-checksums.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5462 Add Sensape case study engage page
  templates/engage/casestudy-sensape.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5477 [Engage] Add Whats new in Ubuntu 14.04 LTS page
  templates/engage/whats-new-ubuntu-14-04-lts.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5479 [Engage] Add public cloud on Ubuntu OpenStack eBook page
  templates/engage/public-cloud.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5488 Update the UA datasheet
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#5492 Email address -> Work email in interactive forms
  templates/shared/forms/interactive/_bootstack.html
  templates/shared/forms/interactive/_embedded.html
  templates/shared/forms/interactive/_general.html
  templates/shared/forms/interactive/_kubeflow.html
  templates/shared/forms/interactive/_kubernetes.html
  templates/shared/forms/interactive/_openstack.html
  templates/shared/forms/interactive/_pricing-infra.html
  templates/shared/forms/interactive/_robotics.html
  templates/shared/forms/interactive/_support-openstack.html
  templates/shared/forms/interactive/_support.html
Labels: Review: Code +1, Review: QA +1

#5555 [Engage] Update metadata syntax for multi cloud guide page
  templates/engage/multi-cloud-guide.html
Labels: Review: Code +1, Review: QA +1

#5556 [Engage] Update metadata syntax for essential guide for big data page
  templates/engage/essential-guide-big-data-solutions.html
Labels: Review: Code +1, Review: QA +1

#5557 [Engage] Update metadata syntax for Hiri case study page
  templates/engage/hiri-case-study.html
Labels: Review: Code +1, Review: QA +1

#5559 [Engage] Update metadata syntax on 451 cloud economics page
  templates/engage/451-cloud-economics.html
Labels: Review: Code +1, Review: QA +1

#5560 [Engage] Update metadata syntax for 14-04 ESM page
  templates/engage/14-04-esm.html
Labels: Review: Code +1

#5561 [Engage] Update metadata syntax for events page
  templates/engage/events.html
Labels: Review: Code +1, Review: QA +1

#5490 Add /engage index
  redirects.yaml
  templates/engage/index.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5562 Add a new strip for BT on the homepage
  templates/index.html
  templates/takeovers/_bt_announcement.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5558 Update /telecommunications page
  templates/shared/contextual_footers/_telco_further_reading.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#5563 Update bt link
  templates/takeovers/_bt_announcement.html
Labels: Review: QA +1

#5399 Build: Overview Default suru strip - /iot
  static/sass/_pattern_blog-suru.scss
  static/sass/_pattern_strip.scss
  templates/blog/cloud-and-server.html
  templates/blog/desktop.html
  templates/blog/internet-of-things.html
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5565 Fix typo on BT strip
  templates/takeovers/_bt_announcement.html
Labels: Review: Code +1, Review: QA +1

#5549 [Engage] Update metadata syntax for VMware to Openstack page
  templates/engage/vmware-to-openstack.html
Labels: Review: Code +1, Review: QA +1

#5550 [Engage] Update metadata syntax for core18 security page
  templates/engage/core18-security.html
Labels: Review: Code +1, Review: QA +1

#5552 [Engage] Update metadata syntax for openstack telco clouds page
  templates/engage/openstack-telco-clouds.html
Labels: Review: Code +1, Review: QA +1

#5551 [Engage] Update metadata syntax for openstack security webinar page
  templates/engage/openstack-security-webinar.html
Labels: Review: Code +1, Review: QA +1

#5554 [Engage] Update metadata syntax for IoT devops page
  templates/engage/iot-devops.html
Labels: Review: Code +1, Review: QA +1

#5553 [Engage] Update metadata syntax for city network case study page
  templates/engage/casestudy-city-network.html
  templates/templates/_extra_metadata.html
Labels: Review: Code +1, Review: QA +1

#5590 [Engage] Update metadata syntax for deploy AI/ML model page
  templates/engage/deploy-ai-ml-model.html
Labels: Review: Code +1, Review: QA +1

#5593 [Engage] Update metadata syntax for modern cloud page
  templates/engage/modern-cloud.html
Labels: Review: Code +1, Review: QA +1

#5594 [Engage] Update metadata syntax for DevOps IoT webinar page
  templates/engage/devops-iot-webinar.html
Labels: Review: Code +1, Review: QA +1

#5595 [Engage] Update metadata syntax for OpenStack made easy page
  templates/engage/openstack-made-easy.html
Labels: Review: Code +1, Review: QA +1

#5596 [Engage] Update metadata syntax for industrial drones case study page
  templates/engage/industrial-drones-case-study.html
Labels: Review: Code +1, Review: QA +1

#5597 [Engage] Update metadata syntax for financial services month page
  templates/engage/financial-services-month.html
Labels: Review: Code +1, Review: QA +1

#5598 [Engage] Update metadata syntax for CTO's guide to SDN, NFV and VNF page
  templates/engage/cto-guide-sdn-nfv-vnf.html
Labels: Review: Code +1, Review: QA +1

#5599 [Engage] Update metadata syntax for OpenStack security whitepaper page
  templates/engage/openstack-security-whitepaper.html
Labels: Review: Code +1, Review: QA +1

#5600 [Engage] Update metadata syntax for low latency report page
  templates/engage/low-latency-report.html
Labels: Review: Code +1, Review: QA +1

#5603 [Engage] Delete duplicate of ITstrategen case study page
  templates/engage/casestudy-itstratagen.html
Labels: Review: Code +1, Review: QA +1

#5606 [Engage] Update metadata syntax for DE VMware to OpenStack page
  templates/engage/de/vmware-to-openstack.html
Labels: Review: Code +1, Review: QA +1

#5607 [Engage] Update metadata syntax of DE OpenStack made easy page
  templates/engage/de/openstack-made-easy.html
Labels: Review: Code +1, Review: QA +1

#5608 [Engage] Update metadata syntax for snap deltas page
  templates/engage/snap-deltas.html
Labels: Review: Code +1, Review: QA +1

#5609 [Engage] Update metadata syntax for 19.04 webinar page
  templates/engage/19-04-webinar.html
Labels: Review: Code +1, Review: QA +1

#5605 [Engage] Update metadata syntax for finserv multi cloud page
  templates/engage/finserv-multi-cloud.html
Labels: Review: Code +1, Review: QA +1

#5601 [Engage] Update metadata syntax for future proof IoT page
  templates/engage/future-proof-iot.html
Labels: Review: Code +1, Review: QA +1

#5591 [Engage] Update metadata syntax for telco cloudification page
  templates/engage/telco-cloudification-ebook.html
Labels: Review: Code +1, Review: QA +1

#5589 [Engage] Update metadata syntax for IoT business model page
  templates/engage/iot-business-model.html
Labels: Review: Code +1, Review: QA +1

#5588 [Engage] Update metadata syntax for Cloud-init page
  templates/engage/cloud-init-whitepaper.html
Labels: Review: Code needed, Review: QA needed

#5610 [Engage] Update metadata syntax for AI and ML with Ubuntu page
  templates/engage/ai-ml-ubuntu.html
Labels: Review: Code +1, Review: QA +1

#5586 [Engage] Update metadata syntax for heading help page
  templates/engage/_heading-help.html
Labels: Review: Code +1, Review: QA +1

#5585 [Engage] Update metadata syntax for 451 automotive page
  templates/engage/451-automotive.html
Labels: Review: Code +1, Review: QA +1

#5584 [Engage] Update metadata syntax for cloud economics page
  templates/engage/cloud-economics.html
Labels: Review: Code +1, Review: QA +1

#5583 [Engage] Update metadata syntax for Ubuntu 18.10 page
  templates/engage/ubuntu-18-10.html
Labels: Review: Code +1, Review: QA +1

#5582 [Engage] Update metadata syntax for DevOps CI/CD page
  templates/engage/devops-cicd-webinar.html
Labels: Review: Code needed, Review: QA needed

#5581 [Engage] Update metadata syntax for FR OpenStack made easy page
  templates/engage/fr/openstack-made-easy.html
Labels: Review: Code needed, Review: QA needed

#5579 [Engage] Update metadata syntax for FR VMware page
  templates/engage/fr/vmware-to-openstack.html
Labels: Review: Code needed, Review: QA needed

#5578 [Engage] Update metadata syntax for FR ESM page
  templates/engage/fr/esm.html
Labels: Review: Code +1, Review: QA +1

#5577 [Engage] Update metadata syntax for IoT disk encryption page
  templates/engage/iot-disk-encryption.html
Labels: Review: Code +1, Review: QA +1

#5612 Button text to "Watch the webinar"
  templates/engage/edge-month.html
Labels: Review: Code +1

#5604 [Engage] Update metadata syntax for DE what can you do with Kubernetes page
  templates/engage/de/what-can-you-do-with-kubernetes.html
Labels: Review: Code +1, Review: QA +1

#5440 Shift to app store takeover & engage page
  templates/engage/shift-to-app-store-experience.html
  templates/index.html
  templates/takeovers/_shift-to-app-store_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5572 [Engage] Update metadata syntax for ITstrategen case study page
  templates/engage/ITstrategen-case-study.html
Labels: Review: Code +1, Review: QA +1

#5571 [Engage] Update metadata syntax for evolving software page
  templates/engage/evolving-software.html
Labels: Review: Code +1, Review: QA +1

#5569 [Engage] Update metadata syntax for robot OS choice page
  templates/engage/robot-operating-system-choice.html
Labels: Review: Code +1, Review: QA +1

#5587 [Engage] Update metadata syntax for Fingbox case study page
  templates/engage/fingbox-case-study.html
Labels: Review: Code +1, Review: QA +1

#5567 [Engage] Update metadata syntax for developer desktop page
  templates/engage/developer-desktop.html
Labels: Review: Code +1, Review: QA +1

#5564 [Engage] Update metadata syntax for Northstar case study page
  templates/engage/northstar.html
Labels: Review: Code +1, Review: QA +1

#5566 [Engage] Update metadata syntax for Ubuntu Core and Kura page
  templates/engage/ubuntu-core-and-kura.html
Labels: Review: Code +1, Review: QA +1

#5580 [Engage] Update metadata syntax for kernel telco NFV page
  templates/engage/kernel-telco-nfv.html
Labels: Review: Code +1, Review: QA +1

#5575 [Engage] Update metadata syntax for LXD whitepaper page
  templates/engage/lxd-whitepaper.html
Labels: Review: Code +1, Review: QA +1

#5573 [Engage] Update metadata syntax for small robot company page
  templates/engage/small-robot-company.html
Labels: Review: Code +1, Review: QA +1

#5613 Add bottomed suru strip to IoT robotics page
  static/sass/_pattern_strip.scss
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5617 Change slug snappy to snapcraft for topic page
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#5592 Add half-and-half-reverse-suru strip
  .sass-lint.yml
  static/sass/_pattern_strip.scss
  templates/embedded/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5576 Change the IoT illustration
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5614 Updates Ubuntu Core link
  templates/shared/contextual_footers/_iot_developers.html
Labels: Review: Code +1, Review: QA +1

#5616 Add topped suru strip to IoT gateways page
  static/sass/_pattern_strip.scss
  templates/internet-of-things/gateways.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5619 Adding whitepaper and moving a link
  templates/kubeflow/consulting.html
Labels: Review: Code +1, Review: QA +1

#5622 Added UTMs to "shift to app store" takeover
  templates/takeovers/_shift-to-app-store_takeover.html
Labels: Review: Code +1, Review: QA +1

#5602 [Engage] Update metadata syntax for Microsoft active directory page
  templates/engage/microsoft-active-directory.html
Labels: Review: Code +1, Review: QA +1

#5621 Add image Suru strip to IoT digital signage page
  static/sass/_pattern_strip.scss
  templates/internet-of-things/digital-signage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5623 Add half-and-half suru strip to IoT Appstore page
  static/sass/_pattern_strip.scss
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5625 Update design of server and desktop download pages
  templates/download/desktop/thank-you.html
  templates/download/server/thank-you.html
  templates/download/shared/_verify-checksums.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5629 Fix broken link
  templates/download/iot/intel-joule.html
Labels: Review: Code +1, Review: QA +1

#5628 Update content to match copy doc
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#5630 Remove BT strip
  templates/index.html
Labels: Review: Code +1, Review: QA +1
