Repository canonical/ubuntu.com, pull requests merged in 2019-05, with the labels that each got.

#5066 Change copydoc link
  templates/download/index.html
Labels: Review: Code +1

#5062 Add devops iot webinar takeover and landing page
  templates/engage/devops-iot-webinar.html
  templates/index.html
  templates/takeovers/_devops-iot-webinar_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing needed, Review: QA +1, Review: UX +1

#5069 1117 replace old takeovers with new takeovers
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5065 5029 lxd takeover and landing page
  templates/engage/lxd-whitepaper.html
  templates/index.html
  templates/takeovers/_lxd-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5072 Update uasd page from scratch
  static/sass/_layout-legal-pages.scss
  templates/legal/shared/_uasd_toc_new.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#5073 Add cloud-init takeover and landing page
  templates/engage/cloud-init-whitepaper.html
  templates/index.html
  templates/takeovers/_cloud-init-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1, Review: UX +1

#5074 Remove 19.04 takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5076 Rename Foundation Cloud Build to Private Cloud Build
  templates/financial-services/index.html
  templates/openstack/consulting.html
  templates/openstack/contact-us.html
  templates/openstack/index.html
  templates/openstack/thank-you.html
  templates/shared/contextual_footers/_consulting_packages.html
  templates/telecommunications/index.html
Labels: Review: Code +1

#5080 Clean-up and link definitions in /uasd
  templates/legal/shared/_uasd_toc_new.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#5085 Update UA datasheet on /support
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#5089 Update snapcraft links on /desktop/developers page
  templates/desktop/developers.html
Labels: Review: Code +1, Review: QA +1

#5091 Update /pricing/infra page
  templates/pricing/infra.html
  templates/shared/pricing/_openstack-kubernetes-lma.html
  templates/shared/pricing/_ua-advanced-storage.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#5093 Update text of /uasd
  templates/legal/shared/_uasd_toc_new.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#5082 Remove promotional references to 14.04 (Trusty Tahr) as it is EOL
  templates/download/alternative-downloads.html
  templates/download/server/arm.html
  templates/livepatch/index.html
  templates/security/index.html
Labels: Review: Code +1, Review: QA +1

#5086 Add ai/consulting page
  navigation.yaml
  templates/ai/consulting.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#5068 Update release chart on /server page
  static/js/release-chart.js
  templates/shared/_release_schedule.html
Labels: Review: Code +1, Review: QA +1

#5098 Copy doc changes
  templates/openstack/managed.html
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#5099 Add auth page for Kubernetes docs
  navigation.yaml
  templates/kubernetes/docs/auth.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1, Review: QA +1

#5071 Add blog module and homepage
  redirects.yaml
  requirements.txt
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_blog-featured.scss
  static/sass/_pattern_blog-list.scss
  static/sass/_utility_crop.scss
  static/sass/pattern_blog-post.scss
  static/sass/styles.scss
  templates/blog/blog-card.html
  templates/blog/featured-articles.html
  templates/blog/index.html
  webapp/settings.py
  webapp/templatetags/utils.py
  webapp/urls.py
Labels: Review: Code +1, Review: QA +1

#5104 Add copy doc changes
  templates/ai/consulting.html
Labels: Review: Code +1, Review: QA +1

#5103 Change release table
  templates/desktop/organisations.html
Labels: Review: Code +1, Review: QA +1

#5109 More updates to /uasd
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/pricing/infra.html
  templates/security/certifications.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#5111 Remove canal from /pricing/consulting
  templates/shared/pricing/_kubernetes-consulting.html
Labels: Review: Code +1, Review: QA +1

#5107 Adds basic article page
  requirements.txt
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#5113 More /uasd changes
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#5087 Group pages
  requirements.txt
  templates/blog/cloud-and-server.html
  templates/blog/desktop.html
  templates/blog/internet-of-things.html
  templates/blog/press-centre.html
  webapp/urls.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5106 5031 iot devops landing and takeover
  templates/engage/iot-devops.html
  templates/index.html
  templates/takeovers/_iot-devops_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5123 1124 ubuntu 19.04 takeover and webinar
  templates/index.html
  templates/takeovers/_1904-webinar_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5116 Change sector heading in footer style
  static/sass/_pattern_footer.scss
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#5126 Skip global takeovers for fr and de users
  templates/takeovers/_1904-webinar_takeover.html
  templates/takeovers/_cloud-init-takeover.html
  templates/takeovers/_iot-devops_takeover.html
  templates/takeovers/_openstack_security_takeover.html
Labels: Review: QA +1

#5128 Add logic to including form validation
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#5124 Update CTAs on /openstack
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#5129 Change back to iot devops webinar takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5134 Add changes from copy doc
  templates/security/certifications.html
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#5137 Add /legal/data-privacy/esxi page
  navigation.yaml
  templates/legal/data-privacy/esxi.md
Labels: Review: Code +1, Review: QA +1

#5140 Add link to ESXi page on data privacy page
  templates/legal/data-privacy/index.html
Labels: Review: Code +1, Review: QA +1

#5141 3920 opening the menu breaks the back button
  static/js/navigation.js
Labels: Review: Code +1, Review: QA +1

#5142 Remove highlighted cards
  templates/download/cloud/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5143 Update low res logos on /download/iot page
  templates/download/iot/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5145 Remove partners logo sections
  templates/server/hyperscale.html
Labels: Review: Code +1, Review: QA +1

#5146 Change learn how to make a snap link
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: QA +1

#5147 Replace IoT DevOps webinar takeover with the whitepaper takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5144 5117 improve IoT template
  navigation.yaml
  requirements.txt
  static/sass/_pattern_blog-suru.scss
  static/sass/styles.scss
  templates/blog/blog-card.html
  templates/blog/internet-of-things.html
  templates/blog/pagination.html
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5152 Update /ai/consulting copy
  templates/ai/consulting.html
Labels: Review: Code +1, Review: QA +1

#5149 5118 improve blog desktop template
  navigation.yaml
  templates/blog/blog-card.html
  templates/blog/desktop.html
  templates/blog/internet-of-things.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5151 5119 Improve cloud and server page
  templates/blog/cloud-and-server.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5159 Create takeover template
  templates/takeovers/_takeover-help.html
  templates/takeovers/shared/_takeover.html
Labels: Review: Code +1, Review: QA +1

#5160 5130 implement blog archive
  .gitignore
  navigation.yaml
  requirements.txt
  templates/blog/archives.html
  templates/templates/_navigation.html
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5168 Fix openstack made easy french form
  templates/engage/fr/openstack-made-easy.html
Labels: Priority: High, Review: Code +1, Review: QA +1

#5164 Add a redirect for ubuntu.com/cc-eal for better search result hits
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5167 5120 improve blog press centre
  requirements.txt
  templates/blog/blog-card-large.html
  templates/blog/press-centre.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5171 5135 implement author page
  requirements.txt
  templates/blog/archives.html
  templates/blog/author.html
  templates/blog/blog-card.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5183 Update live takeovers
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5186 Remove reference to Unity's LIM
  templates/desktop/index.html
Labels: Review: Code +1, Review: QA +1

#5188 4153: Update sass-lint to fail if there are any warnings
  package.json
  static/sass/_layout-whitepapers.scss
  static/sass/_pattern_desktop-statistics.scss
  static/sass/print.scss
Labels: Review: Code +1, Review: QA +1

#5174 Add config for “Stale” Github app
  .github/stale.yml
Labels: Review: Code +1

#5182 Change to suit copy doc
  templates/download/desktop/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5187 Remove /legal/managed-services section
  navigation.yaml
  redirects.yaml
  templates/legal/index.html
  templates/legal/managed-services-description.html
  templates/legal/managed-services-privacy.html
  templates/legal/managed-services/2015-07-01.html
  templates/legal/managed-services/2018-02-15.html
  templates/legal/managed-services/2018-07-13.html
  templates/legal/managed-services/index.html
Labels: Review: Code +1, Review: QA +1

#5189 3074 remove install open stack video
  templates/openstack/install.html
Labels: Review: Code +1, Review: QA +1

#5193 5181: Reduce width of graph image on about page
  templates/about/index.html
Labels: Review: Code +1, Review: QA +1

#5191 Make use of name Charmed Kubernetes consistent
  templates/ai/install.html
  templates/kubernetes/features.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/partners.html
  templates/shared/contextual_footers/_download_more_info_enterprise.html
  templates/takeovers/_improving_productivity_kubernetes.html
Labels: Review: Code +1, Review: QA +1

#5195 Update image for app store
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: QA +1

#5197 fix scss lints
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_blog-featured.scss
  static/sass/_pattern_blog-suru.scss
Labels: Review: Code +1

#5196 "Releases" global template context
  .gitignore
  releases.yaml
  run
  templates/base_index.html
  templates/desktop/developers.html
  templates/download/alternative-downloads.html
  templates/download/desktop/index.html
  templates/download/iot/intel-iei-tank-870.html
  templates/download/iot/intel-joule-desktop.html
  templates/download/iot/intel-joule.html
  templates/download/iot/intel-nuc.html
  templates/download/iot/raspberry-pi-2-3.html
  templates/download/server/arm.html
  templates/download/server/index.html
  templates/download/server/power.html
  templates/download/server/provisioning.html
  templates/download/server/s390x.html
  templates/download/server/thank-you-s390x.html
  templates/public-cloud/index.html
  templates/server/index.html
  templates/shared/contextual_footers/_download_desktop_guide.html
  templates/shared/contextual_footers/_download_documentation.html
  templates/shared/contextual_footers/_download_server_guide.html
  templates/templates/_navigation-download-h.html
  templates/templates/base.html
  webapp/context_processors.py
  webapp/settings.py
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: QA +1

#5199 5148 fix middot alignment
  static/sass/_pattern_footer.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#5198 K8s-docs update for bugfix release
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA +1

#5202 32m -> 32M
  templates/download/iot/installation-media.html
Labels: Review: QA +1

#5194 Upgrade VF to 2.0.0-alpha.1
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5162 5122 Add newsletter signup form
  templates/blog/index.html
  templates/blog/internet-of-things.html
  templates/blog/newsletter-form.html
  templates/download/desktop/thank-you.html
  templates/shared/forms/_form-validation.html
Labels: Review: Code +1, Review: QA +1

#5205 Explicitly require pyyaml 5.1 (needed for FullLoader)
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5190 Add sha256 checksums for desktop and server downloads
  releases.yaml
  templates/download/desktop/thank-you.html
  templates/download/server/s390x.html
  templates/download/server/thank-you.html
  templates/download/shared/_verify-checksums.html
Labels: Review: Code needed, Review: Design needed, Review: QA needed

#5203 Update stale to focus on ignored issues
  .github/stale.yml
Labels: Review: Code +1

#5207 [Trivial] Fix Markdown syntax error
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#5212 5166 implement events and webinars
  requirements.txt
  static/sass/_pattern_icons.scss
  static/sass/_utility_crop.scss
  static/sass/styles.scss
  templates/blog/blog-card-upcoming.html
  templates/blog/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5216 5204 persist query params on pagination links
  requirements.txt
  templates/blog/pagination.html
  webapp/templatetags/utils.py
Labels: Review: Code +1, Review: QA +1

#5215 Add SRC landing page
  templates/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing needed, Review: QA +1

#5233 Add title to the SRC page
  templates/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots.html
Labels: Review: Code +1, Review: QA +1

#5234 Add maas topic page
  static/sass/_pattern_blog-topic.scss
  static/sass/styles.scss
  templates/blog/topics/maas.html
  webapp/urls.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5220 Core 18 security takeover and landing page
  templates/engage/core18-security.html
  templates/index.html
  templates/takeovers/_core18-security_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5226 Add font-display attribute to font loading
  static/sass/styles.scss
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#5225 Remove _html5 shiv as no longer required
  templates/shared/_html5_shiv.html
  templates/templates/base.html
  templates/templates/base_no_nav.html
Labels: Project Fuse ⚡️, Review: Code +1

#5224 Add preconnect tag to gstatic.com
  templates/templates/base.html
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#5223 5154 implement design topic page
  templates/blog/cloud-and-server.html
  templates/blog/desktop.html
  templates/blog/internet-of-things.html
  templates/blog/posts.html
  templates/blog/topics/design.html
  templates/blog/topics/maas.html
  webapp/urls.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5232 Redirect /404 and /500 to homepage
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5180 Add product context handling to forms
  static/js/dynamic-contact-form.js
  templates/shared/forms/interactive/_bootstack.html
  templates/shared/forms/interactive/_embedded.html
  templates/shared/forms/interactive/_general.html
  templates/shared/forms/interactive/_kubeflow.html
  templates/shared/forms/interactive/_kubernetes.html
  templates/shared/forms/interactive/_openstack.html
  templates/shared/forms/interactive/_pricing-infra.html
  templates/shared/forms/interactive/_robotics.html
  templates/shared/forms/interactive/_support.html
Labels: Review: Code +1, Review: QA +1

#5169 5133 Starting with AI Takeover & Engage
  templates/engage/starting-with-ai.html
  templates/index.html
  templates/takeovers/_starting-with-ai-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#5218 5123 improve blog card template
  static/sass/_pattern_blog-card.scss
  templates/blog/blog-card.html
  templates/blog/featured-articles.html
  templates/blog/index.html
  templates/blog/newsletter-form.html
  templates/blog/singular-category.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5239 1207 Update /openstack/training copy
  templates/openstack/training.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5238 451 automotive takeover landing
  .gitignore
  templates/engage/451-automotive.html
  templates/index.html
  templates/takeovers/_451-automotive_takeover.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1
