Repository canonical/ubuntu.com, pull requests merged in 2019-03, with the labels that each got.

#4754 k8sdocs update dashboard image
  templates/kubernetes/docs/quickstart.md
Labels: Review: Code +1

#4744 Add contact/help page to Kubernetes docs
  navigation.yaml
  templates/kubernetes/docs/get-in-touch.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1

#4740 Revert "update full disc encryption cta"
  templates/takeovers/_ubuntu-core-full-disk-encryption.html
Labels: Review: Code +1

#4784 Update the FDE takeover link
  templates/takeovers/_ubuntu-core-full-disk-encryption.html
Labels: Review: Code +1, Review: Design +1

#4785 Remove the Ubuntu Core 18 takeover
  templates/index.html
Labels: Review: Code +1

#4753 Remove IE conditionals
  templates/templates/base.html
  templates/templates/base_no_nav.html
Labels: Project Fuse ⚡️, Review: Code +1

#4787 Remove an FAQ from the ESM page
  templates/esm/index.html
Labels: Review: Code +1, Review: QA +1

#4788 Update to 14.04.6 from 14.04.5
  templates/download/alternative-downloads.html
  templates/download/server/power.html
Labels: Review: Code +1, Review: QA +1

#4791 Updated pricing page and related pages
  static/js/global-nav.js
  templates/kubernetes/index.html
  templates/legal/shared/_appendix-support-scope.html
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/legal/ubuntu-advantage-service-description/ja/2017-02-09.html
  templates/server/index.html
  templates/shared/pricing/_kubernetes-consulting-add-ons.html
  templates/shared/pricing/_kubernetes-consulting.html
  templates/shared/pricing/_landscape.html
  templates/shared/pricing/_livepatch.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_openstack-packages.html
  templates/shared/pricing/_storage-support.html
  templates/shared/pricing/_ua-desktop-support.html
  templates/shared/pricing/_ua-for-infrastructure-options.html
  templates/shared/pricing/_ua-for-infrastructure-physical.html
  templates/shared/pricing/_ua-for-infrastructure-virtual.html
  templates/shared/pricing/_ua-for-infrastructure.html
  templates/shared/pricing/_ua-server-support-add-ons.html
  templates/support/base_support.html
  templates/support/plans-and-pricing.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#4786 Build the CI/CD webinar takeover
  templates/engage/devops-cicd-webinar.html
  templates/index.html
  templates/takeovers/_ci-cd-webinar.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1, Review: UX +1

#4795 Update /esm page
  templates/esm/index.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#4800 add checksum links to download thank-you page
  templates/download/desktop/thank-you.html
  templates/download/server/thank-you.html
Labels: Review: Code +1, Review: QA +1

#4801 Update to the iot download next steps strip and contibute footer
  templates/download/iot/_install-snaps-strip.html
  templates/shared/contextual_footers/_core_contribute.html
Labels: Review: Code +1, Review: QA +1

#4812 Remove lang class from 3 takeovers
  templates/takeovers/_ci-cd-webinar.html
  templates/takeovers/_fin-serv-whitepaper-takeover.html
  templates/takeovers/_ubuntu-core-full-disk-encryption.html
Labels: Review: Code +1, Review: QA +1

#4811 Update datasheet on /livepatch
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#4774 Update yarn.lock
  yarn.lock
Labels: Review: QA +1

#4821 Remove some options for livepatch
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#4823 [ua4i] Remove azure and aws livepatch options from /livepatch
  templates/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#4810 Create the Compliance german takeover
  templates/index.html
  templates/takeovers/_german-compliance-webinar.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4819 Update global-nav dep to @canonical/global-nav
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4814 Update data-privacy on /enage page forms
  templates/shared/forms/_landing_page_default.html
Labels: Review: Code +1, Review: QA +1

#4825 Add resolutions against critical vulnerabilities
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA needed

#4827 Sync updated k8s release-notes into website
  templates/kubernetes/docs/release-notes.md
Labels: Review: Code +1

#4828 Add updates from k8s docs manual install
  templates/kubernetes/docs/install-manual.md
Labels: Review: Code +1

#4848 Fix use of everyday vs every day
  templates/legal/font-licence/index.html
  templates/shared/pricing/_kubernetes-enterprise-support.html
  templates/shared/pricing/_kubernetes-managed.html
  templates/shared/pricing/_landscape.html
  templates/shared/pricing/_maas-support.html
  templates/shared/pricing/_storage-support.html
  templates/shared/pricing/_ua-desktop-support.html
  templates/shared/pricing/_ua-server-support.html
Labels: Review: Code needed, Review: QA needed

#4829 Minify and combine js
  .babelrc
  .gitignore
  package.json
  static/js/chart.js
  static/js/chartData.js
  static/js/cookie-proxy.js
  static/js/core.js
  static/js/desktopStatistics.js
  static/js/dummyData.js
  static/js/release-chart.js
  templates/about/release-cycle.html
  templates/core/index.html
  templates/desktop/statistics.html
  templates/esm/index.html
  templates/shared/forms/_state.html
  templates/shared/forms/interactive/_bootstack.html
  templates/shared/forms/interactive/_embedded.html
  templates/shared/forms/interactive/_general.html
  templates/shared/forms/interactive/_kubeflow.html
  templates/shared/forms/interactive/_kubernetes.html
  templates/shared/forms/interactive/_openstack.html
  templates/shared/forms/interactive/_robotics.html
  templates/shared/forms/interactive/_support.html
  templates/templates/base.html
  webpack.config.js
  yarn.lock
Labels: Project Fuse ⚡️, Review: QA +1

#4826 New IoT board: Intel IEI Tank 870
  navigation.yaml
  templates/download/iot/index.html
  templates/download/iot/intel-iei-tank-870.html
  templates/templates/_navigation-download-h.html
Labels: Review: Code +1, Review: QA +1

#4830 Update NUC image + copy tweaks
  templates/download/iot/intel-nuc.html
Labels: Review: Code +1, Review: QA +1

#4845 Added the Partner portal privacy notice - /legal/data-privacy/partner-portal
  navigation.yaml
  templates/legal/data-privacy/contact.md
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/online-purchase.md
  templates/legal/data-privacy/partner-portal.md
  templates/legal/data-privacy/snap-store.md
  templates/legal/data-privacy/snapcraft-nps.md
  templates/legal/data-privacy/sso.md
  templates/legal/data-privacy/user-survey.md
  templates/legal/data-privacy/webinar.md
Labels: Review: Code +1, Review: QA +1

#4837 Create apparmor engage page
  templates/engage/apparmor-intro.html
  templates/engage/shared/_header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4844 Add /legal/partner-portal-terms page
  navigation.yaml
  templates/legal/_base_legal_markdown.html
  templates/legal/partner-portal-terms.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4853 Create /engage/fr/vmware-to-openstack page
  templates/engage/_heading-help.html
  templates/engage/fr/vmware-to-openstack.html
  templates/engage/shared/_header.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4856 Add french vmware to os takeover
  templates/index.html
  templates/takeovers/_french_vmware-to-os.html
Labels: Review: Code +1, Review: QA +1

#4850 K8s integration docs
  navigation.yaml
  templates/kubernetes/docs/aws-integration.md
  templates/kubernetes/docs/gcp-integration.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1, Review: QA +1

#4838 Created the engage snap deltas page
  templates/engage/shared/_header.html
  templates/engage/snap-deltas.html
Labels: Don't merge, Review: Code +1, Review: Design +1, Review: QA +1

#4858 traditionnelle -> traditionnel
  templates/takeovers/_french_vmware-to-os.html
Labels: Review: Code +1

#4857 Update terms-and-policies with partner portal
  templates/legal/terms-and-policies/index.html
Labels: Review: Code +1, Review: QA +1

#4854 Snap delta takeover
  templates/index.html
  templates/takeovers/_snap-deltas-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4861 updated button text
  templates/engage/14-04-esm.html
Labels: Review: Code needed, Review: QA needed

#4862 updated button text - takeover
  templates/takeovers/_14-04-esm.html
Labels: Review: Code +1, Review: QA +1

#4863 Update 12.04 to 14.04 on security page
  templates/security/index.html
  templates/shared/contextual_footers/_security_esm.html
Labels: Review: Code +1, Review: QA +1

#4869 1.14 updates for Kubernetes Docs
  navigation.yaml
  templates/kubernetes/docs/audit-logging.md
  templates/kubernetes/docs/decommissioning.md
  templates/kubernetes/docs/get-in-touch.md
  templates/kubernetes/docs/gpu-workers.md
  templates/kubernetes/docs/hacluster.md
  templates/kubernetes/docs/high-availability.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/tigera-secure-ee.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/using-vault.md
  templates/kubernetes/docs/validation.md
Labels: Review: Code +1, Review: QA +1

#4874 Add Basic ops for Kubernetes docs
  navigation.yaml
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: Code +1, Review: QA +1

#4882 Minor copy cange to /support
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#4871 [UA-I] updates for /uasd page
  static/sass/_layout-legal-pages.scss
  templates/legal/shared/_uasd_toc_new.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: Code +1, Review: QA +1

#4867 Language skipping for takeovers
  templates/base_index.html
  templates/index.html
  templates/takeovers/_14-04-esm.html
Labels: Review: Code +1, Review: QA +1

#4880 [UA4I] Update /esm
  templates/esm/index.html
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#4884 Small tweak to metallb page in k8s docs
  templates/kubernetes/docs/metallb.md
Labels: Review: Code +1, Review: QA +1

#4872 [UA-I] update /openstack/features
  templates/openstack/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4878 [UA4I] Update copy on /livepatch
  templates/livepatch/index.html
  templates/shared/_call-sales.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4876 [UA4I] Update /openstack/storage page
  templates/openstack/storage.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4886 Update the K8s docs for monitoring per 1.14 changes
  templates/kubernetes/docs/monitoring.md
Labels: Review: Code +1, Review: QA +1

#4892 Stopped the at&t logo from being streched
  templates/openstack/shared/_openstack_clients.html
  templates/security/index.html
  templates/support/index.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#4891 Remove cursor on non-link Sectors in footer
  static/sass/_pattern_footer.scss
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4897 Update /ai/install kubeflow instructions
  templates/ai/install.html
Labels: Review: Code +1, Review: QA +1
