Repository canonical/ubuntu.com, pull requests merged in 2019-09, with the labels that each got.

#5736 fix contact modal launcher in footer of /contact-us
  templates/contact-us/index.html
Labels: Review: Code +1, Review: QA +1

#5737 Fix 404ing groups by upgrading blog to v3.0.1
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5738 Implement basic login page
  redirects.yaml
  templates/advantage.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#5740 remove .html extension from data-form-location values
  templates/about/base_about.html
  templates/base_index.html
  templates/community/_base_community.html
  templates/contact-us/index.html
  templates/containers/base_containers.html
  templates/core/index.html
  templates/desktop/base_desktop.html
  templates/download/_base_download.html
  templates/embedded/index.html
  templates/esm/base_esm.html
  templates/financial-services/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/robotics.html
  templates/kubeflow/consulting.html
  templates/kubeflow/features.html
  templates/kubeflow/index.html
  templates/kubeflow/install.html
  templates/kubernetes/features.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/partners.html
  templates/livepatch/base_livepatch.html
  templates/openstack/consulting.html
  templates/openstack/features.html
  templates/openstack/index.html
  templates/openstack/install.html
  templates/openstack/managed.html
  templates/openstack/storage.html
  templates/openstack/what-is-openstack.html
  templates/pricing/consulting.html
  templates/pricing/index.html
  templates/pricing/infra.html
  templates/public-cloud/_base_public-cloud.html
  templates/rfp/_base_rfp.html
  templates/security/certifications.html
  templates/security/index.html
  templates/server/hyperscale.html
  templates/server/index.html
  templates/support/community-support.html
  templates/support/index.html
  templates/telecommunications/index.html
  templates/training/index.html
Labels: Review: Code +1, Review: QA +1

#5744 Add context for passing markdown variables to base.html
  templates/engage/_base_engage_markdown.html
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#5745 Restructure views
  webapp/app.py
  webapp/login.py
  webapp/macaroons.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5739 New grad template for takeovers
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/takeovers/_template.html
  templates/takeovers/templates.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5752 Add colour variations of the takeovers
  static/sass/_pattern_takeovers.scss
  templates/takeovers/_template.html
  templates/takeovers/templates.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5754 Build advantage from copy doc
  static/sass/styles.scss
  templates/advantage.html
  templates/advantage/_table.html
  templates/advantage/base_advantage.html
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5750 Parse markdown files with template parser
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5758 Add vmware takeover and engage page
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/engage/_base_engage_markdown.html
  templates/engage/vmware-to-charmed-openstack.md
  templates/index.html
  templates/takeovers/_vmware-to-charmed-openstack.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5759 Copy update install.html
  templates/openstack/install.html
Labels: Review: Code +1

#5747 Fix notices styling
  templates/shared/_notice_default.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5742 Fix logic for http tests
  templates/engage/shared/_header-case-study.html
  templates/engage/shared/_header.html
  templates/takeovers/shared/_takeover.html
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#5761 Make feed more resilient
  webapp/context.py
Labels: Review: Code needed, Review: QA needed

#5764 Add back campaign params to context
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#5760 /financial-services copy update
  templates/financial-services/index.html
Labels: Review: Code +1, Review: QA +1

#5765 Adjust lang setting on the new takeover template
  templates/takeovers/_template.html
  templates/takeovers/_vmware-to-charmed-openstack.html
Labels: Review: Code +1, Review: QA +1

#5757 Display free UA token
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5768 Properly enable FLASK_DEBUG in development; use only one worker in development
  .env
  entrypoint
Labels: Review: Code +1, Review: QA +1

#5770 Fix raw template variable in UASD legal page
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5771 Dynamic instructions
  static/sass/styles.scss
  templates/advantage/_table.html
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5773 Apply design to the personal section of the UA dashboard
  static/sass/styles.scss
  templates/advantage/_table.html
  templates/advantage/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5774 Add buy.u.c takeover
  static/sass/_pattern_takeovers.scss
  templates/index.html
  templates/takeovers/_buy-ubuntu-advantage.html
  templates/takeovers/index.html
  templates/takeovers/templates.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5775 Update the livepatch page
  templates/livepatch/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5772 Improve logout
  templates/advantage/index.html
  webapp/login.py
Labels: Review: Code +1

#5783 Doc fix: clarification for kubectl configuration
  templates/kubernetes/docs/operations.md
Labels: Review: Code +1, Review: QA +1

#5785 Advantage design changes
  static/sass/styles.scss
  templates/advantage/index.html
  templates/livepatch/index.html
Labels: Review: Code +1, Review: Design +1

#5786 Move homepage blog feed client-side
  requirements.txt
  static/js/latest-news.js
  templates/base_index.html
  templates/shared/_insights_news_strip.html
  templates/takeovers/templates.html
Labels: Review: Code +1, Review: QA +1

#5790 Changes “esm” to “esm-infra” in instructions
  templates/advantage/index.html
Labels: Review: Code +1

#5791 Add google analytic events to the interactions
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1

#5792 Add a terms and conditions link to the token section of the page
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1

#5789 Remove the login from the global navigation
  static/js/core.js
Labels: Review: Code +1, Review: QA +1

#5788 Update the readme and hacking pages
  HACKING.md
  README.md
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5794 Create takeover and engage page for getting started with ai webinar
  static/sass/_pattern_takeovers.scss
  templates/engage/get-started-with-ai-part-2.md
  templates/engage/index.html
  templates/index.html
  templates/takeovers/_get-started-with-ai-part-2.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5796 Fix 410 template syntax error
  templates/410.html
Labels: Review: Code +1, Review: QA +1

#5795 Replace all blog lists with client-side feed
  requirements.txt
  static/js/latest-news.js
  templates/base_index.html
  templates/shared/contextual_footers/_cloud_further_reading.html
  templates/shared/contextual_footers/_desktop_further_reading.html
  templates/shared/contextual_footers/_further_reading.html
  templates/shared/contextual_footers/_iot_further_reading.html
  templates/shared/contextual_footers/_security_further_reading.html
  templates/shared/contextual_footers/_telco_further_reading.html
  templates/templates/_further_reading_links.html
Labels: Review: Code +1, Review: QA +1

#5797 Copy update on /desktop/features
  templates/desktop/features.html
Labels: Review: Code +1, Review: QA +1

#5801 Build the ESM page ready for the advantage release
  static/sass/_pattern_strip.scss
  templates/esm/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#5813 Update /desktop/partners hero
  templates/desktop/partners.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5811 Update /desktop/organisations hero
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/desktop/organisations.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5815 Edit vmware engage
  templates/engage/vmware-to-charmed-openstack.md
Labels: Review: Code +1, Review: QA +1

#5809 Add the image-template on homepage
  .circleci/config.yml
  requirements.txt
  static/sass/styles.scss
  templates/base_index.html
  templates/engage/451-cloud-economics.html
  templates/engage/_heading-help.html
  templates/engage/apparmor-intro.html
  templates/engage/casestudy-azeti.html
  templates/engage/casestudy-azlogica.html
  templates/engage/casestudy-cinergy.html
  templates/engage/casestudy-city-network.html
  templates/engage/casestudy-imsevolve.html
  templates/engage/casestudy-innovapos.html
  templates/engage/casestudy-nexiona.html
  templates/engage/casestudy-rocketchat.html
  templates/engage/casestudy-sensape.html
  templates/engage/cloud-fray.html
  templates/engage/cloud-init-whitepaper.html
  templates/engage/cto-guide-sdn-nfv-vnf.html
  templates/engage/data-pipelines-kubeflow.html
  templates/engage/ebook-maas.html
  templates/engage/finserv-multi-cloud.html
  templates/engage/industrial-drones-case-study.html
  templates/engage/iot-disk-encryption.html
  templates/engage/low-latency-report.html
  templates/engage/lxd-whitepaper.html
  templates/engage/maas-hardware-testing.html
  templates/engage/nfv-sdn-openstack.html
  templates/engage/openstack-made-easy.html
  templates/engage/openstack-telco-clouds.html
  templates/engage/private-cloud.html
  templates/engage/public-cloud.html
  templates/engage/shared/_header.html
  templates/engage/snap-deltas.html
  templates/engage/stuckstack-ebook.html
  templates/engage/telco-cloudification-ebook.html
  templates/engage/whats-new-ubuntu-14-04-lts.html
  templates/engage/whitepaper-containers.html
  templates/takeovers/_buy-ubuntu-advantage.html
  templates/takeovers/_get-started-with-ai-part-2.html
  templates/takeovers/_takeover-help.html
  templates/takeovers/_template.html
  templates/takeovers/_vmware-to-charmed-openstack.html
  templates/takeovers/templates.html
  templates/templates/base.html
  webapp/app.py
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#5819 Add recaptcha to modals
  static/js/dynamic-contact-form.js
Labels: Review: Code +1, Review: QA +1

#5820 Add prefix for meta image for LinkedIn
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#5821 Update og metadata and current url"
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#5822 Optimise Dockerfile using multistage builds
  .dockerignore
  Dockerfile
  package.json
  scripts/get-mirrors-rss
Labels: Review: Code +1, Review: QA +1

#5816 Move ubuntu logo into title of readme
  README.md
Labels: Review: Code +1

#5826 Remove .com
  README.md
Labels: Review: Code +1, Review: QA +1

#5812 Update desktop/developers hero
  templates/desktop/developers.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5835 Updated /legal/terms-of-service markup
  templates/legal/terms-of-service.html
Labels: Review: Code +1, Review: QA +1

#5808 desktop/features - applied suru headings
  static/sass/_pattern_strip.scss
  templates/desktop/features.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5836 Make advantage API overrideable, and set to staging in local development
  .env
  webapp/app.py
  webapp/login.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#5814 Update /desktop/statistics hero
  static/sass/_pattern_strip.scss
  templates/desktop/statistics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5837 Update drawers and look of s390x pages
  templates/download/server/s390x.html
  templates/download/server/thank-you-s390x.html
Labels: Review: Code +1, Review: QA +1

#5838 Advantage design tweaks
  templates/advantage/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5818 Initial commit of new docs section
  navigation.yaml
  templates/_docs/engage.html
  templates/_docs/engage_pages.html
  templates/_docs/index.html
  templates/_docs/strips.html
  templates/_docs/takeovers.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5841 Update iot installation media mac gunzip command
  templates/download/iot/installation-media.html
Labels: Review: Code +1

#5840 Update text of /telecommunications page
  static/sass/styles.scss
  templates/shared/contextual_footers/_cloud_nfv.html
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5842 Updated pricing table
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#5843 Add rss icon to the footer
  static/sass/_pattern_lists.scss
  templates/templates/footer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#5844 Update links to new juju docs
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: QA +1

#5859 Fix the contact us button in the banner
  static/sass/_pattern_strip.scss
  templates/telecommunications/index.html
Labels: Review: Code +1, Review: QA +1

#5857 Update pricing table
  templates/pricing/infra.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#5862 Update Kubernetes docs for 1.16
  navigation.yaml
  templates/kubernetes/docs/audit-logging.md
  templates/kubernetes/docs/auth.md
  templates/kubernetes/docs/aws-iam-auth.md
  templates/kubernetes/docs/aws-integration.md
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/base_docs.html
  templates/kubernetes/docs/ceph.md
  templates/kubernetes/docs/certs-and-trust.md
  templates/kubernetes/docs/custom-loadbalancer.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/gcp-integration.md
  templates/kubernetes/docs/get-in-touch.md
  templates/kubernetes/docs/gpu-workers.md
  templates/kubernetes/docs/hacluster.md
  templates/kubernetes/docs/high-availability.md
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/kata.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/openstack-integration.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/snap-refresh.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/tigera-secure-ee.md
  templates/kubernetes/docs/troubleshooting.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/using-vault.md
  templates/kubernetes/docs/validation.md
Labels: Review: Code +1

#5861 Update kubeflow install instructions
  templates/download/iot/intel-iei-tank-870.html
  templates/kubeflow/install.html
Labels: Review: Code +1, Review: QA +1

#5864 Update robotics.html
  templates/internet-of-things/robotics.html
Labels: Review: Code +1, Review: QA +1

#5867 K8sdocs-Fix release notes for 1.16
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA +1

#5870 Smooth suru
  static/sass/_pattern_strip.scss
  templates/desktop/statistics.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
