Repository canonical/ubuntu.com, pull requests merged in 2020-10, with the labels that each got.

#8403 K8sdocs 1.19 fixes
  templates/kubernetes/docs/1.19/components.md
  templates/kubernetes/docs/supported-versions.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8411 Hide "Survey" in secondary nav from /legal/data-privacy
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#8415 Fix link to multipass on download/server
  templates/download/server/choose.html
Labels: Review: Code +1

#8416 K8sdocs - Update release-notes.md
  templates/kubernetes/docs/1.19/release-notes.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8408 Rebuild what is kubeflow
  templates/kubeflow/what-is-kubeflow.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8420 Add redirect for /appliances to /appliance
  redirects.yaml
Labels: Review: Code +1

#8352 Add release endpoints
  webapp/app.py
  webapp/security/schemas.py
  webapp/security/views.py
Labels: Project, Review: Code +1

#8418 Update navigation of /security-series
  templates/security-series/index.html
Labels: Review: Code +1, Review: QA +1

#8417 Add Spanish meta image and fix URL
  templates/engage/es/guia-implementacion-openstack.md
  templates/engage/index.html
  templates/index.html
  templates/takeovers/es/guia-implementacion-openstack.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8426 Add charmed-kubeflow links
  templates/kubeflow/what-is-kubeflow.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8409 Update blog to 6.3.1 and image-template to 1.3.1
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#8430 Support resources coming from ubuntu assets
  templates/engage/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8435 Resolve merge conflict
  templates/engage/index.html
Labels: Review: Code +1, Review: QA +1

#8439 Create authenticated session for authenticated endpoints
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#8442 Add LXD to appliance homepage and portfolio
  appliances.yaml
  templates/appliance/lxd/_next-steps.html
  templates/appliance/portfolio.html
  templates/appliance/shared/_featured_appliances.html
  templates/download/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8449 Fix download page image
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1

#8438 CVE search by description update
  webapp/security/views.py
Labels: Review: Code +1, Review: QA +1

#8434 Reverse order of release
  webapp/security/views.py
Labels: Review: Code +1, Review: QA +1

#8445 Add covid notice to /training page
  templates/training/index.html
Labels: Review: Code +1, Review: QA +1

#8349 Add information tool-tip for CVE statuses
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-table.html
  templates/security/cve/index.html
Labels: Project, Review: Code +1 (with changes), Review: QA +1

#8447 Filter languages for related pages
  tests/cassettes/TestRoutes.test_engage_index.yaml
  tests/test_routes.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8453 K8sDocs: fix rendering of image list
  templates/kubernetes/docs/1.19/components.md
Labels: Review: Code needed, Review: QA needed

#8427 K8sDocs: Remove todo, which has been done
  templates/kubernetes/docs/1.19/release-notes.md
  templates/kubernetes/docs/release-notes.md
Labels: Docs 📚, Review: Code needed, Review: QA needed

#8446 Add charmed-kubeflow links throughout the Kubeflow journey
  templates/blog/product-cards/_kubeflow_jaas-bundle.html
  templates/kubeflow/index.html
Labels: Review: Code +1, Review: QA +1

#8432 Security series updates
  templates/security-series/index.html
Labels: Review: Code +1, Review: Marketing +1

#8457 Fix the engage page thank you pages
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_pt_thank-you.html
Labels: Review: Code +1, Review: QA +1

#8462 Remove typos from the base index template
  templates/base_index.html
Labels: hacktoberfest-accepted

#8452 Add the smart-start guide as static content
  static/sass/_layout-documentation.scss
  templates/shared/forms/interactive/smart-start.html
  templates/smart-start/guide/advanced-options.md
  templates/smart-start/guide/app-store-commissioning.md
  templates/smart-start/guide/base.html
  templates/smart-start/guide/base_docs.html
  templates/smart-start/guide/certification-and-validation.md
  templates/smart-start/guide/custom-image-creation.md
  templates/smart-start/guide/device-enablement.md
  templates/smart-start/guide/document.html
  templates/smart-start/guide/hardware-setup.md
  templates/smart-start/guide/index.md
  templates/smart-start/guide/operating-an-app-store.md
  templates/smart-start/guide/secure-device-onboarding.md
  templates/smart-start/guide/snap-application-packaging.md
  templates/smart-start/guide/snap-publishing.md
  templates/smart-start/guide/technical-support.md
  templates/smart-start/guide/training-workshops.md
  templates/smart-start/shared/_side-navigation.md
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#8460 Copy update - Snap store data privacy page
  templates/legal/data-privacy/snap-store.md
Labels: Review: Code +1, Review: QA +1

#8459 Add Snap Store terms of service
  templates/legal/terms-and-policies/index.html
  templates/legal/terms-and-policies/snap-store-terms.html
Labels: Review: Code +1, Review: QA +1

#8458 Rebuild /telco
  templates/telco/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8480 Update text on /openstack/install
  templates/openstack/install.html
Labels: Review: Code +1, Review: QA +1

#8470 Use px instead of pct for icon sizes
  templates/appliance/shared/_base_appliance_index.html
Labels: Review: Code needed, Review: QA needed

#8463 Replace work email with email on iot and /core modal contact us forms
  templates/shared/forms/interactive/internet-of-things.html
Labels: Review: Code +1, Review: QA +1

#8512 Update /openstack/install for beta microstack
  templates/openstack/install.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8465 Add video to hero on IoT/appstore
  templates/internet-of-things/appstore.html
Labels: Review: Code +1, Review: QA +1

#8514 On /download/desktop/thank-you show contribution form if no download
  templates/download/desktop/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8519 Copy update /managed/kafka page
  templates/managed/kafka.html
  templates/shared/pricing/_managed-pricing.html
Labels: Review: Code +1, Review: QA +1

#8518 Update /telco page
  templates/telco/index.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8521 “invoice” > “receipt”
  templates/advantage/_stripe-modal.html
Labels: Review: Code +1, Review: QA +1

#8528 Maximum 1000 machines
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: QA +1

#8530 Update releases.yaml and /download/server to include 20.10
  releases.yaml
  templates/download/alternative-downloads.html
  templates/download/server/choose.html
  templates/shared/contextual_footers/_download_helping_hands.html
  templates/shared/contextual_footers/_download_server_guide.html
  templates/shared/contextual_footers/_download_server_installation.html
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#8548 Change logic and correct CTA for youtube webinars
  templates/engage/base.html
Labels: Review: Code +1, Review: QA +1

#8551 20.10 takeover
  templates/index.html
  templates/takeovers/_2010-takeover.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8549 Fix path for download mirror list
  scripts/create-usns.py
  templates/list_endpoints.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8546 Update 'What's new' section on /server
  templates/server/index.html
Labels: Review: Code +1, Review: QA +1

#8547 Update /download/raspberry-pi for 20.10
  templates/download/raspberry-pi/index.html
  templates/download/raspberry-pi/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8552 Build Raspberry Pi page
  navigation.yaml
  templates/raspberry-pi/_base_raspberry-pi.html
  templates/raspberry-pi/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8557 Raspberry pi section
  navigation.yaml
  templates/raspberry-pi/_base_raspberry-pi.html
  templates/raspberry-pi/index.html
  templates/raspberry-pi/server.html
Labels: Review: QA +1

#8559 Add mascots to /download
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1

#8564 Update link on /raspberry-pi to livestream
  templates/raspberry-pi/index.html
  templates/takeovers/_2010-takeover.html
Labels: Review: Code +1, Review: QA +1

#8563 Update /download/raspberry-pi/thank-you
  templates/download/iot/index.html
  templates/download/raspberry-pi/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8566 Add webinar notice on /download
  templates/download/index.html
Labels: Review: Code +1, Review: QA +1

#8555 Add rasp-pi to /download/desktop
  templates/download/shared/_everywhere.html
Labels: Review: Code +1, Review: QA +1

#8506 Added the Rapsberry Pi livestream blog product card
  templates/blog/product-cards.html
  templates/blog/product-cards/_raspberry-pi_2010-livestream.html
Labels: Review: Code +1, Review: QA +1

#8565 Remove pi desktop 32bit from /download/raspberry-pi
  templates/download/raspberry-pi/index.html
Labels: Review: Code needed, Review: QA needed

#8558 Raspberry pi desktop
  navigation.yaml
  static/sass/styles.scss
  templates/raspberry-pi/desktop.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8560 Add raspberry-pi to the footer, add redirect
  navigation.yaml
  redirects.yaml
  templates/templates/_footer_item.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#8568 Update managed pricing on /pricing/infra
  templates/shared/pricing/_openstack-kubernetes-lma.html
Labels: Review: Code +1, Review: QA +1

#8527 Remove the double scroll bar on the purchase modal
  static/sass/_pattern_renewal-modal.scss
Labels: Review: Code +1, Review: QA +1

#8526 Copy update /what-is-ros
  templates/robotics/what-is-ros.html
  templates/shared/contextual_footers/_iot_newsletter_signup.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8571 Update checksums for 20.10
  releases.yaml
Labels: Review: Code needed, Review: QA needed

#8572 Add &rsquo; to homepage and /download
  templates/base_index.html
  templates/download/index.html
  templates/download/server/choose.html
Labels: Review: Code +1, Review: QA +1

#8573 Update meta description on /uasd page
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: QA +1

#8575 Add GetUbuntu redirects
  redirects.yaml
Labels: Review: QA +1

#8525 Advantage shop free token menu
  static/js/src/contextual-menu.js
  static/js/src/cve/cve.js
Labels: Review: Code +1, Review: QA +1

#8579 Build takeover - cloud native and computing
  templates/index.html
  templates/takeovers/_security-cloud-computing.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8567 Use “For this period:” for subtotal when purchase is prorated
  static/js/src/advantage/set-modal-info.js
  static/js/src/ua-payment-modal.js
Labels: Review: Code +1, Review: QA +1

#8598 Remove hardcoded youtube id with variable for engage pages
  templates/engage/base.html
Labels: Review: Code +1, Review: QA +1

#8534 Unstack the purchase button on small screens
  templates/advantage/_stripe-modal.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#8597 Build takeover for manage risk with service providers
  templates/index.html
  templates/takeovers/_manage-risk-service-providers.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8604 Ubuntu 20.10 engage page
  templates/base_index.html
  templates/download/index.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8603 Change the secondary CTA on 20.10 takeover
  templates/takeovers/_2010-takeover.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8608 Allow missing form-id in engage pages
  templates/engage/base.html
Labels: Review: Code +1, Review: QA +1

#8550 advantage guest purchases: provide account/comany name
  static/js/src/advantage/contracts-api.js
  static/js/src/ua-payment-modal.js
  static/js/src/ua-product-selector.js
  static/sass/_pattern_renewal-modal.scss
  templates/advantage/_stripe-modal.html
  templates/advantage/subscribe/index.html
  tests/test_advantage.py
  webapp/advantage.py
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#8610 Remove LTS from the latest server download button
  templates/download/server/choose.html
Labels: Review: Code +1

#8613 Add embed youtube link as the other form has a x-origin error
  templates/blog/product-cards/_raspberry-pi_2010-livestream.html
Labels: Review: Code +1, Review: QA +1

#8614 Update list of phone numbers
  templates/advantage/index.html
  templates/shared/_call-sales-long.html
Labels: Review: Code +1, Review: QA +1

#8622 Change header image cassandra page
  templates/managed/cassandra.html
Labels: Review: Code +1, Review: QA +1

#8618 Add /security/disclosure-policy page
  templates/security/disclosure-policy.html
  templates/security/index.html
Labels: Review: Code +1 (with changes), Review: Marketing needed, Review: QA +1

#8619 Update cta on /raspberry-pi
  templates/raspberry-pi/index.html
Labels: Review: Code +1, Review: QA +1

#8621 Add updated tutorials to /download/raspberry-pi page
  templates/download/raspberry-pi/index.html
Labels: Review: Code +1, Review: QA +1

#8520 Change takeover image on mobile
  static/sass/styles.scss
  templates/takeovers/_cassandra-webinar-takeover.html
  templates/takeovers/_fips_certification_cis_compliance.html
  templates/takeovers/_kubernetes-enterprise-whitepaper-takeover.html
  templates/takeovers/_redhat-openstack.html
  templates/takeovers/_template.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8631 Remove terser
  package.json
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8623 Update cookie policy 2
  package.json
  static/js/src/core.js
  templates/templates/_footer-copyright-and-legal.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8589 Make /getubuntu redirects more greedy
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8638 Make contributions GAevent
  static/js/src/contributions.js
Labels: Review: Code +1, Review: QA +1

#8625 Copy update on /support
  templates/support/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8637 More prominent “Buy a subscription”
  templates/advantage/_table.html
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
