Repository canonical/ubuntu.com, pull requests merged in 2020-11, with the labels that each got.

#8532 Improve the small screen view of the subscriptions
  static/js/src/accordion.js
  static/js/src/advantage/entitlements-callout.js
  static/sass/_pattern_table.scss
  templates/advantage/index.html
  templates/advantage/shared/_certifications-info.html
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
  templates/openstack/compare.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8639 Change CTA on takeover
  templates/takeovers/_security-cloud-computing.html
Labels: Review: Code +1, Review: QA +1

#8641 Removed Managed risk takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#8642 Move quote to separate section
  templates/smartstart/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8632 add version specific esm and livepatch instructions to /advantage
  static/sass/_pattern_table.scss
  static/sass/styles.scss
  templates/advantage/shared/_certifications-info.html
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8645 Copy update on /pricing/devices
  templates/pricing/devices.html
  templates/pricing/shared/_enablement-strip.html
  templates/shared/pricing/_smart-start-prices.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8624 Add ecom analytics to UA shop
  static/js/src/advantage/ecom-analytics-events.js
  static/js/src/ua-payment-modal.js
  static/js/src/ua-product-selector.js
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#8649 Pin vanilla to 2.18.0
  package.json
  yarn.lock
Labels: Review: Code +1

#8646 Add pi 400 to /download/raspberry-pi
  templates/download/raspberry-pi/index.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8653 Fix link on /smartstart/guide/hardware-setup
  templates/smartstart/guide/hardware-setup.md
Labels: Review: Code +1, Review: QA +1

#8655 Increase logo size on /what-is-kubeflow
  templates/kubeflow/what-is-kubeflow.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8656 Redhat takeover and engage page
  templates/index.html
  templates/takeovers/es/_redhat-openstack-comparacion-manual.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8657 Change "What is Kubeflow" blog product card link to /kubeflow/what-is-kubeflow
  templates/blog/product-cards/_kubeflow_what-is-kubeflow.html
Labels: Review: Code +1, Review: QA +1

#8635 Takeovers from Discourse
  .github/workflows/pr.yaml
  templates/base_index.html
  templates/index.html
  templates/takeovers/_14-04-esm.html
  templates/takeovers/_1704_takeover.html
  templates/takeovers/_1710_takeover.html
  templates/takeovers/_451-automotive_takeover.html
  templates/takeovers/_451-microk8s.html
  templates/takeovers/_anbox-cloud-webinar.html
  templates/takeovers/_anbox-takeover.html
  templates/takeovers/_security-webinar-series.html
  templates/takeovers/_template.html
  templates/takeovers/es/guia-implementacion-openstack.html
  templates/takeovers/fr/_french_vmware-to-os.html
  templates/takeovers/fr/_vmware-to-charmed-openstack_french.html
  templates/takeovers/index.html
  templates/takeovers/pt/_vmware-para-o-openstack.html
  templates/takeovers/takeunders/_iot-02-2017.html
  templates/takeovers/takeunders/_iot-business-report-08-2017.html
  templates/takeovers/takeunders/_kubernetes.html
  templates/takeovers/takeunders/_landscape-self-service.html
  templates/takeovers/takeunders/_openstack-ebook.html
  templates/takeovers/takeunders/_stuck-stack.html
  templates/takeovers/takeunders/_ubuntu-product-month.html
  tests/cassettes/TestRoutes.test_homepage.yaml
  webapp/app.py
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#8660 Fix wrong parameter name and remove unused locale
  templates/index.html
  templates/takeovers/_template.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8668 Add smartstart link to digital-signage
  templates/internet-of-things/digital-signage.html
Labels: Review: Code +1, Review: QA +1

#8666 Add smartstart link to internet-of-things
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: QA +1

#8662 Add smartstart to the enterprise menu
  templates/templates/navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#8665 UA shop: account check
  templates/advantage/subscribe/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8673 rename ecom analytics js file to please ublock
  static/js/src/advantage/ecom-events.js
  static/js/src/ua-payment-modal.js
  static/js/src/ua-product-selector.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8674 Remove secrets for discourse
  konf/site.yaml
Labels: Review: Code +1

#8676 Fix copy doc link
  templates/engage/base.html
Labels: Review: Code +1, Review: QA +1

#8677 get first invoice in renewal invoice array, not the last
  static/js/src/renewal-modal.js
Labels: Review: Code +1

#8672 Gclid in forms
  static/js/src/dynamic-contact-form.js
  templates/blog/newsletter-form.html
  templates/download/desktop/thank-you.html
  templates/download/server/s390x.html
  templates/download/shared/_get-ebook-security.html
  templates/download/shared/_get_ebook_maas.html
  templates/download/shared/_server_weekly_news.html
  templates/engage/shared/_de_engage_form.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_engage_form.html
  templates/engage/shared/_fr_engage_form.html
  templates/engage/shared/_it_engage_form.html
  templates/engage/shared/_pt_engage_form.html
  templates/gov/form.html
  templates/internet-of-things/edgex.html
  templates/kubernetes/_get_ebook.html
  templates/rfp/index.html
  templates/shared/_client-contact-us-form.html
  templates/shared/_cloud-contact-us-form-german.html
  templates/shared/_cloud-contact-us-form.html
  templates/shared/contextual_footers/_cloud_newsletter.html
  templates/shared/contextual_footers/_iot_newsletter_signup.html
  templates/shared/forms/interactive/_appliance.html
  templates/shared/forms/interactive/aws.html
  templates/shared/forms/interactive/azure.html
  templates/shared/forms/interactive/bootstack.html
  templates/shared/forms/interactive/embedded.html
  templates/shared/forms/interactive/general.html
  templates/shared/forms/interactive/internet-of-things.html
  templates/shared/forms/interactive/kubeflow.html
  templates/shared/forms/interactive/kubernetes.html
  templates/shared/forms/interactive/managed-apps.html
  templates/shared/forms/interactive/managed-cassandra.html
  templates/shared/forms/interactive/managed-kafka.html
  templates/shared/forms/interactive/masters-conference.html
  templates/shared/forms/interactive/openstack.html
  templates/shared/forms/interactive/partner-dell.html
  templates/shared/forms/interactive/pricing-infra.html
  templates/shared/forms/interactive/robotics.html
  templates/shared/forms/interactive/smart-start.html
  templates/shared/forms/interactive/storage.html
  templates/shared/forms/interactive/support-openstack.html
  templates/shared/forms/interactive/support.html
  templates/shared/forms/interactive/telco.html
  templates/whitepapers/beta/shared/form.html
  templates/whitepapers/shared/form.html
Labels: Review: Code +1, Review: QA +1

#8670 Fix engage thank-you pages and <space>&nbsp;
  templates/advantage/index.html
  templates/appliance/index.html
  templates/base_index.html
  templates/download/desktop/thank-you.html
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_it_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/thank-you.html
  templates/server/hyperscale.html
  tests/cassettes/TestRoutes.test_blog.yaml
Labels: Review: Code +1, Review: QA +1

#8685 Authentication clean-up
  .github/workflows/pr.yaml
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#8688 Add ceph and smartstart to footer
  navigation.yaml
  templates/templates/footer.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#8690 Update GPU enablement link on homepage
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#8699 Change copy on AWS page
  templates/aws/index.html
Labels: Review: Code +1, Review: QA +1

#8696 Redirect buy.ubuntu.com to /advantage
  konf/site.yaml
Labels: Review: Code +1

#8709 Build /aws/outposts page
  navigation.yaml
  templates/aws/outposts.html
Labels: Review: Code +1, Review: QA +1

#8703 UA shop: add marketo form
  static/js/src/ua-payment-modal.js
  templates/advantage/_stripe-modal.html
  webapp/views.py
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#8711 Remove TCO calculator from /kubernetes secondary nav
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#8712 Copy update on digital signage
  templates/internet-of-things/digital-signage.html
Labels: Review: Code +1, Review: QA +1

#8714 Keep test-redirects script in scripts dir
  scripts/test-redirects.pl
Labels: Review: Code +1

#8713 Updated sitemap
  static/files/sitemap.xml
Labels: Review: Code +1, Review: QA +1

#8716 Copy update on /security-series
  templates/security-series/index.html
Labels: Review: Code +1, Review: QA +1

#8707 Copy update on IoT page
  templates/internet-of-things/index.html
Labels: Review: Code +1, Review: QA +1

#8719 Add education discount on /support
  package.json
  templates/shared/_thank_you.html
  templates/shared/_thank_you_footer.html
  templates/support/contact-us.html
  templates/support/index.html
  templates/support/thank-you.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8715 Add redirect for /engage/charmed-openstack-adoption-whitepaper
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8736 K8sdocs-1.19 version updates
  templates/kubernetes/docs/1.19/components.md
  templates/kubernetes/docs/1.19/release-notes.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8735 update buy.u.c links to point to /advantage
  templates/0_docs/strips.html
  templates/containers/index.html
  templates/desktop/organisations.html
  templates/download/server/download.html
  templates/pricing/index.html
  templates/pricing/infra.html
  templates/security/esm.html
  templates/security/index.html
  templates/shared/_thank_you_footer.html
  templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
  templates/shared/contextual_footers/_download_cloud_buy_landscape.html
  templates/shared/contextual_footers/_download_enterprise_support.html
  templates/shared/contextual_footers/_professional_support.html
  templates/shared/contextual_footers/_server_contact_us.html
  templates/shared/contextual_footers/_support-image.html
  templates/shared/contextual_footers/_support.html
  templates/shared/forms/_desktop_ua-shop.html
  templates/support/index.html
  templates/support/thank-you.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8734 Remove pre-commit hook requiring dotrun
  package.json
Labels: Review: Code +1, Review: QA +1

#8732 UA shop: maintenance mode
  .env
  .github/workflows/pr.yaml
  konf/site.yaml
  templates/advantage/maintenance.html
  tests/test_routes.py
  webapp/decorators.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8741 redirect shop links to buy.u.c
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8737 Build /cloud page
  redirects.yaml
  static/sass/styles.scss
  templates/cloud/_base-cloud.html
  templates/cloud/index.html
  templates/shared/contextual_footers/_cloud_engage_further_reading.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8740 Update meta title and add meta image
  templates/managed/cassandra.html
Labels: Review: Code +1, Review: QA +1

#8745 Copy update on /managed
  templates/managed/index.html
Labels: Review: Code +1, Review: QA +1

#8748 Copy update on /cloud
  templates/cloud/index.html
Labels: Review: Code +1, Review: QA +1

#8731 Update product-cards.html
  templates/blog/product-cards.html
  templates/blog/product-cards/_IoT_appstore.html
  templates/blog/product-cards/_financialservices-awerness.html
  templates/blog/product-cards/_smartstart.html
  templates/blog/product-cards/_telco.html
Labels: Review: Code +1, Review: QA +1

#8730 Add education discount and webinar to /sercurity
  templates/security/index.html
  templates/shared/_education-discount.html
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#8751 Update images on /download/raspberry-pi
  templates/download/raspberry-pi/index.html
Labels: Review: Code +1, Review: QA +1

#8752 filter out "closed" status renewals
  tests/test_views.py
  webapp/views.py
Labels: Review: Code +1

#8739 UA shop form changes
  redirects.yaml
  static/js/src/ua-payment-modal.js
  templates/advantage/_stripe-modal.html
  templates/shared/forms/_ca_provinces.html
  templates/shared/forms/_us_states.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#8746 Add contact-us pages and cta to /financial-services
  navigation.yaml
  templates/c/contact-us.html
  templates/financial-services/_base_financial-services.html
  templates/financial-services/contact-us.html
  templates/financial-services/index.html
  templates/financial-services/thank-you.html
  templates/shared/_thank_you.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8754 Copy update on /masters-conference
  templates/masters-conference/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8760 Sum all contract allowances regardless of metric
  tests/test_views.py
  webapp/views.py
Labels: Review: Code +1

#8764 Update Kafka meta title
  templates/managed/kafka.html
Labels: Review: Code +1

#8742 Build /kubernetes/compare page
  navigation.yaml
  static/sass/_pattern_ratings.scss
  static/sass/styles.scss
  templates/kubernetes/compare.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing needed, Review: PdM needed, Review: QA +1, Review: UX +1

#8767 K8sDocs Update ldap.md
  templates/kubernetes/docs/ldap.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8782 sitemap.xml autogenerated for discourse module
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#8781 Update what is kubernetes copy
  templates/kubernetes/what-is-kubernetes.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#8779 K8sDocs add clarifications for etcd upgrade
  templates/kubernetes/docs/upgrading.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8797 Add redirect for /engage/finance
  redirects.yaml
Labels: Review: Code needed, Review: QA needed

#8798 Remove Pricing from /support secondary nav
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#8803 Update the release charts for Kernel and OpenStack
  static/js/src/chart-data.js
  static/js/src/chart.js
  static/js/src/release-chart.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#8804 Only move chars with versions right
  static/js/src/chart.js
Labels: Review: Code +1, Review: QA +1

#8799 Add missing world map files for /desktop/statistics
  static/js/data/world-110m-country-names.tsv
  static/js/data/world-110m.v1.json
Labels: Review: Code +1, Review: QA +1

#8802 Build new /security/docker-images page
  navigation.yaml
  templates/security/base_security.html
  templates/security/certifications.html
  templates/security/contact-us.html
  templates/security/disclosure-policy.html
  templates/security/docker-images.html
  templates/security/esm.html
  templates/security/index.html
  templates/security/livepatch.html
  templates/security/notice.html
  templates/security/oval.html
  templates/security/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8780 Update the webinars on both the Kafka and Cassandra managed pages
  templates/managed/cassandra.html
  templates/managed/kafka.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1, Review: UX needed

#8801 Update download link on /core
  templates/core/index.html
Labels: Review: Code +1, Review: QA +1

#8793 Remove Allan Gray from /financial-services
  templates/financial-services/index.html
  templates/shared/_case-study-allan-gray.html
Labels: Review: Code +1, Review: QA +1

#8791 Update /kubeflow ctas
  templates/kubeflow/index.html
Labels: Review: Code +1, Review: QA +1

#8813 [Cube] - Initial view
  templates/cube/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8814 Create horizontal latest news strip for the homepage, /telco and /wsl
  templates/base_index.html
  templates/shared/_latest_news_strip.html
  templates/telco/index.html
  templates/wsl/index.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8808 Create campaign ROS contact us modal
  templates/robotics/base_robotics.html
  templates/shared/forms/interactive/robotics_ros.html
Labels: Review: Code +1, Review: QA +1

#8819 UA shop: increase the amount of time we wait for a payment to process
  static/js/src/ua-payment-modal.js
Labels: Review: Code +1

#8817 Update /training with new Landscape course and Kubeflow pdf
  templates/training/contact-us.html
  templates/training/index.html
  templates/training/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8796 Update ctas and image in /kubeflow/what-is-kubeflow
  templates/kubeflow/what-is-kubeflow.html
Labels: Review: Code +1 (with changes), Review: QA +1

#8820 Build basic data structure and template
  templates/cube/base_cube.html
  templates/cube/index.html
  templates/cube/microcerts.html
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8822 Update Masters 4 section of /masters-conference
  templates/masters-conference/index.html
Labels: Review: Code +1, Review: QA +1

#8812 3448 build tutorials search
  static/js/src/tutorial-list.js
  static/js/src/tutorial-list.test.js
  templates/tutorials/index.html
  webapp/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA needed

#8805 Allow LSNs
  webapp/security/schemas.py
Labels: Review: Code +1

#8829 Add ESM contact form
  static/sass/_pattern_active-reveal.scss
  static/sass/styles.scss
  templates/security/esm.html
  templates/security/thank-you.html
  templates/shared/forms/interactive/esm.html
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#8835 Show microcerts only if you are logged in
  templates/cube/index.html
  templates/cube/microcerts.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1
