Repository canonical/ubuntu.com, pull requests merged in 2020-07, with the labels that each got.

#7851 Fix url for jaas.ai on enterprise mega menu
  templates/templates/navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#7858 Handle VAT validation error
  .env
  static/js/src/renewals/error-handler.js
  static/js/src/renewals/tests/error-handler.test.js
  static/js/src/renewals/tests/fixtures/error-responses.js
  templates/advantage/_stripe-modal.html
  webapp/advantage.py
Labels: Review: Code +1, Review: QA +1

#7859 Replace usn.ubuntu.com references
  navigation.yaml
  redirects.yaml
  templates/security/cve/cve.html
  templates/security/index.html
  templates/templates/navigation-developer-h.html
  templates/whitepapers/beta/robotics.html
  templates/whitepapers/robotics/_content.html
Labels: Review: Code +1, Review: QA +1

#7860 move /advantage signout button to its own row
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1

#7849 Add the AT&T Ubuntu Pro webinar
  templates/engage/at&t-azure-webinar.html
Labels: Review: Code +1, Review: QA +1

#7870 Copy and link updated to /kubeflow/install page
  templates/kubeflow/install.html
  templates/kubeflow/shared/_learn-more.html
Labels: Review: Code +1, Review: QA +1

#7871 Remove and redirect /download/orange-pi page
  navigation.yaml
  redirects.yaml
  templates/download/orange-pi-zero.html
Labels: Review: Code +1, Review: QA +1

#7873 Update /masters-conference page post event
  templates/masters-conference/index.html
Labels: Review: Code +1, Review: QA +1

#7879 Open cors to all sites for mega menu
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#7875 Expand tests of endpoints
  .env
  tests/cassettes/TestRoutes.test_advantage.yaml
  tests/cassettes/TestRoutes.test_blog.yaml
  tests/cassettes/TestRoutes.test_server_docs.yaml
  tests/cassettes/TestRoutes.test_tutorials.yaml
  tests/test_routes.py
Labels: Review: Code +1, Review: QA +1

#7889 K8sdocs Remove stale conjure-up refs
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/troubleshooting.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#7891 Update #enterprise menu
  templates/templates/navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#7881 Add motd legal page
  navigation.yaml
  templates/legal/motd.html
  templates/legal/terms-and-policies/index.html
Labels: Review: Code +1, Review: QA +1

#7888 Remove conjure-up.io from nav and update list of /legal/websites
  templates/legal/websites.html
  templates/templates/navigation-developer-h.html
Labels: Review: Code +1, Review: QA +1

#7880 Update to Vanilla framework v2.14.0
  package.json
  static/sass/_global-settings.scss
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#7900 Add webinar to /openstack/what-is-openstack
  templates/openstack/what-is-openstack.html
Labels: Review: Code +1, Review: QA +1

#7896 Add webinar to /server
  templates/server/index.html
Labels: Review: Code +1, Review: QA +1

#7894 Add webinar to /kernel page
  templates/kernel/index.html
Labels: Review: Code +1, Review: QA +1

#7898 Add webinar to /openstack/features
  templates/openstack/features.html
Labels: Review: Code +1, Review: QA +1

#7902 Update resources on /openstack
  templates/shared/_resources_openstack.html
Labels: Review: Code +1 (with changes), Review: QA +1

#7878 Add the smart start whitepaper engage page
  templates/engage/index.html
  templates/engage/smart-start-whitepaper.md
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#7903 Add a space to /masters-conference
  templates/masters-conference/index.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#7906 Update nuc bios update link
  templates/appliance/shared/_install_instructions_intel-nuc.html
  templates/download/intel-nuc-desktop.html
  templates/download/intel-nuc.html
Labels: Review: Code +1, Review: QA +1

#7907 Reduce the vertical space at the top of the appliance page
  templates/appliance/index.html
Labels: Review: Code +1, Review: QA +1

#7911 Update USN ID regex in marshmallow shcema
  webapp/security/schemas.py
Labels: Review: Code +1, Review: QA +1

#7913 Revert /azure/pro to promote 18.04 first
  templates/azure/pro.html
Labels: Review: Code +1, Review: QA +1

#7908 Anbox whitepaper engage page
  templates/engage/index.html
  templates/engage/intro-to-anbox-cloud-whitepaper.md
Labels: Review: Code +1, Review: QA +1

#7915 remove inline polyfill script
  package.json
  static/js/src/polyfills.js
  templates/templates/base.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#7914 Move serialize JS to module for performance
  static/js/src/form-validation.js
  static/js/third-party/serialize.js
  templates/templates/base.html
Labels: Review: Code +1, Review: QA +1

#7892 Validate deployment config
  .github/workflows/pr.yaml
Labels: Review: Code needed, Review: QA needed

#7918 Adds "What is Kubernetes" blog card
  templates/blog/product-cards.html
Labels: Review: Code needed, Review: QA needed

#7919 Added a break to the sub heading
  templates/engage/at&t-azure-webinar.html
Labels: Review: Code +1, Review: QA +1

#7920 Add security page for K8s docs
  navigation.yaml
  templates/kubernetes/docs/security.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#7922 Update link on /lega/motd
  templates/legal/motd.html
Labels: Review: Code needed, Review: QA needed

#7909 Add new nginx proxy
  deploy/site.yaml
Labels: Review: Code +1, Review: QA +1

#7939 Ceph docs
  templates/ceph/base_docs.html
  templates/ceph/document.html
  tests/test_routes.py
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#7936 Change colours on OpenStack chart to match others
  static/js/src/chart-data.js
Labels: Review: Code +1, Review: QA +1

#7944 Reduces whitespace around USN title + summary
  templates/security/notice.html
Labels: Review: Code needed, Review: Design needed

#7938 Update linkedin link in footer
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#7955 Fix typos
  templates/appliance/hardware.html
  templates/appliance/shared/_base_appliance_index.html
  templates/desktop/partners.html
  templates/engage/public-cloud.html
  templates/engage/vmware-to-charmed-openstack.md
  templates/kubernetes/docs/1.16/charm-docker-registry.md
  templates/kubernetes/docs/1.17/charm-docker-registry.md
  templates/kubernetes/docs/1.18/charm-docker-registry.md
  templates/kubernetes/docs/charm-docker-registry.md
  templates/kubernetes/docs/snap-refresh.md
  templates/legal/developer-terms-and-conditions/2016-04-06.html
  templates/legal/developer-terms-and-conditions/2018-07-23.html
  templates/legal/developer-terms-and-conditions/index.html
  templates/legal/ubuntu-advantage-assurance.html
Labels: Review: Code +1, Review: QA +1

#7835 Link /public-cloud main CTA to the right contact form
  templates/public-cloud/index.html
Labels: Review: Code +1, Review: QA +1

#7966 Replaced NextCloud with Nextcloud everywhere
  appliances.yaml
  templates/appliance/nextcloud/_next-steps.html
  templates/appliance/nextcloud/index.md
  templates/appliance/shared/_featured_appliances.html
  tests/cassettes/TestRoutes.test_blog.yaml
Labels: Review: Code +1, Review: QA +1

#7965 Fix copy on discourse appliance cta
  templates/appliance/shared/_join_the_community.html
Labels: Review: Code +1, Review: QA +1

#7958 Removed ubuntu masters takeover
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#7956 Ubuntu on AWS copy update
  templates/aws/index.html
Labels: Review: Code +1, Review: QA +1

#7972 Fix OpenStack chart key text
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: Code needed, Review: QA needed

#7945 Add CVE component search field
  static/js/src/cve/cve.js
  templates/security/cve/index.html
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#7976 if a contract has expired, but has a renewal, allow users to renew
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#7954 Ubuntu Pro for Azure copy update
  templates/azure/pro.html
Labels: Review: Code +1, Review: QA +1

#7957 Ubuntu pro amazon copy update
  templates/aws/pro.html
Labels: Review: Code needed, Review: QA needed

#7942 Restore discourse docs "edit" link and update date
  templates/ceph/document.html
Labels: Review: Code +1, Review: QA +1

#7978 Portuguese Vmware to OpenStack takeover and engage page
  templates/engage/pt/vmware-para-o-openstack.md
  templates/engage/shared/_pt_engage_form.html
  templates/index.html
  templates/takeovers/fr/_cio-guide-to-multipass.html
  templates/takeovers/index.html
  templates/takeovers/pt/_vmware-para-o-openstack.html
Labels: Review: Code +1, Review: QA +1

#7960 Add CVE search Ubuntu version and status fields
  static/js/src/cve/cve-search.js
  static/js/src/cve/cve.js
  templates/security/cve/_cve-table.html
  templates/security/cve/_status-fields.html
  templates/security/cve/_version-fields.html
  templates/security/cve/index.html
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#7980 Add Anbox whitepaper takeover
  templates/index.html
  templates/takeovers/_intro-to-anbox-cloud-whitepaper.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#7981 Fix broken /takeovers page
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#7983 GitHub Action conditionals for main repo
  .github/workflows/cypress.yaml
  .github/workflows/external-links.yaml
  .github/workflows/live-links.yaml
  .github/workflows/master-links.yaml
Labels: Review: Code +1

#7973 Add bug links to CVE pages
  templates/security/cve/cve.html
Labels: Review: Code +1, Review: QA +1

#7984 Fix rendering for k8s docs container image list
  templates/kubernetes/docs/1.18/components.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#7985 Updated the benefits of Ceph diagram on /ceph
  templates/ceph/index.html
Labels: Review: Code needed, Review: QA needed

#7987 Update copy and logos on /azure
  templates/azure/index.html
Labels: Review: Code +1, Review: QA +1

#7977 Update the automotive page
  static/sass/_pattern_strip.scss
  templates/automotive/index.html
Labels: Review: Code +1, Review: Design +1

#7990 Fix page jump as global nav loads
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#7974 Add links to Debian, NVD and Launchpad to CVE page
  templates/security/cve/cve.html
Labels: Project, Review: Code +1, Review: QA +1

#7996 Update the link in the hero of Kubernetes event
  templates/engage/kubernetes-event-us.md
Labels: Review: Code +1, Review: QA +1

#7986 Add gsi webinar takeover and engage page
  templates/engage/_article-card.html
  templates/engage/gsi-webinar-series.html
  templates/engage/index.html
  templates/index.html
  templates/takeovers/_gsi-webinar-series-takeover.html
  templates/takeovers/index.html
Labels: Review: Code +1 (with changes), Review: QA +1

#7993 Ungated the ebook
  templates/azure/pro.html
Labels: Review: Code +1, Review: QA +1

#8002 create debounce util module
  static/js/src/desktop-statistics.js
  static/js/src/imageBuilder.js
  static/js/src/release-chart.js
  static/js/src/utils/debounce.js
Labels: Review: Code +1, Review: QA +1

#7997 Add animation to automotive page
  templates/automotive/_chassis_animation.html
  templates/automotive/index.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#8000 Redhat takeover and engage page
  templates/engage/index.html
  templates/engage/redhat-openstack-comparison-whitepaper.md
  templates/index.html
  templates/takeovers/_redhat-openstack.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#7959 Make CVEs support components
  webapp/security/alembic/versions/8e9386e7a94b_add_component_column_to_status_table.py
  webapp/security/models.py
  webapp/security/schemas.py
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8001 Update copy on /security/certifications
  templates/security/certifications.html
Labels: Review: Code +1, Review: QA +1

#8005 Automotive corp logo
  static/js/src/chassis-animation.js
  templates/automotive/_chassis_animation.html
  templates/automotive/index.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8008 Fix CVE page for missing status
  templates/security/cve/_cve-table.html
Labels: Review: Code +1, Review: QA +1

#8016 update /advantage customer info API call
  templates/advantage/index.html
  webapp/advantage.py
Labels: Review: Code +1, Review: QA +1

#8018 Update global-nav to the v2.4.3
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8019 Fix images to improve Calibre score
  templates/appliance/shared/_featured_appliances.html
  templates/blog/article.html
  templates/blog/author.html
Labels: Review: Code +1, Review: QA +1

#8015 Fix single CVE page
  templates/security/cve/cve.html
Labels: Review: Code +1, Review: QA +1
