Repository canonical/ubuntu.com, pull requests merged in 2020-09, with the labels that each got.

#8196 Update K8s release chart
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#8199 Update time on Telco VEVT Sept 2020 event
  templates/engage/telco-virtual-event.md
Labels: Review: Code +1, Review: QA +1

#8159 Fix contextual footer on /openstack/managed
  templates/openstack/managed.html
  templates/shared/contextual_footers/_cloud_bootstack.html
  templates/shared/contextual_footers/_k8s_managed.html
Labels: Review: Code +1, Review: QA +1

#8204 Add install video to the Kubeflow install page
  templates/kubeflow/install.html
Labels: Review: Code +1, Review: QA +1

#8202 Updated appliance SHA256 checksum
  appliances.yaml
Labels: Review: Code +1

#8134 Add takeover and engage page for enterprise kubernetes
  templates/engage/index.html
  templates/engage/kubernetes-deployment-enterprise-whitepaper.md
  templates/index.html
  templates/takeovers/_kubernetes-enterprise-whitepaper-takeover.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8173 Update homepage
  package.json
  static/sass/_pattern_inline-images.scss
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1

#8209 Add webinar to the enterprise kubernetes engagement
  templates/engage/kubernetes-deployment-enterprise-whitepaper.md
Labels: Review: Code +1, Review: QA +1

#8215 Update powerful to scalable in the GSI engagement
  templates/engage/gsi-webinar-series.html
  templates/engage/index.html
  templates/takeovers/_gsi-webinar-series-takeover.html
Labels: Review: Code +1

#8210 Build the new internet-of-things modal
  templates/core/build/index.html
  templates/core/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/networking.html
  templates/shared/forms/interactive/internet-of-things.html
Labels: Review: Code +1, Review: QA +1

#8206 K8sDocs: Add k8s snap reference page
  navigation.yaml
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/snaps.md
  templates/kubernetes/docs/supported-versions.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8219 Update the IoT contact thank you content
  templates/internet-of-things/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8187 Add new purchase preview endpoint for shop
  webapp/advantage.py
  webapp/app.py
  webapp/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8217 Advantage shop polish
  .env
  static/js/src/ua-product-selector.js
  templates/advantage/subscribe.html
  tests/cassettes/TestRoutes.test_advantage.yaml
  webapp/advantage.py
  webapp/app.py
  webapp/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8223 Remove extraneous closing tag on index
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#8211 Optimise CVE filters
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8222 Change user auth config
  webapp/security/auth.py
Labels: Review: Code +1

#8212 Build IT da-vmware-a-openstack engagment
  templates/engage/index.html
  templates/engage/it/da-vmware-a-openstack.md
  templates/engage/shared/_it_engage_form.html
  templates/index.html
  templates/takeovers/index.html
  templates/takeovers/it/_da-vmware-a-openstack.html
Labels: Review: Code +1, Review: QA +1

#8232 Remove sticky from the newsletter sign up on the blog
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#8230 Correctly send form submission GA event
  static/js/src/dynamic-contact-form.js
Labels: Review: Code +1, Review: QA +1

#8234 Removed Anbox introduction takeover
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#8225 Kubernetes 1.19 blog redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8237 Update the homepage content
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#8239 Replace Launchpad username with Github username the legal copy
  templates/legal/contributors/agreement.html
  templates/legal/contributors/index.html
Labels: Review: Code +1

#8238 Proxy Wordpress API
  konf/site.yaml
Labels: Review: Code +1, Review: QA +1

#8240 WordPress API under /blog
  konf/site.yaml
Labels: Review: Code +1

#8142 Remove architecture selection logic from /core/build
  requirements.txt
  static/js/src/imageBuilder.js
  templates/core/build/index.html
  tests/cassettes/TestRoutes.test_ceph_docs.yaml
  webapp/views.py
Labels: Review: Code +1

#8213 Build the edgex page
  navigation.yaml
  templates/internet-of-things/edgex.html
  templates/wsl/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8253 if a contract has multiple renewals, return earliest one
  tests/test_views.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8245 Display related notices
  templates/security/notice.html
  webapp/security/models.py
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8267 Clean up Prettier and formatting checks
  .dockerignore
  .eslintrc.js
  .github/workflows/pr.yaml
  package.json
  static/js/src/chart.js
  static/js/src/contextual-menu.js
  static/js/src/contributions.js
  static/js/src/core.js
  static/js/src/dummy-data.js
  static/js/src/forms.js
  static/js/src/lightbox.js
  static/js/src/scratch.js
  static/js/src/sticky-nav.js
  static/js/src/tco-calculator.js
  static/js/src/tutorial-list.js
  static/js/src/tutorial.js
  static/js/third-party/prism.js
  static/sass/_layout-documentation.scss
  static/sass/_layout-legal-pages.scss
  static/sass/_layout-tutorial.scss
  static/sass/_layout-tutorials.scss
  static/sass/_layout-whitepapers.scss
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_blog-featured.scss
  static/sass/_pattern_blog-suru.scss
  static/sass/_pattern_calculator.scss
  static/sass/_pattern_chart.scss
  static/sass/_pattern_contact-modal.scss
  static/sass/_pattern_desktop-statistics.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_gaming.scss
  static/sass/_pattern_heading-icon.scss
  static/sass/_pattern_lightbox.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip-photos.scss
  static/sass/_pattern_strip.scss
  static/sass/_pattern_takeunders.scss
  static/sass/_pattern_ubuntu_intro.scss
  static/sass/_settings_colors.scss
  static/sass/_utility-animations.scss
  static/sass/_utility_vertically-center.scss
  static/sass/_vanilla-placeholders.scss
  static/sass/print.scss
  static/sass/styles.scss
  static/sass/takeovers/_ai-webinar.scss
  static/sass/takeovers/_financial-services.scss
  templates/engage/ai-ml-ubuntu.html
  templates/engage/deploy-ai-ml-model.html
  templates/engage/future-proof-iot.html
  templates/takeovers/_ai_webinar-2018-10-01.html
  templates/takeovers/_ai_webinar.html
  templates/takeovers/de/_german_ai_webinar.html
  tests/cypress/navigation_spec.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#8251 Optimise CVE filter
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8265 Fix CVE order
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8282 Add redirect for active directory to discourse topic
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8250 Add notification banner to ESM page
  templates/esm/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8228 Update the /managed page
  templates/managed/index.html
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1

#8284 Add GMO pepabo engage page
  templates/engage/case-study-gmo-pepabo.md
  templates/engage/index.html
Labels: Review: Code +1, Review: QA +1

#8266 Display cve package sources
  templates/security/cve/cve.html
Labels: Project, Review: Code +1, Review: QA +1

#8224 Edit bulk import
  webapp/security/views.py
Labels: Project, Review: Code +1

#8268 Fix print page layout
  static/sass/print.scss
Labels: Review: Code +1, Review: QA +1

#8290 Build da-vmware-a-charmed-openstack engage page and takeover
  templates/engage/index.html
  templates/engage/it/da-vmware-a-charmed-openstack.md
  templates/index.html
  templates/takeovers/index.html
  templates/takeovers/it/_da-vmware-a-charmed-openstack.html
Labels: Review: Code +1, Review: QA +1

#8297 Show machine allowances on /renewals when possible
  .env
  tests/cassettes/TestRoutes.test_advantage.yaml
  tests/test_views.py
  webapp/advantage.py
  webapp/app.py
  webapp/views.py
Labels: Don't merge, Review: Code +1, Review: QA +1

#8296 Make the EdgeX newsletter monthly instead of weekly
  templates/internet-of-things/edgex.html
Labels: Review: Code +1

#8289 Remove /desktop/activedirectory redirect
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#8304 Move ESM and Livepatch to security from support
  navigation.yaml
  redirects.yaml
  templates/security/esm/base_esm.html
  templates/security/esm/index.html
  templates/security/livepatch/base_livepatch.html
  templates/security/livepatch/index.html
Labels: Review: Code +1, Review: QA +1

#8285 Update list of live takeovers
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#8308 Re-add overview on /security
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#8293 Revert "Add notification banner to ESM page"
  templates/security/esm/index.html
Labels: Review: Code +1, Review: QA +1

#8306 Update redirect to snapcraft.io
  konf/site.yaml
Labels: Review: Code +1

#8286 Update patches and tags
  templates/security/cve/cve.html
Labels: Project, Review: Code +1

#8310 Rebuild livepatch hero
  templates/security/livepatch/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8269 Update managed kafka
  templates/managed/kafka.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8302 Update bulk cve update
  webapp/security/views.py
Labels: Project, Review: Code +1

#8311 Remove PROVEN IN THE FIELD strip
  templates/internet-of-things/edgex.html
Labels: Review: Code +1, Review: QA +1

#8312 Add cves in usn listings
  templates/security/_notice-brief.html
Labels: Project, Review: Code +1, Review: QA +1

#8303 SMART START guide
  konf/site.yaml
  requirements.txt
  templates/smart-start/base_docs.html
  templates/smart-start/document.html
  webapp/app.py
Labels: Review: Code +1 (with changes), Review: QA +1

#8316 Add lang=es to Spanish takeover
  templates/takeovers/es/guía-implementación-openstack.html
Labels: Review: Code +1, Review: QA +1

#8313 Update /openstack/install with updated instructions
  templates/openstack/install.html
Labels: Review: Code +1, Review: QA +1

#8249 Blog product cards (round 1)
  static/js/src/navigation.js
  templates/blog/product-cards.html
  templates/blog/product-cards/_bootstack_managed-private-cloud.html
  templates/blog/product-cards/_bosch_ubuntu-for-iot.html
  templates/blog/product-cards/_ceph_what-is-ceph.html
  templates/blog/product-cards/_kubeflow_deploy-tutorial.html
  templates/blog/product-cards/_kubeflow_jaas-bundle.html
  templates/blog/product-cards/_kubeflow_what-is-kubeflow.html
  templates/blog/product-cards/_kubernetes_what-is-kubernetes.html
Labels: Review: Code +1, Review: QA +1

#8320 Update case study on /security/esm
  templates/security/esm.html
  templates/security/esm/base_esm.html
  templates/security/livepatch.html
  templates/security/livepatch/base_livepatch.html
Labels: Review: Code +1, Review: QA +1

#8323 Copy update - Privacy notice - Online purchase
  templates/legal/data-privacy/online-purchase.md
Labels: Review: Code +1, Review: QA +1

#8322 Fix detele status on bulk upload
  webapp/security/views.py
Labels: Project, Review: Code +1

#8073 Download promotions for server
  redirects.yaml
  static/sass/_pattern_links.scss
  static/sass/styles.scss
  templates/400.html
  templates/download/desktop/thank-you.html
  templates/download/raspberry-pi/thank-you.html
  templates/download/server/choose.html
  templates/download/server/download.html
  templates/download/server/index.html
  templates/download/server/step1.html
  templates/download/server/step2.html
  templates/download/server/thank-you.html
  templates/download/shared/_server_weekly_news.html
  templates/templates/navigation-download-h.html
  tests/test_routes.py
  webapp/app.py
  webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py
  webapp/security/models.py
  webapp/security/schemas.py
  webapp/security/views.py
  webapp/views.py
Labels: Review: Code +1, Review: Design +1, Review: Marketing +1, Review: QA +1, Review: UX +1

#8328 /download/server Impressions tracking
  static/js/src/navigation.js
  templates/download/server/choose.html
  templates/download/server/download.html
  templates/download/server/step1.html
  templates/download/server/step2.html
Labels: Review: Code +1, Review: QA +1

#8330 Fix desktop contributions
  templates/download/desktop/thank-you.html
  tests/test_routes.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#8327 Add compliance takeover
  package.json
  templates/index.html
  templates/takeovers/_fips_certification_cis_compliance.html
  templates/takeovers/index.html
  webapp/app.py
  webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py
  webapp/security/models.py
  webapp/security/schemas.py
  webapp/security/views.py
  webapp/views.py
Labels: Review: Code +1 (with changes), Review: QA +1

#8333 Build Cassandra webinar takeover
  templates/index.html
  templates/takeovers/_cassandra-webinar-takeover.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8332 Update the docker image to 1.6.8
  run
Labels: Review: Code +1, Review: QA +1

#8331 Smart Start moves to /smart-start/guide
  requirements.txt
  templates/smart-start/guide/base_docs.html
  templates/smart-start/guide/document.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#8344 Changed the button text to "Download the pro tips"
  templates/download/shared/_server_weekly_news.html
Labels: Review: Code +1, Review: QA +1

#8342 Removed text on server/download for MAAS step
  templates/download/server/step2.html
Labels: Review: Code +1, Review: QA +1

#8318 Update blog to version 6.2.4
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#8334 [Smart Start] Static contact form and thank you page
  templates/smart-start/base_smart-start.html
  templates/smart-start/contact-us.html
  templates/smart-start/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8339 Add endpoint to read notices
  webapp/app.py
  webapp/security/models.py
  webapp/security/views.py
Labels: Project, Review: Code +1, Review: QA +1

#8340 Hide 'Featured in' section and update blog strip typography'
  static/sass/styles.scss
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#8338 Improve titles and descriptions on the /download/server section
  templates/download/server/arm.html
  templates/download/server/choose.html
  templates/download/server/provisioning.html
  templates/download/server/step1.html
  templates/download/server/step2.html
Labels: Review: Code +1, Review: QA +1

#8350 Fix bulk CVE update when published date is None
  webapp/security/views.py
Labels: Project, Review: Code +1

#8353 Sharpen blog images
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#8364 Remove environments from takeover
  templates/takeovers/_fips_certification_cis_compliance.html
Labels: Review: Code needed, Review: QA needed

#8368 Update /download/cloud copy
  templates/download/cloud/index.html
  templates/public-cloud/index.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Review: Code +1, Review: QA +1

#8372 Copy update - security/certifications
  templates/security/certifications.html
Labels: Review: Code +1, Review: QA +1

#8370 Make the download server journey more of a wizard
  static/sass/_pattern_links.scss
  static/sass/styles.scss
  templates/download/server/choose.html
  templates/download/server/step1.html
  templates/download/server/step2.html
Labels: Review: Code +1 (with changes), Review: Design needed, Review: Marketing needed, Review: QA +1, Review: UX +1

#8244 Advantage shop VAT
  .env
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/error-handler.js
  static/js/src/advantage/set-modal-info.js
  static/js/src/advantage/tests/error-handler.test.js
  static/js/src/advantage/tests/set-modal-info.test.js
  static/js/src/ua-payment-modal.js
  static/js/src/ua-product-selector.js
  static/sass/_pattern_renewal-modal.scss
  templates/advantage/_stripe-modal.html
  templates/advantage/index.html
  templates/advantage/subscribe.html
  templates/advantage/table/_contract-name.html
  templates/advantage/table/_renewal-actions.html
  webapp/advantage.py
  webapp/app.py
  webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py
  webapp/security/models.py
  webapp/security/schemas.py
  webapp/views.py
Labels: Project, Review: Code +1, Review: QA +1, Review: UX +1

#8218 K8sDocs - Update 1.18 components for 1.18ck2
  templates/kubernetes/docs/1.18/charm-aws-iam.md
  templates/kubernetes/docs/1.18/charm-aws-integrator.md
  templates/kubernetes/docs/1.18/charm-azure-integrator.md
  templates/kubernetes/docs/1.18/charm-calico.md
  templates/kubernetes/docs/1.18/charm-canal.md
  templates/kubernetes/docs/1.18/charm-containerd.md
  templates/kubernetes/docs/1.18/charm-docker-registry.md
  templates/kubernetes/docs/1.18/charm-docker.md
  templates/kubernetes/docs/1.18/charm-easyrsa.md
  templates/kubernetes/docs/1.18/charm-etcd.md
  templates/kubernetes/docs/1.18/charm-flannel.md
  templates/kubernetes/docs/1.18/charm-gcp-integrator.md
  templates/kubernetes/docs/1.18/charm-kata.md
  templates/kubernetes/docs/1.18/charm-keepalived.md
  templates/kubernetes/docs/1.18/charm-kubeapi-load-balancer.md
  templates/kubernetes/docs/1.18/charm-kubernetes-master.md
  templates/kubernetes/docs/1.18/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.18/charm-openstack-integrator.md
  templates/kubernetes/docs/1.18/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.18/charm-vsphere-integrator.md
  templates/kubernetes/docs/1.18/components.md
  templates/kubernetes/docs/1.18/release-notes.md
  templates/kubernetes/docs/1.18/upgrading.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#8360 Create /appliance/lxd pages
  appliances.yaml
  navigation.yaml
  templates/appliance/adguard/index.md
  templates/appliance/lxd/_next-steps.html
  templates/appliance/lxd/index.md
  templates/appliance/lxd/intel-nuc.html
  templates/appliance/lxd/raspberry-pi.html
  templates/appliance/mosquitto/index.md
  templates/appliance/nextcloud/index.md
  templates/appliance/openhab/index.md
  templates/appliance/plex/index.md
  templates/appliance/shared/_base_appliance_index.html
  templates/appliance/shared/_what_you_will_need_pi.html
Labels: Review: Code +1, Review: Marketing +1, Review: QA +1

#8374 Change the notice import
  webapp/security/views.py
Labels: Review: Code +1

#8379 Exclude tag not:ubuntu on ubuntu.com/blog
  tests/cassettes/TestRoutes.test_blog.yaml
  webapp/app.py
Labels: Review: Code +1

#8384 Ubuntu Core on KVM guide: tweaks to make it clear we're installing UC18
  templates/download/kvm.html
Labels: Review: QA +1

#8386 Fix expiry date/new label bug on /advantage
  templates/advantage/table/_contract-name.html
Labels: Project, Review: Code +1, Review: QA +1

#8387 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1, Review: Code needed

#8371 Update USN search by details
  webapp/security/views.py
Labels: Review: Code +1, Review: QA +1

#8391 Update security series takeover CTA URL
  templates/takeovers/_security-webinar-series.html
Labels: Priority: High, Review: Code +1, Review: QA +1

#8382 Trilio webinar - takeover and engage page
  templates/engage/index.html
  templates/engage/trilio-backup-recovery.md
  templates/index.html
  templates/takeovers/_trilio-backup-recovery.html
  templates/takeovers/index.html
Labels: Review: Code +1, Review: QA +1

#8375 Copy update Kubeflow training
  templates/training/contact-us.html
  templates/training/index.html
  templates/training/thank-you.html
Labels: Review: Code +1, Review: QA +1

#8390 Replace with transparent logos on /security/certifications
  templates/security/certifications.html
Labels: Review: Code +1, Review: QA +1
