Repository canonical/ubuntu.com, pull requests merged in 2021-05, with the labels that each got.

#9656 K8s install page refresh
  static/sass/_pattern_tabs.scss
  templates/kubernetes/_install-aws.html
  templates/kubernetes/_install-azure.html
  templates/kubernetes/_install-google.html
  templates/kubernetes/_install-linux.html
  templates/kubernetes/_install-lxd.html
  templates/kubernetes/_install-macos.html
  templates/kubernetes/_install-windows.html
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9643 Kubernetes landing page refresh
  templates/kubernetes/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9677 Change cube register link
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#9682 Update /security/esm copy
  templates/security/esm.html
Labels: Review: Code +1, Review: QA +1

#9684 Fix contact us modals on /kubernetes and /kubernetes/install
  templates/kubernetes/contact-us.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
Labels: Review: Code +1, Review: QA +1

#9685 Update /openstack/consulting page
  templates/openstack/consulting.html
  templates/openstack/index.html
  templates/pricing/consulting.html
  templates/shared/pricing/_openstack-packages.html
Labels: Review: Code +1, Review: QA +1

#9629 Add Canonical and Dell AI webinar page
  templates/workstations-journey-to-ai/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9689 Update the title of the /16-04 page
  templates/16-04/index.html
Labels: Review: Code +1

#9690 Update the OpenStack features page content
  templates/openstack/features.html
Labels: Review: Code +1 (with changes), Review: QA +1

#9688 Add blog strip on /financial-services page
  templates/financial-services/index.html
Labels: Review: Code +1, Review: QA +1

#9668 Remove space after Sign in link on /advantage
  templates/advantage/index-no-login.html
Labels: Review: Code +1, Review: QA +1

#9676 Add ROS and update link to azure on /16-04
  templates/16-04/index.html
Labels: Review: Code +1, Review: QA +1

#9692 Meta title fix for K8s overview page
  templates/kubernetes/index.html
Labels: Review: Code +1

#9663 Update CTA on aws and azure
  templates/aws/pro.html
  templates/azure/pro.html
Labels: Review: Code +1, Review: QA +1

#9680 Update OpenStack X to Xena on /about/release-cycle
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#9659 Fix period being hardcoded to monthly for resizing
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/manage-subscription.js
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
Labels: Bug 🐛, Review: Code +1, Review: QA +1

#9670 Add GCP to the product selector
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  static/sass/_pattern_card.scss
  templates/advantage/subscribe/form/_type_select.html
Labels: Review: Code +1, Review: Design +1, Review: PdM +1, Review: QA +1, UA shop 🛒

#9693 updates datasheet link on livepatch page
  templates/security/livepatch.html
Labels: Review: Code +1, Review: QA +1

#9679 Update /openstack with new whitepaper and logo
  templates/openstack/index.html
Labels: Review: Code +1, Review: QA +1

#9691 Update /advantage logged out copy
  templates/advantage/_table.html
  templates/advantage/index-no-login.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9694 K8s1.21+ck1 release updates
  templates/kubernetes/docs/1.21/release-notes.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/supported-versions.md
Labels: Docs 📚, Review: Code needed, Review: QA needed

#9687 Update /robotics/ros-esm page
  navigation.yaml
  redirects.yaml
  templates/robotics/base_robotics.html
  templates/robotics/ros-esm.html
  templates/robotics/shared/_learn-more-about-robotics.html
  templates/robotics/thank-you.html
  templates/shared/contextual_footers/_robotics_newsletter_signup.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9702 Fix typo on /download/iot
  templates/download/iot/index.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9695 Add release paths for API
  konf/site.yaml
Labels: Review: Code +1

#9699 updates average hourly ubuntu pro cost range
  templates/gcp/pro.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9704 Add azure private offer page
  templates/azure/private-offer.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9669 Update instruction copy
  build.js
  static/js/src/advantage/entitlements-callout.js
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
  templates/advantage/table/_attached-machines.html
Labels: Review: Code +1, Review: Design +1, Review: PdM +1, Review: QA +1, Review: UX +1, UA shop 🛒

#9700 CUBE: Fix login URL
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#9710 Text changes on private offer page
  templates/azure/private-offer.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9714 Remove accordion one release
  templates/certification/model-details.html
Labels: Review: Code +1, Review: QA +1

#9715 Fix a load of link errors across the site
  .github/workflows/live-links.yaml
  redirects.yaml
  static/sass/_pattern_renewal-modal.scss
  templates/ai/what-is-kubeflow.html
  templates/internet-of-things/gateways.html
  templates/pricing/devices.html
  templates/pricing/index.html
  templates/server/hyperscale.html
  templates/shared/contextual_footers/_containers_juju.html
  templates/shared/contextual_footers/_desktop_buy_preinstalled.html
Labels: Review: Code +1 (with changes)

#9723 Azure private offer link text
  templates/azure/private-offer.html
Labels: Review: Code +1, Review: QA +1

#9728 Add closing script tab to allow download script to work
  templates/advantage/index.html
  templates/download/desktop/thank-you.html
Labels: Review: Code +1, Review: QA +1

#9718 Add FIPS to the UA service description
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: QA +1

#9735 Remove loading state from modal if the payment preview fails
  static/js/src/ua-payment-modal.js
Labels: Review: Code +1, Review: QA +1

#9743 Pass customer name when setting customer info as guest
  static/js/src/advantage/contracts-api.js
  static/js/src/ua-payment-modal.js
  webapp/advantage/api.py
  webapp/advantage/schemas.py
  webapp/advantage/views.py
Labels: Review: Code +1

#9701 K8s charm rev updates for 1.21+ck1
  templates/kubernetes/docs/1.21/components.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#9762 Refactor search results page
  templates/certification/search-results.html
Labels: Review: Code +1, Review: QA +1

#9713 update removes title from ubuntu on azure video at /16-04/azure
  templates/16-04/azure.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9763 Update copy on aws/pro
  templates/aws/pro.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9708 Update payment methods page
  static/js/src/ua-payment-methods.js
  templates/advantage/index.html
  templates/advantage/payment-methods/index.html
  webapp/advantage/api.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Commercial 🛒, Review: Code +1 (with changes), Review: Design +1, Review: QA +1, Review: UX +1

#9767 Change CUBE homepage copy
  templates/cube/index.html
Labels: Review: Code +1, Review: QA +1

#9781 Update adds managed app link to navigation
  templates/templates/navigation-enterprise-h.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9778 Change to number of machines
  webapp/advantage/views.py
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#9775 Certified overview laptops
  templates/certification/index.html
  webapp/certification/views.py
Labels: Project, Review: Code +1, Review: QA +1

#9780 Update part-3.md
  templates/cube/study/juju/part-3.md
Labels: Review: QA +1

#9779 Update _navigation.md
  templates/cube/study/_navigation.md
Labels: Review: QA +1

#9745 Replace dupe paragraph on /robotics/ros-esm
  templates/robotics/ros-esm.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9770 Updates copy on /kubernetes/kubernetes-operations-survey
  templates/kubernetes/kubernetes-operations-survey.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9769 Rename is_binary to is_visible
  webapp/security/schemas.py
  webapp/security/views.py
Labels: Review: Code +1

#9711 Fix auto renewal section's spacing
  templates/advantage/index.html
Labels: Commercial 🛒, Review: Code +1, Review: Design +1, Review: QA +1

#9783 Add case studies to financial-services
  templates/financial-services/index.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9794 Add rich structure data ubuntu.com/blog posts
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#9791 Add contact form for /kubernetes/managed
  templates/kubernetes/managed.html
  templates/shared/forms/interactive/managed-kubernetes.html
Labels: Review: Code +1, Review: QA +1

#9793 CUBE: Use links that authenticate the user before redirecting to EDX
  templates/cube/microcerts.html
  tests/test_cube.py
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#9772 Updates copy on /security/esm
  templates/security/esm.html
Labels: Copy update 📝, Review: Code +1 (with changes), Review: QA +1

#9784 [Certs] Refactor overview page
  navigation.yaml
  templates/certification/index.html
  templates/certification/model-details.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#9810 Updates copy on /public-cloud
  templates/public-cloud/index.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Copy update 📝, Review: Code +1 (with changes), Review: QA +1

#9798 [CUBE] Fix progression hero and broken mobile view
  package.json
  static/sass/_pattern_cube-progression.scss
  templates/cube/microcerts.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#9809 CUBE: Microcerts page copy
  templates/cube/microcerts.html
  webapp/cube/content/cube-qa.yaml
  webapp/cube/content/cube.yaml
Labels: Review: Code +1, Review: QA +1

#9817 Updates to "Performing Administrative Tasks"
  templates/cube/study/_navigation.md
Labels: Review: Code +1

#9815 Certification master branch merge
  navigation.yaml
  redirects.yaml
  static/sass/_pattern_certification-results.scss
  static/sass/_pattern_component-details-table.scss
  static/sass/_pattern_component-table.scss
  static/sass/_pattern_hardware-details-table.scss
  static/sass/styles.scss
  templates/certified/base_certification.html
  templates/certified/component-details.html
  templates/certified/hardware-details.html
  templates/certified/index.html
  templates/certified/model-details.html
  templates/certified/search-results.html
  templates/dell/index.html
  templates/security/cve/_pagination.html
  tests/cassettes/TestCertification.test_component_details.yaml
  tests/cassettes/TestCertification.test_home.yaml
  tests/cassettes/TestCertification.test_model_details.yaml
  tests/cassettes/TestCertification.test_model_hardware_details.yaml
  tests/cassettes/TestCertification.test_search_results.yaml
  tests/test_certification.py
  webapp/app.py
  webapp/certified/api.py
  webapp/certified/views.py
Labels: Review: Code +1, Review: QA +1

#9826 Fix certified device count for IoT and SoC
  templates/certified/index.html
Labels: Review: Code +1, Review: QA +1

#9811 Update /financial-services
  templates/financial-services/index.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1

#9822 Copy update IBM
  templates/ibm/index.html
Labels: Copy update 📝, Review: Code +1, Review: QA +1
