Repository canonical/ubuntu.com, pull requests merged in 2021-09, with the labels that each got.

#10243 Fix the loading of smart-quotes
  static/js/src/main.js
  static/js/src/smart-quotes.js
Labels: Review: QA +1, Review: Code +1

#10263 Add a space
  templates/openstack/compare.html
Labels: Review: Code +1

#10264 Copy update on /pricing/consulting
  templates/shared/pricing/_kubernetes-consulting.html
Labels: Review: QA +1, Review: Code +1

#10240 Rebuilt /security/livepatch page
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10251 Updated copy title and contact link for CUBE /faq
  templates/cube/faq.html
Labels: Review: QA +1, Review: Code +1

#10193 K8sDocs component updates 1.21+ck3
  templates/kubernetes/docs/1.21/components.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#10257 Add last-payment-ids endpoint
  tests/advantage/test_helpers.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#10260 Update logos on /core page
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#10268 Updated copy and links on /kubernetes/compare
  templates/kubernetes/compare.html
Labels: Review: QA +1, Review: Code +1

#10252 updated copy and images on /public-cloud page
  templates/public-cloud/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10270 Add Xilinx to automotive
  templates/automotive/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10255 Display free token data from the new API
  static/js/src/advantage/api/enum.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/react/utils/formatDate.ts
  static/js/src/advantage/react/utils/getFeaturesDisplay.test.ts
  static/js/src/advantage/react/utils/getFeaturesDisplay.ts
  static/js/src/advantage/react/utils/index.ts
  static/js/src/advantage/react/utils/isFreeSubscription.test.ts
  static/js/src/advantage/react/utils/isFreeSubscription.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#10267 New advantage contract token endpoint
  tests/advantage/test_api.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10275 Build Xilinx download page
  navigation.yaml
  templates/download/xilinx/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10262 Include Xilinx on /download/iot
  templates/download/contact-us.html
  templates/download/iot/index.html
  templates/download/thank-you.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Don't merge

#10271 Add advantage/users route
  build.js
  navigation.yaml
  static/js/src/advantage/users/app.jsx
  templates/advantage/users/index.html
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10284 Add Xilinx to mega nav
  templates/templates/navigation-download-h.html
Labels: Review: QA +1, Review: Code +1

#10286 Remove release notes on Xilnix page
  templates/download/xilinx/index.html
Labels: Review: QA +1, Review: Code +1

#10269 New advantage user info endpoint
  tests/advantage/fixtures/subscriptions.json
  tests/advantage/test_helpers.py
  tests/advantage/test_parsers.py
  webapp/advantage/ua_contracts/builders.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10288 Updates to /download/xilinx
  templates/download/xilinx/index.html
Labels: Review: QA +1, Review: Code +1

#10256 Scroll to the subscription content if it is off the screen
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useScrollIntoView.test.tsx
  static/js/src/advantage/react/hooks/useScrollIntoView.ts
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#10283 Lower case c in all instances of "Ubuntu certified..."
  templates/core/smartstart/guide/certification-and-validation.md
  templates/desktop/partners.html
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/pricing/shared/_enablement-strip.html
Labels: Review: Code +1

#10280 Remove inline muted heading content strip styles
  templates/0_docs/content_strips.html
  templates/containers/shared/_whitepaper.html
  templates/core/index.html
  templates/kubernetes/index.html
  templates/managed/apps/cassandra.html
  templates/managed/apps/kafka.html
  templates/openstack/index.html
  templates/security/esm.html
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1

#10285 Update recaptcha on the /legal/contributors/agreement form
  templates/legal/contributors/agreement.html
Labels: Review: QA +1, Review: Code +1

#10293 Update xilinx links on people.c.c
  templates/download/xilinx/index.html
Labels: Review: QA +1, Review: Code +1

#10289 Changes for Discourse v4
  konf/site.yaml
  requirements.txt
  templates/tutorials/index.html
  tests/cassettes/TestRoutes.test_tutorials_homepage.yaml
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  tests/test_routes.py
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#10294 Added missing secrets
  konf/site.yaml
Labels: Review: Code +1

#10300 Remove modal class to contact us CTA under /managed
  templates/managed/apps/cassandra.html
  templates/managed/apps/index.html
  templates/managed/apps/kafka.html
  templates/managed/index.html
Labels: Review: QA needed, Review: Code needed

#10302 Add pi4 to /download/raspberry-pi desktop 21.04
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#10277 Remove old contracts API
  static/js/src/advantage/api/contracts-types.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx
  static/js/src/advantage/react/hooks/useLoadWindowData.ts
  static/js/src/advantage/react/hooks/usePersonalAccount.test.tsx
  static/js/src/advantage/react/hooks/usePersonalAccount.ts
  static/js/src/advantage/tests/factories/api.ts
  static/js/src/advantage/tests/factories/contracts.ts
  templates/advantage/index.html
Labels: Review: Code +1, Commercial 🛒

#10290 Display UA subscriptions in the list.
  static/js/src/advantage/api/enum.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#10291 Display details for a UA subscription
  static/js/src/advantage/api/enum.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/react/utils/formatDate.ts
  static/js/src/advantage/react/utils/getMachineTypeDisplay.test.ts
  static/js/src/advantage/react/utils/getMachineTypeDisplay.ts
  static/js/src/advantage/react/utils/getPeriodDisplay.test.ts
  static/js/src/advantage/react/utils/getPeriodDisplay.ts
  static/js/src/advantage/react/utils/getSubscriptionCost.test.ts
  static/js/src/advantage/react/utils/getSubscriptionCost.ts
  static/js/src/advantage/react/utils/index.ts
  static/js/src/advantage/tests/factories/api.ts
  static/sass/styles.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10292 Account users/Add organisation title
  package.json
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/app.jsx
  static/js/src/advantage/users/app.tsx
  static/js/src/advantage/users/components/Organisation.tsx
  tests/cypress/advantage_spec.js
  tsconfig.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10278 Fix filter count on /certified search results
  static/js/src/certified-search-results.js
Labels: Review: QA +1, Review: Code +1

#10282 New advantage legacy user subscriptions
  tests/advantage/fixtures/contract-item-legacy.json
  tests/advantage/fixtures/contract-item-shop.json
  tests/advantage/fixtures/contract-item-trial.json
  tests/advantage/fixtures/contract-items.json
  tests/advantage/fixtures/renewal.json
  tests/advantage/helpers.py
  tests/advantage/test_helpers.py
  tests/advantage/test_parsers.py
  webapp/advantage/models.py
  webapp/advantage/ua_contracts/builders.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10273 Refactor UA error handling
  tests/advantage/fixtures/customer-info.json
  tests/advantage/fixtures/ensured-account.json
  tests/advantage/fixtures/purchase.json
  tests/advantage/fixtures/purchases.json
  tests/advantage/fixtures/subscription-auto-renewal.json
  tests/advantage/test_api.py
  tests/test_advantage.py
  webapp/advantage/flaskparser.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: Code +1, Commercial 🛒

#10281 Adds security-livepatch docs
  navigation.yaml
  templates/security/livepatch/docs/document.html
  templates/security/livepatch/docs/search-results.html
  templates/sitemap_index.xml
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#10298 Rebuild openstack contact form
  templates/shared/forms/interactive/bootstack.html
  templates/shared/forms/interactive/openstack.html
Labels: Review: QA +1, Review: Code +1

#10304 Expiry notifications
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/index.ts
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/sass/_pattern_subscriptions.scss
Labels: Review: Code +1 (with changes), Commercial 🛒

#10310 Fix presentation issues on livepatch pages
  navigation.yaml
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1

#10309 Account Users/Add TableView
  .eslintrc.js
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/app.tsx
  static/js/src/advantage/users/components/TableView.tsx
  static/js/src/advantage/users/mockData.ts
  static/js/src/advantage/users/types.ts
Labels: Review: QA +1, Review: Code +1

#10274 Openstack consulting piechart
  build.js
  static/js/data/openstack-deployment-stats.json
  static/js/src/openstack-deployment-chart.js
  templates/openstack/consulting.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10315 Align buttons in one line
  templates/shared/forms/interactive/bootstack.html
  templates/shared/forms/interactive/openstack.html
Labels: Review: QA +1, Review: Code +1

#10276 Refactor advantage decorator
  templates/account/payment-methods/index.html
  templates/advantage/_stripe-modal.html
  templates/advantage/subscribe/index.html
  webapp/advantage/context.py
  webapp/advantage/decorators.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/views.py
  webapp/app.py
  webapp/decorators.py
Labels: Review: Code +1 (with changes), Commercial 🛒

#10311 Copy update on /security/docker-images
  static/js/third-party/typer.js
  templates/security/docker-images.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10224 Certified design fixes
  static/sass/_pattern_certification-results.scss
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10297 fix k8s image list
  templates/kubernetes/docs/1.22/components.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#10318 Fix user subscriptions endpoint
  tests/advantage/test_helpers.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10313 Close the edit form when switching subscriptions or closing the modal
  static/js/src/advantage/react/components/Subscriptions/Content/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10314 Sort the subscriptions by most recently started
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10308 Add `can_be_trialled` to product listings
  templates/advantage/subscribe/index.html
  tests/advantage/fixtures/subscription.json
  tests/advantage/helpers.py
  tests/advantage/test_api.py
  tests/advantage/test_helpers.py
  tests/advantage/test_parsers.py
  webapp/advantage/decorators.py
  webapp/advantage/models.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
Labels: Review: Code +1, Commercial 🛒

#10319 Sync with copydoc for FIPS and CIS pages
  templates/security/cis.html
  templates/security/fips.html
Labels: Review: QA +1, Review: Code +1

#10191 Fix cypress tests to ensure they pass
  .gitignore
  package.json
  templates/shared/_client-contact-us-form.html
  tests/cypress/forms_spec.js
  tests/cypress/navigation_spec.js
  yarn.lock
Labels: Maintenance 🔨, Review: QA +1, Review: Code +1

#10326 Ensure drawer is closed on page reload (small screens)
  static/js/src/certified-search-results.js
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
Labels: Review: QA +1, Review: Code +1

#10332 Build new /download/iot/intel-iotg page
  navigation.yaml
  templates/download/iot/intel-iotg.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM needed

#10327 Account users/user row
  package.json
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/TableView.tsx
  static/js/src/advantage/users/components/TableView/TableView.test.tsx
  static/js/src/advantage/users/components/TableView/TableView.tsx
  static/js/src/advantage/users/components/TableView/components.tsx
  static/js/src/advantage/users/mockData.ts
  static/js/src/advantage/users/types.ts
  tests/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10329 Account users/add new user button
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUser.test.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUser.tsx
  static/js/src/advantage/users/components/TableView/components.tsx
  static/js/src/advantage/users/constants.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10324 Fix logo alignment
  templates/managed/apps/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10335 Make covered texts visible on /cube
  templates/cube/index.html
Labels: Review: QA +1, Review: Code +1

#10320 updated ctas on /kubernetes and /kubernetes/what-is-kubernetes
  templates/kubernetes/index.html
  templates/kubernetes/what-is-kubernetes.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10338 Fix invoice download
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10316 Add trial endpoints
  webapp/advantage/schemas.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10328 User subscription in trial
  webapp/advantage/ua_contracts/builders.py
  webapp/advantage/ua_contracts/helpers.py
Labels: Review: Code +1, Commercial 🛒

#10321 Contract enterprise in trial
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10336 added fix for search function on /tutorials
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#10241 use certified category pages instead of search
  templates/certified/index.html
Labels: Review: QA +1, Review: Code +1

#10348 Account users/new user modal
  package.json
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUser.test.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUser.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.test.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
  static/js/src/advantage/users/components/TableView/TableView.test.tsx
  static/js/src/advantage/users/components/TableView/TableView.tsx
  static/js/src/advantage/users/components/TableView/components.tsx
  static/js/src/advantage/users/constants.ts
  static/js/src/advantage/users/mockData.ts
  static/js/src/advantage/users/types.ts
  yarn.lock
Labels: Review: Design needed, Review: QA +1, Review: Code +1

#10317 Changes to modal step 1
  static/js/src/advantage/subscribe/listeners/ui-event-listeners.js
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.tsx
  static/js/src/advantage/subscribe/react/PurchaseModal.jsx
  static/js/src/advantage/subscribe/react/app.tsx
  static/js/src/advantage/subscribe/react/components/ModalParts/ModalBody.tsx
  static/js/src/advantage/subscribe/react/components/ModalParts/ModalFooter.tsx
  static/js/src/advantage/subscribe/react/components/ModalParts/ModalHeader.tsx
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepOne.tsx
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
  static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  static/sass/_pattern_shop-cart.scss
Labels: Review: QA needed, Review: Code +1 (with changes), Commercial 🛒

#10350 exclude test files from watch-js glob pattern
  package.json
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10322 Select subscriptions via contract id
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/types.ts
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/react/utils/getSubscriptionCost.test.ts
  static/js/src/advantage/react/utils/getSubscriptionCost.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10330 Display the contract token
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/api/contracts.test.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useContractToken.test.tsx
  static/js/src/advantage/react/hooks/useContractToken.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10345 Add account users endpoint
  tests/advantage/fixtures/user.json
  tests/advantage/fixtures/users.json
  tests/advantage/test_api.py
  tests/advantage/test_parsers.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10349 Add is trialling to shop view
  tests/advantage/fixtures/subscription.json
  tests/advantage/test_parsers.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10341 Removed /robotics from IoT subnav
  navigation.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#10351 Add/Edit/Delete account user role
  tests/advantage/test_api.py
  tests/advantage/test_parsers.py
  webapp/advantage/schemas.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: Code +1, Commercial 🛒

#10353 [Certified] - Keep query string when filters are cleared
  static/js/src/certified-search-results.js
  tests/cypress/certified_spec.js
Labels: Review: QA +1, Review: Code +1

#10355 account users/delete user modal
  static/js/src/advantage/tests/utils.ts
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
  static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.test.tsx
  static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.tsx
  static/js/src/advantage/users/components/TableView/TableView.test.tsx
  static/js/src/advantage/users/components/TableView/TableView.tsx
  static/js/src/advantage/users/components/TableView/components.tsx
  static/js/src/advantage/users/mockData.ts
  static/js/src/advantage/users/types.ts
  static/js/src/advantage/users/utils.ts
Labels: Review: QA +1, Review: Code +1

#10331 Get the test backend flag from the URL
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/hooks/useLoadWindowData.ts
  static/js/src/advantage/react/hooks/useURLs.test.tsx
  static/js/src/advantage/react/hooks/useURLs.ts
  static/js/src/advantage/react/hooks/useUsingTestBackend.test.tsx
  static/js/src/advantage/react/hooks/useUsingTestBackend.ts
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10358 Add account name
  webapp/advantage/views.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#10356 Build /ceph/managed page
  navigation.yaml
  templates/ceph/managed.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10354 Build /ceph/consulting page
  navigation.yaml
  templates/ceph/consulting.html
  templates/shared/pricing/_ceph-cluster-build-pricing.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10367 Fix links from certified homepage
  templates/certified/index.html
Labels: Review: QA +1, Review: Code +1

#10368 Update contact form
  static/js/src/dynamic-forms.js
  templates/kubernetes/install.html
  templates/shared/forms/interactive/kubernetes.html
  templates/shared/forms/interactive/managed-kubernetes.html
Labels: Review: QA +1, Review: Code +1

#10361 Content update on the page "Charmed Kubernetes features"
  templates/kubernetes/features.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#10342 Changes to Modal step 2
  static/js/src/advantage/subscribe/react/APICalls/useFreeTrial.tsx
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.tsx
  static/js/src/advantage/subscribe/react/components/FreeTrialRadio/FreeTrialRadio.test.tsx
  static/js/src/advantage/subscribe/react/components/FreeTrialRadio/FreeTrialRadio.tsx
  static/js/src/advantage/subscribe/react/components/FreeTrialRadio/index.ts
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
Labels: Review: Code +1

#10363 Free trial error states
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  templates/advantage/subscribe/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#10366 204/account users/API integration
  static/js/src/advantage/users/AccountUsers.test.tsx
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/api.ts
  static/js/src/advantage/users/app.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.test.tsx
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
  static/js/src/advantage/users/types.ts
  static/js/src/advantage/users/utils.ts
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#10383 Fix trial parameter typo
  webapp/advantage/views.py
Labels: Review: Code +1, Commercial 🛒

#10371 Ua subs window title
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10357 Display contract features and docs links
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes), Commercial 🛒

#10391 Update releases.yaml for bionic to point 6
  releases.yaml
Labels: Review: QA +1, Review: Code +1

#10385 API subscription cancel
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/api/contracts.test.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useCancelContract.test.tsx
  static/js/src/advantage/react/hooks/useCancelContract.ts
  static/js/src/advantage/react/hooks/useLastPurchaseIds.test.tsx
  static/js/src/advantage/react/hooks/useLastPurchaseIds.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: Code +1, Commercial 🛒

#10395 Add proxy docs for k8s
  templates/kubernetes/docs/proxy-settings.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#10397 Modal form not working on /managed/apps
  templates/managed/apps/index.html
Labels: Review: Code +1

#10392 Copy update azure aws pro
  templates/aws/pro.html
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1

#10390 Fix free trial call
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/subscribe/react/APICalls/useFreeTrial.tsx
  static/js/src/advantage/subscribe/react/APICalls/usePreview.tsx
  static/js/src/advantage/subscribe/react/APICalls/useProduct.jsx
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepOne.tsx
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
  static/js/src/advantage/subscribe/react/components/Summary/Summary.tsx
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10402 Build new ubuntu advantage service description
  templates/legal/ubuntu-advantage-service-description/_toc.html
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/shared/_ubuntu-advantage-service-description.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#10340 Gray out the logo and secondary nav
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#10380 Build simple cube purchase app
  build.js
  static/js/src/cube/app.tsx
  static/js/src/cube/components/MicrocertificationsTable/MicrocertificationsTable.tsx
  static/js/src/cube/components/MicrocertificationsTable/index.ts
  templates/cube/microcerts.html
Labels: Review: QA +1, Review: Code +1

#10401 Fix typo cancel trial
  webapp/app.py
Labels: Review: Code +1, Commercial 🛒

#10399 Fix user info page
  webapp/advantage/ua_contracts/builders.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10398 Add user subscription id
  webapp/advantage/models.py
  webapp/advantage/ua_contracts/builders.py
  webapp/advantage/ua_contracts/helpers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10389 Expiry notification border
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Commercial 🛒

#10370 Display a spinner for the initial load
  static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10369 Cancel a subscription via the API.
  package.json
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  yarn.lock
Labels: Review: QA +1, Review: Code needed, Review: Code +1 (with changes), Commercial 🛒

#10393 Update the Ceph webinar link
  templates/ceph/managed.html
Labels: Review: QA +1, Review: Code +1

#10343 Invoke modal from managed
  templates/managed/index.html
Labels: Review: Code +1

#10381 200/account users/edit view
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.tsx
  static/js/src/advantage/users/components/TableView/TableView.test.tsx
  static/js/src/advantage/users/components/TableView/TableView.tsx
  static/js/src/advantage/users/components/TableView/UserRow.test.tsx
  static/js/src/advantage/users/components/TableView/UserRow.tsx
  static/js/src/advantage/users/components/TableView/components.tsx
  static/js/src/advantage/users/utils.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10400 Update the content of /ceph to match the copy doc
  templates/ceph/index.html
  templates/ceph/managed.html
Labels: Review: QA +1, Review: Code +1

#10412 Update the content of /16-04 to match the copy doc
  templates/16-04/index.html
Labels: Review: QA +1, Review: Code +1

#10410 Update the content of /security/esm to match the copy doc
  templates/security/esm.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#10396 Increase the timeout when linkchecking
  .github/workflows/blog-links.yaml
  .github/workflows/ceph-docs-links.yaml
  .github/workflows/core-docs-links.yaml
  .github/workflows/kubernetes-docs-links.yaml
  .github/workflows/live-links.yaml
  .github/workflows/openstack-charm-deployment-guide-docs-links.yaml
  .github/workflows/openstack-charm-guide-docs-links.yaml
  .github/workflows/security-links.yaml
  .github/workflows/server-docs-links.yaml
Labels: Review: Code +1

#10405 Select subscriptions using their id
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/tests/factories/api.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10372 Select the most recently started subscription
  static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/utils/index.ts
  static/js/src/advantage/react/utils/sortSubscriptionsByStartDate.test.ts
  static/js/src/advantage/react/utils/sortSubscriptionsByStartDate.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10418 fix new user submission on Enter key
  static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10403 Remove image builder
  build.js
  deleted.yaml
  requirements.txt
  static/js/src/imageBuilder.js
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_card.scss
  static/sass/_pattern_divider.scss
  static/sass/styles.scss
  templates/core/build/base_build.html
  templates/core/build/error.html
  templates/core/build/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#10382 Copy update ros esm
  templates/robotics/ros-esm.html
Labels: Review: Code -1, Review: QA needed

#10386 Subscription loading failed message
  static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10420 Updated the page /16-04/azure (copy doc)
  templates/16-04/azure.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10436 Updates to release cycle
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#10419 Account users/incremental loading
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/app.tsx
  templates/advantage/users/index.html
Labels: Review: QA +1, Review: Code +1

#10433 Fix display date when when lastLoginAt is null
  static/js/src/advantage/users/api.ts
  static/js/src/advantage/users/components/TableView/UserRow.tsx
  static/js/src/advantage/users/types.ts
Labels: Review: QA +1, Review: Code +1

#10424 Get the pending purchase status from the subscriptions.
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx
  static/js/src/advantage/react/hooks/useLoadWindowData.ts
  static/js/src/advantage/react/hooks/usePendingPurchaseId.test.tsx
  static/js/src/advantage/react/hooks/usePendingPurchaseId.ts
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/tests/factories/api.ts
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10425 Remove server-side subscription fetching.
  tests/test_routes.py
  tests/test_views.py
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10430 Allow e2e tests for logged-in user journeys - account users e2e tests
  .github/workflows/cypress.yaml
  cypress.env.template.json
  package.json
  tests/cypress/advantage-users_spec.js
  tests/cypress/cypress.json
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/utils.js
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10376 Update pie-chart with suggestions
  static/js/src/openstack-deployment-chart.js
  templates/openstack/consulting.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10435 Hide free trial message on live if not eligible
  static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  templates/advantage/subscribe/index.html
Labels: Review: QA +1, Review: Code +1

#10422 Call the delete trial endpoint when the button is clicked
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/manage-subscription.js
  templates/advantage/table/_free-trial.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#10451 Fixed duplicated normal strip at the end of the page
  templates/robotics/ros-esm.html
Labels: Review: QA +1, Review: Code +1

#10453 Updated links for "Contributor licence agreement"
  templates/legal/contributors/agreement.html
Labels: Review: QA +1, Review: Code +1

#10446 K8s links fix
  templates/kubernetes/docs/1.16/charm-kubernetes-master.md
  templates/kubernetes/docs/1.16/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.16/release-notes.md
  templates/kubernetes/docs/1.17/charm-kubernetes-master.md
  templates/kubernetes/docs/1.17/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.17/release-notes.md
  templates/kubernetes/docs/1.18/charm-containerd.md
  templates/kubernetes/docs/1.18/charm-kubernetes-master.md
  templates/kubernetes/docs/1.18/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.18/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.18/release-notes.md
  templates/kubernetes/docs/1.19/charm-containerd.md
  templates/kubernetes/docs/1.19/charm-kubernetes-master.md
  templates/kubernetes/docs/1.19/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.19/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.20/charm-containerd.md
  templates/kubernetes/docs/1.20/charm-kubernetes-master.md
  templates/kubernetes/docs/1.20/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.20/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.21/charm-containerd.md
  templates/kubernetes/docs/1.21/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.21/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.22/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.22/components.md
  templates/kubernetes/docs/charm-azure-integrator.md
  templates/kubernetes/docs/charm-kubernetes-worker.md
  templates/kubernetes/docs/charm-openstack-integrator.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/ipv6.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/multiple-networks.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/security.md
  templates/kubernetes/docs/storage.md
Labels: Review: QA +1, Docs 📚, Review: Code +1 (with changes)

#10441 Remove old advantage
  build.js
  static/js/src/advantage/auto-renewal.js
  static/js/src/advantage/set-modal-info.js
  static/js/src/advantage/tests/set-modal-info.test.js
  static/js/src/ua-payment-modal.js
  templates/advantage/_stripe-modal.html
  templates/advantage/shared/_certifications-info.html
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
  templates/advantage/table/_attached-machines.html
  templates/advantage/table/_contract-name.html
  templates/advantage/table/_expiry-date.html
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
  templates/advantage/table/_renewal-actions.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10442 Add analytics events to subscription interactions.
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx
  static/js/src/advantage/react/utils/sendAnalyticsEvent.test.ts
  static/js/src/advantage/react/utils/sendAnalyticsEvent.ts
  static/js/src/globals.d.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10438 Build the table layout
  static/js/src/cube/components/MicrocertificationsTable/MicrocertificationsTable.tsx
  static/sass/_pattern_cube-table.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10467 add TypeScript check to GitHub actions
  .github/workflows/pr.yaml
  package.json
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.tsx
Labels: Review: QA +1, Review: Code +1

#10448 added pie chart to page
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#10484 Remove hide free trial header until we release it
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  templates/advantage/subscribe/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10447 Build /cloud/hybrid-cloud page
  navigation.yaml
  templates/cloud/hybrid-cloud.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10487 K8s: Add Equinix page
  navigation.yaml
  templates/kubernetes/docs/equinix.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#10437 Build /cloud/private-cloud page
  navigation.yaml
  redirects.yaml
  templates/cloud/private-cloud.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10444 Reintroduce the ubuntu pro beta invite
  templates/advantage/index-no-login.html
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10491 Disable JS minification in development
  README.md
  build.js
Labels: Review: QA +1, Review: Code +1

#10492 fix advantage cypress test
  tests/cypress/advantage_spec.js
Labels: Review: Code +1

#10439 Observability build
  navigation.yaml
  templates/observability/what-is-observability.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10466 Build /cloud/multi-cloud page
  navigation.yaml
  templates/cloud/hybrid-cloud.html
  templates/cloud/multi-cloud.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10375 Add update default entitlements endpoint
  tests/advantage/test_api.py
  webapp/advantage/schemas.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: Code +1, Commercial 🛒

#10457 Add sentry to advantage/users
  static/js/src/advantage/subscribe/react/app.tsx
  static/js/src/advantage/users/app.tsx
Labels: Review: QA +1, Review: Code +1

#10490 Reorder docs links
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10443 Cta copy update
  templates/kubernetes/compare.html
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10465 Updated the page /cube/microcerts
  webapp/cube/content/cube-qa.yaml
  webapp/cube/content/cube.yaml
Labels: Review: QA +1, Review: Code +1
