Repository canonical/ubuntu.com, pull requests merged in 2021-08, with the labels that each got.

#10085 Updates cube terms of service
  templates/legal/terms-and-policies/cube-terms.html
Labels: Review: Code +1, Review: QA +1

#10061 Microstack installation instructions on openstack page
  templates/openstack/install.html
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1 (with changes), Review: QA +1, Review: UX +1

#10107 [Certified improvements] - Add clear filters button
  templates/certified/index.html
  templates/certified/search-results.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#10108 Add new /certified/desktops page
  redirects.yaml
  templates/certified/desktops-search-results.html
  templates/certified/index.html
  templates/desktop/developers.html
  webapp/app.py
  webapp/certified/views.py
Labels: Review: Code +1, Review: QA +1

#10116 move is-dense accordion modifier to accordion
  static/sass/_pattern_accordion.scss
  static/sass/_pattern_certification-results.scss
  static/sass/styles.scss
  templates/certified/search-results.html
Labels: Review: Code +1, Review: QA +1

#10068 Creates /osm page
  navigation.yaml
  templates/shared/forms/interactive/osm-contact-us.html
  templates/telco/osm/contact-us.html
  templates/telco/osm/index.html
  templates/telco/osm/thank-you.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#10117 Copy update on /legal/companies
  templates/legal/companies.html
  templates/shared/contextual_footers/_cloud_bootstack.html
Labels: Review: Code +1, Review: QA +1

#10127 K*sDocs-1.21+ck3 updates
  templates/kubernetes/docs/1.21/release-notes.md
  templates/kubernetes/docs/charm-containerd.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/supported-versions.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#10128 Copy update on /ceph/what-is-ceph
  templates/ceph/what-is-ceph.html
Labels: Review: Code +1, Review: QA +1

#10124 Fix VAT problems
  webapp/advantage/views.py
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#10121 Add subscription notifications component
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/index.ts
  static/js/src/advantage/react/components/Subscriptions/Subscriptions.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useURLs.test.tsx
  static/js/src/advantage/react/hooks/useURLs.ts
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#10123 Add responsive cancel modal
  package.json
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/index.ts
  static/sass/_pattern_subscribe.scss
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#10104 Add API types
  static/js/src/advantage/api/contracts-types.ts
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/auto-renewal.js
  static/js/src/advantage/manage-subscription.js
  static/js/src/advantage/subscribe/react/APICalls/registerPaymentMethod.jsx
  static/js/src/advantage/subscribe/react/APICalls/usePendingPurchase.jsx
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoAnon.jsx
  static/js/src/advantage/subscribe/react/APICalls/usePreview.jsx
  static/js/src/advantage/subscribe/react/APICalls/usePurchase.jsx
  static/js/src/advantage/subscribe/react/APICalls/useStripeCustomerInfo.jsx
  static/js/src/ua-payment-methods.js
  static/js/src/ua-payment-modal.js
  yarn.lock
Labels: Commercial 🛒, Review: Code +1

#10110 Add subscription group and card components
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/sass/_pattern_subscriptions.scss
  static/sass/styles.scss
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#10122 Add header buttons
  static/js/src/advantage/react/components/Subscriptions/Subscriptions.tsx
  static/sass/_pattern_subscribe.scss
  static/sass/_pattern_subscriptions.scss
  templates/advantage/index.html
Labels: Commercial 🛒, Review: Code +1, Review: QA +1

#10134 Add TypeScript linting
  .eslintrc.js
  package.json
  static/js/src/cloud-price-slider.js
  static/js/src/contributions.js
  yarn.lock
Labels: Commercial 🛒, Review: Code +1

#10133 Fix components table releases
  templates/certified/model-details.html
Labels: Review: Code +1, Review: QA +1

#10130 Copy update on /download
  templates/download/index.html
Labels: Review: Code +1

#10126 Update ceph copy doc
  templates/ceph/index.html
Labels: Review: Code +1

#10098 Add tests for /subscribe components
  static/js/src/advantage/subscribe/react/components/FormRow/FormRow.jsx
  static/js/src/advantage/subscribe/react/components/FormRow/FormRow.test.jsx
  static/js/src/advantage/subscribe/react/components/FormRow/index.ts
  static/js/src/advantage/subscribe/react/components/PaymentMethodSummary/PaymentMethodSummary.jsx
  static/js/src/advantage/subscribe/react/components/PaymentMethodSummary/PaymentMethodSummary.test.jsx
  static/js/src/advantage/subscribe/react/components/PaymentMethodSummary/index.ts
  static/js/src/advantage/subscribe/react/components/Summary/Summary.jsx
  static/js/src/advantage/subscribe/react/components/Summary/Summary.test.jsx
  static/js/src/advantage/subscribe/react/components/Summary/index.ts
  static/js/src/advantage/subscribe/react/utils/test/Mocks.js
Labels: Review: Code +1 (with changes), Commercial 🛒

#10105 Observability build
  templates/observability/base_observability.html
  templates/observability/contact-us.html
  templates/observability/index.html
  templates/observability/thank-you.html
  templates/shared/forms/interactive/observability-contact-us.html
  templates/shared/forms/interactive/osm-contact-us.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10139 Copy update on /azure
  templates/azure/index.html
Labels: Review: QA +1, Review: Code +1

#10138 Report issues with the marketo API into sentry
  webapp/views.py
Labels: Review: Code +1

#10140 Add link to /managed from /observability
  templates/observability/index.html
Labels: Review: QA +1, Review: Code +1

#10125 Add count to closed accordion
  build.js
  static/js/src/certified-search-results.js
  static/sass/_pattern_accordion.scss
  static/sass/_pattern_certification-results.scss
  templates/certified/search-results.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#10143 /observability: Streamline first subtitle
  templates/observability/index.html
Labels: Review: Code +1

#10146 Marketo API token refresh
  webapp/marketo.py
Labels: Review: Code needed

#10148 Copy update on /managed/kafka
  templates/managed/kafka.html
Labels: Review: QA +1, Review: Code +1

#10132 Copy update on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#10149 Encode email address when calling Open edX API
  webapp/cube/api.py
Labels: Review: Code +1

#10136 Display a pending purchase notification
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/usePendingPurchaseId.test.tsx
  static/js/src/advantage/react/hooks/usePendingPurchaseId.ts
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10142 Fix timezones in js tests
  package.json
Labels: Review: Code +1

#10084 Copy updates on /security
  templates/security/index.html
  templates/shared/contextual_footers/_security_esm.html
Labels: Review: QA +1, Review: Code +1

#10114 Add new certified category views
  redirects.yaml
  templates/certified/desktops-search-results.html
  templates/certified/desktops.html
  templates/certified/devices.html
  templates/certified/laptops.html
  templates/certified/servers.html
  templates/certified/socs.html
  webapp/app.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#10154 Fix watch script
  package.json
Labels: Review: QA +1, Review: Code +1

#10099 Desktop developers copy updates
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#10160 Copy update on /kubernetes/what-is-kubernetes
  templates/kubernetes/what-is-kubernetes.html
Labels: Review: QA +1, Review: Code +1

#10161 Update some more forms to work with the new endpoint
  templates/shared/_telco-contact-us.html
  templates/shared/contextual_footers/_openstack_install_newsletter.html
  templates/shared/forms/interactive/observability-contact-us.html
  templates/shared/forms/interactive/osm-contact-us.html
Labels: Review: Code +1

#10165 Updates yarn build to --production
  Dockerfile
  package.json
Labels: Review: QA +1, Review: Code +1

#10162 Add observability to navigation
  navigation.yaml
  templates/templates/footer.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Code +1

#10106 Update payment methods page
  static/js/src/advantage/contracts-api.js
  static/sass/styles.scss
  templates/account/index.html
  templates/account/invoices/index.html
  templates/account/payment-methods/index.html
  webapp/advantage/api.py
  webapp/advantage/schemas.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Commercial 🛒

#10153 Bugfix for arch and board selection & Added Ubuntu Core 20
  static/js/src/imageBuilder.js
  templates/core/build/index.html
Labels: Review: QA +1, Review: Code +1

#10135 Append the test backend flag to URLs
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/hooks/useLoadWindowData.ts
  static/js/src/advantage/react/hooks/useURLs.test.tsx
  static/js/src/advantage/react/hooks/useURLs.ts
  static/js/src/advantage/react/hooks/useUsingTestBackend.test.tsx
  static/js/src/advantage/react/hooks/useUsingTestBackend.ts
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10167 Add footer_item_small to make adding footer lists more explicit
  static/sass/_pattern_footer.scss
  templates/templates/_footer_item.html
  templates/templates/_footer_item_small.html
  templates/templates/footer.html
Labels: Review: QA +1, Review: Code +1

#10145 Engage language filter
  templates/engage/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#10164 16.04 ESM page discusses 'april 2021' in the future tense
  templates/16-04/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10184 Tidy up redundant css
  static/sass/_pattern_tco-calculator.scss
  static/sass/styles.scss
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
  templates/certified/component-details.html
  templates/certified/hardware-details.html
  templates/certified/index.html
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#10185 Copy update on /telco/osm/onboarding-network-functions
  templates/telco/osm/onboarding-network-functions.html
Labels: Review: QA +1, Review: Code +1

#10171 Limit number of filters by category
  templates/certified/desktops.html
  templates/certified/devices.html
  templates/certified/laptops.html
  templates/certified/servers.html
  templates/certified/socs.html
  webapp/certified/api.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#10163 Add renewal settings component.
  package.json
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/index.ts
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10173 Copy update on /managed
  templates/managed/index.html
Labels: Review: QA +1, Review: Code +1

#10155 Add tax id condition
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10170 Copy update on /kubernetes
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1

#10157 Fix renewal modal problems
  static/js/src/ua-payment-modal.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10176 Fix linkchecker issues
  templates/base_index.html
  templates/observability/index.html
Labels: Review: QA +1, Review: Code +1

#10186 Use new logo pattern on /security/livepatch
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10194 Add conversion api cookies to facebook on /legal/data-privacy
  templates/legal/data-privacy/index.html
Labels: Review: QA +1, Review: Code +1

#10199 Copy update on /kubernetes
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1

#10187 Copy update on /telco/osm
  templates/telco/osm/index.html
Labels: Review: QA +1, Review: Code +1

#10196 Fail the build when esbuild has an error
  build.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10201 Create /cube/faq page
  navigation.yaml
  templates/cube/faq.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10198 Select a contract when clicking on a card
  build.js
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/Content/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/react/utils/index.ts
  static/js/src/advantage/react/utils/makeInteractiveProps.test.tsx
  static/js/src/advantage/react/utils/makeInteractiveProps.ts
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#10202 Fix broken links across the kubernetes docs
  templates/kubernetes/docs/1.21/charm-kubernetes-master.md
  templates/kubernetes/docs/1.21/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.21/charm-tigera-secure-ee.md
  templates/kubernetes/docs/certs-and-trust.md
  templates/kubernetes/docs/charm-kubernetes-worker.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/cni-multus.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/ipv6.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/security.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/using-vault.md
Labels: Review: Code +1

#10206 Fix invoices page
  static/sass/styles.scss
  templates/account/invoices/index.html
  webapp/advantage/views.py
Labels: Review: QA +1, Review: Code +1

#10200 Fix results per page
  static/js/src/certified-search-results.js
  templates/certified/desktops.html
  templates/certified/devices.html
  templates/certified/laptops.html
  templates/certified/search-results.html
  templates/certified/servers.html
  templates/certified/socs.html
Labels: Review: QA +1, Review: Code +1

#10188 Adapt the content component for small screens
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10192 Engage pages tags filter
  templates/engage/_article-card.html
  templates/engage/index.html
  webapp/views.py
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#10190 Add cron job to check Ubuntu download mirrors
  .github/workflows/mirrors.yaml
Labels: Review: QA +1, Review: Code +1

#10211 Update the subscription list for small screens
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10208 Build /managed page
  navigation.yaml
  templates/managed/apps/contact-us.html
  templates/managed/apps/index.html
  templates/managed/apps/thank-you.html
  templates/managed/index.html
  templates/shared/forms/interactive/managed-services.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#10209 Backend new advantage init
  tests/test_advantage.py
  webapp/advantage/flaskparser.py
  webapp/advantage/models.py
  webapp/advantage/ua_contracts/api.py
  webapp/advantage/ua_contracts/builders.py
  webapp/advantage/ua_contracts/helpers.py
  webapp/advantage/ua_contracts/parsers.py
  webapp/advantage/ua_contracts/primitives.py
  webapp/advantage/views.py
  webapp/app.py
Labels: Review: Code needed, Commercial 🛒

#10214 Filter out CUBE contracts
  webapp/advantage/api.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10215 Fix price preview recalculation
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.jsx
  static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10217 #4369, updated kafka copy
  templates/managed/kafka.html
Labels: Review: QA +1, Review: Code +1

#10220 Fix guest user vat calculation
  static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.jsx
  static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx
Labels: Review: QA +1, Review: Code +1

#10222 Update /managed secondary nav
  navigation.yaml
  redirects.yaml
  templates/base_index.html
  templates/financial-services/index.html
  templates/managed/apps/cassandra.html
  templates/managed/apps/kafka.html
  templates/managed/contact-us.html
  templates/managed/thank-you.html
  templates/observability/index.html
  templates/shared/forms/interactive/managed-apps.html
  templates/shared/forms/interactive/managed-services.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#10221 Pass IP and user agent to the Marketo API during form submission
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#10216 build /cpu-compatibility page
  templates/cpu-compatibility/base_cpu-compatibility.html
  templates/cpu-compatibility/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Don't merge, Review: Code +1 (with changes)

#10247 Only display the edit or cancel modal.
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10248 Adapt the resize form for the mobile view.
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10197 Display personal contract details
  package.json
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/api/contracts.test.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx
  static/js/src/advantage/react/hooks/useLoadWindowData.ts
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/react/utils/formatDate.test.ts
  static/js/src/advantage/react/utils/formatDate.ts
  static/js/src/advantage/react/utils/index.ts
  static/js/src/advantage/tests/factories/api.ts
  static/sass/styles.scss
  templates/advantage/index.html
  tests/setupTests.js
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#10258 Xilinx copy update on /internet-of-things
  templates/internet-of-things/index.html
Labels: Review: QA +1, Review: Code +1

#10259 Add Xilinx to /embedded
  templates/embedded/index.html
Labels: Review: QA +1, Review: Code +1

#10261 Add Xilinx board to /robotics
  templates/robotics/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1
