Repository canonical/ubuntu.com, pull requests merged in 2021-01, with the labels that each got.

#8975 Fix sitemap CVE url
  webapp/security/views.py
Labels: Review: Code +1

#8977 Include the grecaptcha script in the newsletter sign up include
  templates/blog/newsletter-form.html
Labels: Review: Code +1, Review: QA +1

#8979 Include the grecaptcha script in the contact us form
  templates/shared/_cloud-contact-us-form.html
Labels: Review: Code +1, Review: QA +1

#8981 Remove Tech Preview from Openstack chart
  static/js/src/chart-data.js
Labels: Review: Code +1, Review: QA +1

#8984 Cube EDX API proxy settings
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#8988 Get user enrollments
  webapp/cube/views.py
Labels: Review: Code needed, Review: QA +1

#8951 Build MicroCerts page
  static/sass/_pattern_cube-progression.scss
  static/sass/_pattern_cube-table.scss
  static/sass/styles.scss
  templates/cube/microcerts.html
  webapp/cube/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8982 Add contact us for CUBE beta
  navigation.yaml
  templates/cube/contact-us.html
  templates/cube/index.html
  templates/cube/thank-you.html
  templates/shared/forms/interactive/cube-beta.html
Labels: Review: Code +1, Review: QA +1

#8991 Fix prepare button - broken link
  templates/cube/microcerts.html
Labels: Review: Code +1, Review: QA +1

#8994 Remove the engage takeover on the homepage
  webapp/app.py
Labels: Review: Code needed, Review: QA needed

#8998 Add missing commas
  static/js/src/chart-data.js
Labels: Review: Code needed

#8999 Revert "Remove the engage takeover on the homepage"
  webapp/app.py
Labels: Review: Code +1

#8985 Update sitemap.xml for static files
  static/files/sitemap.xml
Labels: Review: Code +1 (with changes), Review: QA +1

#8970 Create AI page
  navigation.yaml
  redirects.yaml
  templates/ai/_base_ai.html
  templates/ai/contact-us.html
  templates/ai/index.html
  templates/ai/install-kubeflow.html
  templates/ai/services.html
  templates/ai/shared/_learn-more.html
  templates/ai/thank-you.html
  templates/ai/what-is-kubeflow.html
  templates/kubeflow/base_kubeflow.html
  templates/kubeflow/features.html
  templates/kubeflow/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9007 Switch account name property to the right case
  static/js/src/advantage/contracts-api.js
Labels: Review: Code needed, Review: QA needed

#8978 Update the server download journey
  templates/download/server/choose.html
  templates/download/server/step1.html
  templates/download/server/step2.html
Labels: Review: Code +1, Review: Design +1, Review: PdM +1, Review: QA +1, Review: UX +1

#9011 Explain that attaching is unnecessary on 16.04/18.04
  templates/advantage/index.html
  templates/advantage/table/_attached-machines.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#8934 Core docs
  navigation.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9019 redirect /guide
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#9022 Update logos on /telco
  templates/telco/index.html
Labels: Review: Code +1, Review: QA +1

#9021 Update copy on /azure/pro
  templates/azure/pro.html
Labels: Review: Code +1, Review: QA +1

#9020 Update copy on /wsl
  templates/wsl/index.html
Labels: Review: Code +1, Review: QA +1

#9008 Add different views for microcerts page
  package.json
  static/js/src/contextual-menu.js
  static/sass/_pattern_cube-table.scss
  static/sass/_pattern_strip.scss
  templates/cube/index.html
  templates/cube/microcerts.html
  webapp/cube/views.py
  yarn.lock
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9025 Add /cloud to the footer
  navigation.yaml
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#9023 Fix copy and layout on /aws/pro
  templates/aws/pro.html
Labels: Review: Code +1, Review: QA +1

#9037 Fix JS error on renewal form blocking purchases
  static/js/src/ua-payment-modal.js
Labels: Review: Code +1, Review: QA +1

#9040 Simplify the advantage hero sections
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1

#9033 Replace CUBE certified badge
  templates/cube/index.html
  templates/cube/microcerts.html
  webapp/cube/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9046 Fix 12.04 esm date
  scripts/create-releases.py
  webapp/security/alembic/versions/0fe2f3a871da_update_release_12_04.py
Labels: Review: Code +1, Review: QA +1

#9024 Update financial services page
  templates/financial-services/index.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9052 Exclude x-frame-options header for templatefinder
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9012 Create LSN template
  static/js/src/scratch.js
  templates/internet-of-things/edgex.html
  templates/security/notices/lsn.html
  templates/security/notices/usn.html
  webapp/security/models.py
  webapp/security/views.py
Labels: Review: Code +1, Review: QA +1

#9036 Optimise CVE table cells
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-table.html
  templates/security/cve/cve.html
Labels: Review: Code +1, Review: QA +1

#9056 Make cve table pretty
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-table.html
Labels: Review: Code +1, Review: QA +1

#9047 Replace text describing Landscape
  templates/advantage/_ubuntu_version_select.html
  templates/pricing/devices.html
  templates/shared/pricing/_ua-for-infrastructure.html
  templates/telco/index.html
Labels: Review: Code +1, Review: QA +1

#9042 JS homepage takeover with endpoint to avoid taking down homepage
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/base_index.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#8983 Get list of assertions for user from Badgr
  HACKING.md
  konf/site.yaml
  templates/cube/microcerts.html
  webapp/cube/api.py
  webapp/cube/mappings/courses.yaml
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#9066 Protect /takeovers.json from Discouse errors (a bit)
  templates/takeovers/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9067 Enable CVE in /security subnav
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#9031 Build message for public clouds
  static/js/src/ua-product-selector.js
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1, UA shop 🛒

#9069 Added missing instruction to WSL page
  templates/wsl/index.html
Labels: Priority: High, Review: Code needed, Review: QA needed

#9070 fix appliance regex
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#9071 Index all CVEs, regardless of status
  templates/security/cve/cve.html
Labels: Review: Code needed

#9074 Fix index takeovers count
  templates/takeovers/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9064 Share CUBE badge and microcerts to social
  templates/cube/microcerts.html
Labels: Review: Code +1, Review: QA +1

#9076 Send a GA impression event when displaying a takeover
  static/js/src/navigation.js
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1

#9078 K8sDocs: update store link for coredns
  templates/kubernetes/docs/cdk-addons.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#9044 /advantage copy doc link update
  templates/advantage/index.html
  templates/advantage/subscribe/index.html
Labels: Review: QA +1

#9059 Update organisation field
  templates/advantage/_stripe-modal.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#9058 Disable entire payment form whilst submitting
  static/js/src/ua-payment-modal.js
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#9077 Fix squashed passed badge from badgr issue
  templates/cube/microcerts.html
Labels: Review: Code +1, Review: QA +1

#9085 Fix dependency conflicts
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#9055 Focus quantity field when product is selected
  static/js/src/ua-product-selector.js
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#9015 Update subscription call to use filters
  webapp/advantage.py
Labels: Review: Code +1 (with changes), Review: QA +1

#9068 Add pricing and what's including headings to all pricing tables and Landscape row on /advantage
  templates/advantage/_table.html
  templates/pricing/infra.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9094 Fix badge alignment on mobile view
  static/sass/_pattern_cube-table.scss
  templates/cube/microcerts.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9096 Fix CVE broken links
  templates/security/cve/cve.html
  webapp/security/models.py
Labels: Review: Code +1, Review: QA +1

#9087 Copy update on /security/certifications
  templates/security/certifications.html
Labels: Review: Code +1, Review: QA +1

#9099 Copy update for /security/oval
  templates/security/oval.html
Labels: Review: Code +1, Review: QA +1

#9098 Ammend navigation items for core docs
  navigation.yaml
Labels: Review: Code +1, Review: QA +1

#9104 Correct Livepatch instructions for 16.04/18.04
  templates/advantage/shared/_livepatch-info.html
Labels: Review: Code +1, Review: QA +1

#9084 K8sdocs: add warning about juju/lxd bug
  templates/kubernetes/docs/1.19/upgrading.md
  templates/kubernetes/docs/1.20/upgrading.md
  templates/kubernetes/docs/troubleshooting.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#9100 Add not-in-ubuntu details
  templates/security/cve/cve.html
Labels: Review: Code +1, Review: QA +1

#9120 UA: make form inputs readonly when submitting customer info
  static/js/src/ua-payment-modal.js
Labels: Review: Code +1, Review: QA +1

#9121 K8sdocs updates for etcd issue
  templates/kubernetes/docs/1.18/upgrading.md
  templates/kubernetes/docs/1.19/upgrading.md
  templates/kubernetes/docs/1.20/upgrading.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
Labels: Docs 📚, Review: Code +1

#9110 Build new /stories page for core
  navigation.yaml
  static/sass/_pattern_strip.scss
  templates/core/stories.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9112 Build new features page for /core
  navigation.yaml
  templates/core/features/index.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9079 Clarifies description of community support sources
  templates/support/community-support.html
Labels: Review: Code +1, Review: QA +1

#9102 Add CUBE Beta privacy notice
  templates/legal/data-privacy/cube-beta.md
  templates/legal/data-privacy/index.html
Labels: Review: Code +1, Review: QA +1

#9119 Build new /core/features/secure-boot page
  navigation.yaml
  templates/core/features/secure-boot.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#9127 Build /core/features/full-disk-encryption page
  navigation.yaml
  templates/core/features/full-disk-encryption.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9130 Get attempts for each course from EDX
  .env
  konf/site.yaml
  templates/cube/microcerts.html
  webapp/cube/api.py
  webapp/cube/content/cube.yaml
  webapp/cube/mappings/courses.yaml
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1
