Repository canonical/ubuntu.com, pull requests merged in 2021-03, with the labels that each got.

#9310 Update payment summary and remove cart functionality
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/set-modal-info.js
  static/js/src/advantage/tests/set-modal-info.test.js
  static/js/src/ua-payment-modal.js
  static/js/src/ua-product-selector.js
  static/sass/_pattern_shop-cart.scss
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9287 Upgrade to canonicalwebteam.search v1 to use default session
  Dockerfile
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9332 Copy update - /advantage table
  templates/advantage/_table.html
Labels: Review: Code +1, Review: QA +1

#9336 Make empty POST show step 1, instead of 500
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#9223 Ensure background submit works for marketo modals
  static/js/src/bg-form-submit.js
  static/js/src/core.js
  static/js/src/dynamic-forms.js
  static/js/src/form-access.js
  static/js/src/form-validation.js
  static/js/src/utils/cookies.js
  static/js/src/utils/reverseString.js
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#9333 Add auto renewal endpoint
  webapp/advantage.py
  webapp/views.py
Labels: Review: Code +1 (with changes)

#9335 Bump discourse-docs to v3
  requirements.txt
  templates/templates/docs/discourse.html
  tests/cassettes/TestRoutes.test_ceph_docs.yaml
  tests/cassettes/TestRoutes.test_server_docs.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9343 Update discourse topics to original topics
  tests/cassettes/TestRoutes.test_ceph_docs.yaml
  tests/cassettes/TestRoutes.test_server_docs.yaml
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#9334 Update ROS contact-us modal
  templates/shared/forms/interactive/robotics_ros.html
Labels: Review: Code +1, Review: QA +1

#9344 Update /financial-services page design
  templates/financial-services/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9348 Add DFI logo to /core
  templates/core/index.html
Labels: Review: Code +1, Review: QA +1

#9351 Adapt tutorials search for new module version
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#9080 Test smooth scrolling
  static/sass/styles.scss
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#9361 Correct links to CUBE prepare material
  templates/cube/microcerts.html
  webapp/cube/views.py
Labels: Review: Code +1, Review: QA +1

#9365 Add new whitepaper section
  templates/core/index.html
Labels: Review: Code +1, Review: QA +1

#9350 Copy update - Ubuntu components table /azure/fips
  templates/azure/fips.html
Labels: Review: Code +1, Review: QA +1

#9360 Update LSN template
  templates/security/notices/lsn.html
  templates/security/notices/usn.html
  webapp/security/views.py
Labels: Review: Code +1, Review: QA +1

#9341 CUBE: refactor code and add meta data
  navigation.yaml
  static/js/src/contextual-menu.js
  static/sass/_pattern_cube-progression.scss
  templates/cube/index.html
  templates/cube/microcerts.html
Labels: Review: Code +1 (with changes), Review: QA +1

#9356 Optional primary cta and syntax fixes
  templates/engage/base.html
Labels: Review: Code +1, Review: QA +1

#9249 Build warning payment issue
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code needed, Review: Design +1, Review: QA needed, Review: UX +1

#9315 Build subscription management options into the table
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/manage-subscription.js
  static/sass/styles.scss
  templates/advantage/index.html
  templates/advantage/shared/_certifications-info.html
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: UX +1

#9313 Add contract details
  templates/advantage/index-no-login.html
  templates/advantage/index.html
  webapp/views.py
Labels: Review: Code needed

#9372 Copy updates for /support
  templates/support/index.html
Labels: Review: Code +1, Review: QA +1

#9374 add 1.20 release to k8s chart
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: Code +1, Review: QA +1

#9357 Refactor advantage
  requirements.txt
  tests/test_advantage.py
  tests/test_routes.py
  tests/test_views.py
  webapp/advantage.py
  webapp/advantage/api.py
  webapp/advantage/parser.py
  webapp/advantage/schemas.py
  webapp/advantage/views.py
  webapp/app.py
  webapp/decorators.py
  webapp/views.py
Labels: Review: Code needed

#9383 Fix typo on NextCloud navigaiton
  navigation.yaml
Labels: Review: Code +1

#9384 Replace /gov section and update gov page
  redirects.yaml
  templates/gov/base_gov.html
  templates/gov/contact-us.html
  templates/gov/form.html
  templates/gov/index.html
  templates/gov/thank-you.html
Labels: Review: Code +1 (with changes), Review: QA +1

#9389 Change cancel contract
  webapp/advantage/schemas.py
  webapp/advantage/views.py
Labels: Review: Code +1

#9391 Fix security endpoints bugs
  webapp/security/schemas.py
  webapp/security/views.py
Labels: Review: Code +1

#9382 CUBE: Authorize specific users
  konf/site.yaml
  webapp/cube/views.py
Labels: Review: Code +1

#9393 Add contract product listing
  webapp/advantage/views.py
Labels: Review: Code +1

#9395 Change auto renewal parameter location
  webapp/advantage/views.py
Labels: Review: Code +1

#9399 Fix auto renewal status read
  webapp/advantage/views.py
Labels: Review: Code +1

#9398 GCP pages
  navigation.yaml
  templates/gcp/base_gcp.html
  templates/gcp/contact-us.html
  templates/gcp/index.html
  templates/gcp/pro.html
  templates/gcp/thank-you.html
  templates/shared/forms/interactive/gcp.html
Labels: Review: Code +1 (with changes), Review: Design +1, Review: Marketing needed, Review: QA +1

#9408 Adjust monthly info
  webapp/advantage/views.py
Labels: Review: Code +1, Review: Code needed

#9403 Add new 16-04 pages
  navigation.yaml
  static/js/src/chart.js
  static/js/src/release-chart.js
  static/sass/_pattern_chart.scss
  templates/16-04/base_16-04.html
  templates/16-04/gcp.html
  templates/16-04/index.html
  templates/kernel/lifecycle.html
  templates/shared/_kernel-support-schedule.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9376 Rebuild openstack/features page
  templates/openstack/features.html
  templates/shared/contextual_footers/_openstack_delivery.html
  templates/shared/contextual_footers/_openstack_further_reading.html
Labels: Review: Code needed, Review: Design +1, Review: QA needed

#9405 Add some redirects to '/cloud'
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#9404 Copy updates to '/gov'
  templates/gov/index.html
Labels: Review: Code +1, Review: QA +1

#9413 Add contracts total
  webapp/advantage/views.py
Labels: Review: Code +1

#9369 Add advantage beta form
  templates/advantage/base_advantage.html
  templates/advantage/subscribe/index.html
  templates/shared/forms/interactive/advantage-beta.html
Labels: Review: Code +1, Review: Design +1, Review: PdM +1, Review: QA +1, Review: UX +1

#9418 Remove /16-04/gcp page
  navigation.yaml
  templates/16-04/gcp.html
  templates/templates/footer.html
Labels: Review: Code +1, Review: QA +1

#9355 Add tests for tutorials search
  .github/workflows/pr.yaml
  tests/cassettes/TestRoutes.test_tutorials.yaml
  tests/cassettes/TestRoutes.test_tutorials_homepage.yaml
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  tests/test_routes.py
Labels: Review: Code +1, Review: QA +1

#9407 [CUBE] Update thank you and contact us
  templates/cube/contact-us.html
  templates/cube/thank-you.html
  templates/shared/forms/interactive/cube-beta.html
Labels: Review: Code +1, Review: QA +1

#9373 Dropdown visual improvements
  static/sass/styles.scss
  templates/advantage/index.html
  templates/advantage/shared/_certifications-info.html
  templates/advantage/shared/_esm-info.html
  templates/advantage/shared/_livepatch-info.html
  templates/advantage/table/_attached-machines.html
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9428 Setup project structure for /certification
  redirects.yaml
  templates/certification/base_certification.html
  templates/certification/index.html
  tests/test_routes.py
  webapp/app.py
  webapp/certification/views.py
Labels: Review: Code +1, Review: QA +1

#9415 Restyle site search to match the design
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9430 K8s-1.20ck1-update
  templates/kubernetes/docs/1.20/charm-aws-iam.md
  templates/kubernetes/docs/1.20/charm-aws-integrator.md
  templates/kubernetes/docs/1.20/charm-azure-integrator.md
  templates/kubernetes/docs/1.20/charm-calico.md
  templates/kubernetes/docs/1.20/charm-canal.md
  templates/kubernetes/docs/1.20/charm-containerd.md
  templates/kubernetes/docs/1.20/charm-docker-registry.md
  templates/kubernetes/docs/1.20/charm-docker.md
  templates/kubernetes/docs/1.20/charm-easyrsa.md
  templates/kubernetes/docs/1.20/charm-etcd.md
  templates/kubernetes/docs/1.20/charm-flannel.md
  templates/kubernetes/docs/1.20/charm-gcp-integrator.md
  templates/kubernetes/docs/1.20/charm-kata.md
  templates/kubernetes/docs/1.20/charm-keepalived.md
  templates/kubernetes/docs/1.20/charm-kubeapi-load-balancer.md
  templates/kubernetes/docs/1.20/charm-kubernetes-master.md
  templates/kubernetes/docs/1.20/charm-kubernetes-worker.md
  templates/kubernetes/docs/1.20/charm-openstack-integrator.md
  templates/kubernetes/docs/1.20/charm-tigera-secure-ee.md
  templates/kubernetes/docs/1.20/charm-vsphere-integrator.md
  templates/kubernetes/docs/1.20/components.md
  templates/kubernetes/docs/1.20/release-notes.md
Labels: Review: Code +1 (with changes), Review: QA +1

#9439 9433: Enterprise nav copy changes
  static/sass/_pattern_lists.scss
  templates/templates/navigation-enterprise-h.html
Labels: Review: Code +1, Review: QA +1

#9435 9318: Fix form fields overlapping
  static/sass/_pattern_contact-modal.scss
  templates/shared/forms/interactive/bootstack.html
  templates/shared/forms/interactive/support-openstack.html
Labels: Review: Code +1, Review: QA +1

#9438 Remove logos section and update number
  templates/gcp/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9440 Copy the beta programme for Ubuntu Pro form to advantage page
  templates/advantage/index.html
Labels: Review: Code +1, Review: QA +1

#9441 Update the agreement file downloads to use assets
  templates/legal/contributors/agreement.html
Labels: Review: Code +1, Review: QA +1

#9401 Reorder the microcerts table
  templates/cube/microcerts.html
  webapp/cube/content/cube-qa.yaml
  webapp/cube/content/cube.yaml
Labels: Review: Code +1, Review: QA +1

#9421 Fix community links in mega menu
  templates/community/governance.html
  templates/community/index.html
  templates/legal/contributors/thank-you.html
  templates/legal/websites.html
  templates/templates/navigation-community-h.html
Labels: Review: Code +1, Review: QA +1

#9394 Sync front and back ends
  static/js/src/advantage/auto-renewal.js
  static/js/src/advantage/contracts-api.js
  static/js/src/advantage/manage-subscription.js
  templates/advantage/index.html
  templates/advantage/table/_manage-monthly.html
  templates/advantage/table/_manage-yearly.html
Labels: Review: Code +1, Review: QA +1

#9379 Replace discourse with launchpad answers for Helping hands
  templates/shared/contextual_footers/_download_helping_hands.html
Labels: Review: Code +1, Review: QA +1

#9377 Fix Issue #9306 - UC20 only work with UEFI.
  templates/download/kvm.html
Labels: Review: Code +1, Review: QA +1

#9443 Fix tax_id parameter
  webapp/advantage/schemas.py
Labels: Review: Code +1

#9420 Add "can_be_trialled" prop to listings
  webapp/advantage/views.py
Labels: Review: Code +1

#9455 Update the Modern Slavery legal pages
  templates/legal/index.html
  templates/legal/modern-slavery-statement/_base_markdown.html
  templates/legal/modern-slavery-statement/index.md
Labels: Review: Code +1, Review: QA +1

#9449 9447: Add new datasheet link Ubuntu Pro Azure
  templates/azure/pro.html
Labels: Review: Code +1

#9470 Add nvidia redirect to the engage page
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#9469 Add new financial modal contact us
  templates/financial-services/_base_financial-services.html
  templates/shared/forms/interactive/financial.html
Labels: Review: Code +1, Review: QA +1

#9450 Extend the search when activated
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#9471 #9444: 16.04 page copy updates
  templates/16-04/index.html
Labels: Review: Code +1, Review: QA +1

#9473 Fix Iot var swap and add URLs for search
  webapp/certification/views.py
Labels: Review: Code needed, Review: QA +1

#9478 Copy update to UA service description
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: Code +1 (with changes), Review: QA +1

#9456 Fix the LXD set password command
  templates/appliance/lxd/_next-steps.html
Labels: Review: Code +1, Review: QA +1

#9482 Canonical url to juju.is for article with tag 4059 (juju.is)
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#9458 Redesign wizard
  package.json
  static/js/src/advantage/subscribe/listeners/form-event-listeners.js
  static/js/src/advantage/subscribe/listeners/ui-event-listeners.js
  static/js/src/advantage/subscribe/product-selector.js
  static/js/src/advantage/subscribe/reducers/form-reducer.js
  static/js/src/advantage/subscribe/reducers/ui-reducer.js
  static/js/src/advantage/subscribe/renderers/UI-renderer.js
  static/js/src/advantage/subscribe/renderers/form-renderer.js
  static/js/src/advantage/subscribe/renderers/main-renderer.js
  static/js/src/advantage/subscribe/renderers/version-details.js
  static/js/src/ua-product-selector.js
  static/js/src/utils/state.js
  static/js/src/utils/tests/state.test.js
  static/sass/_pattern_card.scss
  static/sass/_pattern_shop-cart.scss
  static/sass/styles.scss
  templates/advantage/_ubuntu_version_select.html
  templates/advantage/subscribe/form/_feature_coverage.html
  templates/advantage/subscribe/form/_tech_support.html
  templates/advantage/subscribe/form/_type_select.html
  templates/advantage/subscribe/form/_ubuntu_version_select.html
  templates/advantage/subscribe/index.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#9425 Update caching rules with flask-base v0.8.0
  requirements.txt
  tests/test_cube.py
  webapp/app.py
  webapp/decorators.py
Labels: Review: Code +1, Review: QA +1

#9476 fixes #3930
  templates/advantage/index.html
  templates/advantage/subscribe/index.html
Labels: Review: Code +1, Review: QA +1

#9490 Add actions to check docs links
  .github/workflows/ceph-docs-links.yaml
  .github/workflows/core-docs-links.yaml
  .github/workflows/kubernetes-docs-links.yaml
  .github/workflows/server-docs-links.yaml
Labels: Review: Code +1, Review: QA +1

#9492 Add GA events
  static/js/src/advantage/auto-renewal.js
  static/js/src/advantage/manage-subscription.js
  templates/advantage/index.html
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#9475 Certification search
  templates/certification/search-results.html
  tests/test_certification.py
  webapp/certification/api.py
  webapp/certification/helpers.py
  webapp/certification/views.py
Labels: Review: Code +1, Review: QA +1
