Repository canonical/ubuntu.com, pull requests merged in 2022-03, with the labels that each got.

#11293 Update links on /telco
  templates/telco/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11279 Fix bug links
  templates/security/cve/cve.html
Labels: Review: QA +1, Review: Code +1

#11302 change p-icon--contextual-menu to p-icon--chevron-down
  static/sass/_layout-tutorial.scss
  static/sass/styles.scss
  templates/advantage/table/_contract-name.html
  templates/security/cve/_pagination.html
  templates/shared/_pagination.html
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Code +1

#11303 Use UK spelling of "optimise" and its derivatives
  templates/ai/what-is-kubeflow.html
  templates/aws/fips.html
  templates/aws/index.html
  templates/azure/fips.html
  templates/azure/index.html
  templates/download/iot/intel-iotg.html
  templates/gcp/index.html
  templates/legal/data-privacy/2013-03-25/index.html
  templates/legal/data-privacy/2016-02-08/index.html
  templates/legal/data-privacy/index.html
  templates/managed/apps/cassandra.html
  templates/security/fips.html
  templates/support/community-support.html
  templates/telco/openran.html
Labels: Review: QA +1, Review: Code +1

#11298 Update copy on /cube
  templates/cube/index.html
Labels: Review: QA +1, Review: Code needed, Commercial 🛒

#11309 Fix categories for vendor pages
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#11306 Update p-navigation styles to vanilla-3.0
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/_menu_section.html
Labels: Review: QA +1, Review: Code +1

#11310 Update notifications structure to new pattern - part 1
  static/js/src/advantage/manage-subscription.js
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx
  static/js/src/ua-payment-methods.js
  templates/account/payment-methods/index.html
  templates/advantage/_stripe-modal.html
  templates/advantage/table/_free-trial.html
  templates/appliance/lxd/_next-steps.html
  templates/appliance/mosquitto/_next-steps.html
  templates/appliance/shared/_steps_pi_prep-sd-card.html
  templates/appliance/shared/_steps_setup-kvm.html
  templates/cube/study/index.md
  templates/download/iot/installation-media.html
  templates/kubernetes/docs/1.17/release-notes.md
  templates/kubernetes/docs/1.18/release-notes.md
  templates/kubernetes/docs/1.19/release-notes.md
  templates/kubernetes/docs/audit-logging.md
  templates/kubernetes/docs/auth.md
  templates/kubernetes/docs/aws-iam-auth.md
  templates/kubernetes/docs/aws-integration.md
  templates/kubernetes/docs/azure-integration.md
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/ceph.md
  templates/kubernetes/docs/certs-and-trust.md
  templates/kubernetes/docs/cis-compliance.md
  templates/kubernetes/docs/cni-canal.md
  templates/kubernetes/docs/cni-flannel.md
  templates/kubernetes/docs/cni-multus.md
  templates/kubernetes/docs/cni-overview.md
  templates/kubernetes/docs/container-runtime.md
  templates/kubernetes/docs/custom-loadbalancer.md
  templates/kubernetes/docs/decommissioning.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/equinix.md
  templates/kubernetes/docs/get-in-touch.md
  templates/kubernetes/docs/gpu-workers.md
  templates/kubernetes/docs/hacluster.md
  templates/kubernetes/docs/high-availability.md
  templates/kubernetes/docs/kata.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/multiple-networks.md
  templates/kubernetes/docs/overview.md
  templates/kubernetes/docs/proxies.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/snap-coherence.md
  templates/kubernetes/docs/snap-refresh.md
  templates/kubernetes/docs/troubleshooting.md
  templates/openstack/install.html
  templates/openstack/pricing-calculator.html
  templates/resources/index.html
  templates/shared/_partner-logos.html
  templates/templates/base.html
  templates/templates/docs/shared/_docs.html
  templates/training/index.html
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Code +1

#11294 Match codename with release number (mixup)
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#11318 Fix active machines count
  webapp/shop/api/ua_contracts/advantage_mapper.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11314 Update notification pattern for vanilla 3.0 in k8s docs
  templates/kubernetes/docs/1.16/upgrading.md
  templates/kubernetes/docs/1.17/upgrading.md
  templates/kubernetes/docs/1.18/charm-aws-integrator.md
  templates/kubernetes/docs/1.18/upgrading.md
  templates/kubernetes/docs/1.19/charm-aws-integrator.md
  templates/kubernetes/docs/1.19/charm-easyrsa.md
  templates/kubernetes/docs/1.19/upgrading.md
  templates/kubernetes/docs/1.20/charm-aws-integrator.md
  templates/kubernetes/docs/1.20/charm-easyrsa.md
  templates/kubernetes/docs/1.20/upgrading.md
  templates/kubernetes/docs/1.21/charm-aws-integrator.md
  templates/kubernetes/docs/1.21/charm-easyrsa.md
  templates/kubernetes/docs/1.21/upgrading.md
  templates/kubernetes/docs/1.22/charm-aws-integrator.md
  templates/kubernetes/docs/1.22/charm-easyrsa.md
  templates/kubernetes/docs/1.22/upgrading.md
  templates/kubernetes/docs/1.23/charm-aws-integrator.md
  templates/kubernetes/docs/1.23/charm-easyrsa.md
  templates/kubernetes/docs/1.23/upgrading.md
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/charm-aws-integrator.md
  templates/kubernetes/docs/charm-easyrsa.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/cni-sriov.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/gcp-integration.md
  templates/kubernetes/docs/ingress.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/install-offline.md
  templates/kubernetes/docs/ipv6.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/openstack-integration.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/packages.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/tigera-secure-ee.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/using-vault.md
  templates/kubernetes/docs/validation.md
  templates/kubernetes/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1

#11319 Update accordion to vanilla-3.0 patterns
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#11326 Update kernel name in release cycle chart
  static/js/src/chart-data.js
Labels: Review: QA +1, Review: Code +1

#11331 Correct spelling of Memcached on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#11334 Support CVEs without publish date
  templates/security/cve/cve.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11336 Add subsystem id to hardware details
  templates/certified/hardware-details.html
  templates/certified/model-details.html
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#11332 Allow registration for embedded brighttalk videos
  templates/security/certifications.html
  templates/security/disa-stig.html
  templates/security/fips.html
  templates/security/index.html
Labels: Review: QA +1, Review: Code +1

#11305 Fix security error pages
  templates/404.html
  templates/security-error-500.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#11340 Update micro-clouds image on /telco
  templates/telco/index.html
Labels: Review: QA +1, Review: Code +1

#11335 Expand columns for engage pages without forms
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1

#11337 Fix spacing issue in chart.js
  static/js/src/chart-data.js
  static/js/src/chart.js
  templates/shared/_kernel-support-schedule.html
Labels: Review: QA +1, Review: Code +1

#11338 Redirects calls to /index to the same url minus /index
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#11273 Move API response conversion to mapper
  tests/shop/advantage/test_advantage_mapper.py
  tests/shop/advantage/test_api.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11343 Improve handling of API errors
  requirements.txt
  templates/404.html
  webapp/app.py
  webapp/security/api.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#11296 k8s charmhub updates
  templates/kubernetes/docs/1.16/charm-azure-integrator.md
  templates/kubernetes/docs/1.17/charm-azure-integrator.md
  templates/kubernetes/docs/1.18/charm-azure-integrator.md
  templates/kubernetes/docs/1.19/charm-azure-integrator.md
  templates/kubernetes/docs/1.19/charm-openstack-integrator.md
  templates/kubernetes/docs/1.20/charm-azure-integrator.md
  templates/kubernetes/docs/1.20/charm-openstack-integrator.md
  templates/kubernetes/docs/1.21/charm-azure-integrator.md
  templates/kubernetes/docs/1.21/charm-openstack-integrator.md
  templates/kubernetes/docs/1.22/charm-azure-integrator.md
  templates/kubernetes/docs/1.22/charm-openstack-integrator.md
  templates/kubernetes/docs/1.23/charm-azure-integrator.md
  templates/kubernetes/docs/1.23/charm-openstack-integrator.md
  templates/kubernetes/docs/aws-iam-auth.md
  templates/kubernetes/docs/aws-integration.md
  templates/kubernetes/docs/azure-integration.md
  templates/kubernetes/docs/charm-azure-integrator.md
  templates/kubernetes/docs/charm-containerd.md
  templates/kubernetes/docs/charm-openstack-integrator.md
  templates/kubernetes/docs/equinix.md
  templates/kubernetes/docs/gcp-integration.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/ipv6.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/openstack-integration.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/using-vault.md
  templates/kubernetes/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#11341 Update wsl page
  templates/wsl/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11348 Update 'Ubuntu Advantage Plans' table on /advantage
  static/sass/styles.scss
  templates/advantage/_table.html
  templates/advantage/index-no-login.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11347 Update /ai as per copydoc
  templates/ai/index.html
Labels: Review: QA +1, Review: Code +1

#11346 Render all wsl tutorials from discourse on `/wsl`
  templates/wsl/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11354 Advantage: only update customer info if the payment form has changed
  static/js/src/PurchaseModal/components/PaymentMethodForm.tsx
Labels: Review: QA +1, Review: Code +1

#11352 Update /openstack/features as per copydoc
  templates/openstack/features.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11349 Updates copy on '/secure-boot'
  templates/core/features/secure-boot.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11350 Update extendable containers illustration
  templates/openstack/index.html
  templates/telco/vnf.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11280 Create purchase objects
  templates/account/invoices/index.html
  tests/shop/advantage/fixtures/purchase-3ds.json
  tests/shop/advantage/fixtures/purchase-failed.json
  tests/shop/advantage/test_advantage_mapper.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/schema.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11355 Update /what-is-kubeflow as per copydoc
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11362 Update p-inline-image to p-logo-section on /what-is-kubeflow
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1

#11363 Updates inline-images to logo-section
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1

#11358 Remove data-testid on `/wsl`
  templates/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#11364 Remove repeating sections
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1

#11365 k8s: fix store 404s
  templates/kubernetes/docs/1.16/release-notes.md
  templates/kubernetes/docs/1.17/release-notes.md
  templates/kubernetes/docs/1.18/release-notes.md
  templates/kubernetes/docs/1.19/release-notes.md
  templates/kubernetes/docs/1.20/release-notes.md
  templates/kubernetes/docs/1.21/release-notes.md
  templates/kubernetes/docs/1.22/release-notes.md
  templates/kubernetes/docs/1.23/release-notes.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: Code +1

#11372 Change instances of 'e-book' to 'eBook'
  templates/azure/ebook/index.html
  templates/azure/fips.html
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1

#11373 Update '/azure/private-offer' buttons lengths
  templates/azure/private-offer.html
Labels: Review: QA +1, Review: Code +1

#11375 Add unlisted engage pages
  redirects.yaml
  templates/engage/base_engage_unlisted.html
  templates/engage/unlisted/custom-ubuntu-pro-image-on-azure.html
  templates/engage/unlisted/shell-onboarding.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11382 Update link on`/containers/what-are-containers`
  templates/containers/what-are-containers.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11327 Add dismissible notification
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/hooks/useURLs.ts
  static/js/src/advantage/users/app.tsx
  static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#11384 Ignore amd link from blog linkchecker
  .github/workflows/blog-links.yaml
Labels: Review: Code +1

#11381 Reduce width of success notification banner
  static/sass/styles.scss
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#11386 Fix switches on /advantage
  static/js/src/advantage/react/components/FeatureSwitch/FeatureSwitch.tsx
Labels: Review: QA +1, Review: Code +1

#11351 Update /openstack page as per copydoc
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#11368 Update /smart-displays page
  navigation.yaml
  redirects.yaml
  templates/core/index.html
  templates/core/stories.html
  templates/industrial/index.html
  templates/internet-of-things/contact-us.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/index.html
  templates/internet-of-things/smart-city.html
  templates/internet-of-things/smart-displays.html
  templates/templates/navigation-developer-h.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM needed

#11380 Remove releases from cve view
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#11388 Update '/wsl' as per copydoc
  templates/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#11390 Disable cypress test on `/wsl` temporarily
  tests/cypress/utils.js
Labels: Review: Code +1

#11385 Remove vendor name from model name in the table on `/certified`
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
Labels: Review: QA +1, Review: Code +1

#11383 Remove marketing ping when cypress fails
  .github/workflows/cypress-main.yaml
Labels: Review: Code +1

#11369 Update notice views to consume security api
  templates/security/notices/lsn.html
  templates/security/notices/usn.html
  webapp/security/api.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11376 Change subscription to token
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11394 Ensure Marketo forms do not send duplicated utm fields
  templates/engage/shared/_de_engage_form.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_engage_form.html
  templates/engage/shared/_it_engage_form.html
  templates/engage/shared/_pt_engage_form.html
  templates/engage/shared/_ru_engage_form.html
Labels: Review: QA +1, Review: Code +1

#11353 Update /what-is-kubernetes as per copydoc
  templates/kubernetes/what-is-kubernetes.html
  templates/shared/contextual_footers/_cloud_lxd.html
  templates/shared/contextual_footers/_containers_juju.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11391 Update old intel logo across site
  templates/gov/index.html
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#11377 UA selector: Set billing period to monthly when selecting apps.
  static/js/src/advantage/subscribe/reducers/form-reducer.js
  templates/advantage/subscribe/form/_feature_coverage.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11399 Add a regex match on USN routes.
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#11401 Update typo on /aws
  templates/aws/index.html
Labels: Review: QA +1, Review: Code +1

#11402 Remove outdated redirect to /digital-signage
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#11396 Copy update on `/download/iot/intel-iotg`
  templates/download/iot/intel-iotg.html
  templates/shared/forms/interactive/internet-of-things.html
  tests/cypress/forms/forms_spec.js
  tests/cypress/utils.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#11378 Build `/lxd` page
  navigation.yaml
  redirects.yaml
  templates/lxd/base_lxd.html
  templates/lxd/index.html
  templates/shared/forms/interactive/lxd.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11407 Fix typo on /lxd
  templates/lxd/index.html
Labels: Review: QA +1, Review: Code +1

#11367 Add new purchase endpoint and get purchase v2
  tests/shop/advantage/test_advantage_mapper.py
  tests/shop/advantage/test_api.py
  tests/shop/advantage/test_parsers.py
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/primitives.py
  webapp/shop/api/ua_contracts/schema.py
  webapp/shop/decorators.py
  webapp/shop/schemas.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11411 Drive-by to make line of copy be more accurate
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
Labels: Review: QA +1, Review: UX +1

#11409 Remove iot pages from cypress test
  tests/cypress/forms/forms_spec.js
  tests/cypress/utils.js
Labels: Review: QA +1, Review: Code +1

#11418 Update /esm
  templates/security/esm.html
Labels: Review: QA +1, Review: Code +1

#11406 Update UASD page
  templates/legal/ubuntu-advantage-service-description/_toc.html
  templates/legal/ubuntu-advantage-service-description/index.md
Labels: Review: QA +1, Review: Code +1

#11419 Update cypress test on /pricing/devices
  tests/cypress/utils.js
Labels: Review: QA +1, Review: Code +1

#11417 Update Get in touch button url
  navigation.yaml
  templates/lxd/index.html
Labels: Review: QA +1, Review: Code +1

#11414 Reintroduce beta notification
  templates/advantage/index-no-login.html
  templates/advantage/index.html
  templates/shared/forms/interactive/advantage-beta.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11404 Update README.md
  README.md
Labels: Review: QA +1

#11424 Update to site restricted custom search
  requirements.txt
  tests/cassettes/TestRoutes.test_ceph_docs.yaml
  tests/cassettes/TestRoutes.test_security_certs_docs.yaml
  tests/cassettes/TestRoutes.test_server_docs.yaml
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  webapp/app.py
  webapp/views.py
Labels: Review: QA needed, Review: Code needed

#11431 Update lxd link
  redirects.yaml
  templates/containers/index.html
  templates/containers/what-are-containers.html
  templates/embedded/index.html
  templates/openstack/compare.html
  templates/server/index.html
  templates/telco/index.html
  templates/templates/navigation-developer-h.html
Labels: Review: QA +1, Review: Code +1
