Repository canonical/ubuntu.com, pull requests merged in 2022-06, with the labels that each got.

#11537 Update copy for certifications page
  navigation.yaml
  redirects.yaml
  templates/credentialing/base_cube.html
  templates/credentialing/contact-us.html
  templates/credentialing/faq.html
  templates/credentialing/index.html
  templates/credentialing/microcerts.html
  templates/credentialing/thank-you.html
  templates/cube/index.html
  templates/cube/study/_markdown.html
  templates/cube/study/_navigation.md
  templates/cube/study/admin-tasks/part-1.md
  templates/cube/study/admin-tasks/part-2.md
  templates/cube/study/admin-tasks/part-3.md
  templates/cube/study/admin-tasks/part-4.md
  templates/cube/study/bash/part-1.md
  templates/cube/study/command-line-tools/part-1.md
  templates/cube/study/devices/part-1.md
  templates/cube/study/devices/part-2.md
  templates/cube/study/devices/part-3.md
  templates/cube/study/filesystems/part-1.md
  templates/cube/study/filesystems/part-2.md
  templates/cube/study/filesystems/part-3.md
  templates/cube/study/index.md
  templates/cube/study/juju/part-1.md
  templates/cube/study/juju/part-2.md
  templates/cube/study/juju/part-3.md
  templates/cube/study/kernel/part-1.md
  templates/cube/study/kernel/part-2.md
  templates/cube/study/kernel/part-3.md
  templates/cube/study/kernel/part-4.md
  templates/cube/study/maas/part-1.md
  templates/cube/study/microk8s/part-1.md
  templates/cube/study/networking/part-1.md
  templates/cube/study/networking/part-2.md
  templates/cube/study/networking/part-3.md
  templates/cube/study/packages/part-1.md
  templates/cube/study/packages/part-2.md
  templates/cube/study/packages/part-3.md
  templates/cube/study/packages/part-4.md
  templates/cube/study/security/part-1.md
  templates/cube/study/security/part-2.md
  templates/cube/study/security/part-3.md
  templates/cube/study/services/part-1.md
  templates/cube/study/services/part-2.md
  templates/cube/study/services/part-3.md
  templates/cube/study/storage/part-1.md
  templates/cube/study/storage/part-2.md
  templates/cube/study/storage/part-3.md
  templates/cube/study/system-architecture/part-1.md
  templates/cube/study/system-architecture/part-2.md
  templates/cube/study/system-architecture/part-3.md
  templates/cube/study/virtualisation/part-1.md
  templates/cube/study/virtualisation/part-2.md
  templates/cube/study/virtualisation/part-3.md
  webapp/app.py
  webapp/shop/cube/views.py
Labels: Review: QA +1, Commercial 🛒

#11674 Removes cloud pricing survey banner
  templates/ceph/index.html
  templates/ceph/what-is-ceph.html
  templates/cloud/hybrid-cloud.html
  templates/cloud/index.html
  templates/cloud/multi-cloud.html
  templates/cloud/private-cloud.html
  templates/cloud/public-cloud.html
  templates/kubernetes/index.html
  templates/kubernetes/what-is-kubernetes.html
  templates/openstack/index.html
  templates/openstack/what-is-openstack.html
  templates/server/index.html
  templates/shared/_cloud-survey-banner.html
Labels: Review: QA +1, Review: Code +1

#11683 Add a link on dropdown menu
  templates/templates/navigation-developer-h.html
Labels: Review: Code +1

#11671 Update datasheet link on /desktop/organisations
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#11677 Updates link on /ceph
  templates/ceph/index.html
Labels: Review: QA +1, Review: Code +1

#11668 Update FAQ on /security/docker-images
  templates/security/docker-images.html
Labels: Review: QA +1, Review: Code +1

#11675 Add 22.04 content to /aws/pro
  templates/aws/pro.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11686 Remove public sector event strip
  templates/aws/index.html
  templates/aws/pro.html
  templates/aws/shared/_aws-public-sector-summit.html
  templates/gov/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11670 Update copy for 22.04 LTS and 20.04 LTS
  static/js/src/advantage/subscribe/renderers/version-details.js
Labels: Review: QA +1, Review: Code +1

#11666 Copy update download ubuntu desktop page
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11621 /embedding build
  templates/embedding/base_embedding.html
  templates/embedding/index.html
  templates/shared/forms/interactive/embedding.html
  templates/templates/footer.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11682 Fix broken cypress test
  templates/credentialing/contact-us.html
  templates/credentialing/microcerts.html
  templates/shared/_credentialing-contact-us-form.html
  templates/shared/forms/interactive/automotive.html
  tests/cypress/forms/forms_spec.js
  tests/cypress/utils.js
Labels: Review: QA +1, Review: Code +1

#11687 Add calculate price endpoint
  tests/shop/advantage/test_api.py
  webapp/app.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/schemas.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11471 Update search with new arguments
  requirements.txt
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11692 Update Xilinx logo on /iot
  templates/internet-of-things/index.html
Labels: Review: QA +1, Review: Code +1

#11693 Copy update on /security/esm
  templates/security/esm.html
Labels: Review: QA +1, Review: Code +1

#11672 Create /financial-services/resources page
  navigation.yaml
  templates/financial-services/resources.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#11694 Copy update on /azure
  templates/azure/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11707 Update typos on financial-service/resources
  templates/financial-services/resources.html
Labels: Review: Code +1 (with changes)

#11709 Update blog card images to be responsive on smaller screens
  templates/blog/blog-card.html
Labels: Review: QA +1, Review: Code +1

#11710 Disable site restricted search
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11708 Remove repeated section
  templates/download/iot/_login.html
  templates/download/raspberry-pi-core.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11717 Revert "Disable site restricted search"
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11699 UC22 copy updates
  releases.yaml
  templates/download/intel-nuc.html
  templates/download/iot/index.html
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#11705 update /core/features page
  templates/core/features/index.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#11703 Refrseh core page (due June 16th)
  build.js
  static/js/src/random-partner-logos.js
  templates/core/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#11697 Build /data/kafka page
  navigation.yaml
  redirects.yaml
  templates/data/base_data.html
  templates/data/kafka/index.html
  templates/shared/forms/interactive/kafka.html
Labels: Review: QA +1, Review: Code +1

#11723 fix version number typo on core page
  templates/core/index.html
Labels: Review: Code +1

#11665 /openstack/resources build
  navigation.yaml
  static/js/src/openstack/react/components/CostCalculatorForm.jsx
  templates/openstack/_resource-card.html
  templates/openstack/resources.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11691 Fix greedy redirects and typo
  redirects.yaml
  templates/core/services/guide/document.html
  templates/core/services/guide/search-results.html
Labels: Review: QA +1, Review: Code +1

#11727 update core rpi 22 links with latest checksums
  releases.yaml
  templates/download/shared/_core_raspberry_pi_download.html
Labels: Review: QA +1, Review: Code +1

#11728 Revert "Revert "Disable site restricted search""
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1

#11732 Remove search temporarily
  templates/_search.html
  templates/templates/_navigation.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#11721 Add redirect for Openstack to openstack
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#11718 Docker: Make pip install slightly faster
  Dockerfile
Labels: Review: QA +1, Review: Code +1

#11730 Fix /blog description formatting
  templates/blog/blog-card.html
Labels: Review: QA +1, Review: Code +1

#11733 Uncomment sign-in button
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#11722 Delete unnecessary survey link
  static/js/src/openstack-deployment-chart.js
Labels: Review: QA +1, Review: Code +1

#11726 Remove state from forms
  build.js
  static/js/src/forms.js
  templates/download/shared/_get-ebook-security.html
  templates/rfp/index.html
  templates/shared/_client-contact-us-form.html
  templates/shared/_cloud-contact-us-form-german.html
  templates/shared/_cloud-contact-us-form.html
  templates/shared/forms/_state.html
Labels: Review: QA +1, Review: Code +1

#11704 New purchase endpoint offers
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/schema.py
  webapp/shop/schemas.py
Labels: Review: Code +1, Commercial 🛒

#11737 Temporarily remove all search
  templates/templates/docs/shared/_docs.html
  templates/tutorials/index.html
  tests/test_routes.py
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11408 Update notice list view to consume api
  templates/security/_notice-brief.html
  templates/security/notices.html
  templates/shared/_pagination.html
  webapp/security/api.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11740 Only show certified search page of search query present
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#11497 Update reduced nav and secondary nav
  package.json
  run
  static/js/src/core.js
  static/js/src/navigation.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation.scss
  static/sass/print.scss
  static/sass/styles.scss
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_header.html
  templates/engage/shared/_it_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/shared/_ru_thank-you.html
  templates/engage/thank-you.html
  templates/index.html
  templates/security/cve/cve.html
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/tutorials/tutorial.html
  webapp/context.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#11745 Fix a typo in a link on /core
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#11749 update support dates in /download/server
  templates/download/server/step2.html
Labels: Review: QA +1, Review: Code +1

#11747 Invoice cost for trial fixed
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/schema.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#11753 Update /legal copy
  static/sass/_pattern_table-of-contents.scss
  templates/legal/data-privacy/_toc.html
  templates/legal/terms-and-policies/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#11761 update order of nav items on /core
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#11758 add iot links section
  templates/automotive/index.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/networking.html
  templates/internet-of-things/shared/_links.html
  templates/internet-of-things/smart-city.html
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#11762 Openstack survey
  templates/openstack/install.html
  templates/openstack/tutorials.html
Labels: Review: QA +1, Review: Code +1

#11759 Reinstate all search except server docs search
  templates/search.html
  templates/templates/_navigation.html
  templates/templates/docs/shared/_docs.html
  templates/tutorials/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11764 Disable tutorials search again
  templates/tutorials/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11664 Add finance newsletter signup
  templates/blog/newsletter-form.html
Labels: Review: QA +1, Review: Code +1

#11768 Copy update on /security/smart-city
  templates/internet-of-things/smart-city.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11769 Update search module
  requirements.txt
Labels: Review: Code +1

#11770 Fix wrong links on /core
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#11763 Fix missing patches and tags in CVEs
  templates/security/cve/cve.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11774 Reenable search for /server/docs
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#11773 update landscape pricing copy
  templates/landscape/pricing.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11776 update ubuntu core datasheet links to 22 version
  templates/core/index.html
  templates/internet-of-things/smart-city.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11779 Remove mention of support from cloud options on /subscribe
  templates/advantage/subscribe/form/_type_select.html
Labels: Review: QA +1, Review: Code +1

#11767 Refactor 16-04 API calls
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11784 Update Credentialing exam links to point to QA
  templates/credentialing/index.html
Labels: Review: QA +1, Review: Code +1

#11782 update copy on /openstack
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#11777 Fix contact link typo
  templates/core/index.html
Labels: Review: Code +1

#11790 Temporarily remove searches
  templates/templates/docs/shared/_docs.html
  templates/tutorials/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11791 Update us pricing table to include active directory
  templates/shared/pricing/_ua-for-infrastructure-ja.html
  templates/shared/pricing/_ua-for-infrastructure-physical.html
  templates/shared/pricing/_ua-for-infrastructure-virtual.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA +1, Review: Code +1

#11716 New purchase endpoint renewals
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/schemas.py
Labels: Review: Code +1, Commercial 🛒

#11781 Add /iot/smart-home
  navigation.yaml
  templates/internet-of-things/smart-home.html
  templates/shared/forms/interactive/smart-home.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1
