Repository canonical/ubuntu.com, pull requests merged in 2022-10, with the labels that each got.

#12092 fix broken de engage thank you page
  templates/engage/shared/_de_thank-you.html
Labels: Review: QA +1, Review: Code +1

#12083 /pricing/infra => /pricing/pro
  redirects.yaml
  static/files/sitemap.xml
  templates/pricing/infra.html
  templates/pricing/pro.html
  templates/shared/pricing/_maas-pricing.html
  templates/shared/pricing/_openstack-kubernetes-lma.html
  templates/shared/pricing/_ua-advanced-storage.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12078 Pro change support
  templates/shared/_security-patching-logo-cloud.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#12098 Render latest news strip dynamically on /download/desktop
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#12065 WIP- Pro selector
  static/js/src/advantage/subscribe/react/UAPurchase.tsx
  static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/Form.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  static/sass/_pattern_card.scss
  static/sass/_pattern_shop-cart.scss
  static/sass/_pattern_subscribe.scss
  templates/advantage/subscribe/index.html
Labels: Review: Design -1, Review: QA needed, Review: Code needed, Review: UX needed, Review: PdM needed, Commercial 🛒

#12095 Pro change legal personal
  templates/legal/ubuntu-advantage/personal/index.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#12066 Add copy for /credentialling/self-study
  navigation.yaml
  templates/credentialling/self-study.html
  webapp/app.py
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12102 Fix incorrect id value for aria-controls attributes
  templates/advantage/table/_contract-name.html
  templates/appliance/shared/_verify-checksums-pc.html
  templates/appliance/shared/_verify-checksums.html
  templates/credentialling/microcerts.html
  templates/download/shared/_verify-checksums.html
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#12097 Service Description changes for Pro
  redirects.yaml
  templates/legal/ubuntu-advantage-service-description/ja/_toc_ja.html
  templates/legal/ubuntu-pro-description/_base_legal_markdown.html
  templates/legal/ubuntu-pro-description/_toc.html
  templates/legal/ubuntu-pro-description/index.md
  templates/legal/ubuntu-pro-description/ja/_base_legal_markdown_ja.html
  templates/legal/ubuntu-pro-description/ja/_toc_ja.html
  templates/legal/ubuntu-pro-description/ja/index.html
  templates/legal/ubuntu-pro-description/ros-esm-service-description/_base_legal_markdown.html
  templates/legal/ubuntu-pro-description/ros-esm-service-description/_toc.html
  templates/legal/ubuntu-pro-description/ros-esm-service-description/index.html
  templates/shared/_ubuntu-pro-description.html
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#12103 Update product listings and remove Apps support
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  static/sass/_pattern_subscribe.scss
Labels: Review: Code +1, Commercial 🛒

#12105 fix scss lints
  static/sass/_pattern_card.scss
  static/sass/_pattern_shop-cart.scss
  static/sass/_pattern_subscribe.scss
Labels: Review: QA +1, Review: Code +1

#12100 Ubuntu pro price changes
  templates/pricing/pro.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA +1, Review: Code +1

#11986 Update k8s release cycle
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#12108 Fix mobile version
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/sass/_pattern_card.scss
  static/sass/_pattern_shop-cart.scss
  static/sass/_pattern_subscribe.scss
Labels: Review: Design needed, Commercial 🛒

#12104 K8s updates for ck2
  templates/kubernetes/docs/1.25/release-notes.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA +1, Review: Code +1

#12084 Take down shop
  konf/site.yaml
  templates/advantage/index.html
  templates/advantage/maintenance.html
  webapp/app.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12109 Pro nav
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Code +1

#12112 Take shop down
  tests/shop/advantage/test_advantage_mapper.py
  tests/shop/advantage/test_api.py
  tests/shop/advantage/test_helpers.py
  tests/shop/advantage/test_parsers.py
  webapp/app.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1

#12113 /support table update
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#12099 add pro/beta page
  static/sass/_pattern_lists.scss
  static/sass/styles.scss
  templates/pro/beta.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12087 New Ubuntu Pro Page
  static/js/src/core.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/advantage/base_advantage.html
  templates/advantage/index-no-login.html
  templates/pro/index.html
  templates/pro/thank-you.html
  templates/shared/forms/interactive/advantage-beta.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12114 add discourse tutorial links
  templates/advantage/index-no-login.html
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1

#12115 add redirect for /pro/beta to discourse post
  redirects.yaml
Labels: Review: QA needed

#12106 Enable ubuntu pro shop
  konf/site.yaml
  tests/shop/advantage/test_advantage_mapper.py
  tests/shop/advantage/test_api.py
  tests/shop/advantage/test_helpers.py
  tests/shop/advantage/test_parsers.py
  webapp/app.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12116 add link to pro press release
  templates/advantage/base_advantage.html
  templates/advantage/index-no-login.html
Labels: Review: QA +1

#12117 Update subscribe copy
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
Labels: Review: QA needed, Commercial 🛒

#12118 change advantage to pro
  templates/advantage/index.html
Labels: Review: QA +1, Review: Code +1

#12119 Update remaining UA to Pro
  static/js/src/advantage/offers/Offers.tsx
  static/js/src/advantage/offers/components/Offer/Offer.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/advantage/subscribe/blender/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/react/components/Heading/Heading.tsx
  templates/advantage/index-no-login.html
Labels: Commercial 🛒

#12120 Fix sticky footer
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/sass/_pattern_shop-cart.scss
Labels: Commercial 🛒

#12101 Update /azure/pro as per copydoc
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1

#12123 update pro subnav to read "Pro"
  navigation.yaml
Labels: Review: QA needed

#12129 update let's talk link
  templates/advantage/index-no-login.html
Labels: Review: QA +1

#12125 fix blurry logos; fix author and h2 spacing
  static/sass/styles.scss
  templates/advantage/index-no-login.html
  templates/pro/beta.html
Labels: Review: QA +1, Review: Code +1

#12127 Get blog section dynamically on /desktop/flavours
  templates/desktop/developers.html
  templates/desktop/flavours.html
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#12130 Update pricing table
  templates/pricing/pro.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA needed, Review: Code needed

#12133 Add automotive link
  templates/templates/footer.html
Labels: Review: QA +1, Review: Code +1

#12128 Update USN template
  templates/security/notices/usn.html
Labels: Review: QA +1, Review: Code +1

#12136 change to Pro for /account and /account/invoices
  templates/account/index.html
  templates/account/invoices/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12139 UA to Pro copy changes
  templates/advantage/subscribe/index.html
  templates/advantage/subscribe/thank-you.html
Labels: Review: QA +1

#12107 Remove block access to content
  templates/engage/thank-you.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12142 Remove Netflix from the site
  templates/ai/index.html
  templates/aws/index.html
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#12140 copy changes to add link and change adv to pro
  templates/security/disa-stig.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12138 Fix charm link
  templates/about/packages.html
Labels: Review: QA +1, Review: Code +1

#12027 Implement renewal expiration notification
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  webapp/shop/api/ua_contracts/builders.py
Labels: Review: Code +1, Commercial 🛒

#12146 Fix copy typo
  templates/security/disa-stig.html
Labels: Review: QA +1, Review: Code +1

#12148 Update centos logo on homepage
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#12150 Update the pro pricing content
  templates/pricing/pro.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA +1, Review: Code +1

#12159 Replace chips with status labels
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/sass/_global-settings.scss
  static/sass/_pattern_subscribe.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12165 Copy update on /legal/upd
  templates/legal/ubuntu-pro-description/index.md
Labels: Review: QA +1, Review: Code +1

#12096 Refresh page on /financial-services/resources
  static/sass/_utility_crop.scss
  templates/financial-services/resources.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#12145 Remove pro page on cypress test
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#12172 Change renewal notification message
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
Labels: Review: Code +1

#12177 Updates /pro/beta to match copydoc
  templates/pro/beta.html
Labels: Review: QA +1, Review: Code +1

#12175 Remove USG for 16.04 and 18.04
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12143 Move and trap focus in modal when opened
  static/js/src/dynamic-forms.js
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#12170 Create dashboard page
  navigation.yaml
  static/js/src/navigation.js
  templates/pro/index.html
  webapp/app.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12134 Update /aws/pro for 22.04
  static/sass/styles.scss
  templates/aws/pro.html
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12184 remove /pro/beta redirect
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12179 capitalize Ubuntu Security Team
  templates/kubernetes/index.html
  templates/security/cve/cve.html
  tests/cassettes/TestRoutes.test_engage_index.yaml
  tests/cassettes/TestRoutes.test_engage_index_with_preview_flag_sees_inactive_pages.yaml
  tests/cassettes/TestRoutes.test_engage_index_without_preview_flag_cannot_see_inactive_page.yaml
Labels: Review: QA +1, Review: Code +1

#12185 Update link
  templates/financial-services/resources.html
Labels: Review: QA +1, Review: Code +1

#12168 Update the company address across the site
  templates/contact-us/index.html
  templates/legal/anbox-cloud-privacy-notice.html
  templates/legal/anbox-cloud-terms-of-service.html
  templates/legal/companies.html
  templates/legal/data-privacy/contact.md
  templates/legal/data-privacy/cube-beta.md
  templates/legal/data-privacy/esxi.md
  templates/legal/data-privacy/events.md
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/newsletter.md
  templates/legal/data-privacy/online-competitions.md
  templates/legal/data-privacy/online-purchase.md
  templates/legal/data-privacy/partner-portal.md
  templates/legal/data-privacy/recruitment.html
  templates/legal/data-privacy/snap-store.md
  templates/legal/data-privacy/snapcraft-nps.md
  templates/legal/data-privacy/sso.md
  templates/legal/data-privacy/survey.md
  templates/legal/data-privacy/user-survey.md
  templates/legal/data-privacy/webinar.md
  templates/legal/developer-terms-and-conditions/2016-04-06.html
  templates/legal/developer-terms-and-conditions/2018-07-23.html
  templates/legal/developer-terms-and-conditions/index.html
  templates/legal/jaas-beta-terms-of-service.html
  templates/legal/livepatch-terms-of-service.html
  templates/legal/motd.html
  templates/legal/online-account-terms.html
  templates/legal/systems-information-notice.html
  templates/legal/terms-and-policies/cube-terms.html
  templates/legal/terms-and-policies/snap-store-terms.html
  templates/legal/terms-of-service.html
  templates/legal/terms.html
  templates/legal/ua-dell-tc.html
  templates/legal/ua-miracle-tc-ja.html
  templates/legal/ua-miracle-tc.html
  templates/legal/ubuntu-advantage-service-terms/2015-06-24.html
  templates/legal/ubuntu-advantage-service-terms/2015-09-09.html
  templates/legal/ubuntu-advantage-service-terms/2016-05-20.html
  templates/legal/ubuntu-advantage-service-terms/2016-06-24.html
  templates/legal/ubuntu-advantage-service-terms/2019-02-11.md
  templates/legal/ubuntu-advantage-service-terms/index.md
  templates/legal/ubuntu-advantage-service-terms/ja.html
Labels: Review: Code +1 (with changes), hacktoberfest-accepted

#12195 Fix typo on pro description
  templates/legal/ubuntu-pro-description/index.md
Labels: Review: Code +1

#12191 Add global nav to new navigation
  package.json
  static/js/src/core.js
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#12205 Fix typo on /kubernetes/charmed-k8s
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1, Review: Code +1

#12169 templates/kernel/index.html: Fix link to Ubuntu CVE priorities
  templates/kernel/index.html
Labels: Review: QA +1, Review: Code +1

#12200 Add tutorial link on free token
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12204 Add all links to meganav.yaml
  meganav.yaml
  templates/templates/navigation-get-ubuntu.html
  templates/templates/navigation-meganav-base.html
  webapp/context.py
Labels: Review: QA +1, Review: Code +1

#12189 ubuntu server page: update copy
  templates/server/index.html
  templates/shared/_release_schedule.html
Labels: Review: QA +1, Review: Code +1

#12209 Update mascot asset on /download
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1

#12214 22 10 checksums
  releases.yaml
Labels: Review: QA +1, Review: Code +1 (with changes)

#12197 Ubuntu 22.10 raspberry Pi page update
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#12207 Update charts for Ubuntu 22.10
  static/js/src/chart-data.js
Labels: Review: QA +1, Review: Code +1

#12201 22.10 launch
  releases.yaml
  static/js/src/chart-data.js
  templates/desktop/developers.html
  templates/desktop/flavours.html
  templates/download/desktop/index.html
  templates/download/index.html
  templates/download/raspberry-pi/index.html
  templates/download/server/manual.html
Labels: Review: QA +1

#12183 Update entitlement if beta
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.tsx
  static/js/src/advantage/react/utils/filterAndFormatEntitlements.test.ts
  static/js/src/advantage/tests/factories/api.ts
  tests/shop/advantage/fixtures/entitlements.json
  tests/shop/advantage/test_parsers.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12208 Update Pro beta links to point to /pro/beta
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/sass/styles.scss
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1

#12217 Update copy on /pricing/pro
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1

#12181 Add pro service description checkbox
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/PurchaseModal/components/ModalSteps/StepTwo.tsx
  static/js/src/PurchaseModal/utils/utils.ts
  static/js/src/advantage/offers/components/BuyButton.tsx
  static/js/src/advantage/offers/components/Offer/Offer.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx
  static/js/src/advantage/subscribe/blender/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/blender/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  tests/cypress/integration/advantage/subscribe_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12222 Fix broken package links
  templates/security/cve/cve.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#12224 get contextual menu by id rather than query selector
  static/js/src/contextual-menu.js
Labels: Review: QA needed, Review: Code needed

#12182 Update /risc-v with new boards and 22.10 update
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
Labels: Review: QA +1, Don't merge, Review: Code +1 (with changes)

#12203 Fix Juju link in Kubernetes docs
  templates/kubernetes/docs/overview.md
Labels: Review: Code +1

#12229 Add new engage page redirect: iot time to market
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12227 Build page on /aws/support
  navigation.yaml
  templates/aws/support.html
Labels: Review: QA +1, Review: Code +1

#12226 Build page on /azure/support
  navigation.yaml
  templates/azure/support.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12216 Fix renewal css
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12219 Fix label for renewals
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  webapp/shop/api/ua_contracts/helpers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12132 Add previous and next buttons for doc navigation
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#12233 update copy on landscape/install
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1

#12239 updated /legal/ubuntu-pro-description
  templates/legal/ubuntu-pro-description/_toc.html
  templates/legal/ubuntu-pro-description/index.md
  templates/shared/_ubuntu-pro-description.html
Labels: Review: QA +1, Review: Code +1
