Repository canonical/ubuntu.com, pull requests merged in 2022-04, with the labels that each got.

#11433 Copy update on /16-04
  templates/16-04/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11443 Update copy on /aws/fips
  templates/aws/fips.html
Labels: Review: QA +1, Review: Code +1

#11442 K8s cs fixes
  templates/kubernetes/docs/1.21/components.md
  templates/kubernetes/docs/1.22/components.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/supported-versions.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#11444 Update /azure/fips copy
  templates/azure/fips.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11445 Update copy, add cta button on /cloud/public-cloud
  templates/cloud/public-cloud.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Review: Code +1

#11412 Build page on `/azure/sql`
  navigation.yaml
  templates/azure/sql.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#11446 Update copy, add google cloud logo and link
  templates/security/fips.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11415 Prevent 404 sentry errors from advantage/users
  static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx
  webapp/shop/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11435 Fix error handling for unauthorized exceptions
  tests/shop/advantage/test_api.py
  webapp/app.py
  webapp/shop/api/ua_contracts/api.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11451 Update contact us button
  templates/download/iot/intel-iotg.html
Labels: Review: Code +1

#11456 Remove contact us and newsletter from Ukraine blog
  templates/blog/article.html
Labels: Review: QA +1, Review: Code +1

#11422 Add cancel trial button
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useCancelTrail.ts
  static/js/src/advantage/react/hooks/useCancelTrial.test.tsx
  webapp/shop/api/ua_contracts/api.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11449 Adds acquisition URL to enrichment form data
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#11460 Change "Google Cloud Marketplace" to "Google Cloud Console".
  templates/advantage/subscribe/form/_type_select.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11461 fix exception on hardware details page
  templates/certified/hardware-details.html
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#11458 Fix /invoices page
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/schema.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11465 Remove countries from list
  static/js/src/advantage/countries-and-states.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11466 Update cancellation modal
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11325 Add tracking at different steps before checkout
  static/js/src/advantage/ecom-events.js
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/subscribe/listeners/form-event-listeners.js
  static/js/src/advantage/subscribe/listeners/ui-event-listeners.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11473 Refresh /server page
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#11486 add new "jammy" takeover class for pre release
  static/sass/_pattern_takeovers.scss
  templates/takeovers/shared/_takeover.html
Labels: Review: QA needed, Review: Code needed, Review: Code +1

#11475 Refresh /kubernetes/features page
  navigation.yaml
  redirects.yaml
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11488 make sure takeover text appears if image is not present
  templates/base_index.html
  templates/takeovers/shared/_takeover.html
Labels: Review: QA +1, Review: Code +1

#11485 Refresh /kubernetes page
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1

#11490 Revert /kubernetes nav
  navigation.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#11496 Fix bug where takeovers would show an empty anchor element if not CTA data was present
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#11491 Fix incorrect codecov reports for pull requests
  .github/workflows/pr.yaml
  codecov.yml
Labels: Review: Code +1

#11492 Refresh /organisations
  templates/desktop/organisations.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11493 Refresh /desktop/developers page
  templates/desktop/developers.html
  templates/shared/contextual_footers/_desktop_buy_preinstalled.html
  templates/shared/contextual_footers/_desktop_developer_community.html
Labels: Review: QA +1, Review: Code +1

#11489 Refresh /flavours page
  navigation.yaml
  redirects.yaml
  templates/desktop/flavours.html
  templates/download/flavours.html
Labels: Review: Design needed, Review: QA +1, Review: Code +1 (with changes)

#11494 Update raspberry-pi download page
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11500 Refresh desktop download page
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#11484 ua service description: fix wrong Japanese translation
  templates/shared/_ubuntu-advantage-service-description-ja.html
Labels: Review: QA +1, Review: Code +1

#11502 Update screenshots
  static/sass/styles.scss
  templates/dell/index.html
  templates/desktop/features.html
  templates/desktop/index.html
  templates/desktop/organisations.html
  templates/desktop/partners.html
  templates/download/cloud/index.html
Labels: Review: QA +1, Review: Code +1

#11507 Remove Honeywell logo
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#11504 Update Canonical Kubernetes release cycle chart
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11505 Update Ubuntu mascot
  templates/download/index.html
  templates/download/raspberry-pi/index.html
  templates/download/server/step2.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11509 Update with suggestions
  templates/ceph/index.html
  templates/download/alternative-downloads.html
  templates/download/server/step2.html
  templates/download/xilinx/index.html
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#11514 update desktop image on /desktop
  templates/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#11515 Update with suggestions
  templates/desktop/developers.html
  templates/desktop/flavours.html
  templates/desktop/organisations.html
  templates/download/index.html
  templates/download/raspberry-pi/index.html
Labels: Review: QA needed, Review: Code +1

#11501 22.04 refresh
  navigation.yaml
  redirects.yaml
  releases.yaml
  static/sass/styles.scss
  templates/ceph/index.html
  templates/dell/index.html
  templates/desktop/developers.html
  templates/desktop/features.html
  templates/desktop/flavours.html
  templates/desktop/index.html
  templates/desktop/organisations.html
  templates/desktop/partners.html
  templates/download/alternative-downloads.html
  templates/download/cloud/index.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/download/flavours.html
  templates/download/index.html
  templates/download/raspberry-pi/index.html
  templates/download/raspberry-pi/thank-you.html
  templates/download/server/step2.html
  templates/download/xilinx/index.html
  templates/server/index.html
  templates/shared/contextual_footers/_desktop_buy_preinstalled.html
  templates/shared/contextual_footers/_desktop_developer_community.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1, Review: PdM needed

#11438 Add notification banner and form for kernel beta signup
  build.js
  redirects.yaml
  static/js/src/kernel-form.js
  templates/embedded/index.html
  templates/internet-of-things/index.html
  templates/robotics/index.html
  templates/shared/_rt-kernel-beta-banner.html
  templates/shared/forms/interactive/kernel-beta-signup.html
  templates/telco/index.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11516 Update copy on ua for infra table and related pages
  templates/ceph/index.html
  templates/openstack/features.html
  templates/openstack/support.html
  templates/pricing/infra.html
  templates/shared/pricing/_ua-for-infrastructure.html
Labels: Review: QA +1, Review: Code +1

#11527 Update lenovo laptop images
  templates/desktop/developers.html
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#11520 update pricing/devices copy
  templates/pricing/devices.html
  templates/shared/pricing/_smart-start-prices.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11529 Removes /statistics from the navigation
  navigation.yaml
  templates/raspberry-pi/desktop.html
Labels: Review: QA +1, Review: Code +1

#11530 Update desktop image on /raspberry-pi/desktop
  templates/raspberry-pi/desktop.html
Labels: Review: QA +1, Review: Code +1

#11528 Clean up remaining /core/smartstart links and copy
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/blog/product-cards.html
  templates/blog/product-cards/_services.html
  templates/core/services/_markdown.html
  templates/core/services/contact-us.html
  templates/core/services/guide/advanced-options.md
  templates/core/services/guide/app-store-commissioning.md
  templates/core/services/guide/certification-and-validation.md
  templates/core/services/guide/custom-image-creation.md
  templates/core/services/guide/device-enablement.md
  templates/core/services/guide/hardware-setup.md
  templates/core/services/guide/index.md
  templates/core/services/guide/operating-an-app-store.md
  templates/core/services/guide/secure-device-onboarding.md
  templates/core/services/guide/snap-application-packaging.md
  templates/core/services/guide/snap-publishing.md
  templates/core/services/guide/technical-support.md
  templates/core/services/guide/training-workshops.md
  templates/core/services/index.html
  templates/core/services/shared/_side-navigation.md
  templates/core/stories.html
  templates/internet-of-things/digital-signage.html
  templates/templates/docs/markdown.html
  templates/templates/markdown/base.html
  templates/templates/navigation-enterprise-h.html
  tests/cypress/utils.js
Labels: Review: QA +1, Review: Code +1

#11532 Updates final 22.04 images
  templates/desktop/features.html
  templates/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#11519 Remove 'development board' text
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#11533 Replace the deploy kubeflow tutorial with get started docs
  templates/blog/product-cards/_kubeflow_deploy-tutorial.html
Labels: Review: QA +1, Review: Code +1

#11539 Lead the help button to the support form on the advantage page
  templates/shared/contextual_footers/_ua_got_questions.html
  templates/support/thank-you.html
Labels: Review: QA +1, Review: Code +1

#11548 Update kubernetes nav
  navigation.yaml
  redirects.yaml
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1, Review: Code +1

#11544 Build page on /kubernetes/resources
  navigation.yaml
  templates/kubernetes/resources.html
Labels: Review: QA +1, Review: Code +1

#11550 Fix aria controls for Canonical k8s release chart
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#11546 Openstack copy updates
  templates/openstack/compare.html
  templates/openstack/shared/_cheatsheet.html
  templates/openstack/tutorials.html
Labels: Review: QA +1, Review: Code +1

#11555 Update copy on /download/server/power
  templates/download/server/power.html
Labels: Review: QA +1, Review: Code +1

#11476 Add roles explaining table
  static/js/src/advantage/users/AccountUsers.tsx
  static/js/src/advantage/users/components/ExplainingTable.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11498 Improve TAX message
  static/sass/_pattern_shop-cart.scss
  templates/advantage/subscribe/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11540 Fix and schedule cypress test for forms
  .github/workflows/cypress-main.yaml
  templates/core/services/index.html
  templates/shared/_rt-kernel-beta-banner.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#11556 Update cypress schedule time
  .github/workflows/cypress-main.yaml
  templates/desktop/organisations.html
Labels: Review: QA needed, Review: Code needed

#11547 Refresh what-is-openstack page
  templates/openstack/what-is-openstack.html
  templates/shared/contextual_footers/_openstack-detailed-documentation.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11554 Copy update on /kubernetes
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1
