Repository canonical/ubuntu.com, pull requests merged in 2022-11, with the labels that each got.

#12235 Fix list of tutorial topics/categories
  templates/tutorials/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12244 Update the hero content of the RISC-V download page
  templates/download/risc-v/index.html
Labels: Review: QA +1, Review: Code +1

#12238 Redirect broken tutorial
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12243 Update names for Cred
  navigation.yaml
  redirects.yaml
  templates/credentials/base_cube.html
  templates/credentials/contact-us.html
  templates/credentials/faq.html
  templates/credentials/index.html
  templates/credentials/microcerts.html
  templates/credentials/self-study.html
  templates/credentials/syllabus.html
  templates/credentials/thank-you.html
  templates/shared/_credentials-contact-us-form.html
  tests/cypress/forms/forms_spec.js
  webapp/app.py
  webapp/shop/cube/syllabus.json
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE

#12245 Update company delivery addresses
  templates/legal/companies.html
Labels: Review: QA +1, Review: Code +1

#12220 Update /hpe page
  templates/hpe/_base_hpe.html
  templates/hpe/index.html
  templates/shared/forms/interactive/hpe.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX needed

#12247 Fix anchor link column
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Code +1

#12248 Require SSO login for /pro beta signup form
  redirects.yaml
  templates/pro/index.html
  templates/shared/forms/interactive/advantage-beta.html
Labels: Review: QA +1, Review: Code +1

#12221 Get Ubuntu meganav section
  build.js
  meganav.yaml
  static/js/src/main.js
  static/js/src/navigation.js
  static/js/src/tabbed-content.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/about/release-cycle.html
  templates/core/features/index.html
  templates/download/amd-xilinx/index.html
  templates/download/risc-v/index.html
  templates/openstack/install.html
  templates/templates/_navigation.html
  templates/templates/meganav/_list-item.html
  templates/templates/meganav/base.html
  templates/templates/meganav/get-ubuntu.html
  templates/templates/navigation-meganav-base.html
  webapp/app.py
  webapp/context.py
Labels: Review: QA needed, Review: Design +1, Review: Code needed

#12257 Add link on /pro
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12237 Update copy and beta sign up form for CUE
  templates/credentials/contact-us.html
  templates/credentials/index.html
  templates/credentials/sign-up.html
  templates/credentials/thank-you.html
  templates/shared/_credentials-contact-us-form.html
  webapp/app.py
  webapp/shop/cube/views.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12264 Cue beta signup spreadsheet
  konf/site.yaml
  requirements.txt
  templates/credentials/index.html
  templates/shared/_credentials-contact-us-form.html
  webapp/views.py
Labels: Review: QA +1, Review: Code needed, 🧊 CUBE, Commercial 🛒

#12262 Update table to include 22.04
  static/sass/_pattern_component-table.scss
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#12267 [copy update] u.c/model-driven-operations - replace links
  templates/model-driven-operations/index.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#12013 Semi-done Checkout redesign
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.test.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/PurchaseModal/components/BuyButton/index.ts
  static/js/src/PurchaseModal/components/ConfirmAndBuy/ConfirmAndBuy.tsx
  static/js/src/PurchaseModal/components/ConfirmAndBuy/index.ts
  static/js/src/PurchaseModal/components/FreeTrial/FreeTrial.test.tsx
  static/js/src/PurchaseModal/components/FreeTrial/FreeTrial.tsx
  static/js/src/PurchaseModal/components/FreeTrial/index.ts
  static/js/src/PurchaseModal/components/ModalSteps/StepOne.tsx
  static/js/src/PurchaseModal/components/ModalSteps/StepTwo.tsx
  static/js/src/PurchaseModal/components/PaymentMethodSummary/PaymentMethodSummary.jsx
  static/js/src/PurchaseModal/components/PaymentMethodSummary/PaymentMethodSummary.test.jsx
  static/js/src/PurchaseModal/components/SignIn/SignIn.test.tsx
  static/js/src/PurchaseModal/components/SignIn/SignIn.tsx
  static/js/src/PurchaseModal/components/SignIn/index.ts
  static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
  static/js/src/PurchaseModal/components/Taxes/index.ts
  static/js/src/PurchaseModal/components/UserInfoForm/PaymentMethodSummary/PaymentMethodSummary.test.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/PaymentMethodSummary/PaymentMethodSummary.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/PaymentMethodSummary/index.ts
  static/js/src/PurchaseModal/components/UserInfoForm/UserInfoForm.test.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/index.ts
  static/js/src/PurchaseModal/hooks/registerPaymentMethod.tsx
  static/js/src/PurchaseModal/hooks/useCalculateTaxes.tsx
  static/js/src/PurchaseModal/hooks/useGetTaxAmount.tsx
  static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
  static/js/src/PurchaseModal/hooks/usePollPurchaseStatus.tsx
  static/js/src/PurchaseModal/utils/utils.ts
  static/js/src/advantage/offers/components/Offer/Offer.tsx
  static/js/src/advantage/offers/hooks/usePurchaseOffer.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/index.ts
  static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/hooks/useRenewal.ts
  static/js/src/advantage/subscribe/blender/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/blender/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/blender/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/BuyButton/index.ts
  static/js/src/advantage/subscribe/react/components/PaymentModal/PaymentModal.tsx
  static/js/src/advantage/subscribe/react/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  static/sass/_pattern_checkout.scss
  static/sass/styles.scss
Labels: Commercial 🛒

#12276 update /pro and /support subnavs
  navigation.yaml
  static/js/src/navigation.js
Labels: Review: QA +1

#12277 Fix cypress test for /credentials/sign-up
  tests/cypress/forms/forms_spec.js
Labels: Review: QA needed, Review: Code needed

#12255 Refresh /iot/intel-iotg
  redirects.yaml
  templates/download/iot/intel-iot.html
  templates/download/iot/intel-iotg.html
  templates/shared/forms/interactive/intel-iot.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#12260 Store states in the local storage
  static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12231 Refresh /hpc and add contact modal
  templates/hpc/index.html
  templates/shared/forms/interactive/hpc.html
  templates/shared/forms/interactive/kernel-beta-signup.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12282 Remove cypress test for /credentials/sign-up
  tests/cypress/forms/forms_spec.js
Labels: Review: Code +1, Commercial 🛒

#12279 Store checkout states in local storage
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12285 Fix link typo on /intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: Code +1

#12281 Ubuntu Pro Upgrade form - Duplicated hidden email field
  templates/shared/forms/interactive/advantage-beta.html
Labels: Review: QA +1, Review: Code +1

#12273 Build /subscription-centre template
  static/sass/styles.scss
  subscriptions.yaml
  templates/subscription-centre/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#12294 Pass Marketo cookie value to form payload
  webapp/views.py
Labels: Review: Code +1

#12293 Update accordion.js to move to target when panel is opened
  static/js/src/accordion.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#12299 Add tax id type in payload
  static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12173 Disable infra support for 14.04 and 16.04
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
Labels: Review: QA +1, Review: Code +1, hacktoberfest-accepted, Commercial 🛒

#12300 Ignores free contracts outside of personal accounts
  tests/shop/advantage/fixtures/account.json
  tests/shop/advantage/fixtures/accounts.json
  tests/shop/advantage/test_advantage_mapper.py
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/primitives.py
  webapp/shop/api/ua_contracts/schema.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12303 Fix broken retail partners link
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#12268 Update pricing tables for Ubuntu Pro
  package.json
  static/sass/_pattern_table.scss
  static/sass/styles.scss
  templates/pricing/pro.html
  templates/pro/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#12275 Write cypress tests for purchases, trials and some errors
  tests/cypress/integration/advantage/subscribe_spec.js
  tests/cypress/integration/pro/subscribe_spec.js
  tests/cypress/integration/pro/subscriptions_spec.js
  tests/cypress/integration/pro/users_spec.js
  tests/cypress/support/index.js
  tests/cypress/support/pro/commands.js
  tests/cypress/utils.js
Labels: Review: Code +1, Commercial 🛒

#12302 Update VMware webinar engage page links
  redirects.yaml
  templates/lxd/index.html
  templates/managed/index.html
  templates/openstack/consulting.html
  templates/openstack/features.html
  templates/openstack/index.html
  templates/server/index.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#12305 Add product info to payload for trial
  static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12308 Remove link on /model-driven-operations
  templates/model-driven-operations/index.html
Labels: Review: QA +1, Review: Code +1

#12307 add "People and culture" blog topic
  navigation.yaml
  redirects.yaml
  templates/blog/people-and-culture.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#11968 Add exam scheduling and ability to take the exam
  .env
  konf/site.yaml
  navigation.yaml
  templates/credentials/assessments.html
  templates/credentials/base_exam.html
  templates/credentials/exam.html
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  templates/credentials/your-exams.html
  webapp/app.py
  webapp/shop/api/trueability/api.py
  webapp/shop/cube/views.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12311 update link to tshirt ts&cs
  templates/kubernetes/kubernetes-operations-survey.html
Labels: Review: QA +1, Review: Code +1

#12314 update /download/iot/intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1

#12317 Copy update: openstack/consulting (WD-757)
  static/js/data/openstack-deployment-stats.json
  templates/openstack/consulting.html
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#12319 update /landscape/pricing copy
  templates/landscape/pricing.html
Labels: Review: QA +1, Review: Code +1

#12251 Add remaining meganav sections
  meganav.yaml
  package.json
  requirements.txt
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation-dropdown.scss
  templates/templates/_navigation.html
  templates/templates/meganav/base.html
  templates/templates/meganav/community.html
  templates/templates/meganav/get-ubuntu.html
  templates/templates/meganav/products.html
  templates/templates/meganav/support.html
  templates/templates/meganav/use-case.html
  webapp/context.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12325 Set the copydoc link for the Ubuntu Pro legal page
  templates/legal/ubuntu-pro-description/_base_legal_markdown.html
Labels: Review: QA +1

#12309 Ubuntu Pro: Handle new VAT validation error codes
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/advantage/error-handler.js
  static/js/src/advantage/offers/components/BuyButton.tsx
  static/js/src/advantage/subscribe/blender/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
Labels: Review: Code +1, Commercial 🛒
