Repository canonical/ubuntu.com, pull requests merged in 2022-09, with the labels that each got.

#11991 Cred poc abhigyan
  templates/credentialing/schedule.html
  templates/credentialing/scheduled.html
  webapp/shop/api/trueability/api.py
  webapp/shop/cube/views.py
Labels: Review: Code +1, Commercial 🛒

#11990 Update for the 20.04.5 release
  releases.yaml
Labels: Review: QA +1, Review: Code +1

#11993 [Copy update] Ubuntu Server download page
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Code +1

#11988 K8s 1.25 release docs
  templates/kubernetes/docs/1.25/components.md
  templates/kubernetes/docs/1.25/release-notes.md
  templates/kubernetes/docs/1.25/upgrading.md
  templates/kubernetes/docs/azure-integration.md
  templates/kubernetes/docs/charm-reference.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/cni-canal.md
  templates/kubernetes/docs/cni-flannel.md
  templates/kubernetes/docs/cni-kube-ovn.md
  templates/kubernetes/docs/cni-overview.md
  templates/kubernetes/docs/container-runtime.md
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/proxies.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1

#11983 Remove redundant subnav on cve pages and tutorials
  static/sass/_layout-tutorial.scss
  templates/security/cve/cve.html
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11995 Add accessible label to all search submit buttons
  static/js/src/tutorial-list.test.js
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
  templates/search.html
  templates/templates/_navigation.html
  templates/templates/docs/shared/_search-box.html
  templates/tutorials/index.html
Labels: Review: Code +1, Review: A11y +1

#11976 UA: Enable downsells for yearly subscriptions
  tests/shop/advantage/test_helpers.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/schemas.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12003 Change to correct method to get article context
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12006 UA: Improve cancel subscription dialog message.
  static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11997 Tweaked some of the design for credentialing
  templates/credentialing/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12004 Update the web and design blog topic
  navigation.yaml
  templates/blog/topics/design.html
Labels: Review: QA +1, Review: Code +1

#12001 Update flavor screenshots to 22.04
  templates/desktop/flavours.html
Labels: Review: QA +1, Review: Code +1

#12009 Add RISC-V link to global nav
  templates/templates/navigation-download-h.html
Labels: Review: QA +1, Review: Code +1

#11992 Build why-openstack page
  templates/openstack/why-openstack.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#12011 Redirect not found blogs to 404 page
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12014 Copy updates to /openstack/features - NVidia vGPU row, and others
  templates/openstack/features.html
Labels: Review: QA +1, Review: Code +1

#12017 Fix broken button
  templates/openstack/why-openstack.html
Labels: Review: QA +1, Review: Code +1

#12005 Build new HPC page
  templates/hpc/_base_hpc.html
  templates/hpc/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#12010 Build use-cases page
  templates/hpc/use-cases.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#12037 update blog tag on /wsl
  templates/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#12031 Fix broken references link
  templates/security/notices/usn.html
Labels: Review: QA +1, Review: Code +1

#12036 add expandable navigation to core docs
  package.json
  static/js/src/side-navigation.js
  templates/core/docs/document.html
  templates/templates/docs/shared/_docs.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#12032 fix: closing contact modal when we release mouse on backdrop
  static/js/src/dynamic-forms.js
Labels: Review: QA +1, Review: Code +1

#12041 Update /iot/smart-home copy
  templates/core/index.html
  templates/internet-of-things/index.html
  templates/internet-of-things/smart-home.html
Labels: Review: QA +1, Review: Code +1, Don't merge, Review: PdM +1

#12022 Build page on /automotive/developers
  templates/automotive/developers.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12025 Update forms to include country dial codes dropdown
  package.json
  static/js/src/dynamic-forms.js
  static/js/src/intlTelInput.js
  static/js/src/main.js
  static/sass/styles.scss
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#12049 fix expandable navigation in server docs
  templates/server/docs/document.html
Labels: Review: QA +1, Review: Code +1

#12050 add side navigation js to shared docs template
  templates/core/docs/document.html
  templates/server/docs/document.html
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1

#12039 Refresh automotive page
  navigation.yaml
  templates/automotive/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12042 Engage pages access to content feature
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_it_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/shared/_ru_thank-you.html
  templates/engage/thank-you.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#12059 Revert login URL change
  konf/site.yaml
Labels: Review: QA +1, Review: Code +1

#12058 Add Credentialling syllabus
  templates/credentialing/index.html
  templates/credentialing/syllabus.html
  webapp/app.py
  webapp/shop/cube/syllabus.json
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12052 Refresh AT&T onboarding page
  templates/engage/unlisted/at&t-onboarding.html
  templates/shared/_security-patching-logo-cloud.html
  templates/support/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes), Review: PdM +1

#12062 update link to datasheet
  templates/kubernetes/managed.html
Labels: Review: QA +1, Review: Code +1

#12064 Update credentialling URLs
  navigation.yaml
  redirects.yaml
  templates/credentialling/base_cube.html
  templates/credentialling/contact-us.html
  templates/credentialling/faq.html
  templates/credentialling/index.html
  templates/credentialling/microcerts.html
  templates/credentialling/syllabus.html
  templates/credentialling/thank-you.html
  templates/shared/_credentialling-contact-us-form.html
  tests/cypress/forms/forms_spec.js
  webapp/app.py
  webapp/shop/cube/views.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#12067 add temp pro page
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1

#12012 Add renewal status tag on user subscriptions
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx
  static/js/src/advantage/react/hooks/useUserSubscriptions.ts
  static/js/src/advantage/tests/factories/api.ts
  tests/shop/advantage/test_helpers.py
  webapp/shop/api/ua_contracts/helpers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12068 Fix: thank you page missing closing endif
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/shared/_ru_thank-you.html
Labels: Review: QA +1, Review: Code +1

#11823 [pro update] Copy update on /desktop/developers
  static/js/src/developer-chart.js
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#12044 [pro update] Build page on /pricing/desktop
  navigation.yaml
  templates/pricing/desktops.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#12073 Update /security for pro launch
  templates/security/index.html
  templates/shared/contextual_footers/_security_esm.html
Labels: Review: QA +1, Review: Code +1

#12074 Redirect old blog post to new blog post url
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12075 Add `u-hide--medium` class
  templates/security/index.html
Labels: Review: QA +1, Review: Code +1

#12060 Remove pro beta banner
  templates/advantage/beta/thank-you.html
  templates/advantage/index-no-login.html
  templates/advantage/index.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12077 update canonical logos on /hpc
  templates/hpc/index.html
Labels: Review: Design +1, Review: Code +1

#12081 add /aws/workspaces page
  navigation.yaml
  templates/aws/workspaces.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12079 Pro change livepatch
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12082 Update Kubernetes Operations survey
  templates/kubernetes/kubernetes-operations-survey.html
Labels: Review: QA +1, Review: Code +1

#12085 Update copy referencing beta launch and update contextual footer links
  templates/desktop/developers.html
  templates/desktop/index.html
  templates/desktop/organisations.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/pricing/desktops.html
  templates/shared/contextual_footers/_download_enterprise_support.html
  templates/shared/contextual_footers/_download_helping_hands.html
Labels: Review: QA +1, Review: Code +1

#12086 update landscape pricing for pro launch
  templates/landscape/pricing.html
Labels: Review: QA +1, Review: Code +1

#11604 Open-source package licences page
  templates/legal/open-source-licences.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: PdM +1, Review: A11y +1
