Repository canonical/ubuntu.com, pull requests merged in 2022-12, with the labels that each got.

#12338 update intel-iot download page
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1

#12322 Update HPE contact form
  templates/shared/forms/interactive/hpe.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12284 Removed CUBE/edx code
  HACKING.md
  konf/site.yaml
  templates/credentials/faq.html
  templates/credentials/index.html
  templates/credentials/microcerts.html
  tests/cassettes/TestCube.test_microcerts_json.yaml
  tests/cassettes/TestCube.test_microcerts_purchase.yaml
  tests/shop/cube/test_cube.py
  webapp/app.py
  webapp/shop/cube/views.py
Labels: Review: Code needed, 🧊 CUBE, Commercial 🛒

#12225 Resizing calculations fix
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12332 Update CTA to green
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12331 Update physical servers selector
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12329 Reduce padding right
  static/sass/_pattern_subscribe.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12343 Update content
  templates/subscription-centre/index.html
Labels: Review: QA +1, Review: Code +1

#12342 Copy update on /openstack/why-openstack
  templates/about/openstack-release-cycle.html
  templates/about/release-cycle.html
  templates/openstack/why-openstack.html
Labels: Review: QA +1, Review: Code +1

#12346 feat(subnav): add link to landscape subnav LANDPM-474
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#12347 fix(copy): update try landscape contextual footer copy LANDPM-477
  templates/shared/contextual_footers/_support_landscape.html
Labels: Review: QA +1, Review: Code +1

#12349 Add missing data-testid on /esm
  templates/security/esm.html
Labels: Review: QA needed, Review: Code needed

#12312 Fix test-js & lint-ts
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.test.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/PurchaseModal/components/FreeTrial/FreeTrial.test.tsx
  static/js/src/PurchaseModal/components/SignIn/SignIn.test.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/UserInfoForm.test.tsx
  static/js/src/PurchaseModal/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/blender/components/Summary/Summary.test.jsx
  static/js/src/advantage/subscribe/react/components/Summary/Summary.test.jsx
  static/js/src/advantage/subscribe/react/utils/test/Mocks.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12344 Call preview before purchase change
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
  tests/cypress/integration/pro/subscribe_spec.js
  webapp/shop/advantage/views.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#12351 Show display mode
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12315 Display VAT error message
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12334 Add IoT devices option in the product selector
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12359 Hide images on small screens on /openstack/compare
  templates/openstack/compare.html
Labels: Review: QA +1, Review: Code +1

#12364 fix: cypress marketo form interception
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#12353 /certified refresh WD-741
  static/sass/_pattern_lists.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/certified/index.html
  templates/pricing/pro.html
  templates/pro/index.html
  templates/security/esm.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12357 Move reCAPTCHA to step 6
  static/js/src/PurchaseModal/components/ConfirmAndBuy/ConfirmAndBuy.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
  tests/cypress/integration/pro/subscribe_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12370 Change download link of all certified core xilinx devices
  webapp/certified/helpers.py
Labels: Review: QA +1, Review: Code +1

#12371 Update the cancel return URL from PayPal
  templates/download/desktop/thank-you.html
Labels: Review: QA +1, Review: Code +1

#12363 Cred exit survey
  templates/credentials/exit-survey.html
  templates/shared/_credentials-exit-survey.html
  webapp/app.py
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX needed, 🧊 CUBE, Commercial 🛒

#12361 Patch rebuy after expiry
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/ReBuyExpired/ReBuyExpiredButton/ReBuyExpiredButton.tsx
  static/js/src/advantage/react/components/Subscriptions/ReBuyExpired/ReBuyExpiredModal.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12375 update /why-certified to /why-certify
  navigation.yaml
  redirects.yaml
  templates/certified/index.html
  templates/certified/why-certify.html
  templates/credentials/index.html
  webapp/app.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#12373 Hide images for small and medium screens on /certified
  .github/workflows/pr.yaml
  templates/certified/desktops.html
  templates/certified/devices.html
  templates/certified/laptops.html
  templates/certified/servers.html
  templates/certified/socs.html
Labels: Review: Code +1

#12374 Update link text on /download/iot
  templates/download/iot/index.html
Labels: Review: QA +1, Review: Code +1

#12377 Fix /nvidia redirect
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12372 Update copy for Credentials
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#12350 Instant provisioning for TA exams
  templates/credentials/assessments.html
  templates/credentials/provision.html
  webapp/app.py
  webapp/shop/api/trueability/api.py
  webapp/shop/cube/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12380 fix ubuntu pro typos on /esm
  templates/security/esm.html
Labels: Review: QA +1, Review: Code +1

#12376 Update /amd-xilinx based on copydoc
  templates/download/amd-xilinx/index.html
Labels: Review: QA +1, Review: Code +1
