Repository canonical/ubuntu.com, pull requests merged in 2022-07, with the labels that each got.

#11789 Fix small typographical error on ubuntu.com/about/release-cycle
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#11793 Updates alternative download section to /download & updates support platforms logo cloud on /iot
  templates/download/index.html
  templates/download/iot/index.html
  templates/pricing/shared/_enablement-strip.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11801 Fix cve error for missing patches, tags, and bugs
  templates/security/cve/cve.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11800 Enable API docs again
  konf/site.yaml
Labels: Review: Code +1

#11802 Fix typo
  templates/desktop/organisations.html
Labels: Review: Code +1

#11803 ubuntu.com: Sentry schism
  konf/site.yaml
Labels: Review: Code +1

#11582 Robotics page copy update
  static/sass/_pattern_tabs.scss
  templates/robotics/index.html
  templates/robotics/shared/_download-make-strip.html
  templates/robotics/shared/_learn-more-about-robotics.html
  templates/shared/contextual_footers/_robotics_newsletter_signup.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11804 Remove linkcheck Github badges
  README.md
Labels: Review: Code +1

#11805 Updates /certified homepage with certified hardware links for 'devices' and 'socs'
  templates/certified/index.html
Labels: Review: QA +1, Review: Code +1

#11809 Fix invoice status
  templates/account/invoices/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11812 Add a link on `/gcp`
  templates/gcp/pro.html
Labels: Review: QA needed, Review: Code needed

#11807 Fix blog-cards not display variably coloured top strip
  static/sass/_pattern_blog-card.scss
  templates/blog/blog-card-header.html
  templates/blog/blog-card.html
Labels: Review: QA +1, Review: Code +1

#11820 Show cve bugs even when there's only one
  templates/security/cve/cve.html
Labels: Review: QA +1, Review: Code +1

#11796 #11464
  static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: UX +1, Commercial 🛒

#11811 Reenable search
  requirements.txt
  templates/403.html
  templates/templates/docs/shared/_docs.html
  templates/tutorials/index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11824 Update a link /openstack
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#11825 Copy update on /about/release-cycle
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11821 Add org name field to the Contributor agreement form
  templates/legal/contributors/agreement.html
Labels: Review: QA +1, Review: Code +1

#11830 Use release name instead of 'slug'
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#11839 Fix broken CVE query filter
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11835 Remove security db and related files
  .env
  .github/workflows/a11y.yaml
  .github/workflows/cypress-main.yaml
  .github/workflows/cypress-pr.yaml
  .github/workflows/pr.yaml
  .gitignore
  README.md
  alembic.ini
  docker-compose.yaml
  entrypoint
  konf/site.yaml
  redirects.yaml
  requirements.txt
  scripts/clear-database.py
  scripts/create-releases.py
  scripts/create-usns.py
  scripts/delete-usns.py
  webapp/app.py
  webapp/security/alembic/env.py
  webapp/security/alembic/script.py.mako
  webapp/security/alembic/versions/0fe2f3a871da_update_release_12_04.py
  webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py
  webapp/security/alembic/versions/3e0a3f15abb9_add_cve_mitigation_column.py
  webapp/security/alembic/versions/566647193540_release_update.py
  webapp/security/alembic/versions/570b8ff188c4_update_cve_component_field.py
  webapp/security/alembic/versions/765ed540939b_insert_releases.py
  webapp/security/alembic/versions/8008e46e6ea8_add_is_hidden_column_for_notices.py
  webapp/security/alembic/versions/88f1398da6c1_add_cve_pocket_column.py
  webapp/security/alembic/versions/8e9386e7a94b_add_component_column_to_status_table.py
  webapp/security/alembic/versions/c2bc5f0b027d_add_release_support_expiry_dates.py
  webapp/security/alembic/versions/e8760725610a_firstmigration.py
  webapp/security/alembic/versions/fc282ca1dc4d_cve_migration.py
  webapp/security/api.py
  webapp/security/auth.py
  webapp/security/database.py
  webapp/security/models.py
  webapp/security/schemas.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#11846 Create section 1: Product type
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.test.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
  static/sass/_pattern_card.scss
Labels: Review: QA +1, Review: Code +1, Review: UX needed, Commercial 🛒

#11860 Remove `>`
  templates/desktop/organisations.html
Labels: Review: Code +1

#11869 Fix broken links in PR templates
  .github/PULL_REQUEST_TEMPLATE/TAKEOVER_PR.md
  .github/pull_request_template.md
Labels: Review: QA +1, Review: Code +1

#11870 Remove local styles overriding Vanilla's middot list styles
  static/sass/_pattern_footer.scss
  static/sass/_pattern_lists.scss
Labels: Review: QA +1, Review: Code +1

#11868 reinstate blog-p-card__header fallback styles
  static/sass/_pattern_blog-card.scss
Labels: Review: QA +1, Review: Code +1

#11871 Update README.md for a grammar mistake
  README.md
Labels: Review: Code +1

#11862 Increase cypress timeout
  .github/workflows/cypress-main.yaml
Labels: Review: Code +1

#11874 Update image on `/desktop/developers`
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#11873 Disable the contribution button if total is 0
  static/js/src/contributions.js
  static/js/src/navigation.js
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#11867 Update copy on /credentialing
  templates/credentialing/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11875 Increase image size
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#11877 Expand to 2 gunicorn workers
  entrypoint
Labels: Review: QA +1, Review: Code +1

#11878 Fix the global navigation click
  static/js/src/navigation.js
Labels: Review: QA +1, Review: Code +1

#11896 Removed required on the org name in the CLA form
  templates/legal/contributors/agreement.html
Labels: Review: QA +1, Review: Code +1

#11459 Remove and redirect canonical annoucement blogs
  redirects.yaml
  tests/test_routes.py
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11898 Remove Update Focus
  static/js/src/ua-payment-methods.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11900 Update legal document ubuntu-advantage-service-terms
  templates/legal/ubuntu-advantage-service-terms/index.md
Labels: Review: QA +1, Review: Code +1

#11903 update image on /desktop/partners
  templates/desktop/partners.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11904 Blog - 500 when article has no group
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11897 update K8s chart to match upstream
  static/js/src/chart-data.js
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#11911 Update run script dev image version
  run
Labels: Review: QA +1, Review: Code +1

#11912 fix server section of certified home page
  templates/certified/index.html
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1
