Repository canonical/ubuntu.com, pull requests merged in 2022-02, with the labels that each got.

#11191 Rewrite folder structure
  tests/shop/__init__.py
  tests/shop/advantage/__init__.py
  tests/shop/advantage/fixtures/account.json
  tests/shop/advantage/fixtures/accounts.json
  tests/shop/advantage/fixtures/contract-item-legacy.json
  tests/shop/advantage/fixtures/contract-item-shop.json
  tests/shop/advantage/fixtures/contract-item-trial.json
  tests/shop/advantage/fixtures/contract.json
  tests/shop/advantage/fixtures/contracts.json
  tests/shop/advantage/fixtures/customer-info.json
  tests/shop/advantage/fixtures/ensured-account.json
  tests/shop/advantage/fixtures/entitlements.json
  tests/shop/advantage/fixtures/offer.json
  tests/shop/advantage/fixtures/offers.json
  tests/shop/advantage/fixtures/product-listing.json
  tests/shop/advantage/fixtures/product-listings.json
  tests/shop/advantage/fixtures/product.json
  tests/shop/advantage/fixtures/products.json
  tests/shop/advantage/fixtures/purchase.json
  tests/shop/advantage/fixtures/purchases.json
  tests/shop/advantage/fixtures/renewal.json
  tests/shop/advantage/fixtures/subscription-auto-renewal.json
  tests/shop/advantage/fixtures/subscription-items.json
  tests/shop/advantage/fixtures/subscription.json
  tests/shop/advantage/fixtures/subscriptions.json
  tests/shop/advantage/fixtures/user.json
  tests/shop/advantage/fixtures/users.json
  tests/shop/advantage/helpers.py
  tests/shop/advantage/test_api.py
  tests/shop/advantage/test_helpers.py
  tests/shop/advantage/test_parsers.py
  tests/shop/cube/test_cube.py
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/badgr/api.py
  webapp/shop/api/edx/api.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/primitives.py
  webapp/shop/context.py
  webapp/shop/cube/views.py
  webapp/shop/decorators.py
  webapp/shop/flaskparser.py
  webapp/shop/schemas.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11209 Changed "LXD documentation" URL
  templates/cube/study/virtualisation/part-3.md
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11208 Fix CVE pagination
  templates/security/cve/_pagination.html
Labels: Review: QA +1, Review: Code +1

#11211 Patch psycopg2 (for SQLAlchemy) with psycogreen
  .gitignore
  requirements.txt
  scripts/generate-sample-security-data.py
  webapp/security/database.py
Labels: Review: QA +1, Review: Code +1

#11212 Run the site with 3 gunicorn workers
  entrypoint
Labels: Review: Code +1

#11214 Fix /certified pagination
  templates/security/cve/_pagination.html
Labels: Review: QA +1, Review: Code +1

#11220 Adds #standard-pro anchor to /azure page
  templates/azure/index.html
Labels: Review: QA +1, Review: Code +1

#11205 Disabe email field if it was prepopulated
  static/js/src/PurchaseModal/components/PaymentMethodForm.tsx
  static/js/src/PurchaseModal/hooks/useStripeCustomerInfo.jsx
  static/js/src/navigation.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11203 Remove flask g
  webapp/shop/advantage/views.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11194 Change is cancelled condition
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
  tests/shop/advantage/test_helpers.py
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/helpers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11225 Copy update on base_index
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#11223 Update the address of Canonical in London
  templates/contact-us/index.html
  templates/legal/anbox-cloud-privacy-notice.html
  templates/legal/anbox-cloud-terms-of-service.html
  templates/legal/companies.html
  templates/legal/data-privacy/contact.md
  templates/legal/data-privacy/cube-beta.md
  templates/legal/data-privacy/esxi.md
  templates/legal/data-privacy/events.md
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/newsletter.md
  templates/legal/data-privacy/online-competitions.md
  templates/legal/data-privacy/online-purchase.md
  templates/legal/data-privacy/partner-portal.md
  templates/legal/data-privacy/snap-store.md
  templates/legal/data-privacy/snapcraft-nps.md
  templates/legal/data-privacy/sso.md
  templates/legal/data-privacy/user-survey.md
  templates/legal/data-privacy/webinar.md
  templates/legal/developer-terms-and-conditions/2016-04-06.html
  templates/legal/developer-terms-and-conditions/2018-07-23.html
  templates/legal/developer-terms-and-conditions/index.html
  templates/legal/intellectual-property-policy/2013-05-14.html
  templates/legal/intellectual-property-policy/index.html
  templates/legal/jaas-beta-terms-of-service.html
  templates/legal/livepatch-terms-of-service.html
  templates/legal/motd.html
  templates/legal/online-account-terms.html
  templates/legal/systems-information-notice.html
  templates/legal/terms-and-policies/cube-terms.html
  templates/legal/terms-and-policies/snap-store-terms.html
  templates/legal/terms-of-service.html
  templates/legal/terms.html
  templates/legal/ua-dell-tc.html
  templates/legal/ua-miracle-tc-ja.html
  templates/legal/ua-miracle-tc.html
  templates/legal/ubuntu-advantage-service-terms/2015-06-24.html
  templates/legal/ubuntu-advantage-service-terms/2015-09-09.html
  templates/legal/ubuntu-advantage-service-terms/2016-05-20.html
  templates/legal/ubuntu-advantage-service-terms/2016-06-24.html
  templates/legal/ubuntu-advantage-service-terms/2019-02-11.md
  templates/legal/ubuntu-advantage-service-terms/index.md
  templates/legal/ubuntu-advantage-service-terms/ja.html
  templates/legal/ubuntu-advantage/personal/_markdown.html
Labels: Review: Code +1 (with changes)

#11226 Quick fix: format of address
  templates/contact-us/index.html
Labels: Review: Code +1

#11213 Add "Canonical" item to top nav
  package.json
  static/js/src/core.js
  static/js/src/navigation.js
  static/sass/print.scss
  static/sass/styles.scss
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_header.html
  templates/engage/shared/_it_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/shared/_ru_thank-you.html
  templates/engage/thank-you.html
  templates/templates/_navigation.html
  templates/templates/navigation-canonical-h.html
  yarn.lock
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#11229 Remove mybrowser.fyi from issue-template
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: Review: QA +1

#11237 Correct SLA levels for managed services in UASD
  templates/legal/ubuntu-advantage-service-description/index.md
  templates/legal/ubuntu-advantage-service-description/ja/index.html
Labels: Review: Code +1

#11210 Move common view function outisde
  redirects.yaml
  static/js/src/advantage/api/contracts.js
  tests/cypress/integration/advantage/subscribe_spec.js
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11238 change "Canonical" nav item to "Company"
  templates/templates/_navigation.html
  templates/templates/navigation-company-h.html
Labels: Review: QA +1, Review: Code +1

#11240 Update /pro pages
  templates/aws/pro.html
  templates/azure/pro.html
  templates/gcp/pro.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Review: PdM +1

#11224 Close CUBE beta
  navigation.yaml
  redirects.yaml
  templates/cube/contact-us.html
  templates/cube/index.html
  templates/cube/thank-you.html
  templates/shared/_cube-contact-us-form.html
  templates/shared/forms/interactive/cube-beta.html
  webapp/views.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes), Commercial 🛒

#11239 K8s docs link fixes
  templates/kubernetes/docs/install-offline.md
  templates/kubernetes/docs/monitoring.md
Labels: Review: QA +1, Review: Code +1, Docs 📚

#11230 Russian engage pages
  static/sass/_global-settings.scss
  static/sass/styles.scss
  templates/engage/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11245 update data-privacy/survey copy
  templates/legal/data-privacy/survey.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#11221 Create shop decorator
  webapp/shop/advantage/views.py
  webapp/shop/cube/views.py
  webapp/shop/decorators.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11243 Refresh managed apps
  templates/managed/apps/index.html
Labels: Review: QA +1, Review: Code +1

#11248 Fix content overlapping meganav
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11215 Call preview for resizes
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/usePreviewResizeContract.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11247 Fix /cube/contact-us cypress test
  templates/shared/_cube-contact-us-form.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#11251 Fix cube interactive form cypress test
  templates/cube/index.html
  templates/shared/forms/interactive/cube-beta.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#11254 Add redirects to 4 Russian engage pages
  redirects.yaml
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1, Review: PdM +1

#11195 UA: Surface active machine count
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/tests/factories/api.ts
  tests/shop/advantage/helpers.py
  tests/shop/advantage/test_api.py
  tests/shop/advantage/test_parsers.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/primitives.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#11255 add wildcards to Russian page redirects
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#11259 Remove auth from pg db
  .env
  .github/workflows/a11y.yaml
  .github/workflows/cypress-main.yaml
  .github/workflows/cypress-pr.yaml
  .github/workflows/pr.yaml
  docker-compose.yaml
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#11249 Add api class to consume security api
  templates/security-error.html
  templates/security/cve/cve.html
  webapp/app.py
  webapp/security/api.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#11267 fix complaint/compliant typo
  templates/managed/apps/index.html
Labels: Review: QA needed, Review: Code +1

#11257 [security/fips] Add recert module, update 140-3 grammar.
  templates/security/fips.html
Labels: Review: QA +1, Review: Code +1

#11270 Engage: Fix spelling of “Español” in language selector
  templates/engage/index.html
Labels: Review: Code +1

#11250 Create AdvantageMapper class
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11274 Add UTM inheritance script, apply to Azure marketplace links
  build.js
  static/js/src/utm-inheritance.js
  templates/azure/index.html
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1, Review: PdM +1

#11275 Remove `tab=Overview` from Azure Marketplace links
  static/js/src/utm-inheritance.js
  templates/16-04/azure.html
  templates/16-04/index.html
  templates/azure/fips.html
  templates/azure/index.html
  templates/azure/pro.html
  templates/cloud/hybrid-cloud.html
  templates/cloud/multi-cloud.html
  templates/cloud/public-cloud.html
  templates/security/fips.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1, Review: PdM +1

#11276 Update state of robotics video
  templates/robotics/community.html
Labels: Review: QA +1, Review: Code +1

#11277 Update copy on /security/fips
  templates/security/fips.html
Labels: Review: QA +1, Review: Code +1

#11284 Fix vendor test to request a vendor that currently exists
  tests/cassettes/TestCertification.test_vendor_pages.yaml
  tests/test_certification.py
Labels: Review: QA +1, Review: Code +1

#11282 add MWC banner to /telco
  templates/telco/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11285 Update azure private offer page
  templates/azure/private-offer.html
  templates/azure/shared/_azure-logo-strip.html
  templates/azure/shared/_how-ubuntu-pro-helps-you.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11281 Bump the point release to 20.04.4
  releases.yaml
Labels: Review: QA +1, Review: Code +1
