Repository canonical/ubuntu.com, pull requests merged in 2022-08, with the labels that each got.

#11832 Fixed mobile footer links and added some padding.
  static/js/src/main.js
  static/js/src/mobile-footer-navigation.js
  static/sass/_pattern_footer.scss
  templates/templates/_footer_item.html
  templates/templates/footer.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#11922 Content updates for desktop features page
  static/sass/_pattern_gaming.scss
  templates/desktop/features.html
  templates/shared/contextual_footers/_desktop_flavours.html
Labels: Review: QA +1, Review: Code +1

#11918 Return 404 for not found unlisted engage pages
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11925 add equal employment opportunity commitment legal page
  navigation.yaml
  templates/legal/equal-employment-opportunity-commitment.html
  templates/legal/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#11924 Replace laptop image with XPS laptop image
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#11926 fix desktop/org image dimensions
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#11920 Fix certified download links
  templates/certified/model-details.html
  tests/cassettes/TestCertification.test_model_details.yaml
  webapp/certified/helpers.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#11921 Add model name to meta title
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#11931 Promote webinar embed on engage pages when webinar date has passed
  templates/engage/base.html
  templates/engage/shared/_webinar-embed.html
  webapp/app.py
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#11933 Fix typo on /support
  templates/support/index.html
Labels: Review: Code +1

#11932 k8s 1.24ck1 updates
  navigation.yaml
  templates/kubernetes/docs/1.24/components.md
  templates/kubernetes/docs/1.24/release-notes.md
  templates/kubernetes/docs/cdk-addons.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/gpu-workers.md
  templates/kubernetes/docs/how-to-addons.md
  templates/kubernetes/docs/inclusive-naming.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/ipv6.md
  templates/kubernetes/docs/metallb.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/using-vault.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#11934 Close markdown code
  templates/kubernetes/docs/supported-versions.md
Labels: Review: QA +1, Review: Code +1

#11928 [Copy Update] Download Intel IoT G Contact Us form
  static/js/src/dynamic-forms.js
  templates/shared/forms/interactive/intel-iotg.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#11936 Update repo for github actions
  .github/workflows/a11y.yaml
  .github/workflows/blog-links.yaml
  .github/workflows/cypress-main.yaml
  .github/workflows/cypress-pr.yaml
  .github/workflows/live-links.yaml
  .github/workflows/mirrors.yaml
  .github/workflows/security-links.yaml
Labels: Review: Code +1

#11864 Update discourse module to new engage pages system
  requirements.txt
  templates/engage/base.html
  templates/engage/shared/_webinar-embed.html
  templates/index.html
  templates/takeovers/_smartstart.html
  templates/takeovers/_template.html
  templates/takeovers/es/_redhat-openstack-comparacion-manual.html
  templates/takeovers/index.html
  tests/cassettes/TestRoutes.test_active_page_returns_200.yaml
  tests/cassettes/TestRoutes.test_active_page_returns_adds_no_meta_with_preview_flag.yaml
  tests/cassettes/TestRoutes.test_blog.yaml
  tests/cassettes/TestRoutes.test_engage_index.yaml
  tests/cassettes/TestRoutes.test_engage_index_with_preview_flag_sees_inactive_pages.yaml
  tests/cassettes/TestRoutes.test_engage_index_without_preview_flag_cannot_see_inactive_page.yaml
  tests/test_routes.py
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11939 update releases.yaml for 22.04.1
  releases.yaml
Labels: Review: QA +1, Review: Code +1

#11927 Desktop page: Copy update for the new release
  templates/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#11940 Add engage pages endpoint with language
  requirements.txt
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11853 Private engage page build - AT&T Onboarding Site
  redirects.yaml
  templates/engage/unlisted/at&t-onboarding.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes), Review: PdM +1

#11941 Update /credentialing links to point to Production.
  templates/credentialing/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#11930 switch steps 1 and 2 of server download
  redirects.yaml
  templates/download/server/choose.html
  templates/download/server/manual.html
  templates/download/server/multipass.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Review: PdM +1

#11938 copy doc update /securtiy/docker-images
  templates/security/docker-images.html
Labels: Review: QA +1, Review: Code +1

#11947 Handle not found WordPress posts
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11827 update /amd-xilinx copy
  templates/download/amd-xilinx/index.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11950 Revert "Removed Kylin and all references"
  redirects.yaml
  scripts/test-redirects.pl
  static/js/data/openstack-commit-stats.json
  templates/desktop/flavours.html
  templates/templates/navigation-download-h.html
  templates/ubuntu-ia.csv
  templates/ubuntu-ia.txt
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11942 Build new risc-v download page
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Review: PdM +1

#11949 [Copy update] IoT Download Page
  templates/download/iot/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes), Review: PdM +1

#11951 fix link on download/iot
  templates/download/iot/index.html
Labels: Review: QA +1, Review: Code +1

#11944 Add charmed kubeflow beta banner
  templates/ai/index.html
  templates/ai/what-is-kubeflow.html
  templates/shared/_charmed-kubeflow-beta-banner.html
Labels: Review: QA +1, Review: Code +1

#11952 [Copy update] /security/docker-images
  templates/security/docker-images.html
Labels: Review: QA +1, Review: Code +1

#11961 Remove the Spanish homepage call out
  templates/index.html
Labels: Review: Code +1

#11954 Fix engage page links
  templates/edge-computing/index.html
  templates/internet-of-things/smart-city.html
Labels: Review: QA +1, Review: Code +1

#11960 Sanitize blog slugs
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#11956 Create contact-us form for HPC
  templates/hpc/_hpc-contact-us-form.html
  templates/hpc/contact-us.html
  templates/hpc/thank-you.html
  templates/shared/_cloud-contact-us-form.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#11957 remove overview and breadcrumbs from bubble navigations
  navigation.yaml
  templates/security/cve/index.html
  templates/templates/_navigation.html
  webapp/context.py
Labels: Review: QA +1, Review: Code +1

#11966 Add JS to hide/show US state list when country is US on NDA form
  templates/legal/confidentiality-agreement.html
Labels: Review: QA +1, Review: Code +1

#11962 Replace "Microsoft store" with "Microsoft Store."
  templates/download/desktop/index.html
Labels: Review: Code +1

#11965 Correct the Kernel lifecycle versions
  static/js/src/chart-data.js
  templates/shared/_kernel-support-schedule.html
Labels: Review: QA +1, Review: Code +1

#11967 Fix cypress test
  templates/security/index.html
  tests/cypress/forms/forms_spec.js
Labels: Review: QA +1, Review: Code +1

#11981 Fix engage page form cypress tests
  .github/workflows/cypress-main.yaml
Labels: Review: Code +1

#11978 Custom thank-you text for engage pages
  templates/engage/thank-you.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: PdM +1
