Repository canonical/ubuntu.com, pull requests merged in 2023-02, with the labels that each got.

#12490 Fix python linting
  tests/shop/advantage/helpers.py
  webapp/certified/api.py
  webapp/certified/views.py
  webapp/security/views.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/views.py
Labels: Review: Code needed

#12462 Add impact score table
  static/sass/_pattern_cve.scss
  templates/security/cve/cve.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#12491 WD-1788 Add the datasheet link to the hero section of the ROS ESM page
  templates/robotics/ros-esm.html
Labels: Review: QA +1, Review: Code +1

#12441 Nvidia partners page
  redirects.yaml
  static/js/src/dynamic-forms.js
  static/sass/styles.scss
  templates/nvidia/index.html
  templates/shared/forms/interactive/nvidia.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12493 Improve error handling for user-country.json
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12495 Update 18-04 eol banner link to new blog post
  templates/shared/_18-04-eol-banner.html
Labels: Review: Code +1

#12476 Update Community Support Link
  templates/support/community-support.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12499 Fix typo in /pro/tutorial
  templates/pro/tutorial.html
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#12500 Fixed the broken pricing desktops navigation item
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#12496 Redeem Activation Keys (copy over from abhigyanghosh30:redeem_beta_invites)
  Dockerfile
  build.js
  package.json
  static/js/src/advantage/credentials/api/keys.js
  static/js/src/advantage/credentials/app.tsx
  static/js/src/advantage/credentials/components/CredManage/CredManage.tsx
  static/js/src/advantage/credentials/components/CredManage/index.tsx
  static/js/src/advantage/credentials/components/CredShop/CredShop.tsx
  static/js/src/advantage/credentials/components/CredShop/index.tsx
  static/sass/styles.scss
  templates/credentials/redeem.html
  templates/credentials/redeem_with_captcha.html
  templates/credentials/shop/index.html
  webapp/app.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/cred/views.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12506 Change /pro/tutorial command to match latest version of Pro client.
  templates/pro/tutorial.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12436 Keep URL parameters after SSO authentication
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12508 link fix
  templates/shared/contextual_footers/_ua_legal.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12509 Update noOfpages
  tests/cypress/utils.js
Labels: Review: Code +1

#12512 Remove / prefixes; Fix /pricing/desktops 404
  redirects.yaml
Labels: Review: QA needed, Review: Code needed

#12502 Copy updates for rebranding Advantage into Pro
  templates/openstack/features.html
  templates/openstack/index.html
  templates/openstack/support.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12483 Improve testing
  static/js/src/advantage/offers/components/PaymentButton/PaymentButton.test.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.test.tsx
  static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/subscribe/blender/components/PaymentButton/PaymentButton.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
  static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12513 /pro - call get_user_subscriptions for pro marketplace only
  webapp/shop/advantage/views.py
Labels: Commercial 🛒

#12507 WD-1854 Replace "Extended" to "Expanded" for ESM
  templates/16-04/azure.html
  templates/16-04/index.html
  templates/about/index.html
  templates/about/openstack-release-cycle.html
  templates/about/release-cycle.html
  templates/advantage/_table.html
  templates/advantage/index.html
  templates/advantage/subscribe/form/_ubuntu_version_select.html
  templates/advantage/subscribe/thank-you.html
  templates/aws/fips.html
  templates/azure/fips.html
  templates/ceph/index.html
  templates/cpu-compatibility/index.html
  templates/desktop/organisations.html
  templates/download/server/download.html
  templates/download/server/manual.html
  templates/financial-services/index.html
  templates/gcp/fips.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/smart-home.html
  templates/legal/ubuntu-pro-description/ros-esm-service-description/index.html
  templates/observability/managed.html
  templates/openstack/consulting.html
  templates/openstack/managed.html
  templates/openstack/what-is-openstack.html
  templates/pricing/devices.html
  templates/pricing/index.html
  templates/robotics/ros-esm.html
  templates/security/docker-images.html
  templates/security/esm.html
  templates/security/fips.html
  templates/security/thank-you.html
  templates/shared/_kernel-support-schedule.html
  templates/shared/_release_schedule.html
  templates/shared/forms/interactive/embedded.html
  templates/shared/forms/interactive/esm.html
  templates/shared/pricing/_ua-overview.html
  templates/shared/pricing/_ua-server-support.html
  templates/templates/navigation-developer-h.html
Labels: Review: Code +1, Review: PdM +1

#12517 Add redirect for UA JA legal page
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12515 Add appropriate labels to all form elements
  templates/download/desktop/thank-you.html
  templates/download/intel-nuc-desktop.html
  templates/download/server/s390x.html
  templates/download/shared/_get-ebook-security.html
  templates/download/shared/_get_ebook_maas.html
  templates/engage/shared/_de_engage_form.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_engage_form.html
  templates/engage/shared/_fr_engage_form.html
  templates/engage/shared/_it_engage_form.html
  templates/engage/shared/_pt_engage_form.html
  templates/engage/shared/_ru_engage_form.html
  templates/engage/shared/_zh-TW_engage_form.html
  templates/legal/confidentiality-agreement.html
  templates/legal/contributors/agreement.html
  templates/legal/data-privacy/enquiry.html
  templates/openstack/install.html
  templates/security/cve/_version-and-status-row.html
  templates/security/notices.html
  templates/shared/_client-contact-us-form.html
  templates/shared/_cloud-contact-us-form.html
  templates/shared/_pro-contact-us-form.html
  templates/shared/_telco-contact-us.html
  templates/shared/forms/interactive/openstack.html
  templates/shared/forms/interactive/robotics_ros.html
Labels: Review: QA +1, Review: Code +1, Review: A11y +1

#12519 Update logos on /kubernetes/resources
  templates/kubernetes/resources.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: A11y +1

#12505 Update NVIDIA page updates
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#12523 Update engage page tempalate to hide header images on medium screens
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1

#12526 Pro tutorial copy
  templates/pricing/pro.html
  templates/pro/tutorial.html
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#12488 changed NPS scores to range
  templates/shared/_credentials-exit-survey.html
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12529 Remove unnecessary aria-hidden label from side navigation in /tutorials
  templates/tutorials/tutorial.html
Labels: Review: QA +1, Review: Code +1, Review: A11y +1

#12242 Create annotated contract items endpoint
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/api/ua_contracts/primitives.py
  webapp/shop/api/ua_contracts/schema.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12536 Copy update for pro pricing
  templates/pricing/pro.html
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1, Commercial 🛒

#12533 Refresh Managed Apps pages
  templates/managed/apps/cassandra.html
  templates/managed/apps/index.html
  templates/managed/apps/kafka.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12537 [copy update] /core and /core/features
  templates/core/features/index.html
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1, Don't merge

#12527 Copy update on /industrial and /index
  templates/base_index.html
  templates/industrial/index.html
Labels: Review: QA needed, Review: Code needed, Don't merge

#12522 Ensure all inputs across site have aria-labelling
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  templates/blog/article.html
  templates/blog/newsletter-form.html
  templates/certified/index.html
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
  templates/download/iot/intel-iot.html
  templates/shared/contextual_footers/_download_iot_iotg_newsletter.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12531 WD-1836 Swapped the certified laptop images to the jammy background
  templates/certified/index.html
Labels: Review: QA +1, Review: Code +1

#12546 Update CPU compatibility table
  templates/cpu-compatibility/index.html
Labels: Review: QA +1, Review: Code +1

#12534 Checkout visual changes
  package.json
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/components/ConfirmAndBuy/ConfirmAndBuy.tsx
  static/js/src/advantage/subscribe/checkout/components/SignIn/SignIn.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/PaymentMethodSummary/PaymentMethodSummary.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePollPurchaseStatus.tsx
  static/sass/_pattern_checkout.scss
  templates/account/checkout.html
  yarn.lock
Labels: Commercial 🛒

#12544 Replace anbox cloud new logo
  templates/shared/_security-patching-logo-cloud.html
Labels: Review: QA +1, Review: Design +1

#12543 Update edgex integrated framework image
  templates/internet-of-things/edgex.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12553 WD-1233 update illustrations in `/telco/vnf`
  templates/telco/vnf.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12550 Add link to Ubuntu Pro 22.04 LTS on GCP marketplace
  templates/gcp/index.html
Labels: Review: QA +1, Review: Code +1

#12552 Add page for Apache Spark solution offer
  templates/data/kafka/index.html
  templates/data/spark/index.html
  templates/shared/forms/interactive/spark.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12494 Apply visual suggestions on /pro page
  static/sass/styles.scss
  templates/pro/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code needed, Commercial 🛒

#12565 Wild card the localhost ignore from k8s linkchecker
  .github/workflows/kubernetes-docs-links.yaml
Labels: Review: Code +1

#12564 Ignore local JS errors in OpenStack docs
  .github/workflows/openstack-charm-guide-docs-links.yaml
Labels: Review: Code +1

#12562 WD-1231 Update observability managed logos
  templates/observability/managed.html
Labels: Review: QA +1, Review: Design +1

#12572 Update /16-04 table mobile view ESM to 2026
  templates/16-04/_release-chart-1604.html
  templates/16-04/index.html
Labels: Review: QA +1, Review: Code +1

#12559 WD-1269 update k8s page logos
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12542 Update embedded logos
  templates/embedded/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12570 Remove unsued python libraries and upgrade others
  requirements.txt
Labels: Review: QA +1

#12560 Add id "free" to header in /pro page for anchor link
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1

#12561 WD-1269 update managed apps logos
  templates/managed/apps/index.html
Labels: Review: QA +1, Review: Design +1

#12573 Remove humans.txt file
  redirects.yaml
  static/files/humans.txt
  templates/templates/base.html
  templates/templates/base_no_nav.html
Labels: Review: QA +1, Review: Code +1

#12576 Remove more unused Python dependencies and upgrade deps
  requirements.txt
Labels: Review: QA +1

#12568 WD-2072: Add links to Ubuntu Pro and real time kernel from homepage
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#12551 Update Google cloud pro page #WD-1968
  templates/gcp/pro.html
Labels: Review: QA +1, Review: Code +1

#12579 Upgrade GH actions to use latest actions versions
  .github/workflows/a11y.yaml
  .github/workflows/ceph-docs-links.yaml
  .github/workflows/core-docs-links.yaml
  .github/workflows/cypress-main.yaml
  .github/workflows/cypress-pr.yaml
  .github/workflows/kubernetes-docs-links.yaml
  .github/workflows/openstack-charm-deployment-guide-docs-links.yaml
  .github/workflows/openstack-charm-guide-docs-links.yaml
  .github/workflows/pr.yaml
  .github/workflows/server-docs-links.yaml
Labels: Review: QA +1

#12581 Update GCP link
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12580 Upgrade d3 CDNs
  templates/16-04/_release-chart-1604.html
  templates/about/index.html
  templates/about/release-cycle.html
  templates/cpu-compatibility/index.html
  templates/desktop/developers.html
  templates/desktop/statistics.html
  templates/openstack/why-openstack.html
  templates/shared/_kernel-support-schedule.html
  templates/shared/_release_schedule.html
Labels: Review: QA +1

#12571 WD-2135: Limit run-image job to 15 minutes
  .github/workflows/pr.yaml
Labels: Review: Code needed

#12578 Remove redirects that redirect to url containing 'advantage'
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12514 Update search to include rate limits
  .github/workflows/pr.yaml
  requirements.txt
  templates/400.html
  templates/429.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#12584 Fix d3 graphs and data across site
  static/js/src/chart-data.js
  static/js/src/desktop-statistics.js
  templates/desktop/statistics.html
Labels: Review: QA +1, Review: Code +1

#12586 Fix free trial step
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12521 Add redirects to schedule/provision from activate key view
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12589 Update releases.yaml to add 22.04.2
  releases.yaml
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-5.html
Labels: Review: QA needed, Review: Code +1

#12594 Add secondary call to action in /pro
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12532 Cloud copy updates
  templates/cloud/hybrid-cloud.html
  templates/cloud/multi-cloud.html
  templates/cloud/private-cloud.html
Labels: Review: QA +1, Review: Code +1

#12587 Add document title to document template
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1, Don't merge

#12518 Use CS endpoints for instant provisioning
  templates/credentials/provision.html
  templates/credentials/schedule.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12524 Cred UI tweaks
  templates/credentials/your-exams.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12588 Make cancel button use formik initial values
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  tests/cypress/integration/pro/checkout_spec.js
  tests/cypress/support/pro/commands.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12609 Update logos on /appliance/hardware
  templates/appliance/hardware.html
  templates/appliance/shared/_featured_appliances.html
Labels: Review: QA +1, Review: Code +1

#12585 Disable when name and organisation name are the same
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  tests/cypress/integration/pro/checkout_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12607 Display offer discount
  static/js/src/advantage/offers/components/Offer/Offer.test.tsx
  static/js/src/advantage/offers/components/Offer/Offer.tsx
  static/js/src/advantage/offers/tests/factories/offers.ts
  static/js/src/advantage/offers/types.ts
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12608 WD-1726 WD-1727 WD-1728 Replace logos
  templates/security/certifications.html
  templates/security/index.html
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1

#12613 WD-1712, WD-1714 Replace logos in `/download/*`
  templates/appliance/shared/_featured_appliances.html
  templates/download/cloud/index.html
  templates/download/iot/index.html
  templates/pricing/shared/_enablement-strip.html
Labels: Review: QA +1, Review: Code +1

#12615 Tweaks for Credentials on production
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1

#12616 Add data-testid on base_index.html
  templates/base_index.html
Labels: Review: Code +1

#12617 Fix renewal number of machines
  static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx
  webapp/shop/api/ua_contracts/builders.py
Labels: Review: Code +1, Commercial 🛒
