Repository canonical/ubuntu.com, pull requests merged in 2023-12, with the labels that each got.

#13376 WD-7492 - add new section to /confidential-computing
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13365 Refresh /internet-of-things
  templates/internet-of-things/index.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13384 Fix broken network requirements link
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
Labels: Review: QA +1, Review: Code +1

#13366 Refresh /internet-of-things/appstore
  templates/internet-of-things/appstore.html
  templates/observability/managed.html
  templates/openstack/features.html
  templates/robotics/what-is-ros.html
  templates/telco/osm/onboarding-network-functions.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13387 WD-7769 - fix typo in gcp fips
  templates/gcp/fips.html
Labels: Review: QA +1, Review: Code +1

#13390 WD-7771 - update buttons in /robotics
  templates/robotics/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13381 Pass along UTMs when doing a blog redirect
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13391 WD-7815 - redirect from embedded to real-time
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13393 Update links of the support portal
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: QA +1, Review: Code +1

#13389 [WD-7064] Chiselled ubuntu
  build.js
  navigation.yaml
  static/js/src/charts/chiselled-chart.js
  templates/containers/chiselled/_base_chiselled.html
  templates/containers/chiselled/index.html
Labels: Review: QA +1

#13397 [WD-7905] update image on /confidential-computing page
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: Code +1

#13399 /support/contact-us copy update
  templates/support/contact-us.html
Labels: Review: QA +1, Review: Code +1

#13364 Remove old LXD pages and redirect to new ones
  navigation.yaml
  redirects.yaml
  templates/lxd/base_lxd.html
  templates/lxd/index.html
  templates/lxd/install.html
  templates/lxd/manage.html
  templates/shared/forms/interactive/lxd.html
Labels: Review: QA +1, Review: Code +1

#13395 /telco content refresh
  templates/telco/index.html
  templates/telco/shared/_telco-logo-section.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13404 /telco post release clean-up
  templates/telco/index.html
Labels: Review: QA +1, Review: Code +1

#13382 CVEs landing page redesign
  templates/security/cve/index.html
  webapp/security/helpers.py
  webapp/security/views.py
Labels: Review: QA needed, Review: Code needed, Review: UX +1

#13407 Revert the blog module update
  requirements.txt
  tests/cassettes/TestBlogNotice.test_blog_date_notice.yaml
  tests/cassettes/TestRoutes.test_blog.yaml
Labels: Review: QA +1

#13402 Update copy docs for pro pricing
  templates/pricing/pro.html
Labels: Review: QA needed, Review: Code needed

#13409 Fix typo in ceph/install
  templates/ceph/install.html
Labels: Review: QA +1, Review: Code +1

#13392 WD-7757 - add missing images to /internet-of-things
  templates/internet-of-things/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13413 [WD-7973] add small chages to content of legal pages for partner portal
  templates/legal/data-privacy/partner-portal.md
  templates/legal/partner-portal-terms.md
Labels: Review: QA +1, Review: Code +1

#13414 [WD-7975] replace image with a typo in /confidential-computing
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: Code +1

#13405 Parse query params for /certified
  requirements.txt
  static/js/src/certified-search-results.js
  tests/cassettes/TestCertification.test_filters_json.yaml
  webapp/certified/views.py
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1
