Repository canonical/ubuntu.com, pull requests merged in 2023-04, with the labels that each got.

#12743 Update redirects.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12742 Update to vanilla-3.13.0
  package.json
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#12675 Refresh /landscape/install
  static/sass/_pattern_lists.scss
  static/sass/styles.scss
  templates/landscape/install.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12746 Update /landscape/install install time bar chart changes
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1

#12748 Update openstack user server section on /openstack/tutorials
  templates/openstack/tutorials.html
Labels: Review: QA +1, Review: Code +1

#12749 WD-2994 `/download/iot/intel-iot` copy doc update
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1

#12750 WD-2881 [copy update] for `/nvidia`
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12704 Update / based on copy changes
  templates/base_index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12745 Update list activation keys for contract endpoint path
  webapp/shop/api/ua_contracts/api.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12751 Update /pricing/devices with new content and pricing information
  templates/pricing/devices.html
Labels: Review: QA +1, Review: Code +1

#12723 Break pro section out into a module
  templates/desktop/developers.html
  templates/desktop/organisations.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/shared/_pro_strip.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12766 Remove kafka from /support
  templates/shared/_security-patching-logo-cloud.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12758 Build French translation of /why-openstack
  templates/engage/fr_why-openstack.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12770 Update /desktop/flavours with new flavour information
  templates/desktop/flavours.html
Labels: Review: QA +1, Review: Code +1

#12772 Update copy and fix links on /downlaod/iot/intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1

#12768 refactor: move all handlers in their own file
  webapp/app.py
  webapp/context.py
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1

#12769 WD-2123 & WD-2125 - Create MongoDB product page & contact form
  navigation.yaml
  static/sass/styles.scss
  templates/data/mongodb/index.html
  templates/shared/contextual_footers/_data_mongodb_signup.html
  templates/shared/forms/interactive/data-mongodb.html
  templates/silicon/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#12778 [copy update] /cloud/multi-cloud
  templates/cloud/multi-cloud.html
Labels: Review: QA +1, Review: Code +1

#12783 [copy update] /openstack/what-is-openstack
  templates/openstack/what-is-openstack.html
Labels: Review: QA +1, Review: Code +1

#12780 [copy update] /cloud
  templates/cloud/index.html
Labels: Review: QA +1, Review: Code +1

#12774 WD-3167 Add the discourse terms legal page
  templates/legal/partner-portal-terms.md
  templates/legal/terms-and-policies/discourse-terms.md
  templates/legal/terms-and-policies/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12781 [copy update] /cloud/private-cloud
  templates/cloud/private-cloud.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12793 Update syllabus for CUE: Linux
  templates/credentials/index.html
  webapp/shop/cred/syllabus.json
Labels: Review: QA +1, Review: Code needed, Commercial 🛒

#12785 WD-2898 create opensearch product page and form
  navigation.yaml
  static/sass/styles.scss
  templates/data/mongodb/index.html
  templates/data/opensearch/index.html
  templates/shared/contextual_footers/_data_opensearch_signup.html
  templates/shared/forms/interactive/data-opensearch.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#12782 [copy update] /cloud/hybrid-cloud
  templates/cloud/hybrid-cloud.html
Labels: Review: QA +1, Review: Code +1

#12798 [copy update] /legal/nvidia-jetson-and-ubuntu
  templates/legal/nvidia-jetson-and-ubuntu.html
Labels: Review: QA +1, Review: Code +1

#12790 [copy update] WD-3064 `/pricing/pro`
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12796 Cache git.launchpad.net requests for ROS ESM package lists
  webapp/security/views.py
Labels: Review: Code +1

#12797 Modernize Launchpad package URLs
  templates/security/cve/cve.html
Labels: Review: QA +1, Review: Code +1

#12800 [copy update] /observability
  templates/observability/index.html
  templates/shared/_latest_news_strip.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12730 Accessibility for disabled area on /pro/subscribe
  static/js/src/advantage/subscribe/react/UAPurchase.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/Form.tsx
  static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#12803 Update logo on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#12807 Add missing classes in heading icon components
  static/sass/styles.scss
  templates/0_docs/content_strips.html
  templates/azure/sql.html
  templates/blog/topics/robotics.html
  templates/containers/shared/_whitepaper.html
  templates/download/iot/index.html
  templates/download/raspberry-pi/index.html
  templates/download/raspberry-pi/thank-you.html
  templates/edge-computing/index.html
  templates/financial-services/index.html
  templates/hpc/index.html
  templates/internet-of-things/edgex.html
  templates/internet-of-things/smart-city.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/compare.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/what-is-kubernetes.html
  templates/lxd/index.html
  templates/managed/apps/kafka.html
  templates/managed/index.html
  templates/observability/managed.html
  templates/openstack/consulting.html
  templates/openstack/what-is-openstack.html
  templates/security/index.html
  templates/security/livepatch.html
  templates/takeovers/_template.html
  templates/telco/cnf.html
  templates/telco/osm/index.html
  templates/telco/osm/multi-cloud.html
  templates/telco/osm/onboarding-network-functions.html
  templates/telco/vnf.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12789 Add plausible and custom event to track
  static/js/src/advantage/react/app.tsx
  static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12809 Pro: Ubuntu Pro(Infra-Only) offers Real-time kernel.
  templates/pro/index.html
Labels: Review: Code +1, Commercial 🛒

#12777 23 04 - release prep
  releases.yaml
  static/js/src/chart-data.js
  static/sass/_pattern_strip.scss
  templates/desktop/developers.html
  templates/download/desktop/index.html
  templates/download/index.html
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
  templates/download/server/manual.html
  templates/templates/navigation-download-h.html
Labels: Don't merge

#12818 Actions: Force node 16 on test-js job
  .github/workflows/pr.yaml
  HACKING.md
Labels: Review: QA +1, Review: Code +1

#12734 Debugging view for your-exams
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12802 WD-3110 build `/18-04/gcp`
  navigation.yaml
  templates/18-04/gcp.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#12811 [copy update] update marketo form id on `/data/mongodb` and `/data/opensearch`
  templates/data/mongodb/index.html
  templates/data/opensearch/index.html
Labels: Review: QA +1, Review: Code +1

#12824 Fix missing commas HPC page
  templates/hpc/index.html
Labels: Review: QA +1, Review: Code +1

#12821 [page refresh] /download/risc-v
  static/sass/_pattern_tabs.scss
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12828 Cred: Add more materials for Linux resources
  templates/credentials/self-study.html
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#12820 K8s 1.27 updates
  templates/kubernetes/docs/1.27/components.md
  templates/kubernetes/docs/1.27/release-notes.md
  templates/kubernetes/docs/1.27/upgrading.md
  templates/kubernetes/docs/audit-logging.md
  templates/kubernetes/docs/auth.md
  templates/kubernetes/docs/aws-iam-auth.md
  templates/kubernetes/docs/aws-integration.md
  templates/kubernetes/docs/azure-integration.md
  templates/kubernetes/docs/backups.md
  templates/kubernetes/docs/ceph.md
  templates/kubernetes/docs/charm-reference.md
  templates/kubernetes/docs/cis-compliance.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/cni-cilium.md
  templates/kubernetes/docs/cni-kube-ovn.md
  templates/kubernetes/docs/cni-multus.md
  templates/kubernetes/docs/cni-overview.md
  templates/kubernetes/docs/cni-sriov.md
  templates/kubernetes/docs/docker-registry.md
  templates/kubernetes/docs/encryption-at-rest.md
  templates/kubernetes/docs/equinix.md
  templates/kubernetes/docs/gatekeeper.md
  templates/kubernetes/docs/gcp-integration.md
  templates/kubernetes/docs/gpu-workers.md
  templates/kubernetes/docs/hacluster.md
  templates/kubernetes/docs/how-to-addons.md
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/install-manual.md
  templates/kubernetes/docs/install-offline.md
  templates/kubernetes/docs/kata.md
  templates/kubernetes/docs/keepalived.md
  templates/kubernetes/docs/kubevirt.md
  templates/kubernetes/docs/ldap.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/monitoring.md
  templates/kubernetes/docs/multiple-networks.md
  templates/kubernetes/docs/openstack-integration.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/operator-charms.md
  templates/kubernetes/docs/quickstart.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/scaling.md
  templates/kubernetes/docs/security.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/snap-coherence.md
  templates/kubernetes/docs/snap-refresh.md
  templates/kubernetes/docs/storage.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/tigera-secure-ee.md
  templates/kubernetes/docs/troubleshooting.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/using-vault.md
  templates/kubernetes/docs/validation.md
  templates/kubernetes/docs/volcano.md
  templates/kubernetes/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1

#12831 Increase rate limit to 2000 per day
  webapp/app.py
Labels: Review: Code +1

#12718 Added new product card
  templates/blog/product-cards.html
  templates/blog/product-cards/_ubuntu_18.04_end_of_support.html
Labels: Review: QA +1, Review: Code +1

#12829 WD-3147 - Add real-time kernel product card
  templates/blog/product-cards.html
  templates/blog/product-cards/_real-time_linux.html
Labels: Review: QA +1, Review: Code +1
