Repository canonical/ubuntu.com, pull requests merged in 2023-01, with the labels that each got.

#12378 Fix a11y tests
  .github/workflows/a11y.yaml
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/templates/base_no_nav.html
  templates/templates/footer.html
  tests/cypress/a11y/a11y_spec.js
Labels: Review: Code +1

#12392 add partner logo and youtube embed to /automotive WD-803
  templates/automotive/index.html
Labels: Review: QA +1, Review: Code +1

#12394 add title attributes to iframe elements
  templates/appliance/shared/_base_appliance_index.html
  templates/blog/product-cards/_raspberry-pi_2010-livestream.html
  templates/ceph/index.html
  templates/credentials/exam.html
  templates/engage/base.html
  templates/engage/unlisted/custom-ubuntu-pro-image-on-azure.html
  templates/engage/unlisted/shell-onboarding.html
  templates/hpc/index.html
  templates/hpc/use-cases.html
  templates/kubeconeurope2020/index.html
  templates/managed/apps/index.html
  templates/masters-conference/index.html
  templates/security/livepatch.html
  templates/shared/_share_this.html
  templates/templates/_product.html
  templates/templates/base.html
  templates/templates/base_no_nav.html
Labels: Review: Code +1

#12379 Add buy button on nav
  static/js/src/navigation.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12316 Disable buy button when a value is missing
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#12390 Meganav bug fixes
  meganav.yaml
  package.json
  static/js/src/core.js
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/templates/_navigation.html
  templates/templates/meganav/base.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#12366 Call calculate endpoint on step 1 only for guest users
  static/js/src/PurchaseModal/PurchaseModal.tsx
  static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx
  static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
  static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
  static/js/src/advantage/subscribe/react/components/Summary/Summary.tsx
  webapp/shop/schemas.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12407 Update link on /core
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#12393 Clean up /credentials
  .env
  HACKING.md
  konf/site.yaml
  templates/credentials/assessments.html
  templates/credentials/base_cred.html
  templates/credentials/exit-survey.html
  templates/credentials/index.html
  templates/credentials/provision.html
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  templates/credentials/self-study.html
  templates/credentials/sign-up.html
  templates/credentials/syllabus.html
  templates/credentials/thank-you.html
  templates/credentials/your-exams.html
  templates/shared/forms/interactive/cube-beta.html
  webapp/app.py
  webapp/shop/api/edx/api.py
  webapp/shop/cred/syllabus.json
  webapp/shop/cred/views.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12409 Update ASRock logo on /certified
  templates/certified/shared/_partners.html
Labels: Review: QA +1, Review: Code +1

#12412 Update ros-esm-service-description
  templates/legal/ubuntu-pro-description/ros-esm-service-description/index.html
Labels: Review: QA +1, Review: Code +1

#12414 [Bugfix] Add TrueAbility variables to production configuration
  konf/site.yaml
Labels: Review: Code +1, Commercial 🛒

#12419 Update advantage to pro on /support/contact-us
  templates/support/contact-us.html
Labels: Review: QA +1, Review: Code +1

#12418 Copy Changes #753
  templates/desktop/developers.html
Labels: Review: QA +1, Copy update 📝, Review: Code +1 (with changes)

#12421 6315: New Core 22 release notes and 12th gen download link on /download/iot/intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1

#12422 Exit survey error fixed
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12423 Add Google service account creds to /credentials staging & prod
  konf/site.yaml
Labels: Review: Code +1

#12427 Update k8s table data
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#12417 Copy update /download/desktop/thank-you
  templates/download/desktop/thank-you.html
Labels: Review: QA +1, Review: Code +1

#12429 Fix hr separators on /edge-computing
  templates/edge-computing/index.html
Labels: Review: Code +1

#12431 Apply additional updates to the automotive page
  templates/automotive/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12424 Update /subscription-centre with pdm suggestions
  subscriptions.yaml
  templates/subscription-centre/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12435 Update copy on /pricing/devices
  templates/pricing/devices.html
Labels: Review: QA +1, Review: Code +1

#12432 change intel logo
  templates/internet-of-things/index.html
Labels: Review: QA needed, Review: Code needed

#12345 Subscription centre
  static/js/src/modal.js
  static/sass/styles.scss
  subscriptions.yaml
  templates/subscription-centre/base_subscription-centre.html
  templates/subscription-centre/index.html
  templates/templates/base.html
  webapp/app.py
  webapp/views.py
Labels: Review: PdM +1

#12434 Apply more additional updates to the automotive page
  templates/automotive/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12430 Add Snapcraft 101 to /training
  templates/training/contact-us.html
  templates/training/index.html
  templates/training/thank-you.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12442 Add workspaces tutorial video to /aws/workspaces
  templates/aws/workspaces.html
Labels: Review: QA +1, Review: Code +1

#12438 Update incorrect information on /kubernetes/compare table
  templates/kubernetes/compare.html
Labels: Review: QA +1, Review: Code +1

#12446 Very small copy updates on the certified page
  templates/certified/index.html
Labels: Review: Code +1

#12447 Host landscape docs on u.com using discourse module
  navigation.yaml
  templates/advantage/_table.html
  templates/landscape/docs/document.html
  templates/landscape/docs/search-results.html
  templates/landscape/install.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#12450 WD-1473 Update the why-openstack button
  templates/openstack/why-openstack.html
Labels: Review: Code +1

#12416 Build new gcp FIPS page
  navigation.yaml
  templates/gcp/fips.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12445 Add download button for un-certified xilinx boards details pages
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#12428 update desktop bubble from Advantage to Pro
  templates/desktop/organisations.html
  templates/download/desktop/index.html
  templates/pricing/desktops.html
  templates/shared/contextual_footers/_professional_support.html
Labels: Review: QA +1, Review: Code +1, Don't merge

#12451 Rename /pro/beta to pro/tutorial with redirect
  redirects.yaml
  templates/pro/tutorial.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12452 Use geo-lookup to preset the country code for mobile number inputs ac…
  static/js/src/intlTelInput.js
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#12458 Copy update /security/notices page
  templates/security/notices/usn.html
  templates/shared/contextual_footers/_security_need.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12454 Change references to Ubuntu Advantage to Ubuntu Pro in legal pages
  navigation.yaml
  redirects.yaml
  templates/advantage/maintenance.html
  templates/legal/index.html
  templates/legal/ubuntu-advantage/index.html
  templates/legal/ubuntu-pro-assurance.html
  templates/legal/ubuntu-pro-description/index.md
  templates/legal/ubuntu-pro-description/ja/_base_legal_markdown_ja.html
  templates/legal/ubuntu-pro-description/ja/index.html
  templates/legal/ubuntu-pro-service-terms/2015-06-24.html
  templates/legal/ubuntu-pro-service-terms/2015-09-09.html
  templates/legal/ubuntu-pro-service-terms/2016-05-20.html
  templates/legal/ubuntu-pro-service-terms/2016-06-24.html
  templates/legal/ubuntu-pro-service-terms/2019-02-11.md
  templates/legal/ubuntu-pro-service-terms/_base_uast_markdown.html
  templates/legal/ubuntu-pro-service-terms/index.md
  templates/legal/ubuntu-pro-service-terms/ja.html
  templates/legal/ubuntu-pro/index.html
  templates/legal/ubuntu-pro/personal/_markdown.html
  templates/legal/ubuntu-pro/personal/index.md
  templates/shared/_ubuntu-advantage-service-description-ja.html
  templates/shared/_ubuntu-pro-description.html
  templates/shared/contextual_footers/_ua_legal.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12439 Fix reported broken links on the site
  .github/workflows/live-links.yaml
  static/files/sitemap.xml
  templates/legal/data-privacy/contact.md
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/newsletter.md
  templates/legal/data-privacy/sso.md
  templates/legal/data-privacy/webinar.md
  templates/legal/ubuntu-pro-description/_toc.html
Labels: Review: Code +1 (with changes)

#12457 Final ubuntu pro ga updates based on pdm suggestions
  templates/ai/index.html
  templates/ai/services.html
  templates/aws/workspaces.html
  templates/ceph/consulting.html
  templates/desktop/developers.html
  templates/desktop/organisations.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/embedding/index.html
  templates/landscape/index.html
  templates/pricing/desktops.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#11974 Magic Attach
  redirects.yaml
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  templates/pro/attach/confirmation.html
  templates/pro/attach/index.html
  templates/pro/attach/instructions.html
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/api.py
Labels: Commercial 🛒

#12455 Ubuntu pro ga release
  templates/ai/index.html
  templates/ai/services.html
  templates/aws/workspaces.html
  templates/ceph/consulting.html
  templates/desktop/developers.html
  templates/desktop/organisations.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/embedding/index.html
  templates/landscape/index.html
  templates/pricing/desktops.html
  templates/shared/contextual_footers/_professional_support.html
Labels: Don't merge

#12440 Refresh /wsl landing page
  templates/wsl/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12466 Fix a11y cypress error
  templates/pro/index.html
Labels: Review: Code +1

#12467 Adjust /pro tabindex
  templates/pro/index.html
Labels: Review: Code +1

#12468 Add tutorial in the nav
  navigation.yaml
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12459 1.26+ck1 docs changes
  templates/kubernetes/docs/1.26/release-notes.md
  templates/kubernetes/docs/1.26/upgrading.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/operations.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/upgrading.md
  templates/kubernetes/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#12471 Fix the live links check
  .github/workflows/live-links.yaml
Labels: Review: QA +1, Review: Code +1

#12463 WD-221 Set-up community docs
  navigation.yaml
  redirects.yaml
  templates/community/canonical.html
  templates/community/code-of-conduct.html
  templates/community/debian.html
  templates/community/diversity.html
  templates/community/docs/document.html
  templates/community/docs/search-results.html
  templates/community/governance.html
  templates/community/index.html
  templates/community/mission.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#12469 Update copy with time to complete exam
  templates/credentials/schedule.html
Labels: Review: QA +1, Commercial 🛒

#12472 Minor changes bases on pdm feedback after deployment to the revelent …
  templates/download/desktop/index.html
  templates/download/iot/index.html
  templates/pricing/desktop.html
  templates/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#12479 Show the request trial form when the users have paid contracts.
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12480 Fix magic attach button/link issue
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12481 Update logo section
  templates/pro/index.html
Labels: Review: QA needed, Review: Code needed

#12474 Copy update on /hpe
  templates/hpe/index.html
Labels: Review: QA +1, Review: Code +1
