Repository canonical/ubuntu.com, pull requests merged in 2023-10, with the labels that each got.

#13185 Fix subscription status chips
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13179 Remove juju install section and other copy updates
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#13182 Build /pro/why-pro page
  static/sass/styles.scss
  templates/ai/what-is-kubeflow.html
  templates/pro/why-pro.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Review: PdM +1

#13193 Add Pro network requirements documentation link to dashboard
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#13195 [copy update] WD-6242 - update on `/landscape/managed`
  templates/landscape/managed.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13203 fix for checkout error
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13189 [WD-5489] replace an image with HTML table on Ceph page
  static/sass/_pattern_table.scss
  templates/ceph/components/benefits-table.html
  templates/ceph/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13202 increase timeouts in Cypress tests to fix the failing pipeline issue
  .github/workflows/cypress-pr.yaml
  tests/cypress/cypress.json
  tests/cypress/integration/pro/checkout_spec.js
  tests/cypress/integration/pro/subscriptions_spec.js
  tests/cypress/support/commands.js
Labels: Review: Code +1

#13205 #12841 Issue - Correct href value to https://charmhub.io/?q=OpenStack
  templates/shared/contextual_footers/_openstack_documentation.html
Labels: Review: Code +1, hacktoberfest-accepted

#13208 #12840 Issue - Correct href value
  templates/templates/_footer-copyright-and-legal.html
Labels: Review: Code +1, hacktoberfest-accepted

#13219 [WD-6656] change link for QEMU preinstalled image on RISC-V download page
  templates/download/risc-v/tab-3.html
Labels: Review: QA +1, Review: Code +1

#13194 Fix unclosed link in table of contents
  templates/legal/ubuntu-pro-description/ja/_toc_ja.html
Labels: Review: QA +1, Review: Code +1

#13210 Forbidden checkout on technical account
  templates/account/forbidden.html
  webapp/shop/advantage/views.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13125 Add link to CUE Activation Keys shop
  static/js/src/advantage/credentials/api/keys.js
  static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
  static/js/src/advantage/credentials/components/CredKeyShop/CredKeyShop.tsx
  static/js/src/advantage/credentials/components/CredWebhookResponses/CredWebhookResponses.tsx
  static/js/src/advantage/credentials/utils/utils.ts
  templates/credentials/index.html
  webapp/app.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1, 🧊 CUBE, Commercial 🛒

#13220 [copy update] /openstack/compare
  templates/openstack/compare.html
Labels: Review: QA +1, Review: Code +1

#13216 Hide notification for personal users
  static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx
  tests/cypress/integration/pro/checkout_spec.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13183 k8s 1.28+ck1 updates
  templates/kubernetes/docs/1.28/release-notes.md
  templates/kubernetes/docs/cni-overview.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA needed

#13212 [WD-6255] /desktop/developers copy update
  static/js/src/chart-data.js
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13214 WD-6601 - Replace Advantage link with Pro on financial-services
  templates/financial-services/index.html
Labels: Review: Code +1 (with changes), hacktoberfest-accepted

#13227 [WD-6707] Minor changes on download pages
  static/js/src/chart-data.js
  templates/desktop/developers.html
  templates/download/index.html
  templates/download/iot/index.html
Labels: Review: QA +1, Review: Code +1

#13104 Update pro page
  static/sass/styles.scss
  templates/pro/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1, Commercial 🛒

#13229 WD-6705 - update /downloads/raspberry-pi
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13236 WD-6769 - fix dowload link
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#13235 Some small 23-10 release fixes
  templates/desktop/developers.html
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1

#13238 WD-6442 - Update checksums for 23.10
  releases.yaml
Labels: Review: QA needed, Review: Code needed

#13230 Update K8s docs homepage
  templates/kubernetes/docs/index.md
Labels: Review: QA needed

#13237 Update datasheet link
  templates/data/mongodb/index.html
Labels: Review: QA +1, Review: Code +1

#13243 Pro page: fix typos
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1

#13188 Issue #13093 & #12478 resolved
  static/js/src/cve/cve.js
  templates/security/cve/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13009 Implement sliding nav into meganav
  meganav.yaml
  navigation.yaml
  package.json
  requirements.txt
  static/js/src/core.js
  static/js/src/main.js
  static/js/src/navigation.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/download/risc-v/index.html
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/templates/meganav/_list-item.html
  templates/templates/meganav/base.html
  templates/templates/meganav/community.html
  templates/templates/meganav/get-ubuntu.html
  templates/templates/meganav/products.html
  templates/templates/meganav/support.html
  templates/templates/meganav/use-case.html
  webapp/context.py
  webapp/handlers.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13248 Fix form custom fields
  static/js/src/landscape-saas-form.js
  templates/landscape/pricing.html
  templates/shared/forms/interactive/landscape-pricing-saas.html
Labels: Review: QA +1, Review: Code +1

#13249 [WD-6779] enable 23.10 desktop download button/link
  releases.yaml
  templates/download/alternative-downloads.html
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1, Don't merge

#13251 Update Enterprise nav link
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA needed, Review: Code +1

#13226 [copy update] /download/amd
  templates/download/amd/index.html
  templates/download/amd/tab-1.html
  templates/download/amd/tab-2.html
  templates/download/amd/tab-3.html
  templates/download/amd/tab-4.html
Labels: Review: QA +1, Review: Code +1, Don't merge, Review: PdM +1

#13256 WD-6799 - Add EB corbos Linux to the automotive buyers guide
  templates/automotive/buyers-guide/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13232 K8s new navigation
  templates/kubernetes/docs/explain-cloud.md
  templates/kubernetes/docs/how-to-clouds.md
  templates/kubernetes/docs/how-to-cni.md
  templates/kubernetes/docs/how-to-containers.md
  templates/kubernetes/docs/how-to-ha.md
  templates/kubernetes/docs/how-to-install.md
  templates/kubernetes/docs/how-to-operate.md
  templates/kubernetes/docs/how-to-security.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: QA +1

#13141 Nojs meganav
  static/js/src/navigation.js
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/templates/_navigation.html
  templates/templates/meganav/_section-heading.html
  templates/templates/meganav/base.html
  templates/templates/meganav/navigation-nojs.html
  webapp/app.py
  webapp/context.py
  webapp/views.py
Labels: Review: UX +1

#13197 Remove /data and redirect to c.com/data
  navigation.yaml
  redirects.yaml
  templates/data/base_data.html
  templates/data/docs/document.html
  templates/data/docs/kafka/iaas/document.html
  templates/data/docs/kafka/iaas/search-results.html
  templates/data/docs/kafka/k8s/document.html
  templates/data/docs/kafka/k8s/search-results.html
  templates/data/docs/mongodb/iaas/document.html
  templates/data/docs/mongodb/iaas/search-results.html
  templates/data/docs/mongodb/k8s/document.html
  templates/data/docs/mongodb/k8s/search-results.html
  templates/data/docs/mysql/iaas/document.html
  templates/data/docs/mysql/iaas/search-results.html
  templates/data/docs/mysql/k8s/document.html
  templates/data/docs/mysql/k8s/search-results.html
  templates/data/docs/opensearch/iaas/document.html
  templates/data/docs/opensearch/iaas/search-results.html
  templates/data/docs/postgresql/iaas/document.html
  templates/data/docs/postgresql/iaas/search-results.html
  templates/data/docs/postgresql/k8s/document.html
  templates/data/docs/postgresql/k8s/search-results.html
  templates/data/docs/spark/k8s/document.html
  templates/data/docs/spark/k8s/search-results.html
  templates/data/kafka/index.html
  templates/data/opensearch/index.html
  templates/data/spark/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#13254 Add K8s docs index pages
  templates/kubernetes/docs/explanation-index.md
  templates/kubernetes/docs/how-to-index.md
  templates/kubernetes/docs/index.md
  templates/kubernetes/docs/reference-index.md
  templates/kubernetes/docs/tutorials-index.md
Labels: Review: QA +1

#13260 Add a redirect for the realtime engage page
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13262 Revert core version
  releases.yaml
Labels: Review: Code +1

#13228 WD-5991 - update /landscape page
  templates/landscape/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13266 WD-6593 - Update Livepatch column to be architecture specific, closes…
  templates/security/esm.html
Labels: Review: QA +1, Review: Code +1

#13247 twitter to x icon
  static/sass/_pattern_lists.scss
  templates/templates/footer.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13162 Wd 5646 implement dashboard updates removing toggles landscape trial
  static/js/src/advantage/react/components/FeatureSwitch/FeatureSwitch.tsx
  static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.tsx
  static/js/src/advantage/react/components/Subscriptions/Landscape/index.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  static/js/src/advantage/react/components/Subscriptions/Subscriptions.tsx
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Commercial 🛒

#13270 Fix a link
  templates/pro/index.html
Labels: Review: Code +1

#13261 Remove fullName field and add first&last name field on /observibility/managed contact-us form
  templates/shared/forms/interactive/managed-observability.html
Labels: Review: QA +1, Review: Code +1

#13265 WD-6720 - update /internet-of-things/smart-displays
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13278 WD-6937 - update text in /openstack/features
  templates/openstack/features.html
Labels: Review: QA +1, Review: Code +1

#13279 WD-6938 - add link to /openstack/consulting
  templates/shared/pricing/_openstack-packages.html
Labels: Review: QA +1, Review: Code +1

#13280 WD-6939 - update text and link in /openstack/compare
  templates/openstack/compare.html
Labels: Review: QA +1, Review: Code +1

#13281 WD-6935 - update link and text in /openstack
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#13277 WD-6916 - add cells to the cookie table
  templates/legal/data-privacy/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13272 WD-6860 - update real-time link
  templates/core/features/index.html
  templates/core/index.html
  templates/download/iot/intel-iot.html
  templates/industrial/index.html
Labels: Review: QA +1, Review: Code +1

#13285 WD-6948 - add security section to /contact-us
  templates/contact-us/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13286 Bump the version of discourse module to v5.4.4
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#13263 Remove unused files after data bubble migration
  static/sass/styles.scss
  templates/ai/index.html
  templates/ai/mlflow.html
  templates/ai/roadshow.html
  templates/data/mongodb/index.html
  templates/shared/contextual_footers/_data_mongodb_signup.html
  templates/shared/contextual_footers/_data_opensearch_signup.html
  templates/shared/forms/interactive/data-mongodb.html
  templates/shared/forms/interactive/data-opensearch.html
Labels: Review: QA +1, Review: Code +1

#13258 Build /download/mediatek-genio page
  static/sass/styles.scss
  templates/download/mediatek-genio/contact-us.html
  templates/download/mediatek-genio/index.html
  templates/download/mediatek-genio/tab-1.html
  templates/download/mediatek-genio/tab-2.html
  templates/download/mediatek-genio/tab-3.html
  templates/financial-services/index.html
  templates/templates/navigation-download-h.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13288 Update the Mediatek Genio contact us link
  templates/download/mediatek-genio/index.html
Labels: Review: QA +1, Review: Code +1

#13290 Bump canonicalwebteam.blog to 6.4.1
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#13313 Bump canonicalwebteam.discourse to 5.4.5
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#13293 WD-7018 - update vmware link on /openstack/what-is-openstack
  templates/openstack/what-is-openstack.html
Labels: Review: QA +1, Review: Code +1
