Repository canonical/ubuntu.com, pull requests merged in 2023-07, with the labels that each got.

#12993 Fix validation error
  webapp/shop/schemas.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12991 Fix techinical user error
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
  webapp/shop/api/ua_contracts/helpers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12959 Revamp HPE page
  static/sass/styles.scss
  templates/hpe/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13008 Add redirect for `/engage/architecting-price-performance-private-cloud`
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13002 Fix type on the OpenStack release cycle
  templates/about/release-cycle.html
Labels: Review: Code +1

#12998 Add pages to install and manage lxd
  navigation.yaml
  templates/appliance/lxd/_next-steps.html
  templates/appliance/lxd/index.md
  templates/containers/index.html
  templates/download/desktop/index.html
  templates/industrial/index.html
  templates/kubernetes/_install-lxd.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/docs/inclusive-naming.md
  templates/kubernetes/docs/install-local.md
  templates/kubernetes/docs/install-offline.md
  templates/kubernetes/index.html
  templates/legal/websites.html
  templates/lxd/index.html
  templates/lxd/install.html
  templates/lxd/manage.html
  templates/shared/contextual_footers/_cloud_lxd_vs_docker.html
  templates/templates/navigation-developer-h.html
Labels: Review: QA +1, Review: Design +1, Review: UX needed, Review: Code +1 (with changes)

#12995 Build Chiselled Ubuntu and .Net containers - WD-3946
  navigation.yaml
  static/sass/styles.scss
  templates/containers/chiselled/_base_chiselled.html
  templates/containers/chiselled/dotnet.html
  templates/shared/forms/interactive/containers-chiselled-dotnet.html
  templates/silicon/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13014 WD-4878 - Clickable diagram on the Nvidia page
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1

#13001 WD-4924 Add the high-performance computing guide to HPC
  templates/hpc/use-cases.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#13022 quick fix to title and header on `/containers/chiselled/dotnet`
  templates/containers/chiselled/dotnet.html
Labels: Review: QA +1, Review: Code +1

#12987 Update visuals for /credentials/your-exams
  templates/credentials/your-exams.html
  webapp/shop/cred/views.py
Labels: Review: Design needed, Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13013 [copy update] WD-4596 add download datasheet button
  templates/data/mongodb/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13020 Update lxd link in meganav
  static/js/src/navigation.js
Labels: Review: QA +1, Review: Code +1

#12996 Update visuals for /credentials/shop/manage
  static/js/src/advantage/credentials/components/CredManage/CredManage.tsx
  templates/credentials/shop/index.html
Labels: Review: Design needed, Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13004 WD-4286 certified UX improvements
  navigation.yaml
  redirects.yaml
  templates/certified/desktops.html
  templates/certified/devices.html
  templates/certified/index.html
  templates/certified/laptops.html
  templates/certified/search-results.html
  templates/certified/servers.html
  templates/certified/shared/category-search-results.html
  templates/certified/socs.html
  templates/certified/why-certify.html
  templates/core/features/secure-boot.html
  templates/dell/index.html
  templates/download/iot/intel-iot.html
  templates/download/raspberry-pi/index.html
  templates/internet-of-things/smart-displays.html
  templates/robotics/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13023 Update views.py - fix utm_content field
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13021 WD-4995 - Update webinars on the core page
  templates/core/index.html
Labels: Review: Code +1

#12981 Update /pro/subscribe page
  static/js/src/advantage/subscribe/react/UAPurchase.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
  static/js/src/advantage/subscribe/react/components/Form/Form.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductUser/ProductUser.test.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductUser/ProductUser.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductUser/index.ts
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
  static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Review: PdM +1, Commercial 🛒

#13031 Match Pro Desktop infra with uai-essential-desktop
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
  static/js/src/advantage/subscribe/react/utils/utils.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13005 Build landscape saas form
  templates/landscape/pricing.html
  templates/shared/forms/interactive/landscape-pricing-saas.html
Labels: Review: QA +1, Review: Code +1

#13035 Update the ubuntu-cinnamon flavour link
  templates/templates/navigation-download-h.html
Labels: Review: Code +1

#12976 Refresh /ceph/install
  templates/ceph/install.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#12969 WD-3695: Data docs
  konf/site.yaml
  navigation.yaml
  templates/core/index.html
  templates/data/docs/document.html
  templates/data/docs/kafka/iaas/document.html
  templates/data/docs/kafka/iaas/search-results.html
  templates/data/docs/kafka/k8s/document.html
  templates/data/docs/kafka/k8s/search-results.html
  templates/data/docs/mongodb/iaas/document.html
  templates/data/docs/mongodb/iaas/search-results.html
  templates/data/docs/mongodb/k8s/document.html
  templates/data/docs/mongodb/k8s/search-results.html
  templates/data/docs/mysql/iaas/document.html
  templates/data/docs/mysql/iaas/search-results.html
  templates/data/docs/mysql/k8s/document.html
  templates/data/docs/mysql/k8s/search-results.html
  templates/data/docs/opensearch/iaas/document.html
  templates/data/docs/opensearch/iaas/search-results.html
  templates/data/docs/postgresql/iaas/document.html
  templates/data/docs/postgresql/iaas/search-results.html
  templates/data/docs/postgresql/k8s/document.html
  templates/data/docs/postgresql/k8s/search-results.html
  templates/data/docs/spark/k8s/document.html
  templates/data/docs/spark/k8s/search-results.html
  templates/data/kafka/index.html
  templates/data/spark/index.html
  templates/download/desktop/index.html
  templates/landscape/index.html
  templates/nvidia/index.html
  templates/templates/docs/shared/_docs.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13006 Adjust footer size on small screens
  static/sass/_pattern_footer.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#12971 Create Marketo lead if it doesn't exist
  webapp/marketo.py
Labels: Review: Code +1, Commercial 🛒

#12870 /download/risc-v redesign
  static/js/src/risc-v.js
  static/sass/styles.scss
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
  templates/download/risc-v/tab-7.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13042 [copy update] WD-5110 Update on `/lxd`
  templates/lxd/index.html
Labels: Review: QA +1, Review: Code +1

#13037 WD-5114 - Update the legal addresses across the site
  templates/contact-us/index.html
  templates/legal/anbox-cloud-privacy-notice.html
  templates/legal/data-privacy/contact.md
  templates/legal/data-privacy/esxi.md
  templates/legal/data-privacy/events.md
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/newsletter.md
  templates/legal/data-privacy/online-competitions.md
  templates/legal/data-privacy/online-purchase.md
  templates/legal/data-privacy/partner-portal.md
  templates/legal/data-privacy/recruitment.html
  templates/legal/data-privacy/snap-store.md
  templates/legal/data-privacy/snapcraft-nps.md
  templates/legal/data-privacy/sso.md
  templates/legal/data-privacy/survey.md
  templates/legal/data-privacy/unilateral-nda.md
  templates/legal/data-privacy/user-survey.md
  templates/legal/data-privacy/webinar.md
  templates/legal/livepatch-terms-of-service.html
  templates/legal/motd.html
  templates/legal/systems-information-notice.html
Labels: Review: Code +1 (with changes)

#13039 WD-5128 - Build the ai/roadshow page
  navigation.yaml
  templates/ai/roadshow.html
  templates/dell/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13045 Remove instant provisioning for exams
  templates/credentials/provision.html
  templates/credentials/schedule.html
  webapp/app.py
  webapp/shop/cred/views.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#13043 Generate sitemaps and fix robots.txt path for analytics
  redirects.yaml
  robots.txt
  static/files/robots.txt
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1

#13048 Remove silicon page and custom styles, add redirect
  redirects.yaml
  static/sass/styles.scss
  templates/silicon/base_silicon.html
  templates/silicon/index.html
Labels: Review: QA +1, Review: Code +1

#13050 Update copy on /openstack/consulting
  templates/openstack/consulting.html
Labels: Review: QA +1, Review: Code +1

#13049 Update copy on /download/iot/intel-iot
  static/sass/styles.scss
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13053 Update desktop to server on tab 3 of /download/amd-xilinx
  templates/download/amd-xilinx/tab-3.html
Labels: Review: QA +1, Review: Code +1

#12988 WD-3904-credentials-schedule
  static/sass/styles.scss
  templates/credentials/schedule.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Commercial 🛒

#12868 Cred customer purchasing
  static/js/src/advantage/credentials/app.tsx
  static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
  static/js/src/advantage/credentials/components/CredExamShop/index.tsx
  static/js/src/advantage/credentials/components/CredKeyShop/CredKeyShop.tsx
  static/js/src/advantage/credentials/components/CredKeyShop/index.tsx
  static/js/src/advantage/credentials/components/CredPurchaseConfirmation/CredPurchaseConfirmation.tsx
  static/js/src/advantage/credentials/components/CredPurchaseConfirmation/index.tsx
  static/js/src/advantage/credentials/components/CredShop/CredShop.tsx
  static/js/src/advantage/credentials/components/CredShop/index.tsx
  static/js/src/advantage/credentials/components/CredWebhookResponses/CredWebhookResponses.tsx
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/ConfirmAndBuy/ConfirmAndBuy.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  static/sass/_pattern_card.scss
  static/sass/_pattern_shop-cart.scss
  templates/credentials/index.html
  templates/credentials/shop/index.html
  webapp/shop/cred/views.py
Labels: Review: Code needed, Review: UX needed, Don't merge, Commercial 🛒

#13052 [copy update] WD-4341 revamp on `/ceph`
  templates/ceph/index.html
  templates/shared/_resources_ceph.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13055 [copy update] WD-5191 Update on `/nvidia`
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1

#13051 Update /certified paths to favor pretty links
  redirects.yaml
  tests/cassettes/TestCertification.test_search_results.yaml
  tests/test_certification.py
  webapp/app.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13057 Revert "Generate sitemaps and fix robots.txt path for analytics"
  redirects.yaml
  robots.txt
  static/files/robots.txt
  webapp/app.py
  webapp/views.py
Labels: Review: Code +1
