Repository canonical/ubuntu.com, pull requests merged in 2023-08, with the labels that each got.

#13059 [copy update] WD-5355 Update /hpe contact form
  templates/shared/forms/interactive/hpe.html
Labels: Review: QA +1, Review: Code +1

#13054 Update /legal/data-privacy/newsletter
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/newsletter.md
  templates/legal/data-privacy/online-competitions.md
Labels: Review: QA +1, Review: Code +1

#13060 Fix the errors reported from the live linkchecker
  .github/workflows/live-links.yaml
  templates/cloud/private-cloud.html
Labels: Review: Code +1

#13056 WD-5354 Fix hpe links
  templates/hpe/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13064 Redirect /engage/multi-cloud-guide to /engage/a-business-guide-to-cloud-migration
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13065 Change product name
  templates/security/cve/_cve-table.html
  templates/security/cve/cve.html
Labels: Review: Code +1

#13069 Update link name on /legal/data-privacy
  templates/engage/shared/_de_engage_form.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_engage_form.html
  templates/engage/shared/_it_engage_form.html
  templates/engage/shared/_pt_engage_form.html
  templates/engage/shared/_ru_engage_form.html
  templates/engage/shared/_zh-TW_engage_form.html
  templates/legal/data-privacy/index.html
Labels: Review: QA +1, Review: Code +1

#13070 [copy update] WD-5374 remove ceph install link
  templates/ceph/index.html
Labels: Review: QA +1, Review: Code +1

#12918 Build activate page to redeem activation key for OEM store
  build.js
  navigation.yaml
  static/js/src/activate.js
  templates/pro/activate.html
  webapp/app.py
  webapp/shop/advantage/views.py
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes), Commercial 🛒

#13074 [copy update] WD-5338 Fix OpenStack release naming convention
  static/js/src/chart-data.js
  templates/about/openstack-release-cycle.html
  templates/about/release_cycles/microstack-eol.html
  templates/about/release_cycles/openstack-eol.html
Labels: Review: QA +1, Review: Code +1

#13007 Show expiry message for subscriptions activated by keys
  static/js/src/advantage/api/enum.ts
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx
  webapp/shop/api/ua_contracts/builders.py
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes), Commercial 🛒

#13063 Update the /cloud bubbles top-strip CTAs
  templates/cloud/hybrid-cloud.html
  templates/cloud/multi-cloud.html
  templates/openstack/features.html
Labels: Review: QA +1, Review: Code +1

#13073 Update Canonical logo
  templates/ai/what-is-kubeflow.html
  templates/ceph/what-is-ceph.html
  templates/kubernetes/what-is-kubernetes.html
  templates/openstack/compare.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13026 Remove totalPrice from Formik form values
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useCalculate.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
  static/js/src/advantage/subscribe/checkout/utils/types.ts
Labels: Review: Code needed, Commercial 🛒

#13066 Update /pro meta
  templates/pro/index.html
Labels: Review: Code +1

#13067 Remove Support from navigation
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#12992 Fix purchasing after cancelling
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useFinishPurchase.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
  templates/account/invoices/index.html
Labels: Review: QA +1, Review: Code +1

#13082 [copy update] WD-5479 update eurotech logo
  templates/certified/shared/_partners.html
  templates/industrial/index.html
Labels: Review: QA +1, Review: Code +1

#13072 Update download Ubuntu Desktop page
  templates/download/desktop/thank-you.html
Labels: Review: QA +1, Review: Code +1

#13084 Update contributors agreement form US states dropdown
  templates/legal/contributors/agreement.html
Labels: Review: QA +1, Review: Code +1

#13086 Is expiring closed/done Renewal bug fix
  webapp/shop/api/ua_contracts/helpers.py
Labels: Review: Code +1

#13077 Improve not renewed label logic
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Labels: Review: Code +1

#13076 Change cost to use currect number of machines
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/utils/getSubscriptionCost.test.ts
  static/js/src/advantage/react/utils/getSubscriptionCost.ts
  static/js/src/advantage/react/utils/index.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13085 WD-5748 - Replace the Canonical author avatar with the COF
  templates/blog/author.html
Labels: Review: QA +1, Review: Code +1

#13094 Update the Canonical avatar on the article page
  templates/blog/article.html
Labels: Review: QA +1, Review: Code +1

#13095 Update sitemap_index.xml to include robotics sitemap
  templates/sitemap_index.xml
Labels: Review: QA +1, Review: Code +1

#13096 Update 'Upgrade Ubuntu LTS' title and blog link
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1

#13097 Redirect for Ubuntu fan package doc URL
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13100 Update datasheet on /pricing/desktop & /desktop/organisations
  templates/desktop/organisations.html
  templates/pricing/desktop.html
Labels: Review: QA +1, Review: Code +1

#13101 [copy update] WD-5827 Update on /18-04/azure
  templates/18-04/azure.html
Labels: Review: QA +1, Review: Code +1

#13105 k8s docs 1.28 errata
  templates/kubernetes/docs/1.28/release-notes.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA +1, Review: Code +1

#13107 [WD-5943] Added beta message to credentials index page
  templates/credentials/index.html
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13111 WD-5961 - Fix the engage sitemap date format
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13118 Pro subscribe - Version section fixes
  static/js/src/advantage/subscribe/react/components/Form/Form.tsx
  static/js/src/advantage/subscribe/react/utils/FormContext.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13124 Update survery link on /openstack/install
  templates/openstack/install.html
Labels: Review: QA +1, Review: Code +1

#13119 Pro contact form number of machines field
  templates/shared/_pro-contact-us-form.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13121 [copy update] /18-04/azure
  templates/18-04/azure.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13103 WD-4158 Revamp amdxilinx
  static/js/src/risc-v.js
  static/js/src/tabbed-content.js
  static/sass/styles.scss
  templates/download/amd-xilinx/index.html
  templates/download/amd-xilinx/tab-1.html
  templates/download/amd-xilinx/tab-2.html
  templates/download/amd-xilinx/tab-3.html
  templates/download/risc-v/index.html
Labels: Review: QA +1, Review: Code +1 (with changes), Review: PdM +1

#13089 Fix acquisition URLs for jp/cn.ubuntu.com
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1

#13036 WD-4643 - RFQ: Build of the automotive buyers guide
  static/sass/styles.scss
  templates/automotive/_chassis_animation.html
  templates/automotive/buyers-guide/_form.html
  templates/automotive/buyers-guide/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)
