Repository canonical/ubuntu.com, pull requests merged in 2023-03, with the labels that each got.

#12623 WD-1730 replace illustrations with new logo in `/automotive`
  templates/automotive/index.html
Labels: Review: QA +1, Review: Code +1

#12626 Update copy for /credentials.
  templates/credentials/index.html
  templates/credentials/syllabus.html
Labels: Review: QA +1, Commercial 🛒

#12605 Capture referrer during a shop purchase
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12630 Update logos on /server
  static/sass/_pattern_heading-icon.scss
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#12618 WD-1708 replaces Canonical OpenStack, Kubernetes and Ceph logos in `/managed`
  static/sass/styles.scss
  templates/managed/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12633 Correct price of managed ceph on bare metal.
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12631 K8s link fixes and version bumps
  templates/kubernetes/docs/1.25/release-notes.md
  templates/kubernetes/docs/1.26/release-notes.md
  templates/kubernetes/docs/cni-calico.md
  templates/kubernetes/docs/logging.md
  templates/kubernetes/docs/release-notes-historic.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/security.md
  templates/kubernetes/docs/tigera-secure-ee.md
Labels: Review: QA +1, Review: Code +1

#12620 WD-2205 Kubeflow 1.7 beta banner
  templates/ai/index.html
  templates/ai/services.html
  templates/ai/what-is-kubeflow.html
  templates/shared/_charmed-kubeflow-beta-banner.html
  tests/test_context.py
  webapp/app.py
  webapp/context.py
Labels: Review: QA +1, Review: Code +1

#12612 Create mediatek contact-us form
  static/js/src/static-forms.js
  templates/download/mediatek/contact-us.html
  templates/embedding/index.html
  templates/security/fips/beta/contact-us.html
  templates/shared/_credentials-contact-us-form.html
  templates/shared/_pro-contact-us-form.html
  templates/shared/_security-fips.html
Labels: Review: QA +1, Review: Code +1

#12636 WD-2360 copy update
  templates/kubernetes/kubernetes-operations-survey.html
Labels: Review: QA +1, Review: Code +1

#12635 WD-2408 Ubuntu and Bluefield description update
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1

#12634 WD-2362 Redirect engage page
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12610 Update logos on /appliance/vm
  templates/appliance/vm.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12622 WD-2337 Update /landscape page
  templates/landscape/index.html
Labels: Review: QA +1, Review: Code +1

#12644 Update logos on /appliance
  templates/appliance/index.html
Labels: Review: QA +1, Review: Code +1

#12639 Update logos on /raspberry-pi/server
  templates/raspberry-pi/server.html
Labels: Review: QA +1, Review: Code +1

#12598 WD-1315 Cloud-computing page
  navigation.yaml
  static/sass/styles.scss
  templates/cloud/cloud-computing.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#12646 Update copy on /landscape/install
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1

#12645 Update logos on /pricing/devices
  templates/pricing/devices.html
Labels: Review: QA +1, Review: Code +1

#12648 Update copy on /edge-computing
  templates/edge-computing/index.html
Labels: Review: QA +1, Review: Code +1

#12611 WD-1347 Add new Polarfire Risc-v tab
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12641 WD-1721 WD-1720 WD-1722 Replace logos for /core pages
  templates/core/features/index.html
  templates/core/index.html
  templates/core/services/index.html
Labels: Review: QA +1

#12643 Add blog slug renames redirects
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#12628 Add buffer to summery price recalculation
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.test.tsx
  static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useCalculate.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useCalculateTaxes.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useGetTaxAmount.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  static/js/src/advantage/subscribe/react/hooks/usePreview.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12619 WD-2344 - Add real-time contact form
  static/js/src/static-forms.js
  templates/kernel/real-time/contact-us.html
Labels: Review: QA +1, Review: Code +1

#12650 WD-1710 `/desktop/organisations` logo replacements
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12535 Revamp dell partners page
  package.json
  static/sass/_pattern_dell.scss
  static/sass/styles.scss
  templates/dell/index.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12658 WD-1709 `/download/desktop` logo updates
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#12614 Display offer discount on checkout
  static/js/src/advantage/offers/components/Offer/Offer.test.tsx
  static/js/src/advantage/offers/components/Offer/Offer.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12656 fix for peer score coming as string
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12662 Check if tab content contains an D3 chart and trigger resize event if yes
  static/js/src/tabotronic.js
Labels: Review: QA +1, Review: Code +1

#12668 WD-2510 GCP copy update
  templates/gcp/pro.html
Labels: Review: QA +1, Review: Code +1

#12661 WD-1319 German OpenStack page
  templates/engage/de_why-openstack.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#12489 WD-2132 Update the content of the ROS ESM page content
  static/sass/_pattern_card.scss
  static/sass/_pattern_contextual-footer.scss
  static/sass/styles.scss
  templates/pro/index.html
  templates/robotics/ros-esm.html
  templates/robotics/shared/_learn-more-about-robotics.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: PdM +1

#12595 WD-2048 create silicon partners page
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  templates/silicon/base_silicon.html
  templates/silicon/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#12670 Update copy on /landscape/pricing
  templates/contact-us/form/index.html
  templates/landscape/pricing.html
Labels: Review: QA +1, Review: Code +1

#12666 Update advantage to pro in footers
  templates/shared/contextual_footers/_download_cloud_ubuntu_advantage.html
  templates/shared/contextual_footers/_server_contact_us.html
  templates/shared/contextual_footers/_support.html
  templates/shared/forms/_desktop_ua-shop.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12654 Disable buy button when user info is edit mode
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
  static/js/src/advantage/subscribe/checkout/utils/types.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12659 Fix country-code dropdown not overlapping fieldsets
  static/sass/styles.scss
Labels: Review: QA +1, Review: Code +1

#12678 Add meta lang block in jinja2 templates
  templates/engage/de_why-openstack.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#12683 Fix bug when parsing first name and last name from Ubuntu One account
  webapp/shop/cred/views.py
  webapp/shop/utils.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12528 Make select boxes with on change affects accessible
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1, Review: A11y +1

#12673 activation keys list is empty in /credentials/shop/manage
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#12687 Update logos on /kubernetes/managed
  templates/kubernetes/managed.html
Labels: Review: QA +1, Review: Code +1

#12689 Update modern slavery statement to 2023
  templates/legal/modern-slavery-statement/_base_markdown.html
  templates/legal/modern-slavery-statement/index.md
Labels: Review: QA +1, Review: Code +1

#12686 Push shop in maintenanace
  konf/site.yaml
  templates/account/maintenance-check.html
  templates/account/status.html
  templates/advantage/index.html
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/api/ua_contracts/helpers.py
  webapp/shop/decorators.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12693 Fix pro env
  konf/site.yaml
Labels: Review: Code +1, Commercial 🛒

#12680 UI tweaks for Credentials
  templates/credentials/index.html
  templates/credentials/redeem.html
  templates/credentials/self-study.html
  webapp/shop/cred/syllabus.json
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12695 Schedule shop for maintenance
  konf/site.yaml
  webapp/shop/decorators.py
Labels: Review: Code +1, Commercial 🛒

#12653 Change machine number for renewals
  static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  tests/shop/advantage/helpers.py
  tests/shop/advantage/test_parsers.py
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/primitives.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12684 Use retry endpoint
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/hooks/usePendingRenewal.ts
  static/js/src/advantage/subscribe/checkout/app.tsx
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/hooks/useFinishPurchase.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePollPurchaseStatus.tsx
  static/js/src/advantage/subscribe/react/hooks/usePendingPurchase.tsx
  static/js/src/ua-payment-methods.js
  tests/cypress/integration/pro/checkout_spec.js
  tests/shop/advantage/test_api.py
  webapp/app.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12699 Create nvida jetson and ubuntu announcment page
  templates/legal/nvidia-jetson-and-ubuntu.html
Labels: Review: QA +1, Review: Code +1

#12700 Update /nvidia/contact-us based on copy changes
  templates/internet-of-things/nvidia/contact-us.html
Labels: Review: QA +1, Review: Code +1

#12679 Update logos within the /cloud bubble
  templates/cloud/hybrid-cloud.html
  templates/cloud/public-cloud.html
Labels: Review: QA +1, Review: Code +1

#12703 Add community dicourse page and link to privacy policy
  templates/legal/data-privacy/community-discourse.md
  templates/legal/data-privacy/index.html
Labels: Review: QA +1, Review: Code +1

#12702 Update logos on /cloud/hybrid-cloud
  templates/cloud/hybrid-cloud.html
Labels: Review: QA +1, Review: Code +1

#12710 Update meta_copydoc on /pro
  templates/pro/index.html
Labels: Review: QA +1

#12712 WD-2345 - Add banner for GA real time kernel
  templates/core/index.html
  templates/embedded/index.html
  templates/internet-of-things/index.html
  templates/robotics/index.html
  templates/shared/_rt-kernel-beta-banner.html
  templates/shared/_rt-kernel-ga-banner.html
  templates/telco/index.html
Labels: Review: QA +1, Review: Code +1

#12701 Update copy on /landscape
  templates/landscape/index.html
Labels: Review: QA +1, Review: Code +1

#12717 Pro pricing: Change "No support" text to "Self-Support"
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12711 WD-2765 Build the 18-04 out of service page
  navigation.yaml
  redirects.yaml
  templates/18-04/_release-chart-1604.html
  templates/18-04/base_18-04.html
  templates/18-04/index.html
Labels: Review: QA +1, Review: Code +1

#12530 Community member no of machines
  requirements.txt
  webapp/login.py
  webapp/shop/advantage/views.py
  webapp/shop/api/ua_contracts/advantage_mapper.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12719 WD-1490 Add contact number for South Korea
  templates/shared/_call-sales-long.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12721 [copy update] /openstack/features
  templates/openstack/features.html
Labels: Review: QA +1, Review: Code +1

#12720 /certified/why-certify - Update logo list
  templates/certified/shared/_partners.html
Labels: Review: QA +1, Review: Code +1

#12726 Marketo form ID fix - Update index.html
  templates/nvidia/index.html
Labels: Review: Code +1

#12731 update dummy cypress account credentials
  .github/workflows/cypress-pr.yaml
Labels: Review: Code needed

#12690 Enable form validation with Buy button
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/ConfirmAndBuy/ConfirmAndBuy.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/sass/_pattern_checkout.scss
  tests/cypress/integration/pro/checkout_spec.js
  tests/cypress/support/commands.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#12725 Update visuals for Credentials
  templates/credentials/index.html
  templates/credentials/syllabus.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Commercial 🛒

#12722 [copy update] /openstack/what-is-openstack
  templates/openstack/what-is-openstack.html
  templates/shared/contextual_footers/_openstack-detailed-documentation.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#12732 Reorder logos
  templates/certified/shared/_partners.html
Labels: Review: QA +1, Review: Code +1
