Repository canonical/ubuntu.com, pull requests merged in 2023-11, with the labels that each got.

#13218 Wd 6605 verify credly works and replace the api keys and org id in kubernetes secrets
  .env
  konf/site.yaml
  static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
  webapp/shop/api/credly/api.py
  webapp/shop/cred/views.py
Labels: Review: QA needed, Review: Code needed, 🧊 CUBE, Commercial 🛒

#13321 Call google APIs over HTTP on credentials pods
  konf/site.yaml
Labels: Review: Code needed

#13322 Update aws pro links
  templates/aws/shared/_get_pro.html
Labels: Review: QA +1, Review: Code +1

#13323 Update FIPS title and webinar link
  templates/security/fips.html
Labels: Review: QA +1, Review: Code +1

#13088 WD-4664 Certified filters
  .eslintrc.js
  static/js/src/certified-search-results.js
  static/js/src/tests/intlTelInput.test.js
  templates/certified/search-results.html
  templates/certified/shared/_category-filters.html
  templates/certified/shared/category-search-results.html
  templates/certified/vendors/vendor.html
  tests/cassettes/TestCertification.test_filters_json.yaml
  tests/test_certification.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#13244 fix: shorten form acquisition URLs - WD-6294
  tests/test_views.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: Marketing +1

#13325 Add loading state to modal form buttons
  static/js/src/dynamic-forms.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#13319 Update link on homepage
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#13329 Add environment variable to control confidentiality agreement display
  .env
  konf/site.yaml
  webapp/shop/cred/views.py
Labels: Review: QA needed, Review: Code needed

#13330 WD-7093 - change asset in /download/amd
  templates/download/amd/tab-2.html
Labels: Review: QA +1, Review: Code +1

#13223 K8s update HA page
  templates/kubernetes/docs/autoscaler.md
  templates/kubernetes/docs/high-availability.md
Labels: Review: Code +1

#13267 K8s docs - Add backups strategy page
  templates/kubernetes/docs/explain-backups.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: QA +1, Review: Code +1

#13271 K8s docs - Add contributing page and links
  templates/kubernetes/docs/get-in-touch.md
  templates/kubernetes/docs/how-to-contribute.md
  templates/kubernetes/docs/shared/_side-navigation.md
Labels: Review: QA +1, Review: Code +1

#13331 K8s link fixes
  templates/kubernetes/docs/1.21/upgrading.md
  templates/kubernetes/docs/index.md
Labels: Review: QA needed, Review: Code needed

#13335 Remove dead link to jaas.ai/experts
  templates/templates/navigation-enterprise-h.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1

#13327 [WD-7080] add Mediatek to supported platforms on IoT page
  requirements.txt
  templates/download/iot/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13337 WD-7158 - update link on /consulting
  templates/pricing/consulting.html
Labels: Review: QA +1, Review: Code +1

#13338 Kubernetes 1.28+ck2 updates
  templates/kubernetes/docs/1.28/release-notes.md
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA needed, Review: Code +1

#13341 add rebase command to GH actions
  .github/workflows/rebase.yaml
Labels: Review: Code +1

#13342 [WD-7080] squeeze Mediatek logo a bit
  templates/download/iot/index.html
Labels: Review: QA +1, Review: Code +1

#13276 Build /automotive/resources page
  navigation.yaml
  package.json
  templates/automotive/resources.html
  templates/shared/forms/interactive/newsletter-opt-in.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13344 [WD-7202] remove support phone numbers
  templates/contact-us/index.html
  templates/shared/_cloud-contact-us-form.html
  templates/shared/_pro-contact-us-form.html
Labels: Review: QA +1, Review: Code +1

#13346 [WD-7085] add VWO smartcode script to base template's head
  templates/templates/_vwo_smartcode.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#13347 [WD-7314] add a redirect from a blog post to another page
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13292 WD-6863 - update get in touch form
  templates/shared/forms/interactive/storage.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13349 Add partner permission checkbox to engage pages
  templates/engage/shared/_en_engage_form.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1, Review: Marketing +1, Review: PdM +1

#13350 Apply /containers refresh
  templates/containers/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13275 Update pro contact form
  templates/shared/_pro-contact-us-form.html
Labels: Review: QA +1, Review: Code +1

#13345 Update logos on AI page
  templates/ai/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#13353 WD-6807 - update /thank-you page, banner issue
  static/sass/styles.scss
  templates/download/desktop/thank-you.html
  templates/templates/_tag_manager.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13356 [WD-6717] order partner logos according to copy doc in /cloud/public-cloud
  templates/cloud/public-cloud.html
  templates/shared/_partner-logos.html
  webapp/context.py
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1

#13358 [WD-6717] remove one link and replace another one according to copy doc
  templates/cloud/public-cloud.html
Labels: Review: QA +1, Review: Code +1

#13351 WD-7403 - Add the version of the server download GA event label
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Code +1

#13361 Fix notice prefix error
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#13363 WD-7467 - update aws link for cloud download
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Review: QA +1, Review: Code +1

#13368 [WD-7240] remove page for EdgeX IoT and redirect to landing IoT
  navigation.yaml
  redirects.yaml
  templates/internet-of-things/edgex.html
Labels: Review: QA +1, Review: Code +1

#13370 When multiple forms are present in a page, update the UTMs based on which form is opened
  static/js/src/dynamic-forms.js
  templates/shared/contextual_footers/_download_iot_iotg_newsletter.html
Labels: Review: QA +1, Review: Code +1

#13371 [WD-7552] make the checkbox on Thank You page mandatory to comply with GDPR
  templates/download/desktop/thank-you.html
Labels: Review: QA needed, Review: Code needed

#13372 [WD-7240] redirect EdgeX tutorial page to the IoT landing page
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13373 WD-7575 - update contact us link on iot smart displays
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: Code +1

#13369 [WD-7442] update chart and table of Ubuntu releases on /about page
  static/js/src/chart-data.js
  static/js/src/release-chart.js
  templates/about/release_cycles/releases-table.html
  templates/about/release_cycles/ubuntu-eol.html
  templates/about/release_cycles/ubuntu-small-eol.html
Labels: Review: QA +1, Review: Code +1

#13359 WD-7205 - enrich /real-time page with images
  templates/real-time/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1
