Repository canonical/ubuntu.com, pull requests merged in 2024-06, with the labels that each got.

#13881 Add CRA banners to security and certs pages
  templates/security/certifications.html
  templates/security/index.html
  templates/shared/_cra-banner.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13799 Block channel user from accessing regular pro shop
  templates/account/forbidden.html
  webapp/shop/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13873 WD-11339 display pre selected items
  static/js/src/advantage/distributor/DistributorShop.tsx
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/DealRegistration.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/DistributorShopSummary.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
  static/js/src/advantage/distributor/components/InitiateButton/InitiateButton.tsx
  static/js/src/advantage/distributor/utils/FormContext.tsx
  static/js/src/advantage/distributor/utils/utils.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13874 WD-10616 Build /pro/distributor/order page view
  static/js/src/advantage/distributor/Order.tsx
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.tsx
  static/js/src/advantage/distributor/components/DistributorBuyButton/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
  static/js/src/advantage/distributor/components/Order/OrderDetail/OrderDetail.tsx
  static/js/src/advantage/distributor/components/Order/OrderDetail/index.ts
  static/js/src/advantage/distributor/components/Order/OrderSummary/OrderSummary.tsx
  static/js/src/advantage/distributor/components/Order/OrderSummary/index.ts
  static/js/src/advantage/distributor/utils/FormContext.tsx
  static/js/src/advantage/distributor/utils/utils.ts
  static/sass/_pattern_distributor.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13916 Core 24 final copy updates
  templates/core/features/index.html
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13914 WD-11786 - fix chexboxes on newsletter form
  templates/shared/_download-newsletter.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13847 Core 24 release copy updates
  releases.yaml
  static/sass/styles.scss
  templates/download/core/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13810 Show plus sign when maximum tracking is reached
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/js/src/advantage/tests/factories/api.ts
  webapp/shop/api/ua_contracts/builders.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
  webapp/shop/api/ua_contracts/primitives.py
Labels: Don't merge, Commercial 🛒

#13899 Switch from ip to tz for takeovers.
  templates/base_index.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13922 Update kernel release diagram
  templates/about/release_cycles/kernel-eol.html
  templates/shared/_kernel-release-diagram.html
  templates/shared/_kernel-support-schedule.html
Labels: Review: QA +1, Review: Code +1

#13927 WD-11910-copy-changes-for-embedding
  templates/embedding/index.html
Labels: Review: QA +1, Review: Code needed, Review: UX +1

#13924 Update AWS links
  templates/aws/index.html
  templates/aws/pro.html
  templates/aws/shared/_get_pro.html
Labels: Review: QA +1, Review: Code +1

#13298 Add discourse url to engage page
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1

#13932 Fix video on charmed k8s
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1

#13935 WD-11786 - different language answers in desktop download form
  templates/shared/_download-newsletter.html
Labels: Review: QA +1, Review: Code +1

#13942 WD-10438 copy updates
  redirects.yaml
  templates/download/intel-nuc-desktop.html
  templates/download/iot/installation-media.html
Labels: Review: QA +1, Review: Code +1

#13946 chore: Bump cookie-policy to v3.6.4
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#13936 WD-11393 - remove sales numbers
  templates/contact-us/index.html
  templates/download/server/s390x.html
  templates/hpc/_hpc-contact-us-form.html
  templates/openstack/contact-us.html
  templates/pricing/pro.html
  templates/shared/_call-sales-long.html
  templates/shared/_call-sales.html
  templates/shared/_cloud-contact-us-form-german.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13931 WD-8332 Dev - Rebrand /containers/what-are-containers
  templates/containers/what-are-containers.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13952 WD-12132-create-decorator-to-restrict-views
  templates/credentials/dashboard.html
  webapp/app.py
  webapp/login.py
  webapp/shop/api/trueability/api.py
  webapp/shop/cred/views.py
  webapp/shop/decorators.py
Labels: Review: QA needed, Review: Code needed, 🧊 CUBE, Commercial 🛒

#13948 Security copy updates
  redirects.yaml
  templates/aws/index.html
  templates/security/contact-us.html
  templates/shared/_thank_you.html
  templates/support/thank-you.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13954 GROWENG-3818 changing legacy google analytics event to datalayer push
  static/js/src/dynamic-forms.js
  static/js/src/kernel-form.js
Labels: Review: Code +1

#13962 Fix missing phone field on marketo submission
  static/js/src/prepare-form-inputs.js
Labels: Review: QA +1, Review: Code +1

#13968 Route /security/notices.json into a separate service.
  konf/site.yaml
Labels: Review: Code +1

#13965 bug: Move GADownloadImpressionsEvents trigger on /download/server from thank-you page to download page
  templates/download/server/manual.html
  templates/download/server/thank-you.html
Labels: Review: QA +1, Review: Code +1

#13969 add information about formatting and linting to HACKING.MD
  HACKING.md
Labels: Review: Code +1

#13971 /aws fix Ubuntu version typo
  templates/aws/index.html
Labels: Review: QA +1, Review: Code +1

#13955 Landing page redesign feedback
  package.json
  static/sass/_pattern_footer.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/hpe/index.html
  templates/shared/_latest_news_strip.html
  templates/templates/_footer_item.html
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/templates/footer.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13949 Update install ubuntu on AMD with open-source section
  templates/download/amd/tab-1.html
Labels: Review: QA +1, Review: Code +1, Review: PdM +1

#13923 Implement CVE detailed search
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-card.html
  templates/security/cve/_cve-search-results.html
  templates/security/cve/_cve-table.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13991 feat: Add new sections to '/containers/chiselled'
  templates/containers/chiselled/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13992 Reinstate notice order param
  webapp/security/api.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#13950 WD-12033 - Update the Suru across the credentials bubble
  templates/credentials/assessments.html
  templates/credentials/base_cred.html
  templates/credentials/base_exam.html
  templates/credentials/beta-activation.html
  templates/credentials/exam-no-agreement.html
  templates/credentials/exam.html
  templates/credentials/exit-survey.html
  templates/credentials/faq.html
  templates/credentials/index.html
  templates/credentials/redeem.html
  templates/credentials/redeem_with_captcha.html
  templates/credentials/redeem_with_form.html
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  templates/credentials/self-study.html
  templates/credentials/shop/index.html
  templates/credentials/shop/thank-you.html
  templates/credentials/shop/webhook_responses.html
  templates/credentials/sign-up.html
  templates/credentials/syllabus.html
  templates/credentials/thank-you.html
  templates/credentials/your-badges.html
  templates/credentials/your-exams.html
  templates/shared/_credentials-contact-us-form.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13986 Update /download/raspberry-pi copy and Core 24 checksums
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#13977 Wd 12322 modify credentials shop to use the new products and coupons
  static/js/src/advantage/subscribe/checkout/app.tsx
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  templates/credentials/redeem_with_form.html
  templates/credentials/shop/index.html
  webapp/app.py
  webapp/shop/advantage/views.py
  webapp/shop/api/credly/api.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/schema.py
  webapp/shop/cred/exams.json
  webapp/shop/cred/views.py
  webapp/shop/schemas.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#13893 CVE search results clean-up
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-landing.html
  templates/security/cve/_cve-search-results.html
  templates/security/cve/_cve-search.html
  templates/security/cve/_status-fields.html
  templates/security/cve/_version-and-status-row.html
  templates/security/cve/filters/release-filter.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13985 Copy update - /openstack/tutorials
  templates/openstack/tutorials.html
Labels: Review: QA +1, Review: Code +1

#14000 Fix missing timezone errors
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14004 Fix CVE detailed view bug
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-table.html
Labels: Review: QA +1, Review: Code +1

#14005 Update homepage notification banner
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14006 bug: Fix broken link on '/download/server/arm
  templates/download/server/arm.html
Labels: Review: QA +1, Review: Code +1

#14007 chore: Update copy on '/kernel/lifecycle'
  templates/kernel/lifecycle.html
Labels: Review: QA +1, Review: Code +1
