Repository canonical/ubuntu.com, pull requests merged in 2024-09, with the labels that each got.

#14231 WD-12751 - rebrand /core/features/secure-boot
  templates/core/features/secure-boot.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14237 WD-12745 - rebrand /core/features/ota-updates
  templates/core/features/ota-updates.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14250 copy update: Update /download/risc-v download link
  templates/download/risc-v/qemu-emulator.html
Labels: Review: QA +1, Review: Code +1

#14246 Reinstate related engage pages
  templates/engage/base.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#14260 Update engage page section name
  templates/engage/base.html
Labels: Review: QA +1

#14216 chore: Update to use dynamic fonts and don't preload fonts
  templates/templates/base.html
Labels: Review: QA needed, Review: Code +1

#14256 Remove stale link at /community/community-support
  templates/support/community-support.html
Labels: Review: QA +1, Review: Code +1

#14254 WD-14397: add copy-to-clipboard to /pro/dashboard token
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
  static/sass/_pattern_subscriptions.scss
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#14252 Add optional CTA button for engage pages
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1

#14257 Add invoice menu in the navigation
  navigation.yaml
  webapp/app.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14259 Include comments message in payload
  static/js/src/dynamic-forms.js
  templates/shared/forms/interactive/ai.html
  templates/shared/forms/interactive/kafka.html
Labels: Review: QA +1, Review: Code +1

#14264 Remove preview call from the purchase hook
  static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14258 Add PO number in the checkout
  static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
  static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/AdditionalNotes/AdditionalNotes.tsx
  static/js/src/advantage/subscribe/checkout/components/AdditionalNotes/index.ts
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  static/sass/_pattern_checkout.scss
Labels: Review: QA +1, Review: Code needed, Commercial 🛒

#14253 Fix /real-time dynamic forms
  static/js/src/dynamic-forms.js
  templates/shared/forms/interactive/real-time.html
Labels: Review: QA +1, Review: Code +1

#14215 WD-13861 - create a function for form execution
  static/files/forms-data.json
  static/js/src/dynamic-forms.js
  static/js/src/static-forms.js
  templates/base_index.html
  templates/shared/forms/_country.html
  templates/shared/forms/form-fields.html
  templates/shared/forms/form-template.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14273 [WD-14757] Prevent user navigation on checkout page
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/utils/helpers.ts
Labels: Review: QA needed, Review: Code needed

#14277 refactor: Rename openstack chart partial so it doesn't appear as a page
  templates/about/_openstack-release-cycle.html
  templates/engage/de_why-openstack.html
  templates/engage/es_why-openstack.html
  templates/engage/fr_why-openstack.html
  templates/openstack/why-openstack.html
Labels: Review: QA +1, Review: Code +1

#14281 chore: Update datasheet link on '/desktop/organisations'
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#14279 WD-14808 Update the dell logo
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#14285 fix: Show search on search icon click on medium and small screens
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#14280 fix(20years): Add the new page to the sitemap
  static/files/sitemap.xml
Labels: Review: QA +1, Review: Code +1

#14268 Add fallback URL for referrer
  webapp/views.py
Labels: Review: Code +1

#14271 k8s-1.31
  templates/kubernetes/docs/1.31/components.md
  templates/kubernetes/docs/1.31/release-notes.md
  templates/kubernetes/docs/1.31/upgrading.md
  templates/kubernetes/docs/cni-cilium.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/shared/_side-navigation.md
  templates/kubernetes/docs/supported-versions.md
Labels: Review: Code +1

#14291 Prepare for 22.04.5
  releases.yaml
Labels: Review: Code +1

#13412 CVE overhaul
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  static/sass/styles.scss
  templates/certified/search-results.html
  templates/certified/shared/category-search-results.html
  templates/security/cve/_cve-table.html
  templates/security/cve/_pagination.html
  templates/security/cve/_status-fields.html
  templates/security/cve/_version-and-status-row.html
  templates/security/cve/_version-fields.html
  templates/security/cve/cve.html
  templates/security/cve/index.html
  templates/security/cves/_cve-card.html
  templates/security/cves/_cve-filters-sidenav.html
  templates/security/cves/_cve-footer.html
  templates/security/cves/_cve-landing.html
  templates/security/cves/_cve-search-results.html
  templates/security/cves/_cve-search.html
  templates/security/cves/_cve-table.html
  templates/security/cves/_pagination.html
  templates/security/cves/about.html
  templates/security/cves/base_cve.html
  templates/security/cves/cve.html
  templates/security/cves/filters/priority-filter.html
  templates/security/cves/filters/release-filter.html
  templates/security/cves/filters/status-filter.html
  templates/security/cves/index.html
  webapp/security/api.py
  webapp/security/helpers.py
  webapp/security/views.py
Labels: Review: UX +1

#14276 WD-12841 - rebrand /aws/outposts
  templates/aws/outposts.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14266 WD-12843 - rebrand /aws/pro
  templates/aws/pro.html
  templates/aws/shared/_get_pro.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14292 feat: /azure redesign
  templates/azure/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14288 WD-13585 refresh /internet-of-things/management
  static/sass/_pattern_matrix.scss
  templates/internet-of-things/management.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14286 Copy update: /confidential-computing
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14300 Copy update /desktop/organisations
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#14311 Fix certified.spec.ts failing
  templates/certified/search-results.html
Labels: Review: Code needed

#14303 feat: /gcp rebranding
  templates/gcp/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14302 Make copydoc changes to the Data Science page.
  templates/ai/data-science.html
Labels: Review: QA +1, Review: Code +1

#14290 Update ubuntu.com/download/raspberry-pi with 24.10 download section [WD-14863]
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#14313 WD-14746 - fix account nav item to be aligned
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#14314 chore: Upgrade canonicalwebteam.search to 2.1.1
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14305 WD-14962 - update links on /what-is-kubeflow
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1

#14321 disable button while loading
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
Labels: Review: QA needed, Review: Code needed, 🧊 Credentials, Commercial 🛒

#14320 fix(a11y): Fix broken lang attribute
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#14329 bug: fix missing status description for ignored status and update switch functionality
  templates/security/cves/cve.html
Labels: Review: QA +1, Review: Code +1

#14337 copy update: kernel support
  static/js/src/chart-data.js
  templates/shared/_kernel-release-diagram.html
Labels: Review: QA +1, Review: Code +1

#14336 copy: update /confidential-computing/ai. WD-14731
  templates/confidential-computing/ai.html
Labels: Review: QA +1, Review: Code +1

#14340 feat(openstack): Replace youtube URL with embed
  templates/openstack/what-is-openstack.html
Labels: Review: QA +1, Review: Code +1

#14327 change get to post for schedule api endpoint
  webapp/shop/api/ua_contracts/api.py
Labels: 🧊 Credentials, Commercial 🛒

#14345 WD-15300 ui overlap fix and minor upgrades
  templates/containers/chiselled/dotnet.html
Labels: Review: QA +1, Review: Code +1

#14334 WD-15200 Copy update legal ubuntu pro
  templates/legal/ubuntu-pro/personal/_markdown.html
  templates/legal/ubuntu-pro/personal/index.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#14297 feat: Implement a honeypot field on our main search
  static/js/src/main.js
  static/js/src/search.js
  templates/search.html
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#14330 feat: [WD-15113] Copy update for ubuntu>security>livepatch
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1

#14335 WD-15202-Update-https-ubuntu.com-about-release-cycle
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#14349 WD-14874 Fixed Space Bug
  templates/certified/model-details.html
Labels: Review: QA +1, Review: Code +1

#14352 WD-15253 fix the download cheat sheet
  templates/download/server/download.html
  templates/download/server/thank-you.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14338 Create new Grundium case study
  templates/case-study/base_case-study.html
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/macros/_macros-cta.jinja
  templates/macros/_macros-hero.jinja
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-quote.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/_macros-text.jinja
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14354 WD-15383 shortned URL for blogpost
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#14348 Apply copy updates for /pricing/consulting
  templates/pricing/consulting.html
  templates/shared/pricing/_data-solutions.html
  templates/shared/pricing/_maas-deployment.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14360 WD-14869 - Add new interim release 24.10 and discard 23.10
  static/js/src/chart-data.js
  templates/about/release_cycles/releases-table.html
Labels: Review: QA +1, Review: Code +1
