Repository canonical/ubuntu.com, pull requests merged in 2024-02, with the labels that each got.

#13518 WD-8067 - page update for iot
  templates/internet-of-things/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13523 WD-8594 - remove /download/kvm page
  redirects.yaml
  templates/download/kvm.html
Labels: Review: QA +1, Review: Code +1

#13524 WD-8578 - copy update on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#13529 Refresh /server page
  static/sass/styles.scss
  templates/server/hyperscale.html
  templates/server/index.html
  templates/server/partial/_server-footer.html
Labels: Review: Design needed, Review: QA needed, Review: Code needed, Review: UX needed

#13527 Update pro selector page
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13540 [WD-8623] remove Support sub-navigation item from /pricing bubble
  navigation.yaml
Labels: Review: QA +1

#12939 Meganav-rebase
  build.js
  meganav.yaml
  navigation.yaml
  package.json
  requirements.txt
  static/js/src/core.js
  static/js/src/main.js
  static/js/src/navigation.js
  static/js/src/tabbed-content.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_pattern_navigation.scss
  static/sass/print.scss
  static/sass/styles.scss
  templates/about/release-cycle.html
  templates/core/features/index.html
  templates/download/risc-v/index.html
  templates/engage/shared/_de_thank-you.html
  templates/engage/shared/_es_thank-you.html
  templates/engage/shared/_fr_thank-you.html
  templates/engage/shared/_header.html
  templates/engage/shared/_it_thank-you.html
  templates/engage/shared/_pt_thank-you.html
  templates/engage/shared/_ru_thank-you.html
  templates/engage/thank-you.html
  templates/openstack/install.html
  templates/templates/_navigation.html
  templates/templates/base.html
  templates/templates/meganav/_list-item.html
  templates/templates/meganav/_section-heading.html
  templates/templates/meganav/base.html
  templates/templates/meganav/community.html
  templates/templates/meganav/get-ubuntu.html
  templates/templates/meganav/navigation-nojs.html
  templates/templates/meganav/products.html
  templates/templates/meganav/support.html
  templates/templates/meganav/use-case.html
  webapp/app.py
  webapp/context.py
  webapp/handlers.py
  webapp/views.py
  yarn.lock
Labels: Don't merge

#13550 Incorporate PMs feedback to meganav (day 1)
  meganav.yaml
Labels: Review: QA +1, Review: Code +1 (with changes)

#13533 Rebrand /server
  templates/server/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13521 Refresh /server/hyperscale
  static/sass/styles.scss
  templates/server/hyperscale.html
  templates/server/index.html
  templates/server/partial/_server-footer.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Don't merge, Review: Code +1 (with changes)

#13541 /desktop/organisations refresh
  templates/desktop/developers.html
  templates/desktop/flavours.html
  templates/desktop/organisations.html
  templates/desktop/partial/_desktop-latest-news.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13494 CVE search results filters
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-filters-desktop.html
  templates/security/cve/_cve-filters-sidenav.html
  templates/security/cve/_cve-landing.html
  templates/security/cve/_cve-search-results.html
  templates/security/cve/filters/package-filter.html
  templates/security/cve/filters/priority-filter.html
  templates/security/cve/filters/release-filter.html
  templates/security/cve/filters/releases-filter.html
  templates/security/cve/filters/status-filter.html
  templates/security/cve/index.html
  webapp/security/views.py
Labels: Review: UX needed

#13545 WD-8434 - update newsletter signup form
  templates/blog/newsletter-form.html
  templates/download/desktop/thank-you.html
  templates/templates/base.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13559 /desktop/organisations copy update
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#13543 Move WSL page to /desktop/wsl
  navigation.yaml
  redirects.yaml
  templates/desktop/wsl.html
  templates/desktop/wsl/contact-us.html
  templates/desktop/wsl/index.html
  templates/desktop/wsl/thank-you.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13546 Open target meganav dropdown based on url hash on load
  static/js/src/navigation.js
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13568 WD-8567 - update text in /data-privacy
  templates/legal/data-privacy/index.html
Labels: Review: QA +1, Review: Code +1

#13575 Fetch user IP with 'X-Forward-For'
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13578 WD-8723 - update /stories page
  templates/core/stories.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13582 Meganav content updates, week 2
  meganav.yaml
Labels: Review: QA +1, Review: Code +1

#13587 [WD-8852] replace lint text in charmed-k8s page
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1

#13589 Ubuntu Pro service terms typo
  templates/legal/ubuntu-pro-service-terms/index.md
Labels: Review: QA +1, Review: Code +1

#13590 [WD-9002] update favicon with support for mobile devices
  static/favicons/COF-favicon-48x48.png
  static/files/site.webmanifest
  templates/templates/base.html
Labels: Review: QA +1

#13573 Refresh /download/alternative-downloads
  templates/download/alternative-downloads.html
  templates/download/shared/_footer.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13593 WD-9003 - remove image from /developers
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#13591 WD-8974 - update screenly logo on /smart-displays
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: Code +1

#13595 [WD-9029] replace TNM logo with a smaller one to align with other logos in /hpe
  templates/hpe/index.html
Labels: Review: QA +1

#13548 Bump to vanilla-4.7.0
  package.json
  static/js/src/navigation.js
  static/sass/_global-settings.scss
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/templates/_navigation.html
  templates/templates/meganav/base.html
  yarn.lock
Labels: Review: Design +1, Review: Code +1 (with changes)

#13588 WD-8800 Qualcomm dragonboard rebrand
  templates/download/qualcomm-dragonboard-410c.html
  templates/download/shared/_first-boot-setup.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13570 Intel NUC desktop rebrand
  templates/download/intel-iei-tank-870.html
  templates/download/intel-nuc-desktop.html
  templates/download/shared/_setup-ubuntu-sso.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13600 Refresh /download/raspberry-pi-core
  templates/download/intel-iei-tank-870.html
  templates/download/raspberry-pi-core.html
  templates/download/shared/_resources.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13604 Update releases.yaml for 22.04.4.
  ARCHITECTURE.md
  meganav.yaml
  releases.yaml
  templates/about/release_cycles/kernel-eol.html
  templates/download/raspberry-pi/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
Labels: Review: QA +1, Review: Code +1

#13611 Update all instances of 22.04.3 with .4
  static/js/src/chart-data.js
  templates/about/release_cycles/kernel-eol.html
  templates/download/raspberry-pi/index.html
  templates/shared/_kernel-support-schedule.html
Labels: Review: Code +1

#13571 Replace cypress tests with playwright tests
  .eslintrc.js
  .github/workflows/a11y.yaml
  .github/workflows/playwright.yaml
  .gitignore
  package.json
  playwright.config.ts
  tests/cypress/a11y/a11y_spec.js
  tests/cypress/cypress-a11y.json
  tests/cypress/cypress.json
  tests/cypress/integration/certified_spec.js
  tests/cypress/integration/navigation_spec.js
  tests/cypress/integration/pro/checkout_spec.js
  tests/cypress/integration/pro/subscribe_spec.js
  tests/cypress/integration/pro/subscriptions_spec.js
  tests/cypress/integration/pro/users_spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/support/pro/commands.js
  tests/cypress/utils.js
  tests/playwright/tests/certified.spec.ts
  tests/playwright/tests/pro/a11y.spec.ts
  tests/playwright/tests/pro/checkout.spec.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13612 Fix the Kernel versions on release cycle page
  templates/about/release_cycles/kernel-eol.html
Labels: Review: Code +1

#13614 [WD-9067] add Ubuntu Server for 64k page size image download to /download/server/arm
  templates/download/server/arm.html
Labels: Review: QA +1, Review: Code +1

#13607 Remove robotics topic from blog subnav
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#13598 WD-8838 - add instagram to the list of social media
  static/sass/_pattern_lists.scss
  templates/templates/footer.html
Labels: Review: QA +1, Review: Code +1

#13603 [WD-9069] update sitemap and point robots.txt to the correct sitemap file
  static/favicon.ico
  static/files/robots.txt
  static/files/sitemap.xml
Labels: Review: Code +1

#13613 Fix the Kernel versions on release cycle page
  static/js/src/chart-data.js
Labels: Review: Code +1

#13615 [WD-9102] fix Kernel charts and tables for 22.04.4 release
  static/js/src/chart-data.js
  templates/about/release_cycles/kernel-eol.html
  templates/shared/_kernel-support-schedule.html
Labels: Review: QA needed, Review: Code needed

#13606 Copy update /legal/data-privacy/webinar
  templates/legal/data-privacy/webinar.md
Labels: Review: QA +1, Review: Code +1

#13430 Playwright Test - Checkout show correct VAT
  tests/playwright/tests/pro/checkout.spec.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13431 Playwright Test - Click cancel reset fields
  tests/playwright/tests/pro/checkout.spec.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13433 Playwright Test - checkout purchase
  tests/playwright/helpers/mockData.ts
  tests/playwright/helpers/utils.ts
  tests/playwright/tests/pro/checkout.spec.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13434 Playwright test - users spec for /pro/users
  tests/playwright/helpers/utils.ts
  tests/playwright/tests/pro/users.spec.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13623 WD-9155 - update modern slavery statement
  templates/legal/modern-slavery-statement/_base_markdown.html
  templates/legal/modern-slavery-statement/index.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#13619 Hide free token if active subscriptions exist
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
  static/js/src/tabbed-content.js
Labels: Review: QA +1, Review: Code +1 (with changes), Commercial 🛒

#13625 /iot/nvidia/contact-us typo fix
  templates/internet-of-things/nvidia/contact-us.html
Labels: Review: QA +1, Review: Code +1
