Repository canonical/ubuntu.com, pull requests merged in 2024-05, with the labels that each got.

#13822 WD-10785-cred-surface-ta-exams-status-instead-of-resorting-to-mapping
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13818 Update copy on /support
  templates/cloud/cloud-computing.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13837 /openstack/install copy update
  templates/openstack/install.html
Labels: Review: QA +1, Review: Code +1

#13838 Update link on /openstack/consulting
  templates/openstack/consulting.html
Labels: Review: QA +1, Review: Code +1

#13829 WD-10907 Upload links
  templates/download/cloud/index.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
  templates/shared/contextual_footers/_download_cloud_ubuntu_advantage.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13831 Try getting the user location client side
  static/js/src/image-download.js
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13839 Update navigation in core bubble
  navigation.yaml
  templates/core/features/index.html
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#13832 WD-10929-fix-exam-names-in-shop
  static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
  static/js/src/advantage/credentials/utils/utils.ts
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13812 WD-10146 Build new Confidential AI page
  navigation.yaml
  static/sass/styles.scss
  templates/confidential-computing/ai.html
  templates/shared/forms/interactive/confidential-computing.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13840 Refresh /openstack/tutorials
  templates/openstack/tutorials.html
Labels: Review: QA +1, Review: Code +1

#13826 Fix button active
  static/sass/_pattern_navigation-dropdown.scss
Labels: Review: QA +1, Review: Code +1

#13842 Wd 10988 copy updates may 1 2024
  navigation.yaml
  templates/credentials/faq.html
  templates/credentials/syllabus.html
  webapp/shop/cred/syllabus.json
Labels: Review: QA needed, 🧊 CUBE, Commercial 🛒

#13849 Update to Vanilla 4.11 (and fix equal heights component)
  package.json
  templates/desktop/index.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#13843 WD-10911 Update Openstack chart
  static/js/src/chart-data.js
  templates/about/openstack-release-cycle.html
  templates/about/release_cycles/microstack-eol.html
  templates/about/release_cycles/openstack-eol.html
  templates/credentials/syllabus.html
Labels: Review: QA +1, Review: Code +1

#13803 Landing refresh
  static/sass/_pattern_lists.scss
  static/sass/_pattern_takeovers.scss
  static/sass/styles.scss
  templates/base_index.html
  templates/index.html
  templates/shared/_latest_news_strip.html
  templates/shared/forms/interactive/general.html
  templates/takeovers/_template.html
  templates/takeovers/index.html
  templates/takeovers/shared/_takeover.html
Labels: Review: Design +1, Review: UX needed

#13855 Wd 10982 pro copy updates
  redirects.yaml
  static/js/src/chart-data.js
  static/js/src/release-chart-old.js
  static/js/src/release-chart.js
  templates/about/release-cycle.html
  templates/about/release_cycles/releases-table.html
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13858 Removed duplicate tab from syllabus page
  templates/credentials/syllabus.html
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13859 change to orange
  static/js/src/chart-data.js
  static/js/src/release-chart-old.js
  static/js/src/release-chart.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13845 Build /managed/firefighting-support page
  navigation.yaml
  templates/managed/firefighting-support.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13857 Add HWE to kernel lifecycle charts
  navigation.yaml
  static/js/src/chart-data.js
  static/js/src/release-chart-old.js
  static/sass/_pattern_chart.scss
  templates/about/release-cycle.html
  templates/about/release_cycles/kernel-eol.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13860 WD-11096 - update landscape install page
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1

#13862 [WD-11117] add a parameter to YT video URL link to prevent unnecessary suggestions
  templates/core/index.html
Labels: Review: QA +1

#13863 Fix button styling on /security
  templates/security/index.html
Labels: Review: QA +1

#13813 Build /pro/distributor page
  build.js
  static/js/src/advantage/api/enum.ts
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/distributor/Distributor.tsx
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
  static/js/src/advantage/distributor/components/ChannelOffersList/index.ts
  static/js/src/advantage/distributor/components/InitiateButton/InitiateButton.tsx
  static/js/src/advantage/distributor/components/InitiateButton/index.ts
  static/js/src/advantage/distributor/hooks/useGetChannelOffersList.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  templates/account/forbidden.html
  templates/pro/distributor/index.html
  webapp/app.py
  webapp/shop/advantage/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13864 /core update images
  static/sass/styles.scss
  templates/core/index.html
Labels: Review: QA +1, Review: Code +1

#13865 Update copy on /training
  templates/training/index.html
Labels: Review: QA +1, Review: Code +1

#13834 Wd-10605 distributor shop step 1
  static/js/src/advantage/distributor/DistributorShop.tsx
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/DealRegistration.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/index.ts
  static/sass/_pattern_distributor.scss
  static/sass/styles.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13835 WD-10607 add step 2. 3. 5 on the distributor shop page
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Currency/Currency.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Currency/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Duration/Duration.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Duration/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/index.ts
  static/js/src/advantage/distributor/utils/FormContext.tsx
  static/js/src/advantage/distributor/utils/utils.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13866 Fix labels on release charts
  static/js/src/release-chart-old.js
Labels: Review: QA +1, Review: Code +1

#13868 Fix /training typo
  templates/training/index.html
Labels: Review: QA +1

#13850 Wd 10609 step 4 add subscription
  static/js/src/advantage/distributor/DistributorShop.tsx
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
  static/js/src/advantage/distributor/utils/FormContext.tsx
  static/js/src/advantage/distributor/utils/utils.ts
  static/sass/_pattern_distributor.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13851 WD-10613 add summary section
  static/js/src/advantage/distributor/DistributorShop.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/DistributorShopSummary.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/index.ts
  static/js/src/advantage/distributor/components/DistributorShopForm/PaymentButton/PaymentButton.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/PaymentButton/index.ts
  static/js/src/advantage/distributor/utils/FormContext.tsx
Labels: Commercial 🛒

#13827 Change certified API to use the v2 API endpoints
  templates/certified/hardware-details.html
  tests/cassettes/TestCertification.test_component_details.yaml
  tests/cassettes/TestCertification.test_filters_json.yaml
  tests/cassettes/TestCertification.test_hardware_details.yaml
  tests/cassettes/TestCertification.test_home.yaml
  tests/cassettes/TestCertification.test_model_details.yaml
  tests/cassettes/TestCertification.test_search_results.yaml
  tests/cassettes/TestCertification.test_vendor_pages.yaml
  webapp/certified/api.py
  webapp/certified/helpers.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#13872 Add link to smart displays screenly section
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: Code +1

#13867 Update copy on /download/amd
  templates/download/amd/tab-2.html
Labels: Review: QA +1, Review: Code +1

#13854 /core/stories refresh
  templates/core/stories.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13880 Add rate limiting to cves
  webapp/context.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#13876 Update icon and run djlint
  templates/landscape/index.html
Labels: Review: QA +1, Review: Code +1

#13882 Add support portal on /legal/websites
  templates/legal/websites.html
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13879 Populate country field based on user location
  static/js/src/dynamic-forms.js
  static/js/src/intlTelInput.js
  static/js/src/main.js
  static/js/src/prepare-form-inputs.js
  static/js/src/tests/setupIntlTelInput.test.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#13890 Update copy on /kubernetes/compare
  templates/kubernetes/compare.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13891 Update copy on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#13888 WD-11513 Changed occurance of "ROCKs" to "rocks" in ceph
  templates/ceph/index.html
Labels: Review: QA +1, Review: Code +1

#13895 Update core download link
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1

#13898 Change nVidia to NVIDIA and add corresponding redirect
  redirects.yaml
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#13892 WD-11514 Modified "Rock" to "rock" and linted the /ceph/install.html
  templates/ceph/install.html
Labels: Review: QA +1, Review: Code +1

#13901 Update copy on /core/features
  templates/core/features/index.html
Labels: Review: QA +1, Review: Code +1

#13904 Update all instances of ROCKS to rocks
  templates/containers/chiselled/index.html
Labels: Review: QA +1, Review: Code +1

#13896 Add k8s 1.30 to support lifecycle
  static/js/src/chart-data.js
  templates/about/release_cycles/k8s-eol.html
Labels: Review: QA +1, Review: Code +1

#13907 Update copy for /kernel/real-time/contact-us
  templates/kernel/real-time/contact-us.html
Labels: Review: QA +1, Review: Code +1

#13903 [Fix] Handle deprecated products on checkout
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13908 WD-11701 Copyupdates to templates/core
  templates/core/index.html
  templates/core/tabs.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13905 Build new page /security/fedramp
  templates/security/fedramp.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)
