Repository canonical/ubuntu.com, pull requests merged in 2024-01, with the labels that each got.

#13420 [WD-8000] add Jira integration config file
  .github/.jira_sync_config.yaml
Labels: Review: Code +1

#13421 WD-7790 - uptade /telco/osm page
  navigation.yaml
  templates/telco/osm/index.html
  templates/telco/shared/_telco-logo-section.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13423 Update the Ubuntu Pro description to the latest version
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13367 Replaced Last updated text to fix potential ambiguity.
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1

#13415 Update the Ubuntu Pro service description
  redirects.yaml
  templates/legal/ubuntu-pro/index.html
Labels: Review: QA +1, Review: Code +1

#13419 Set up playwright
  .github/workflows/cypress-pr.yaml
  .github/workflows/playwright.yml
  .gitignore
  package.json
  playwright.config.ts
  tests/playwright/helpers/commands.ts
  tests/playwright/helpers/mockData.ts
  tests/playwright/helpers/utils.ts
  tests/playwright/tests/checkout.spec.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13429 WD-8006 - update link in /ai/roadshow
  templates/ai/roadshow.html
Labels: Review: QA +1, Review: Code +1

#13435 Fix typo in MLOps datasheet link
  templates/ai/index.html
Labels: Review: Code +1

#13268 Update OpenStack 2023.2 EOL to 9 months
  static/js/src/chart-data.js
  templates/about/release-cycle.html
  templates/about/release_cycles/openstack-eol.html
Labels: Review: QA +1, Review: Code +1

#13432 Add fixed list of resource types
  templates/engage/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13426 [WD-7913] support portal legal pages
  templates/legal/data-privacy/index.html
  templates/legal/data-privacy/support-portal.md
  templates/legal/terms-and-policies/index.html
  templates/legal/terms-and-policies/support-portal.md
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13441 [WD-8132] bring back accidentally removed /legal/ubuntu-pro page
  templates/legal/ubuntu-pro/index.html
Labels: Review: QA +1, Review: Code +1

#13442 [WD-8137] change link in Ubuntu Pro legal page
  redirects.yaml
  templates/legal/ubuntu-pro/index.html
Labels: Review: QA +1, Review: Code +1

#13425 Update release links
  static/js/src/cve/cve.js
  templates/security/cve/index.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#13446 Update link for automotive resources
  templates/automotive/resources.html
Labels: Review: QA +1, Review: Code +1

#13438 Wd 8076 add magic attach code as query param in pro attach
  templates/pro/attach/index.html
  webapp/shop/advantage/views.py
Labels: Review: QA +1, Review: Code +1

#13451 [WD-8151] fix broken links
  redirects.yaml
  templates/robotics/community.html
  webapp/context.py
Labels: Review: QA +1, Review: Code +1

#13453 Use american spelling of defense on /pro
  templates/pro/index.html
Labels: Review: QA +1, Review: Code +1

#13447 Adds keyboard trapping for mobile
  requirements.txt
  static/js/src/core.js
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/meganav/base.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13439 Limit width of list items
  templates/engage/base.html
Labels: Review: QA +1, Review: Code +1

#13454 /gov copy updates
  templates/gov/index.html
Labels: Review: QA +1, Review: Code +1

#13445 WD-7763 - redesign /managed page
  templates/managed/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13440 Search results page, layout and pagination
  static/js/src/cve/cve.js
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-card.html
  templates/security/cve/_cve-filters.html
  templates/security/cve/_cve-footer.html
  templates/security/cve/_cve-landing.html
  templates/security/cve/_cve-search-results.html
  templates/security/cve/_cve-search.html
  templates/security/cve/_pagination.html
  templates/security/cve/index.html
  webapp/security/api.py
  webapp/security/helpers.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13460 [WD-8235] replace a link in /robotics/what-is-ros
  .github/workflows/live-links.yaml
  templates/robotics/what-is-ros.html
Labels: Review: QA +1, Review: Code +1

#13461 [WD-8261] remove redirect from /embedded to /real-time
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13462 /robotics copy update
  templates/robotics/index.html
Labels: Review: QA +1, Review: Code +1

#13456 [WD-8035] supermicro page
  templates/shared/forms/interactive/supermicro.html
  templates/supermicro/base_supermicro.html
  templates/supermicro/contact-us.html
  templates/supermicro/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13467 Minor bug fixes
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#13458 Add filters sidenav
  static/sass/_pattern_cve.scss
  templates/security/cve/_cve-filters-desktop.html
  templates/security/cve/_cve-filters-sidenav.html
  templates/security/cve/_cve-filters.html
  templates/security/cve/_cve-search-results.html
  templates/security/cve/filters/package-filter.html
  templates/security/cve/filters/priority-filter.html
  templates/security/cve/filters/releases-filter.html
  templates/security/cve/filters/status-filter.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13470 Fix ubuntu pro iot devices selector
  static/js/src/advantage/subscribe/react/UAPurchase.tsx
  static/js/src/advantage/subscribe/react/components/Form/Form.tsx
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13468 Apply desktop landing refresh
  static/sass/styles.scss
  templates/desktop/index.html
  templates/shared/contextual_footers/_desktop.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13481 Use dotrun pip instead of snap
  .github/workflows/playwright.yml
  .github/workflows/pr.yaml
  Dockerfile
Labels: Review: Code +1

#13477 [WD-8305] change content in few places on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#13450 Implement /credentials/shop/order-thank-you as flask view
  static/js/src/advantage/credentials/app.tsx
  static/js/src/advantage/credentials/components/CredPurchaseConfirmation/CredPurchaseConfirmation.tsx
  static/js/src/advantage/credentials/components/CredPurchaseConfirmation/index.tsx
  templates/credentials/shop/thank-you.html
  webapp/app.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13473 Ignore checking the styles
  .github/workflows/live-links.yaml
Labels: Review: Code +1

#13488 Apply /desktop redirects
  navigation.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#13489 Fix 404s in K8s
  templates/kubernetes/docs/1.22/upgrading.md
  templates/kubernetes/docs/1.23/charm-docker-registry.md
  templates/kubernetes/docs/auth.md
Labels: Review: QA +1, Review: Code +1

#13490 Fixes more 404s
  templates/kubernetes/docs/1.16/charm-docker-registry.md
  templates/kubernetes/docs/1.17/charm-docker-registry.md
  templates/kubernetes/docs/1.18/charm-docker-registry.md
  templates/kubernetes/docs/1.19/charm-docker-registry.md
  templates/kubernetes/docs/1.19/upgrading.md
  templates/kubernetes/docs/1.20/charm-docker-registry.md
  templates/kubernetes/docs/1.20/upgrading.md
  templates/kubernetes/docs/1.21/charm-docker-registry.md
  templates/kubernetes/docs/1.22/charm-docker-registry.md
Labels: Review: QA +1, Review: Code +1

#13483 [WD-7737] desktop features rebrand
  static/sass/_pattern_gaming.scss
  static/sass/_pattern_strip-photos.scss
  static/sass/styles.scss
  templates/desktop/features.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13496 Fix /gov modal form by moving it to the correct folder
  templates/gov/index.html
  templates/shared/forms/interactive/gov.html
Labels: Review: QA +1, Review: Code +1

#13491 Refresh desktop/developers
  static/sass/styles.scss
  templates/about/release_cycles/ubuntu-eol.html
  templates/desktop/developers.html
Labels: Review: Design needed, Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13482 Fix p-muted-heading alignment
  static/sass/_pattern_navigation.scss
  templates/templates/meganav/base.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13466 WD-7125 - add loading spinner to static forms
  static/js/src/main.js
  static/js/src/static-forms.js
  templates/download/mediatek-genio/contact-us.html
  templates/internet-of-things/nvidia/contact-us.html
  templates/kernel/real-time/contact-us.html
  templates/real-time/index.html
  templates/shared/_credentials-contact-us-form.html
  templates/shared/forms/interactive/gov.html
  templates/shared/forms/interactive/real-time.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#13497 Fix link
  templates/openstack/what-is-openstack.html
Labels: Review: QA +1

#13495 [WD-4668] update kernel chart and improve charts in general
  static/js/src/chart-data.js
  static/js/src/chart.js
  static/js/src/release-chart.js
  static/sass/_pattern_chart.scss
  templates/about/release_cycles/kernel-eol.html
  templates/about/release_cycles/ubuntu-eol.html
  templates/shared/_kernel-support-schedule.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13502 Use dotrun for flake8 version consistency
  .github/workflows/pr.yaml
Labels: Review: QA +1

#13501 WD-8502 - add sources to nvidia page
  templates/nvidia/index.html
Labels: Review: QA +1, Review: Code +1

#13500 WD-8429 - update aws pro coverage table
  templates/aws/pro.html
Labels: Review: QA +1, Review: Code +1

#13492 Update ubuntu lts security support graph with new design
  static/js/src/chart-data.js
  static/js/src/release-chart.js
  static/js/src/support-chart.js
  static/sass/_pattern_chart.scss
  templates/about/release_cycles/ubuntu-eol.html
  templates/about/release_cycles/ubuntu-small-eol.html
  templates/desktop/developers.html
  templates/shared/_release_schedule.html
Labels: Review: Design needed, Review: QA +1, Don't merge, Review: Code +1 (with changes)

#13507 Fix secondary links bug
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/meganav/base.html
Labels: Review: QA +1, Review: Code +1

#13499 Ignore 301 redirection loop from linkchecker
  .github/workflows/live-links.yaml
Labels: Review: Code +1

#13504 Fix logo misalignment
  static/js/src/support-chart.js
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#13508 WD-7157 - add tables to releases charts
  templates/about/release_cycles/k8s-eol.html
  templates/about/release_cycles/kernel-eol.html
  templates/about/release_cycles/microstack-eol.html
  templates/about/release_cycles/openstack-eol.html
  templates/about/release_cycles/releases-table.html
  templates/about/release_cycles/ubuntu-eol.html
  templates/about/release_cycles/ubuntu-small-eol.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13509 [WD-8387] update /download/risc-v for 24.04 release
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
  templates/download/risc-v/tab-7.html
Labels: Review: QA +1, Review: Code +1

#13510 Reinstate infer language script
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#13512 WD-8531 - update text on /about/release-cycle
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#13516 WD-8565 - update image on /about/release-cycle
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#13517 Add functionality to account for height differences on mobile caused by the url navigation
  static/js/src/navigation.js
  static/sass/_pattern_navigation.scss
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13411 Wd 7967 expired contracts still show the schedule button
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1
