Repository canonical/ubuntu.com, pull requests merged in 2024-11, with the labels that each got.

#14367 Rebrand public representation for components
  templates/certified/component-details.html
  templates/certified/components/_certified-releases.html
  templates/certified/components/_hardware-details.html
  templates/certified/components/_hero-section.html
  templates/certified/components/_machines-present.html
  templates/certified/components/component-details.html
  webapp/certified/views.py
Labels: Review: QA +1, Review: Code +1

#14135 C3-713: Redesign public representation for certified machines
  static/sass/_pattern_certified-model-details-tabs.scss
  static/sass/styles.scss
  templates/certified/hardware-details.html
  templates/certified/model-details.html
  templates/certified/model-details/_components-section.html
  templates/certified/platforms/platform-details.html
  templates/certified/shared/_device-template.html
  templates/certified/shared/category-image.html
  tests/cassettes/TestCertification.test_component_details.yaml
  tests/cassettes/TestCertification.test_filters_json.yaml
  tests/cassettes/TestCertification.test_hardware_details.yaml
  tests/cassettes/TestCertification.test_home.yaml
  tests/cassettes/TestCertification.test_model_details.yaml
  tests/cassettes/TestCertification.test_platform_details.yaml
  tests/cassettes/TestCertification.test_search_results.yaml
  tests/cassettes/TestCertification.test_vendor_pages.yaml
  tests/test_certification.py
  webapp/certified/api.py
  webapp/certified/helpers.py
  webapp/certified/views.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14467 [WD-16659] enable AB tests for takeovers on the landing page
  templates/base_index.html
Labels: Review: QA +1

#14465 Fix radio modal bug for dynamic forms
  static/js/src/dynamic-forms.js
  templates/kernel/real-time/contact-us.html
  templates/shared/_client-contact-us-form.html
  templates/shared/_default-contact-us-form.html
  templates/shared/_pro-contact-us-form.html
  templates/shared/forms/interactive/aws.html
  templates/shared/forms/interactive/esm.html
  templates/shared/forms/interactive/general.html
  templates/shared/forms/interactive/landscape.html
  templates/shared/forms/interactive/pricing-infra.html
  templates/shared/forms/interactive/storage.html
Labels: Review: QA +1, Review: Code +1

#14472 WD-16658 - copy: replace references to 'OCI'
  templates/security/oval.html
Labels: Review: QA +1, Review: Code +1

#14456 chore: Refresh Azure page
  templates/azure/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14468 copy: add Azure banner to multiple pages. WD-16533
  templates/ai/mlops.html
  templates/ai/what-is-kubeflow.html
  templates/azure/index.html
  templates/shared/_azure-banner.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14462 Restrict channel users from editing billing details
  static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14470 Rebrand /ceph/managed
  Dockerfile
  package.json
  templates/ceph/managed.html
  webapp/app.py
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14475 Wd 15543 update sign up forms
  templates/credentials/index.html
  templates/credentials/sign-up.html
  templates/shared/_credentials-contact-us-form.html
  templates/shared/_credentials-signup-sme-form.html
  templates/shared/_credentials-signup-tester-form.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code needed, 🧊 Credentials, Commercial 🛒

#14479 [WD-16570] Redirect - from /download/RPi to /core/docs
  redirects.yaml
  templates/download/raspberry-pi-core.html
Labels: Review: QA +1, Review: Code +1

#14478 Fix copy and remove/update stale classes
  templates/aws/workspaces.html
  templates/azure/shared/_how-ubuntu-pro-helps-you.html
Labels: Review: QA +1, Review: Code +1

#14483 fix: Show where you are in docs navigation
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1

#14484 WD-16975 Copy update ubuntu workspaces
  templates/aws/workspaces.html
Labels: Review: QA +1, Review: Code +1

#14482 chore: Update content for ceph
  templates/ceph/index.html
  templates/openstack/features.html
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14491 Change CTA color to positive (green)
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14477 Fix typo in expiry notification
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx
  static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
Labels: Review: Code +1

#14492 feat: update 'Extended security maintenance' to 'Expanded security maintenance' across site
  templates/16-04/_release-chart-1604.html
  templates/18-04/_release-chart-1604.html
  templates/18-04/aws.html
  templates/18-04/azure.html
  templates/18-04/gcp.html
  templates/18-04/ibm.html
  templates/18-04/index.html
  templates/18-04/oci.html
  templates/account/checkout.html
  templates/advantage/subscribe/index.html
  templates/automotive/developers.html
  templates/aws/fips.html
  templates/azure/index.html
  templates/base_index.html
  templates/ceph/index.html
  templates/desktop/index.html
  templates/engage/unlisted/shell-onboarding.html
  templates/internet-of-things/smart-city.html
  templates/telco/openran.html
Labels: Review: Code +1

#14487 copy changes for landscape
  static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.tsx
Labels: Review: QA +1, Review: Code +1

#14493 feat(/summit): Add /summit to sitemap.xml
  static/files/sitemap.xml
Labels: Review: QA +1, Review: Code +1

#14490 K8s docs update tutorial page
  templates/kubernetes/docs/tutorials-index.md
Labels: Review: QA +1, Review: Code +1

#14448 ui: add Lazy loading for images>1MB
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14372 style: Remove excess padding between footer items
  static/sass/styles.scss
  templates/templates/_footer_item.html
Labels: Review: Design +1, Review: Code +1

#14497 fix: Init cookie-policy even if cookies have been set already
  static/js/src/cookie-policy-with-callback.js
Labels: Review: QA +1, Review: Code +1

#14506 [WD-17261] switch off the A/B for takeovers
  templates/base_index.html
Labels: Review: QA +1

#14502 WD-17171 Tooltip for ubuntu pro button has a typo
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#14510 Fix radio field bug for static forms
  static/js/src/dynamic-forms.js
  static/js/src/static-forms.js
Labels: Review: QA +1, Review: Code +1 (with changes)

#14508 add more options to Pro contact form
  templates/shared/_pro-contact-us-form.html
Labels: Review: QA +1, Review: Code +1

#14514 customise credentials thank you page for each sign up form
  templates/credentials/sign-up.html
  templates/credentials/thank-you.html
  webapp/app.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Commercial 🛒

#14516 [WD-17303] Updating the "Free Trial Available" badge on Pro store page
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
Labels: Review: QA +1, Review: Code +1

#14512 Update compliance-automation.html link
  templates/security/compliance-automation.html
Labels: Review: QA +1, Review: Code +1

#14503 copy: replace 'Charmhub' with 'AI & MLOps' in meganav. WD-17137
  meganav.yaml
Labels: Review: QA +1, Review: Code +1

#14517 Fixed phone modal for country code
  static/js/src/dynamic-forms.js
Labels: Review: QA +1, Review: Code +1
