Repository canonical/ubuntu.com, pull requests merged in 2024-04, with the labels that each got.

#13708 WD-9393 - move /download/server/thank-you to a separate page
  redirects.yaml
  templates/download/server/manual.html
  templates/download/server/thank-you.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#13710 Change mention of advantage to pro in contextual footer template
  templates/shared/contextual_footers/_ua_got_questions.html
Labels: Review: Code +1

#13696 WD-9473 Rebrand Raspi download page
  static/sass/styles.scss
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13716 [WD-10110] add 'safe' instruction to blog post's title on /hpe
  templates/hpe/index.html
Labels: Review: QA +1, Review: Code +1

#13702 Create modal form for nvidia-jetson
  static/js/src/dynamic-forms.js
  static/sass/styles.scss
  templates/download/nvidia-jetson/index.html
  templates/shared/forms/interactive/ai.html
  templates/shared/forms/interactive/nvidia-jetson.html
  templates/thank-you.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13714 Update kernel release chart colours
  static/js/src/chart-data.js
Labels: Review: Code +1, Review: UX +1

#13715 WD-9806: Send X-Forwarded-For to UA-Contracts
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13717 Add docs links to subnavs
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#13712 WD-9610 Rebrand Raspi download thank you
  templates/download/desktop/thank-you.html
  templates/download/raspberry-pi/thank-you.html
  templates/download/server/thank-you.html
  templates/shared/_download-newsletter.html
  templates/shared/_server-download-newsletter.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13704 Rebrand /download/server pages
  releases.yaml
  templates/download/server/choose.html
  templates/download/server/download.html
  templates/download/server/manual.html
  templates/download/server/multipass.html
  templates/shared/_download-ubuntu-thank-you-pro-section.html
  templates/shared/_server-download-newsletter.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13711 WD-6314 - rebrand /ai/what-is-kubeflow
  static/sass/styles.scss
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13724 [WD-10092] add a link to /support page
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#13723 WD-10193 Copy update for 24.04 release
  templates/download/cloud/index.html
Labels: Review: QA +1, Review: Code +1

#13720 Update laptop asset /download
  static/sass/_pattern_buttons.scss
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1

#13727 add information about linting and formatting to README
  HACKING.md
  README.md
Labels: Review: Code +1

#13718 Upgrade vanilla and global nav versions
  package.json
  static/sass/_pattern_buttons.scss
  templates/templates/_navigation.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#13726 Adds pro for IoT banner
  .djlintrc
  templates/ai/services.html
  templates/embedded/index.html
  templates/internet-of-things/index.html
  templates/pro/index.html
  templates/shared/_pro-for-devices-banner.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13731 Remove unused /ai/services page
  redirects.yaml
  templates/ai/services.html
Labels: Review: Code +1 (with changes)

#13735 WD-10215 - add contact button to /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13734 WD-10165 - update release charts for 24.04
  static/js/src/chart-data.js
  templates/about/release_cycles/releases-table.html
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#13728 WD-10161 Remove desktop features
  navigation.yaml
  redirects.yaml
  templates/desktop/features.html
Labels: Review: QA +1, Review: Code +1

#13737 WD-10249 Add Korean engage templates
  templates/engage/index.html
  templates/engage/shared/_kr_engage_form.html
  templates/engage/shared/_kr_thank-you.html
Labels: Review: QA +1, Review: Code +1

#13736 Update link in iot pro banner
  templates/shared/_pro-for-devices-banner.html
Labels: Review: QA +1, Review: Code +1

#13738 WD-10056 Raspi copy update
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13448 Implement /credentials/shop/keys as flask view
  static/js/src/advantage/credentials/api/keys.js
  static/js/src/advantage/credentials/app.tsx
  static/js/src/advantage/credentials/components/CredKeyShop/CredKeyShop.tsx
  static/js/src/advantage/credentials/components/CredKeyShop/index.tsx
  templates/credentials/shop/keys.html
  webapp/app.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13741 [WD-10347] add missing word in section title at /download/server/arm
  templates/download/server/arm.html
Labels: Review: QA +1, Review: Code +1

#13742 Updated cookie policy to v3.6.3
  package.json
  static/js/src/core.js
  templates/base_index.html
  templates/templates/base.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#13706 Wd 10014 credentials sign ups donot end up in marketo
  templates/credentials/sign-up.html
  templates/shared/_credentials-contact-us-form.html
  webapp/app.py
  webapp/shop/cred/views.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes), 🧊 CUBE, Commercial 🛒

#13722 /download/desktop 24.04 copy updates
  templates/download/desktop/index.html
  templates/download/shared/_downloads-resources.html
  templates/download/shared/_secure-enterprise-management.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13748 WD-10162 copy update
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13744 /download/server 24.04 updates
  releases.yaml
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#13753 WD-10166 Update certified image
  templates/certified/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13749 Pro - Hide cost for legacy subscriptions
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13745 Updates p-link--inverted to have a parent with is-dark
  templates/16-04/index.html
  templates/aws/fips.html
  templates/azure/fips.html
  templates/base_index.html
  templates/blog/desktop.html
  templates/blog/press-centre.html
  templates/blog/topics/design.html
  templates/blog/topics/juju.html
  templates/blog/topics/maas.html
  templates/blog/topics/robotics.html
  templates/blog/topics/snapcraft.html
  templates/containers/what-are-containers.html
  templates/dell/index.html
  templates/internet-of-things/management.html
  templates/internet-of-things/smart-city.html
  templates/internet-of-things/smart-displays.html
  templates/kernel/index.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/resources.html
  templates/kubernetes/what-is-kubernetes.html
  templates/openstack/what-is-openstack.html
  templates/raspberry-pi/index.html
  templates/robotics/community.html
  templates/security/livepatch.html
  templates/takeovers/_template.html
  templates/takeovers/shared/_takeover.html
  templates/telco/index.html
  templates/templates/meganav/_list-item.html
  templates/tutorials/index.html
  templates/wsl/index.html
  tests/cassettes/TestRoutes.test_tutorials_search.yaml
Labels: Review: QA +1, Review: Code +1

#13759 /download copy changes from UX research
  templates/download/desktop/index.html
  templates/download/raspberry-pi/index.html
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Code +1

#13740 WD-9474 Refresh download core
  navigation.yaml
  redirects.yaml
  releases.yaml
  templates/desktop/index.html
  templates/download/core/index.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/download/shared/_latest-blogs_download.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13760 Remove releases table for larger screens
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#13758 Update image on /desktop/organisations
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#13765 Update meganav.yaml
  meganav.yaml
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#13757 /desktop refresh
  package.json
  redirects.yaml
  static/sass/styles.scss
  templates/desktop/index.html
  templates/shared/contextual_footers/_desktop.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13750 WD-10160 Server download
  templates/download/server/thank-you-s390x.html
Labels: Review: QA +1, Review: Code +1

#13771 Copy update on /download/server/arm
  templates/download/server/arm.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13769 [WD-10516] update image download
  templates/download/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#13768 [WD-10513] update download raspberry pi
  templates/download/cloud/index.html
  templates/download/raspberry-pi/index.html
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
Labels: Review: QA +1

#13773 /training copy update
  templates/training/index.html
Labels: Review: QA +1, Review: Code +1

#13756 Wd 10378 update references to credentials canonical com to skills canonical com
  templates/credentials/assessments.html
  templates/credentials/base_cred.html
  templates/credentials/base_exam.html
  templates/credentials/beta-activation.html
  templates/credentials/exam-no-agreement.html
  templates/credentials/exam.html
  templates/credentials/exit-survey.html
  templates/credentials/index.html
  templates/credentials/redeem.html
  templates/credentials/redeem_with_captcha.html
  templates/credentials/redeem_with_form.html
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  templates/credentials/self-study.html
  templates/credentials/shop/index.html
  templates/credentials/shop/keys.html
  templates/credentials/shop/thank-you.html
  templates/credentials/shop/webhook_responses.html
  templates/credentials/sign-up.html
  templates/credentials/syllabus.html
  templates/credentials/thank-you.html
  templates/credentials/your-badges.html
  templates/credentials/your-exams.html
  templates/legal/terms-and-policies/credentials-terms.html
  webapp/shop/cred/views.py
Labels: Review: Code +1 (with changes), 🧊 CUBE, Commercial 🛒

#13774 WD-10580-time-zone-on-schedule-page-no-longer-selectable
  templates/credentials/schedule.html
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13776 WD-10546 - change desktop background image
  templates/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#13767 WD-9628 Refresh core services
  static/sass/styles.scss
  templates/core/services/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#13761 Update K8s release notes
  templates/kubernetes/docs/release-notes.md
Labels: Review: QA +1, Review: Code +1

#13781 Update broken link on landing
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#13778 WD-10664 - Fix the broken links on desktop/wsl
  templates/desktop/wsl.html
  templates/desktop/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#13782 WD-10584-exam-products-donot-show-up
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 CUBE, Commercial 🛒

#13792 Fix secondary nav selected items marker being mis-aligned
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#13775 WD-10547 Remove raspberry pi pages
  meganav.yaml
  navigation.yaml
  redirects.yaml
  templates/raspberry-pi/_base_raspberry-pi.html
  templates/raspberry-pi/desktop.html
  templates/raspberry-pi/index.html
  templates/raspberry-pi/server.html
  templates/templates/footer.html
Labels: Review: QA needed, Review: Code needed, Review: UX needed

#13793 24.04 release quick changes
  releases.yaml
  templates/desktop/wsl.html
  templates/download/alternative-downloads.html
  templates/download/desktop/index.html
  templates/download/raspberry-pi/index.html
  templates/download/server/manual.html
Labels: Review: QA +1

#13798 Rotate the back button chevron to face left
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#13794 Fix meganav use-cases section headings
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#13786 K8s docs - Add COS Lite
  templates/kubernetes/docs/how-to-cos-lite.md
  templates/kubernetes/docs/how-to-operate.md
Labels: Review: QA +1, Review: Code +1

#13522 24.04
  meganav.yaml
  navigation.yaml
  package.json
  redirects.yaml
  releases.yaml
  static/js/src/chart-data.js
  static/sass/_pattern_navigation.scss
  static/sass/styles.scss
  templates/about/release_cycles/kernel-eol.html
  templates/about/release_cycles/releases-table.html
  templates/certified/index.html
  templates/desktop/developers.html
  templates/desktop/features.html
  templates/desktop/index.html
  templates/desktop/wsl.html
  templates/download/alternative-downloads.html
  templates/download/cloud/index.html
  templates/download/core/index.html
  templates/download/desktop/index.html
  templates/download/desktop/thank-you.html
  templates/download/index.html
  templates/download/raspberry-pi/index.html
  templates/download/risc-v/index.html
  templates/download/risc-v/tab-1.html
  templates/download/risc-v/tab-2.html
  templates/download/risc-v/tab-3.html
  templates/download/risc-v/tab-4.html
  templates/download/risc-v/tab-5.html
  templates/download/risc-v/tab-6.html
  templates/download/risc-v/tab-7.html
  templates/download/server/arm.html
  templates/download/server/manual.html
  templates/download/server/power.html
  templates/download/server/thank-you-s390x.html
  templates/download/server/thank-you.html
  templates/download/shared/_downloads-resources.html
  templates/download/shared/_latest-blogs_download.html
  templates/download/shared/_more-from-canonical.html
  templates/download/shared/_secure-enterprise-management.html
  templates/raspberry-pi/_base_raspberry-pi.html
  templates/raspberry-pi/desktop.html
  templates/raspberry-pi/index.html
  templates/raspberry-pi/server.html
  templates/server/index.html
  templates/shared/contextual_footers/_desktop.html
  templates/templates/footer.html
  webapp/views.py
  yarn.lock
Labels: Review: QA +1

#13788 Update offer model and types
  static/js/src/advantage/offers/types.ts
  tests/shop/advantage/fixtures/channel-offer.json
  tests/shop/advantage/fixtures/channel-offers.json
  tests/shop/advantage/test_parsers.py
  webapp/shop/api/ua_contracts/models.py
  webapp/shop/api/ua_contracts/parsers.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13809 [WD-10663] fix ESM date on the kernel chart
  static/js/src/chart-data.js
Labels: Review: QA +1

#13783 Add link to Pro documentation
  navigation.yaml
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#13816 Update copy on /gcp/pro
  templates/gcp/pro.html
Labels: Review: QA +1, Review: Code +1

#13814 WD-10777 Copy update
  templates/azure/pro.html
Labels: Review: QA +1, Review: Code +1

#13787 Update /telco page
  navigation.yaml
  templates/telco/index.html
  templates/telco/shared/_telco-logo-section.html
Labels: Review: QA +1, Review: UX +1, Review: Code +1 (with changes)

#13821 fix dates in the release cycle table at /about/release-cycle
  templates/about/release_cycles/releases-table.html
Labels: Review: QA +1

#13820 WD-10776 Copy update for 24.04 Azure release
  templates/azure/index.html
Labels: Review: QA +1, Review: Code +1

#13823 /download/cloud copy update
  templates/download/cloud/index.html
  templates/shared/_ubuntu_pro_on_public_cloud.html
Labels: Review: QA +1, Review: Code +1

#13817 Update copy on /openstack
  templates/openstack/index.html
Labels: Review: QA +1, Review: Code +1

#13791 Standarise the padding of secondary navigaiton items in the meganav
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13828 Update meganav yaml to include 24.04 links
  meganav.yaml
  templates/templates/meganav/navigation-nojs.html
Labels: Review: QA +1, Review: Code +1

#13830 /landscape copy updates
  templates/landscape/index.html
  templates/landscape/install.html
Labels: Review: QA +1, Review: Code +1

#13833 fix(redirect): restored some broken redirects
  redirects.yaml
Labels: Review: QA needed, Review: Code needed
