Repository canonical/ubuntu.com, pull requests merged in 2024-08, with the labels that each got.

#14119 WD-13707 Changed the logo for google cloud on homepage
  templates/base_index.html
Labels: Review: QA +1, Copy update 📝, Review: Code +1 (with changes)

#14097 K8s 1.30 updates
  templates/kubernetes/docs/1.30/components.md
  templates/kubernetes/docs/1.30/release-notes.md
  templates/kubernetes/docs/1.30/upgrading.md
  templates/kubernetes/docs/openstack-integration.md
  templates/kubernetes/docs/release-notes.md
  templates/kubernetes/docs/supported-versions.md
  templates/kubernetes/docs/upgrade-notes.md
  templates/kubernetes/docs/upgrading.md
Labels: Review: QA +1, Review: Code +1 (with changes)

#14133 Add fieldset sections to fix missing payload on dynamic forms
  static/js/src/dynamic-forms.js
  templates/shared/forms/interactive/aws.html
  templates/shared/forms/interactive/esm.html
  templates/shared/forms/interactive/general.html
  templates/shared/forms/interactive/landscape.html
  templates/shared/forms/interactive/pricing-infra.html
  templates/shared/forms/interactive/storage.html
Labels: Review: QA +1

#14137 WD-13803 Add /pro/devices to featured meganav
  meganav.yaml
Labels: Review: QA +1, Review: Code +1

#14136 WD-13834 update navigation for /pro/distributor pages
  navigation.yaml
  static/js/src/advantage/distributor/Distributor.tsx
  templates/templates/_navigation.html
  webapp/app.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#14146 Use the security notices api service
  konf/site.yaml
Labels: Review: Code +1

#14141 WD-13653 Update legal agreement
  templates/legal/confidentiality-agreement.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14143 Add macros for text section
  templates/case-studies/base_case-studies.html
  templates/case-studies/index.html
  templates/case-studies/templates/_macros-text.jinja
Labels: Review: QA +1, Review: Code +1 (with changes)

#14148 Add macros for text list and highlights section
  templates/case-studies/base_case-studies.html
  templates/case-studies/index.html
  templates/case-studies/templates/_macros-highlights.jinja
  templates/case-studies/templates/_macros-text-list.jinja
Labels: Review: QA +1, Review: Code +1

#14085 Refactor summarized status logic
  static/js/src/cve/cve.js
  templates/security/cves/_cve-card.html
  templates/security/cves/_cve-search-results.html
  webapp/security/helpers.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX needed

#14138 Add macros for hero section
  templates/case-studies/index.html
  templates/case-studies/templates/_macros-hero.jinja
  templates/case-studies/templates/_macros-text-list.jinja
  templates/case-studies/templates/_macros-text.jinja
Labels: Review: QA +1, Review: Code +1 (with changes)

#14155 WD-13948 Copyupdate /automotive
  templates/automotive/index.html
Labels: Review: QA needed, Review: Code needed

#14157 Add credly values to production
  konf/site.yaml
Labels: Review: Code needed

#14149 Implement macros for quote and image section
  static/sass/styles.scss
  templates/case-studies/index.html
  templates/case-studies/templates/_macros-image.jinja
  templates/case-studies/templates/_macros-quote.jinja
  templates/case-studies/templates/_macros-text.jinja
Labels: Review: QA +1, Review: Code +1

#14152 [WD-12845] rebrand u.com/aws/support
  templates/aws/support.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14154 WD-13897 Update ubuntu.com meganav IoT quick links
  meganav.yaml
Labels: Review: QA +1, Review: Code +1 (with changes)

#14153 WD-13815 Add a field to containers form
  templates/shared/forms/interactive/containers.html
Labels: Review: QA needed, Review: Code needed

#14144 WD-12825 - rebrand /azure/fips
  templates/azure/fips.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#13976 Bump canonicalwebteam.search
  requirements.txt
  webapp/app.py
Labels: Review: QA needed, Review: Code needed

#14140 Removed is-dark class from code block
  templates/kubernetes/_install-linux.html
Labels: Review: QA needed, Review: Code needed

#14162 Rebrand /aws/workspaces page
  static/sass/_pattern_lists.scss
  templates/aws/workspaces.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#14167 WD-13748 - fix scrolling issue on CVEs
  static/sass/_pattern_cve.scss
  templates/security/cve/index.html
Labels: Review: QA +1, Review: Code +1

#14168 WD-13675 - fix links in the footer
  templates/templates/_footer-copyright-and-legal.html
Labels: Review: QA +1, Review: Code +1

#14156 WD-12827 - rebrand /azure/private-offer
  static/sass/_pattern_lists.scss
  templates/azure/ebook/index.html
  templates/azure/private-offer.html
  templates/azure/shared/_how-ubuntu-pro-helps-you.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14161 Add some tests for distributor store pages
  static/js/src/advantage/distributor/app.tsx
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.test.tsx
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
  static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Currency/Currency.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/DealRegistration.test.tsx
  static/js/src/advantage/distributor/components/DistributorShopForm/Duration/Duration.test.tsx
  static/js/src/advantage/distributor/utils/tests/utils.test.ts
  static/js/src/advantage/offers/tests/factories/channelOffers.ts
  static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts
Labels: Review: Code needed, Commercial 🛒

#14170 WD-13371 - add /data-science to navigation
  navigation.yaml
Labels: Review: QA needed, Review: Code needed

#14171 WD-14066 - remove pro devices from meganav
  meganav.yaml
Labels: Review: QA +1, Review: Code +1

#14172 WD-14096 - update dell logo on home page
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14169 WD-13068 - fix images on /core to be full width
  templates/core/index.html
  templates/core/tabs.html
Labels: Review: QA needed, Review: Code needed

#14174 WD-12835 - rebrand /azure/thank-you
  templates/azure/thank-you.html
  templates/shared/_thank_you_footer.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14176 chore: Update name of /security/compliance-automation and add a redirect
  meganav.yaml
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/advantage/_table.html
  templates/base_index.html
  templates/cloud/hybrid-cloud.html
  templates/cloud/private-cloud.html
  templates/desktop/developers.html
  templates/download/cloud/index.html
  templates/download/shared/_secure-enterprise-management.html
  templates/financial-services/index.html
  templates/gov/index.html
  templates/openstack/consulting.html
  templates/openstack/support.html
  templates/pricing/desktop.html
  templates/pricing/devices.html
  templates/pro/index.html
  templates/pro/why-pro.html
  templates/robotics/index.html
  templates/robotics/ros-esm.html
  templates/security/cis.html
  templates/security/compliance-automation.html
  templates/security/fedramp.html
  templates/security/index.html
  templates/shared/_download-ubuntu-thank-you-pro-section.html
  templates/shared/_pro_strip.html
  templates/shared/_ubuntu-advantage-service-description-ja.html
  templates/shared/_ubuntu-pro-description.html
  templates/shared/pricing/_ua-for-infrastructure.html
  templates/telco/openran.html
  templates/templates/navigation-developer-h.html
Labels: Review: QA +1, Review: Code +1

#14178 chore: Update copy on /real-time
  templates/real-time/index.html
Labels: Review: QA +1, Review: Code +1

#14160 Build an example case study using macros
  static/sass/styles.scss
  templates/case-studies/base_case-studies.html
  templates/case-studies/example.html
  templates/case-studies/index.html
  templates/case-studies/templates/_macros-hero.jinja
  templates/case-studies/templates/_macros-highlights.jinja
  templates/case-studies/templates/_macros-image.jinja
  templates/case-studies/templates/_macros-quote.jinja
  templates/case-studies/templates/_macros-text-list.jinja
  templates/case-studies/templates/_macros-text.jinja
Labels: Review: Design +1, Review: UX +1

#14182 Rename default form template to a more generic name
  templates/ai/contact-us.html
  templates/ai/thank-you.html
  templates/aws/contact-us.html
  templates/contact-us/form/index.html
  templates/containers/contact-us.html
  templates/desktop/wsl/contact-us.html
  templates/download/contact-us.html
  templates/financial-services/contact-us.html
  templates/gov/contact-us.html
  templates/kubernetes/contact-us.html
  templates/managed/contact-us.html
  templates/openstack/contact-us.html
  templates/security/contact-us.html
  templates/security/thank-you.html
  templates/server/contact-us.html
  templates/shared/_default-contact-us-form.html
  templates/support/contact-us.html
  templates/training/contact-us.html
Labels: Review: QA +1

#14184 WD-14151 - Update 'yes' to green checkboxes on /pricing/pro
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Code +1

#14185 WD-14152 - Add link to free trial contact form in /pro/subscribe
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
Labels: Review: Design needed, Review: QA +1, Review: Code +1

#14175 WD-12833 - rebrand /azure/support
  templates/azure/support.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14189 Fix engage sitemap 500
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14188 chore: Update meganav reference from Multipass to MicroCloud
  meganav.yaml
Labels: Review: QA +1, Review: Code +1

#14183 Fix containers forms and remove unused forms
  build.js
  static/js/src/dynamic-forms.js
  static/js/src/kernel-form.js
  static/js/src/static-forms.js
  templates/automotive/index.html
  templates/shared/forms/interactive/containers.html
Labels: Review: QA +1, Review: Code +1

#14186 WD-12823 - rebrand /azure/ebook
  templates/azure/ebook/index.html
  templates/azure/private-offer.html
  templates/azure/shared/_azure-logo-strip.html
  templates/azure/shared/_how-ubuntu-pro-helps-you.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14196 chore: Update copy on /nvidia-jetson
  templates/download/nvidia-jetson/tab-1-jetson-agx-orin.html
  templates/download/nvidia-jetson/tab-2-jetson-orin-nano.html
  templates/download/nvidia-jetson/tab-3-jetson-orin-nx.html
Labels: Review: QA +1, Review: Code +1

#14202 [WD-14301] use an issue form to report issues on GitHub
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.yaml
  templates/templates/_footer-copyright-and-legal.html
  templates/templates/footer.html
Labels: Review: Code +1

#14179 add more checks to keys list
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1

#14207 fix /download/amd tab ids
  templates/download/amd/index.html
  templates/download/amd/tab-1.html
  templates/download/amd/tab-2.html
Labels: Review: Code +1 (with changes)

#14198 bug: Change the regex that finds the CVE indentifier to ignore links that end in '.html'
  .github/workflows/pr.yaml
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#14211 fix: Broken links across the website
  .github/workflows/live-links.yaml
  templates/containers/what-are-containers.html
  templates/internet-of-things/management.html
Labels: Review: QA +1, Review: Code +1

#14212 feat: Add lsn notices to list of references
  templates/security/cve/cve.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14214 chore: Update copy on /security/compliance-automation
  templates/security/compliance-automation.html
Labels: Review: QA +1, Review: Code +1

#14221 fix: Add redirects for removed parts of /community
  redirects.yaml
Labels: Review: QA +1

#14142 Case studies templates
  package.json
  static/sass/styles.scss
  templates/case-study/_case-study-card.html
  templates/case-study/base_case-study.html
  templates/case-study/esa-case-study.html
  templates/case-study/index.html
  templates/macros/_macros-hero.jinja
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-quote.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/_macros-text.jinja
  templates/shared/forms/interactive/case-study.html
  webapp/app.py
  webapp/views.py
  yarn.lock
Labels: Review: QA +1

#14208 feat: /aws/fips redesign
  static/sass/_pattern_lists.scss
  static/sass/styles.scss
  templates/aws/fips.html
  templates/azure/sql.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14223 feat: /aws redesign
  templates/aws/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14192 WD-13781 - refresh pro section on /download/amd
  templates/download/amd/_ubuntu_pro_section.html
  templates/download/amd/_working_commercial_section.html
  templates/download/amd/index.html
  templates/download/amd/tab-1.html
  templates/download/amd/tab-2.html
  templates/download/amd/tab-3.html
  templates/download/amd/tab-4.html
Labels: Review: QA needed, Review: Design +1, Review: Code needed, Review: UX +1

#14224 feat: /aws/thank-you redesign
  templates/aws/thank-you.html
  templates/azure/thank-you.html
  templates/shared/_thank_you_footer.html
Labels: Review: QA +1, Review: Code +1

#14225 feat: /gcp/thank-you redesign
  templates/gcp/thank-you.html
Labels: Review: QA needed, Review: Design +1, Review: Code needed

#14228 Remove unused fields on engage forms
  templates/engage/shared/_de_engage_form.html
  templates/engage/shared/_en_engage_form.html
  templates/engage/shared/_es_engage_form.html
  templates/engage/shared/_it_engage_form.html
  templates/engage/shared/_pt_engage_form.html
  templates/engage/shared/_ru_engage_form.html
  templates/engage/shared/_zh-TW_engage_form.html
Labels: Review: Code +1

#14235 WD-14515 - Update package.json major dependencies
  package.json
  static/js/src/advantage/api/types.ts
  static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
  static/js/src/advantage/react/utils/formatDate.ts
  static/js/src/advantage/react/utils/getNextCycleStart.test.ts
  static/js/src/advantage/react/utils/getNextCycleStart.ts
  static/js/src/advantage/react/utils/sortSubscriptionsByStartDate.test.ts
  static/js/src/advantage/tests/factories/api.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#14232 WD-12753 - rebrand /core and /core/services thank-you pages
  templates/core/services/thank-you.html
  templates/core/thank-you.html
  templates/shared/_thank_you_footer.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14241 Fix image width and update case study content
  templates/case-study/esa.html
Labels: Review: QA +1, Review: UX +1

#14245 [WD-14593] update download links for Risc-V for 24.04.1
  templates/download/risc-v/allwinner-nezha.html
  templates/download/risc-v/microchip-curiosity.html
  templates/download/risc-v/microchip-polarfire.html
  templates/download/risc-v/milk-v-mars.html
  templates/download/risc-v/qemu-emulator.html
  templates/download/risc-v/sifive-unmatched.html
  templates/download/risc-v/sipeed-licheerv.html
  templates/download/risc-v/starfive-visionfive.html
Labels: Review: QA +1, Review: Code +1

#14244 fix(dynamic-forms.js): Don't remove name attribute from form inputs after processing
  package.json
  static/js/src/dynamic-forms.js
  static/sass/styles.scss
  templates/shared/forms/interactive/hpc.html
  templates/shared/forms/interactive/intel-iot.html
  templates/shared/forms/interactive/kernel-beta-signup.html
  templates/shared/forms/interactive/landscape-pricing-saas.html
  webapp/views.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#14239 WD-12747 - rebrand /core/features/full-disk-encryption
  templates/core/features/full-disk-encryption.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14238 WD-12749 - rebrand /core/reatures/recovery
  templates/core/features/recovery.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1
