Repository canonical/ubuntu.com, pull requests merged in 2025-09, with the labels that each got.

#15557 Feat: Updated nav for /ai
  secondary-navigation.yaml
Labels: Review: QA +1, Review: Code +1

#15556 Feat: reduced the size of images on ubuntu homepage
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#15476 refactor(forms): use form generator
  templates/gcp/base_gcp.html
  templates/gcp/form-data.json
  templates/managed/apps/index.html
  templates/managed/firefighting-support.html
  templates/managed/form-data.json
  templates/managed/index.html
  templates/pro/devices.html
  templates/pro/form-data.json
  templates/security/form-data.json
  templates/security/livepatch.html
  templates/shared/forms/interactive/gcp.html
  templates/shared/forms/interactive/managed-services.html
  templates/shared/forms/interactive/pro-devices.html
Labels: Review: QA +1, Review: Code +1

#15571 Use global MARKETO_API_URL env
  konf/site.yaml
Labels: Review: QA +1, Review: Code +1

#15573 Add a link to pro free trial on 20.04 page.
  templates/20-04/index.html
Labels: Review: QA +1, Review: Code +1, Review: UX needed

#15579 feat: Add MARKETO secret to demos
  konf/site.yaml
Labels: Review: QA +1

#15577 update logo and remove the dataset
  templates/toolchains/java.html
Labels: Review: QA +1, Review: Code +1

#15544 revamp: https://ubuntu.com/openstack/install (WD-24782)
  templates/openstack/install.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Don't merge

#15549 chore: Add redirect for /openstack/support
  redirects.yaml
Labels: Review: QA +1

#15568 Replace <img/> to image_template (Part 5)
  templates/security/cmmc/index.html
  templates/security/cves/cve.html
  templates/security/fedramp.html
  templates/security/standards/index.html
  templates/security/standards/pci-dss.html
  templates/shared/forms/interactive/azure-1604.html
  templates/shared/forms/interactive/managed-cassandra.html
  templates/shared/forms/interactive/managed-kafka.html
  templates/shared/forms/interactive/robotics_ros.html
  templates/shared/forms/interactive/telco.html
  templates/supermicro/index.html
  templates/support/index.html
  templates/tests/_thank-you.html
  templates/toolchains/__dotnet.html
  templates/toolchains/java.html
  templates/toolchains/spring.html
Labels: Review: QA needed, Review: Code needed

#15581 chore: add redirect for openstack/features to c.com
  redirects.yaml
  secondary-navigation.yaml
Labels: Review: QA +1, Review: Code +1

#15583 Openstack feature branch
  redirects.yaml
  secondary-navigation.yaml
  templates/openstack/install.html
Labels: Don't merge

#15587 docs: add release notes for `ignore-missing-cni` Charmed K8s backports
  templates/kubernetes/charmed-k8s/docs/1.29/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.30/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.31/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.32/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.33/release-notes.md
  templates/kubernetes/charmed-k8s/docs/release-notes.md
Labels: Review: QA +1, Review: Code +1

#15593 Prevent duplicate submissions
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
Labels: Review: QA +1, Review: Code +1, Portal 🛒

#15609 [WD-26537] fix: community join link resulting in 404
  navigation.yaml
  redirects.yaml
  templates/community/local-communities.html
Labels: Review: QA +1, Review: Code +1

#15613 [WD-23405] feat: show error page if marketo ID is invalid
  templates/400.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15614 feat: add country field to /kernel/real-time/contact-us form
  templates/kernel/real-time/contact-us.html
Labels: Review: QA +1

#15619 fix(WD-26947): add marketo api url to site.yaml
  konf/site.yaml
Labels: Review: QA +1, Review: Code +1

#15621 [WD-27000] feat: dynamically generated vulnerabilities sitemap
  templates/sitemap_index.xml
  webapp/app.py
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#15617 copy updates on /desktop
  templates/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#15625 [WD-27023] Copy update: /kubernetes
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1

#15615 copy: update /download/risc-v for Ubuntu 25.10 release
  templates/download/risc-v/allwinner-nezha.html
  templates/download/risc-v/deepcomputing-fml13v01.html
  templates/download/risc-v/index.html
  templates/download/risc-v/microchip-curiosity.html
  templates/download/risc-v/microchip-polarfire.html
  templates/download/risc-v/milk-v-mars.html
  templates/download/risc-v/pine64-star64.html
  templates/download/risc-v/qemu-emulator.html
  templates/download/risc-v/sifive-unmatched.html
  templates/download/risc-v/sipeed-licheerv.html
  templates/download/risc-v/starfive-visionfive.html
Labels: Review: QA +1, Review: Code +1

#15637 [WD-26079] fix: marketo forms failing for new creations
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15669 Make sure tutorial topics are case-insensitive
  static/js/src/tutorial-list.js
  static/js/src/tutorial-list.test.js
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15668 build: update @canonical/latest-news dependency to 2.0.0
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#15678 Add tracking-api.g2.com to CSP allowlist
  webapp/constants.py
Labels: Review: QA +1, Review: Code +1

#15681 WD-27088 - Copy update: Upgrade navigation link from 18.04 upgrade to 20.04 upgrade
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#15682 copy: update /download/server/thank-you CLI cheat sheet
  templates/download/server/thank-you.html
  templates/download/shared/_server_weekly_news.html
Labels: Review: QA +1, Review: Code +1

#15683 Copyupdate: (WD-27639) updated the form options
  templates/download/server/s390x.html
Labels: Review: QA +1, Review: Code +1 (with changes)
