Repository canonical/ubuntu.com, pull requests merged in 2025-06, with the labels that each got.

#15162 feat: fedramp page refresh, add video with lazy loading
  templates/security/fedramp.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#15166 [WD-21953] Update CTA label on /pro/subscribe
  static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
  static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx
Labels: Review: QA +1, Review: Code +1

#15168 feat: archive /core/services/guide and set up redirects
  ARCHITECTURE.md
  redirects.yaml
  templates/core/services/guide/document.html
  templates/core/services/guide/search-results.html
  templates/core/services/shared/_side-navigation.md
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#15153 feat: replaced ubuntuforums with discourse
  meganav.yaml
  templates/hpc/_hpc-contact-us-form.html
  templates/shared/_default-contact-us-form.html
  templates/shared/_openstack_contact_us.html
  templates/shared/forms/_desktop_help.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#15177 [WD-22632] Security index page copy update
  templates/security/index.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#15178 feat: Add DeepComputing FML13V01 to risc-v download page
  templates/download/risc-v/deepcomputing-fml13v01.html
  templates/download/risc-v/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15182 text changes
  templates/security/fedramp.html
Labels: Review: QA +1, Review: Code +1

#15174 [WD-17822] feat: rebrand kernel bubble
  meganav.yaml
  package.json
  static/sass/styles.scss
  templates/kernel/form-data.json
  templates/kernel/index.html
  templates/kernel/lifecycle.html
  templates/kernel/variants.html
  templates/shared/_kernel-release-diagram.html
  templates/shared/_kernel-support-schedule.html
  yarn.lock
Labels: Review: QA +1

#15167 [WD-17773] feat: Rebrand robotics/what-is-ros
  templates/robotics/what-is-ros.html
  templates/shared/contextual_footers/_robotics_further_reading.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15179 chore: Remove stale pages
  templates/desktop/partners.html
  templates/download/server/download.html
Labels: Review: QA +1, Review: Code +1

#15190 feat: Update logos on /desktop/flavours
  templates/desktop/flavors.html
Labels: Review: QA +1, Review: Code +1

#15194 BAU security standards
  templates/macros/_vf_rich-horizontal-list.jinja
  templates/security/security-standards.html
Labels: Review: QA +1, Review: Code +1

#15200 WD22786: open desktop exam for production for internal users
  templates/credentials/shop/index.html
  webapp/shop/cred/exams.json
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1

#15199 armhf added in "Architectures supported with ESM" for 24.04
  templates/security/esm.html
Labels: Review: QA +1, Review: Code +1

#15201 Redesigned the legal overview page
  templates/legal/_base_legal_markdown.html
  templates/legal/index.md
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#15204 Update /download/mediatek-genio
  templates/download/mediatek-genio/tab-1.html
  templates/download/mediatek-genio/tab-2.html
  templates/download/mediatek-genio/tab-3.html
  templates/download/mediatek-genio/tab-4.html
Labels: Review: QA +1, Review: Code +1

#15195 Rebrand contact-us page
  redirects.yaml
  templates/about/base_about.html
  templates/base_index.html
  templates/cloud/_base-cloud.html
  templates/community/_base_community.html
  templates/confidential-computing/base_confidential-computing.html
  templates/contact-us/base_contact-us.html
  templates/contact-us/form-data.json
  templates/contact-us/form/index.html
  templates/contact-us/form/thank-you.html
  templates/contact-us/index.html
  templates/contact-us/thank-you.html
  templates/download/_base_download.html
  templates/download/risc-v/index.html
  templates/rfp/_base_rfp.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15222 chore: Remove /landscape/docs and redirect to readthedocs
  navigation.yaml
  redirects.yaml
  templates/advantage/_table.html
  templates/desktop/wsl/index.html
  templates/landscape/docs/document.html
  templates/landscape/docs/search-results.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#15223 Use common names for countries in CLA
  static/js/src/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
  static/js/src/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1

#15226 Copy update: update spectro cloud logo
  templates/kubernetes/index.html
Labels: Review: QA +1, Review: Code +1

#15219 [WD-22265] chore: remove blog/upcoming and add redirects
  navigation.yaml
  redirects.yaml
  templates/blog/upcoming.html
  templates/templates/_navigation.html
Labels: Review: QA needed, Review: Code needed

#15220 Copy update on /summit/call-for-collaboration
  templates/summit/call-for-collaboration.html
Labels: Review: QA +1, Review: Code +1

#15242 Revert "Merge pull request #15220 from minkyngkm/WD-22825"
  templates/summit/call-for-collaboration.html
Labels: Review: QA needed

#15241 copy: update https://ubuntu.com/security/cmmc. WD-22655
  templates/security/cmmc/index.html
Labels: Review: QA +1, Review: Code +1

#15237 Update linkchecker to exclude 401 and 403 status codes in error checks
  .github/workflows/live-links.yaml
  .github/workflows/performance-check.yaml
Labels: Review: Code +1

#15232 WD-22392/toolchains-java
  templates/toolchains/java.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15215 chore: Add toolchains page
  templates/toolchains/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15239 Fix typo in what-is-kubeflow.html
  templates/ai/what-is-kubeflow.html
Labels: Review: QA +1, Review: Code +1

#15234 [WD-21621] feat: Rebranded blog/archives
  requirements.txt
  templates/blog/archives.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#15257 WD-23223: disable cue.02 exam in production
  webapp/shop/cred/exams.json
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Portal 🛒

#15246 [WD-21717] feat: Rebranded blog/article page
  static/sass/_pattern_blog-card.scss
  templates/blog/article.html
  templates/blog/blog-card.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15216 feat: Rebrand search page
  requirements.txt
  templates/search.html
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15263 security: add frame-ancestors to CSP to prevent clickjacking
  templates/test.html
  webapp/handlers.py
Labels: Review: QA needed, Review: Code needed

#15172 [WD-17778] feat: Rebrand robotics/community page
  templates/robotics/community.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15264 Remove test page
  templates/test.html
Labels: Review: Code +1

#15266 copy: update ubuntu.com/summit. WD-22824
  navigation.yaml
  templates/summit/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#15270 fix: enable production access for CUE.02 desktop exam
  webapp/shop/cred/exams.json
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Portal 🛒

#15275 copy(/security/livepatch): Update datasheet link
  templates/security/livepatch.html
Labels: Review: QA +1, Review: Code +1

#15269 fix: update country from IP address if not provided in form field
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15277 update pro description
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#15235 feat(api): Expose endpoint for engage page metadata
  webapp/app.py
  webapp/views.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#15176 Copy update for SLA section on /support
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#15274 [K8s Docs] Latest Kubernetes changes and 1.33 release
  templates/kubernetes/charmed-k8s/docs/1.33/components.md
  templates/kubernetes/charmed-k8s/docs/1.33/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.33/upgrading.md
  templates/kubernetes/charmed-k8s/docs/cni-cilium.md
  templates/kubernetes/charmed-k8s/docs/how-to-cos-lite.md
  templates/kubernetes/charmed-k8s/docs/release-notes.md
  templates/kubernetes/charmed-k8s/docs/supported-versions.md
  templates/kubernetes/charmed-k8s/docs/upgrading.md
Labels: Review: QA needed, Review: Code needed
