Repository canonical/ubuntu.com, pull requests merged in 2025-05, with the labels that each got.

#15059 copy: update ubuntu.com/download/mediatek-genio download links. WD-21545
  templates/download/mediatek-genio/tab-1.html
  templates/download/mediatek-genio/tab-2.html
  templates/download/mediatek-genio/tab-3.html
  templates/download/mediatek-genio/tab-4.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15043 fix: Sitemap github action
  .github/workflows/sitemap.yaml
Labels: Review: Code needed

#15062 feat: cta copy update on /containers/container-build-service
  templates/containers/container-build-service.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15068 update /about/release-cycle#ubuntu-kernel-release-cycle
  static/js/src/chart-data.js
  static/sass/_pattern_chart.scss
  templates/shared/_kernel-release-diagram.html
Labels: Review: QA +1, Review: Code +1

#15069 chore: update footer with US english
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/ai/index.html
  templates/aws/workspaces.html
  templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
  templates/desktop/developers.html
  templates/desktop/flavors.html
  templates/desktop/index.html
  templates/desktop/organizations.html
  templates/download/index.html
  templates/pricing/desktop.html
  templates/shared/contextual_footers/_desktop_flavours.html
  templates/templates/footer.html
Labels: Review: QA needed, Review: Code needed

#15073 chore: Update community help link
  templates/support/community-support.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15072 WD-21874 Copy update changes to Renesas-iot page
  templates/download/renesas-iot/tab-1-renesas-rz-g2l.html
Labels: Review: QA +1, Review: Code +1

#15041 add redirects to new consulting page
  meganav.yaml
  redirects.yaml
  templates/shared/_thank_you_footer.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15074 fix: Fix broken redirect
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#14976 pro: edit billing details from invoices page
  build.js
  static/js/src/account-billing.js
  static/sass/_pattern_invoices.scss
  static/sass/styles.scss
  templates/account/invoices/_edit_billing_form.html
  templates/account/invoices/_edit_billing_modal.html
  templates/account/invoices/index.html
  webapp/shop/schemas.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Don't merge, Commercial 🛒

#15076 [K8s Docs] Update k8s doc links
  templates/kubernetes/charmed-k8s/docs/1.30/upgrading.md
  templates/kubernetes/charmed-k8s/docs/1.31/upgrading.md
  templates/kubernetes/charmed-k8s/docs/1.32/upgrading.md
  templates/kubernetes/charmed-k8s/docs/ceph.md
  templates/kubernetes/charmed-k8s/docs/certs-and-trust.md
  templates/kubernetes/charmed-k8s/docs/cni-cilium.md
  templates/kubernetes/charmed-k8s/docs/encryption-at-rest.md
  templates/kubernetes/charmed-k8s/docs/equinix.md
  templates/kubernetes/charmed-k8s/docs/gatekeeper.md
  templates/kubernetes/charmed-k8s/docs/how-to-cos-lite.md
  templates/kubernetes/charmed-k8s/docs/install-existing.md
  templates/kubernetes/charmed-k8s/docs/install-local.md
  templates/kubernetes/charmed-k8s/docs/install-manual.md
  templates/kubernetes/charmed-k8s/docs/install-offline.md
  templates/kubernetes/charmed-k8s/docs/keepalived.md
  templates/kubernetes/charmed-k8s/docs/logging.md
  templates/kubernetes/charmed-k8s/docs/metallb.md
  templates/kubernetes/charmed-k8s/docs/multiple-networks.md
  templates/kubernetes/charmed-k8s/docs/proxies.md
  templates/kubernetes/charmed-k8s/docs/quickstart.md
  templates/kubernetes/charmed-k8s/docs/scaling.md
  templates/kubernetes/charmed-k8s/docs/security.md
  templates/kubernetes/charmed-k8s/docs/storage.md
  templates/kubernetes/charmed-k8s/docs/upgrading.md
  templates/kubernetes/charmed-k8s/docs/using-vault.md
  templates/kubernetes/charmed-k8s/docs/vsphere-integration.md
Labels: Review: QA +1, Review: Code +1

#15083 fix: /desktop/flavors redirect
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#15078 chore: Remove ai-forms.js
  static/js/src/ai-form.js
  templates/ai/consulting.html
  templates/ai/form-data.json
  templates/ai/index.html
  templates/ai/mlflow.html
  templates/ai/mlops-workshop.html
  templates/ai/mlops.html
Labels: Review: QA +1, Review: Code +1

#15090 chore: Update deprecating snap
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#15088 integrate ta paginated response in your-exams view
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#15051 feat: Implement lsn refresh for individual notices
  build.js
  static/js/src/cve/notices.js
  templates/security/notices/lsn.html
  templates/security/notices/usn.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#15085 chore: Remove unused JS files
  build.js
  static/js/src/chassis-animation.js
  static/js/src/dummy-data.js
  static/js/src/landscape-form.js
  static/js/src/landscape-saas-form.js
  static/js/src/random-partner-logos.js
  static/js/src/sticky-nav.js
  static/js/src/utils/cookies.js
  static/js/src/utils/persitState.js
  static/js/src/utils/reverseString.js
  templates/embedded/index.html
Labels: Review: Code +1

#15086 chore: Remove templates from sitemap
  templates/security/vulnerabilities/vulnerability-detailed.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#15087 copy: update contact form emails for /hpe
  templates/shared/forms/interactive/hpe.html
Labels: Review: QA +1, Review: Code +1

#15091 chore: Remove mobile-footer-navigation.js
  static/js/src/main.js
  static/js/src/mobile-footer-navigation.js
  templates/templates/_footer_item.html
Labels: Review: Code +1 (with changes)

#14532 refactor: Run sass-migrator
  package.json
  static/sass/_pattern_blog-card.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_modals.scss
  static/sass/_pattern_navigation-dropdown.scss
  static/sass/_settings_colors.scss
  yarn.lock
Labels: Review: Code +1

#15050 chore: Bump canonicalwebteam.discourse to 6.2.0
  requirements.txt
  static/sass/styles.scss
  templates/security/vulnerabilities/vulnerability-detailed.html
Labels: Review: QA +1, Review: Code +1

#15079 feature: Security notices overhaul
  build.js
  static/js/src/cve/notices-landing.js
  static/js/src/cve/notices.js
  static/sass/_pattern_cve.scss
  static/sass/styles.scss
  templates/security/_notice-brief.html
  templates/security/_subscribe.html
  templates/security/cves/cve.html
  templates/security/notices.html
  templates/security/notices/_further-reading.html
  templates/security/notices/_notice-brief.html
  templates/security/notices/_release-filters.html
  templates/security/notices/_sidenav-filters-container.html
  templates/security/notices/index.html
  templates/security/notices/lsn.html
  templates/security/notices/usn.html
  templates/shared/_pagination.html
  webapp/security/api.py
  webapp/security/helpers.py
  webapp/security/views.py
Labels: Don't merge

#15092 feat: Add redirect for /desktop/organizations
  redirects.yaml
Labels: Review: QA +1

#15095 fix: Urls params are not stored on checkbox click
  static/js/src/certified-search-results.js
Labels: Review: QA +1, Review: Code +1

#14966 [WD-20515] copy update: ubuntu.com/automotive
  templates/automotive/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15102 copy update: update pricing nav
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#15104 chore: add the Renesas logo to iot page
  templates/internet-of-things/index.html
Labels: Review: Design needed, Review: QA +1, Review: Code +1

#15101 fix: replace developer pdf links that were 404ing
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#14941 pro checkout: update error messages
  static/js/src/advantage/error-handler.js
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/components/FormRow/FormRow.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/advantage/subscribe/checkout/utils/translateErrors.test.tsx
  static/js/src/advantage/subscribe/checkout/utils/translateErrors.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  static/js/src/advantage/tests/error-handler.test.js
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#15110 fix: /industrial form
  templates/industrial/form-data.json
  templates/industrial/index.html
  templates/shared/forms/interactive/embedded.html
Labels: Review: QA +1, Review: Code +1

#15117 fix: Fix icon placement
  static/sass/_pattern_cve.scss
  templates/security/cves/_cve-card.html
Labels: Review: QA +1, Review: Code +1

#15119 WD-22182 Copy Update - Ubuntu Desktop for Developers Link
  templates/desktop/developers.html
Labels: Review: QA +1, Review: Code +1

#15121 [WD-21655] Refresh /pro/dashboard
  templates/shared/contextual_footers/_ua_further_reading.html
Labels: Review: QA +1, Review: Code +1

#15115 [WD-17831] feat: Rebrand kernel/lifecycle page
  package.json
  static/sass/styles.scss
  templates/kernel/lifecycle.html
  templates/shared/_kernel-release-diagram.html
  templates/shared/_kernel-support-schedule.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15124 refactor: Remove unused /pricing/consulting and references
  static/files/sitemap.xml
  templates/kubernetes/compare.html
  templates/pricing/consulting.html
  templates/pricing/index.html
Labels: Review: QA +1, Review: Code +1

#15125 [WD-22279] chore: Replace all instances of /digital-signage with /smart-displays
  templates/core/index.html
  templates/core/stories.html
  templates/internet-of-things/form-data.json
  templates/internet-of-things/index.html
  templates/internet-of-things/smart-city/index.html
Labels: Review: QA +1, Review: Code +1

#15123 original form ID to enrichment form
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15071 update links on 24.04 of ubuntu.com download amd
  templates/download/amd/tab-1.html
  templates/download/amd/tab-2.html
  templates/download/amd/tab-3.html
Labels: Review: QA +1, Review: Code +1, Don't merge

#15130 WD-15705: add 24.10 exam to badge issue menu in dashboard
  static/js/src/advantage/credentials/dashboard/constants.ts
  webapp/shop/decorators.py
Labels: Review: QA +1, Review: Code +1

#15133 WD-21375 WD-20560: preserve form values on error for exam scheduling and check expired contracts
  templates/credentials/schedule.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1

#15134 feat: Migrate iot modals to form generator
  templates/core/features/form-data.json
  templates/core/features/full-disk-encryption.html
  templates/core/features/index.html
  templates/core/features/ota-updates.html
  templates/core/features/recovery.html
  templates/core/features/secure-boot.html
  templates/core/form-data.json
  templates/core/index.html
  templates/download/amd/form-data.json
  templates/download/amd/index.html
  templates/pricing/devices.html
  templates/pricing/form-data.json
  templates/shared/forms/interactive/internet-of-things.html
Labels: Review: QA +1, Review: Code +1

#14816 test: Implement Python coverage comparison check on PR
  .github/workflows/pr.yaml
  codecov.yml
Labels: Review: QA needed, Review: Code needed

#15128 [WD-21625] Refresh /training
  static/sass/styles.scss
  templates/training/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15150 WD-22437: use different form id for staging and production for marketo sign ups
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Commercial 🛒

#15152 redirects: add additional redirect to Focal eoss announcement
  redirects.yaml
Labels: Review: QA +1, Review: Code +1
