Repository canonical/ubuntu.com, pull requests merged in 2025-08, with the labels that each got.

#15408 feat: Add community redirects from Discourse redirects table
  redirects.yaml
Labels: Review: QA needed, Review: Code needed

#15406 Fix image loading attribute values
  templates/appliance/hardware.html
  templates/ceph/what-is-ceph.html
  templates/containers/shared/_container-portfolio-tabs.html
  templates/credentials/faq.html
  templates/desktop/developers.html
  templates/desktop/index.html
  templates/embedded/index.html
  templates/internet-of-things/gateways.html
  templates/internet-of-things/management.html
  templates/internet-of-things/smart-city/index.html
  templates/internet-of-things/smart-home/index.html
  templates/landscape/features.html
  templates/landscape/index.html
  templates/landscape/managed/index.html
  templates/pro/why-pro.html
  templates/security/livepatch.html
  templates/support/index.html
  templates/toolchains/java.html
  templates/toolchains/spring.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15412 fix: change GTM initialization from 'load' to 'DOMContentLoaded`
  templates/templates/_tag_manager.html
Labels: Review: QA needed, Review: Code +1

#15410 feat: added konf config for flat notices
  konf/site.yaml
Labels: Review: QA +1, Review: Code +1

#15419 fix: redirect to referrer for failed submissions
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15395 [Rebrand & Migrate] Ubuntu frame
  meganav.yaml
  navigation.yaml
  templates/frame/base_frame.html
  templates/frame/form-data.json
  templates/frame/index.html
  templates/internet-of-things/smart-displays.html
  webapp/handlers.py
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#15424 Vanilla framework bump and images fix
  .github/workflows/playwright.yaml
  .github/workflows/pr.yaml
  package.json
  templates/20-04/azure.html
  templates/20-04/index.html
  templates/base_index.html
  templates/ceph/what-is-ceph.html
  templates/dell/powerflex.html
  templates/robotics/ros-esm.html
  templates/security/assurances.html
  templates/security/osv.html
  templates/security/standards/pci-dss.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#15430 fix(pci-dss): add new whitepaper to /security/pci-dss [WD-24518]
  templates/security/standards/pci-dss.html
Labels: Review: QA +1, Review: Code +1

#15436 Update point release checksums
  releases.yaml
Labels: Review: QA needed, Review: Code +1, Review: PdM +1

#15438 fix: ubuntu/frame image & mir-server.io links
  redirects.yaml
  templates/frame/index.html
Labels: Review: QA +1, Review: Code +1

#15455 copy: update patching security vulnerabilities text in /security/fedramp
  templates/security/fedramp.html
Labels: Review: QA +1, Review: Code +1

#15429 chore: Remove /ai/what-is-kubeflow
  HACKING.md
  meganav.yaml
  navigation.yaml
  redirects.yaml
  templates/ai/data-science.html
  templates/ai/index.html
  templates/ai/mlflow.html
  templates/ai/mlops.html
  templates/ai/roadshow.html
  templates/ai/what-is-kubeflow.html
  templates/base_index.html
  templates/blog/product-cards/_kubeflow_deploy-tutorial.html
  templates/blog/product-cards/_kubeflow_what-is-kubeflow.html
  templates/managed/index.html
  templates/nvidia/index.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#15454 Credit card management updates deux
  navigation.yaml
  static/js/src/advantage/api/contracts.js
  static/js/src/advantage/manage-subscription.js
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
  static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx
  static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
  static/js/src/advantage/react/hooks/index.ts
  static/js/src/advantage/react/hooks/useHasPaymentMethod.test.tsx
  static/js/src/advantage/react/hooks/useHasPaymentMethod.ts
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
  static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
  static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
  static/js/src/ua-payment-methods.js
  static/sass/styles.scss
  templates/account/payment-methods/_confirm-remove-modal.html
  templates/account/payment-methods/index.html
  templates/advantage/index.html
  tests/shop/advantage/test_api.py
  webapp/app.py
  webapp/shop/api/ua_contracts/api.py
  webapp/shop/schemas.py
  webapp/shop/views.py
Labels: Review: QA +1, Review: Code +1, Portal 🛒

#15452 feat: Charm ubuntu.com and migrate to PS6
  .github/workflows/deploy.yaml
  .gitignore
  app.py
  charm/.gitignore
  charm/charmcraft.yaml
  charm/lib/charms/data_platform_libs/v0/data_interfaces.py
  charm/lib/charms/data_platform_libs/v0/s3.py
  charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py
  charm/lib/charms/loki_k8s/v1/loki_push_api.py
  charm/lib/charms/observability_libs/v0/juju_topology.py
  charm/lib/charms/openfga_k8s/v1/openfga.py
  charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  charm/lib/charms/redis_k8s/v0/redis.py
  charm/lib/charms/saml_integrator/v0/saml.py
  charm/lib/charms/smtp_integrator/v0/smtp.py
  charm/lib/charms/tempo_coordinator_k8s/v0/tracing.py
  charm/lib/charms/traefik_k8s/v2/ingress.py
  charm/pyproject.toml
  charm/requirements.txt
  charm/src/charm.py
  charm/tox.ini
  package.json
  rockcraft.yaml
  scripts/build-modules.sh
  webapp/app.py
  webapp/canonical_cla/views.py
  webapp/handlers.py
  webapp/login.py
  webapp/security/api.py
  webapp/shop/api/datastore.py
  webapp/shop/api/proctor360/api.py
  webapp/shop/cred/views.py
  webapp/shop/decorators.py
  webapp/shop/views.py
  webapp/views.py
Labels: Review: QA +1

#15467 Disable robots index on staging
  konf/site.yaml
  tests/test_routes.py
  webapp/handlers.py
Labels: Review: Code +1

#15468 chore: remove /blog/upcoming and add redirects
  navigation.yaml
  redirects.yaml
  templates/blog/index.html
  templates/blog/upcoming.html
  templates/templates/_navigation.html
Labels: Review: QA +1, Review: Code +1

#15402 Update codebase with pre-existing releases.yaml values
  templates/download/core/index.html
  templates/download/desktop/index.html
  templates/download/raspberry-pi/thank-you.html
  templates/download/risc-v/allwinner-nezha.html
  templates/download/shared/_verify-checksums.html
Labels: Review: QA +1, Review: Code +1

#15461 feat: update /confidential-computing modal
  templates/confidential-computing/base_confidential-computing.html
  templates/confidential-computing/form-data.json
  templates/confidential-computing/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15478 chore: remove unused test-links script
  package.json
Labels: Review: Code +1

#15497 Copy update for links on /download/qualcomm-iot
  templates/download/qualcomm-iot/tabs/evaluation-kit-tab.html
  templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
  templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html
Labels: Review: QA +1, Review: Code +1

#15499 fix: Flash a message on successfull form submissions to avoid false negatives
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15498 WD-25669: Copy Update /ceph/consulting
  templates/ceph/consulting.html
Labels: Review: QA +1, Review: Code +1

#15491 Migrate Azure bubble to use form generator
  templates/azure/base_azure.html
  templates/azure/confidential-computing/form-data.json
  templates/azure/confidential-computing/index.html
  templates/azure/form-data.json
  templates/azure/index.html
  templates/azure/pro.html
  templates/azure/sql.html
  templates/azure/support.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#15504 fix: Remove fallback message in failed form notification
  templates/templates/_notifications.html
Labels: Review: QA +1, Review: Code +1

#15506 copy-update: cmmc 2.0
  templates/security/cmmc/index.html
Labels: Review: QA +1, Review: Code +1

#15508 update free trial link
  templates/security/cmmc/index.html
Labels: Review: QA +1, Review: Code +1

#15503 Remove mlops mlflow and mlops workshop pages from ubuntu com ai
  HACKING.md
  meganav.yaml
  navigation.yaml
  redirects.yaml
  templates/ai/form-data.json
  templates/ai/mlflow.html
  templates/ai/mlops-workshop.html
  templates/ai/mlops.html
  templates/ai/shared/_learn-more.html
  templates/managed/index.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1

#15515 feat: Add missing /legal redirect
  redirects.yaml
Labels: Review: QA +1

#15512 [WD-21294] Pro shop - add referral links for sales
  static/js/src/advantage/subscribe/checkout/app.tsx
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
  static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
  static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
  static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
  static/js/src/advantage/subscribe/checkout/utils/types.ts
  static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
  webapp/shop/advantage/views.py
  webapp/shop/schemas.py
Labels: Review: QA +1, Review: Code +1, Portal 🛒

#15528 [WD-26065] feat: update summit/call-for-collaboration
  templates/summit/call-for-collaboration.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#15533 ci: add explicit env variable
  .github/workflows/sitemap.yaml
Labels: Review: QA +1, Review: Code +1 (with changes)

#15531 [WD-25995] fix links and refactor the page to use patterns
  templates/toolchains/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#15524 test: add marketo integration tests
  .env
  .github/workflows/pr.yaml
  konf/site.yaml
  templates/advantage/subscribe/form-data.json
  templates/aws/form-data.json
  templates/contact-us/form-data.json
  templates/containers/form-data.json
  templates/internet-of-things/form-data.json
  templates/security/form-data.json
  templates/toolchains/form-data.json
  tests/test_marketo.py
  tests/test_sitemap.py
  webapp/marketo.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#15532 refactor: improve image loading across multiple pages
  templates/ai/data-science.html
  templates/ai/index.html
  templates/aws/outposts.html
  templates/aws/pro.html
  templates/aws/thank-you.html
  templates/azure/ebook/index.html
  templates/azure/fips.html
  templates/azure/private-offer.html
  templates/azure/thank-you.html
  templates/blog/product-cards/_ai-solutions.html
  templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
  templates/blog/product-cards/_desktop_ubuntu-for-desktops.html
  templates/blog/product-cards/_financialservices-awerness.html
  templates/blog/product-cards/_raspberry-pi_2010-livestream.html
  templates/blog/product-cards/_server_scale-out-with-ubuntu-server.html
  templates/blog/product-cards/_wsl_ubuntu-on-windows.html
  templates/ceph/thank-you.html
  templates/cloud/cloud-computing.html
  templates/cloud/hybrid-cloud.html
Labels: Review: QA +1, Review: Code +1

#15552 feat: Add link to Pro free trial on homepage
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#15547 Feat: Added redirect for blog post
  redirects.yaml
Labels: Review: QA +1

#15539 use image template on /20years & /appliance
  templates/20years/index.html
  templates/advantage/_table.html
  templates/advantage/blender/index.html
  templates/appliance/shared/_base_appliance_index.html
Labels: Review: QA +1, Review: Code +1

#15555 fix(WD-26284): add maintenance window
  konf/site.yaml
  templates/credentials/base_cred.html
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Portal 🛒

#15554 feat: add new sections to Renesas tabs
  templates/download/renesas-iot/tab-1-renesas-rz-g2l.html
  templates/download/renesas-iot/tab-2-renesas-rz-g2lc.html
  templates/download/renesas-iot/tab-3-renesas-rz-g2ul.html
Labels: Review: QA +1, Review: Code +1
