Repository canonical/ubuntu.com, pull requests merged in 2025-02, with the labels that each got.

#14701 Remove case study and redirect to c.com
  meganav.yaml
  redirects.yaml
  templates/case-study/_case-study-card.html
  templates/case-study/base_case-study.html
  templates/case-study/esa.html
  templates/case-study/grundium-ubuntu-pro-for-devices.html
  templates/case-study/index.html
  templates/case-study/lucid-aws-fedramp-compliance-case-study.html
  templates/case-study/sbi-bits.html
  templates/case-study/ubuntu-pro-support-for-games-developer.html
  templates/macros/_macros-cta.jinja
  templates/macros/_macros-highlights.jinja
  templates/macros/_macros-image.jinja
  templates/macros/_macros-text-list.jinja
  templates/macros/_macros-text.jinja
  templates/shared/forms/interactive/case-study.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14690 feat(process_active_vulnerabilities): Create basic view func to process active vulnerabilities and pass them to '/security'
  requirements.txt
  templates/security/index.html
  templates/security/vulnerabilities.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14680 Copy update ceph page
  templates/ceph/index.html
Labels: Review: QA +1, Review: Code +1

#14704 Add redirects for static case studies
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#14706 fix: Add redirect for static case study
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#14687 feat: /security landing rebrand
  package.json
  templates/security/index.html
  templates/shared/_case-study-itstrategen.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14705 removing unused vwo
  templates/legal/data-privacy/index.html
  templates/templates/_vwo_smartcode.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#14709 fix: Remove stale navigation files
  templates/templates/navigation-community-h.html
  templates/templates/navigation-developer-h.html
  templates/templates/navigation-download-h.html
  templates/templates/navigation-enterprise-h.html
Labels: Review: QA +1, Review: Code +1

#14707 fix: Fix reported broken links
  redirects.yaml
  templates/containers/chiseled/index.html
  templates/kubernetes/charmed-k8s.html
  templates/support/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14712 Add header ID to /security/oval
  templates/security/oval.html
Labels: Review: QA +1, Review: Code +1

#14717 copy update: /gcp/fips
  templates/gcp/fips.html
Labels: Review: QA +1, Review: Code +1

#14719 copy update: remove AI consulting pricing
  templates/ai/consulting.html
Labels: Review: QA +1, Review: Code +1

#14720 fix: Add line wrapping to references links
  static/sass/_pattern_cve.scss
  templates/security/cves/cve.html
Labels: Review: QA +1, Review: Code +1

#14296 Canonical CLA integration
  .env
  build.js
  konf/site.yaml
  package.json
  requirements.txt
  static/js/src/canonical-cla/README.md
  static/js/src/canonical-cla/app.tsx
  static/js/src/canonical-cla/components/AgreementTypeForm/IndividualCla.tsx
  static/js/src/canonical-cla/components/AgreementTypeForm/OrganizationCla.tsx
  static/js/src/canonical-cla/components/AgreementTypeForm/index.tsx
  static/js/src/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
  static/js/src/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
  static/js/src/canonical-cla/components/ContactDetailsForm/index.tsx
  static/js/src/canonical-cla/components/GithubEmailSelector.tsx
  static/js/src/canonical-cla/components/LaunchpadEmailSelector.tsx
  static/js/src/canonical-cla/components/ScrollToHashElement.tsx
  static/js/src/canonical-cla/contexts/SignForm.tsx
  static/js/src/canonical-cla/hooks/usePersistedForm.tsx
  static/js/src/canonical-cla/pages/SignPage.tsx
  static/js/src/canonical-cla/pages/SuccessPage.tsx
  static/js/src/canonical-cla/utils/api.ts
  static/js/src/canonical-cla/utils/constants.ts
  static/sass/_pattern_icons.scss
  static/sass/styles.scss
  templates/legal/contributors/agreement.html
  tests/cla/__init__.py
  tests/cla/test_routes.py
  webapp/app.py
  webapp/canonical_cla/views.py
  webapp/handlers.py
  webapp/views.py
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#14729 fix: Update chiselled link
  templates/containers/index.html
Labels: Review: QA +1, Review: Code +1

#14727 add production missing API url for Canonical CLA
  konf/site.yaml
  static/js/src/canonical-cla/contexts/SignForm.tsx
Labels: Review: Code +1

#14728 feat: Rebrand /security/docker-images
  templates/security/docker-images.html
  templates/security/form-data.json
  templates/shared/forms/interactive/docker-images.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#14730 copy-update: update the phrasing used for the "adopting secure enterprise linux desktop" link
  templates/base_index.html
Labels: Review: Code +1

#13592 K8s bubble refresh
  redirects.yaml
  static/js/src/chart-data.js
  static/js/src/release-chart-manager.js
  static/sass/styles.scss
  templates/about/release-cycle.html
  templates/about/release_cycles/k8s-eol.html
  templates/about/release_cycles/k8s-lts.html
  templates/kubernetes/_get_ebook.html
  templates/kubernetes/_install-aws.html
  templates/kubernetes/_install-azure.html
  templates/kubernetes/_install-google.html
  templates/kubernetes/_install-linux.html
  templates/kubernetes/_install-lxd.html
  templates/kubernetes/_install-macos.html
  templates/kubernetes/_install-windows.html
  templates/kubernetes/_k8s-on-openstack.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/compare.html
  templates/kubernetes/contact-us.html
  templates/kubernetes/form-data.json
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/kubernetes-operations-survey.html
  templates/kubernetes/managed.html
  templates/kubernetes/partners.html
  templates/kubernetes/resources.html
  templates/kubernetes/thank-you.html
  templates/kubernetes/what-is-kubernetes.html
  templates/macros/_macros-resource.jinja
  templates/shared/_default-contact-us-form.html
  templates/shared/forms/interactive/kubernetes.html
Labels: Review: QA +1

#14735 K8s docs update landing page update with link to Canonical Kubernetes
  templates/kubernetes/docs/index.md
Labels: Review: QA +1, Review: Code +1

#14738 Update Ubuntu release chart
  static/js/src/chart-data.js
  templates/about/release_cycles/releases-table.html
Labels: Review: QA +1, Review: Code +1

#14734 feat: Apply rebranding for /security/oval
  templates/security/docker-images.html
  templates/security/oval.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#14732 feat: /security/cis redesign
  templates/security/cis.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14742 feat: Remove 'Charmed Kubernetes' from the /kubernetes secondary-nav
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#14713 feat: Use image template for logo on u.com
  requirements.txt
  templates/base_index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#14708 feat: Create a template for individual vulnerability pages
  build.js
  requirements.txt
  static/js/src/dynamic-toc.js
  static/js/src/side-navigation.js
  static/sass/styles.scss
  templates/security/vulnerabilities.html
  templates/security/vulnerabilities/index.html
  templates/security/vulnerabilities/vulnerabilities.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#14703 feat: remove directory page links
  templates/legal/contributors/faq.html
  templates/legal/contributors/index.html
Labels: Review: QA +1, Review: Code +1

#14731 [WD-16596] feat: Rebrand u.com/edge-computing page
  templates/edge-computing/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14741 feat: Add redirect for /docs/server to documentation.ubuntu.com/server
  redirects.yaml
  tests/test_routes.py
Labels: Review: QA +1, Review: Code +1

#14737 Fix failing link checker links
  templates/base_index.html
  templates/desktop/index.html
  templates/desktop/organisations.html
  templates/desktop/wsl/contact-us.html
  templates/desktop/wsl/index.html
  templates/download/index.html
  templates/download/shared/_everywhere.html
  templates/kubernetes/docs/index.md
  templates/wsl/base_wsl.html
  templates/wsl/index.html
Labels: Review: QA +1, Review: Code +1

#14749 fix(/contact-us/newsletter-opt-in): Add appropriate returnURL
  templates/contact-us/newsletter-opt-in.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#14747 Commented the pagination for CVEs
  static/sass/_pattern_cve.scss
  templates/security/cves/_pagination.html
Labels: Review: QA +1, Review: Code +1

#14751 chore: Remove /appliance/portfolio
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/appliance/about.html
  templates/appliance/index.html
  templates/appliance/portfolio.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14740 feat: Add multiple filters functionality on engage pages
  requirements.txt
  templates/engage/_article-card.html
  templates/engage/index.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14758 [WD-19429] remove /edge-computing page as it migrates to c.com
  meganav.yaml
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/cloud/cloud-computing.html
  templates/edge-computing/base_edge-computing.html
  templates/edge-computing/index.html
Labels: Review: QA +1, Review: Code +1

#14761 WD-19441 exclude non-english language tags from blogs
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14769 Update homepage WD-19404
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14755 build vex page
  static/files/sitemap.xml
  templates/security/vex.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14760 [WD-16576] Rebranded /appliance/about page
  templates/appliance/about.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14773 fix(ci): Update broken links to weekly
  .github/workflows/blog-links.yaml
Labels: Review: Code +1

#14757 [WD-16574] Rebranded /appliance
  templates/appliance/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14774 fix(ci): Perf checks weekly cron report
  .github/workflows/performance-check.yaml
Labels: Review: Code +1

#14775 Copy update on /pro/subscribe
  static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
  static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14777 chore: Remove /appliance/vm
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/appliance/about.html
  templates/appliance/hardware.html
  templates/appliance/vm.html
Labels: Review: QA +1, Review: Code +1

#14759 feat(new page): /security/platform-security
  templates/security/platform-security.html
Labels: Review: QA +1, Review: Code +1

#14778 quick fix for /kubernetes/charmed-k8s throwing 404 issue
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA +1

#14780 feat: Allow form generator to process nested index pages when passed to 'childrenPaths'
  templates/kubernetes/charmed-k8s/index.html
  templates/kubernetes/form-data.json
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14783 fix: Masters conferences videos
  templates/masters-conference/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#14772 azure/fips: update content
  templates/azure/fips.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14787 WD-19019 - fix: add checksums to verify desktop download
  templates/download/desktop/thank-you.html
Labels: Review: QA +1, Review: Code +1

#14764 feat: Build /kubernetes/documentation page
  meganav.yaml
  navigation.yaml
  templates/kubernetes/documentation.html
  templates/kubernetes/form-data.json
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14689 [WD-18697] feat: Add "other" option with textarea for radio and checkbox inputs in form generator on u.com
  static/js/src/dynamic-forms.js
  static/js/src/prepare-form-inputs.js
  templates/aws/form-data.json
  templates/shared/forms/form-fields.html
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1

#14786 fix reference error
  templates/templates/_getfeedback.html
Labels: Review: QA +1, Review: Code +1

#14767 feat: Rebrand /security/compliance-automation
  templates/macros/_macros-resource.jinja
  templates/security/compliance-automation.html
  templates/shared/_cra-banner.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14776 [WD-16583] Rebranded /appliance/hardware page
  templates/appliance/hardware.html
  templates/appliance/shared/_certified-appliances.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14785 fix: /iot/smart-home form payload submission
  templates/shared/forms/interactive/smart-city.html
Labels: Review: QA +1, Review: Code +1

#14788 feat: redirect server doc paths to docs site
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#14685 [WD-18634] Ref: use form generator on landscape bubble
  templates/landscape/form-data.json
  templates/landscape/index.html
  templates/landscape/managed/form-data.json
  templates/landscape/managed/index.html
  templates/shared/forms/form-fields.html
Labels: Review: QA +1, Review: Code +1

#14796 Copy update on /about/release-cycle#canonical-kubernetes-release-cycle
  static/js/src/chart-data.js
  templates/about/release_cycles/k8s-eol.html
  templates/about/release_cycles/k8s-lts.html
Labels: Review: QA +1, Review: Code +1

#14792 Fix dead links
  redirects.yaml
  templates/base_index.html
  templates/containers/chiseled/index.html
Labels: Review: QA +1, Review: Code +1

#14791 [WD-18696] Ref: use form generator on /iot bubble
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/form-data.json
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/management.html
  templates/internet-of-things/networking.html
  templates/internet-of-things/smart-city/form-data.json
  templates/internet-of-things/smart-city/index.html
  templates/internet-of-things/smart-displays.html
  templates/internet-of-things/smart-home/form-data.json
  templates/internet-of-things/smart-home/index.html
  templates/shared/forms/interactive/smart-city.html
  templates/shared/forms/interactive/smart-home.html
Labels: Review: QA +1, Review: Code +1

#14684 [WD-18591] Ref: Use form generator on "u.com/embedded"
  static/js/src/prepare-form-inputs.js
  templates/embedded/form-data.json
  templates/embedded/index.html
  templates/shared/forms/form-fields.html
Labels: Review: QA +1, Review: Code +1

#14766 WD-19462 Added turkish language support for engage forms
  templates/engage/index.html
  templates/engage/shared/_tr_engage_form.html
  templates/engage/shared/_tr_thank-you.html
Labels: Review: QA +1, Review: Code +1

#14799 Prevent undefined values from being sent for the address
  static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14803 fix: update link
  templates/containers/chiseled/index.html
Labels: Review: QA +1, Review: Code +1

#14794 feat: Add names and email as default active contact fields
  templates/aws/form-data.json
  templates/kubernetes/form-data.json
  templates/shared/forms/form-fields.html
Labels: Review: QA needed, Review: Code needed

#14698 feat: /security bubble redesign
  package.json
  static/files/sitemap.xml
  static/sass/styles.scss
  templates/macros/_macros-resource.jinja
  templates/security/cc.html
  templates/security/cis.html
  templates/security/compliance-automation.html
  templates/security/disa-stig.html
  templates/security/disclosure-policy.html
  templates/security/docker-images.html
  templates/security/esm.html
  templates/security/fips.html
  templates/security/form-data.json
  templates/security/index.html
  templates/security/livepatch.html
  templates/security/osv.html
  templates/security/oval.html
  templates/security/vex.html
  templates/shared/_case-study-itstrategen.html
  templates/shared/_cra-banner.html
  templates/shared/forms/interactive/docker-images.html
  yarn.lock
Labels: Review: QA +1

#14800 [K8s docs] 1.32 release
  templates/kubernetes/charmed-k8s/docs/1.31/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.32/components.md
  templates/kubernetes/charmed-k8s/docs/1.32/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.32/upgrading.md
  templates/kubernetes/charmed-k8s/docs/how-to-install.md
  templates/kubernetes/charmed-k8s/docs/index.md
  templates/kubernetes/charmed-k8s/docs/install-existing.md
  templates/kubernetes/charmed-k8s/docs/operations.md
  templates/kubernetes/charmed-k8s/docs/release-notes.md
  templates/kubernetes/charmed-k8s/docs/security.md
  templates/kubernetes/charmed-k8s/docs/supported-versions.md
  templates/kubernetes/charmed-k8s/docs/uninstall.md
Labels: Review: QA +1, Review: Code +1
