Repository canonical/ubuntu.com, pull requests merged in 2025-04, with the labels that each got.

#14921 [WD-20691] - COPYDOC: Update /desktop/organizations
  templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#14918 WD-20062: Add /20-04/azure page
  navigation.yaml
  templates/20-04/azure.html
  templates/20-04/base_20-04.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14899 Initializing percy testing
  .github/actions/percy-snapshot/action.yml
  .github/workflows/percy.yml
  .percy.yml
  package.json
  snapshots.js
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#14923 WD-20631 Typo correction
  templates/aws/support.html
Labels: Review: QA needed

#14927 [WD-20814] COPYDOC: Update security/disa-stig
  templates/security/disa-stig.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#14928 fix: Include 'country' field on forms where it was missing
  templates/kubernetes/form-data.json
  templates/shared/_default-contact-us-form.html
  templates/shared/forms/interactive/ai.html
  templates/shared/forms/interactive/managed-services.html
  templates/shared/forms/interactive/robotics_ros.html
Labels: Review: QA +1, Review: Code +1

#14930 fix: Set scrset for takeover images and switch to auto loading
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14919 Update release notes for Charmed Kubernetes 1.32+ck1
  templates/kubernetes/charmed-k8s/docs/1.28/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.29/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.30/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.31/release-notes.md
  templates/kubernetes/charmed-k8s/docs/1.32/release-notes.md
  templates/kubernetes/charmed-k8s/docs/release-notes.md
Labels: Review: Code +1

#14932 [WD-19307] fix typo, update datasheet url
  templates/robotics/ros-esm.html
Labels: Review: QA +1, Review: Code +1

#14922 WD-20901 - Update Pro logo on `desktop/organisations`
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#14920 WD-19392 - Feat: build /security/assurances page
  navigation.yaml
  static/files/sitemap.xml
  templates/security/assurances.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14931 add search to distibutor store
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14924 Update requirements.txt
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#14900 feat: Update sitemap with GH Actions
  .github/workflows/sitemap.yaml
  requirements.txt
  templates/sitemap_children.xml
  templates/sitemap_template.xml
  templates/sitemap_tree.xml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#14935 Build page on /20-04/aws
  navigation.yaml
  templates/20-04/aws.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14934 adjust referenced technologies for ubuntu server ARM
  templates/download/server/arm.html
Labels: Review: QA +1, Review: Code +1

#14947 feat: Prevent unexpected sites from being parsed
  .github/workflows/pr.yaml
  .github/workflows/sitemap.yaml
  .gitignore
  requirements.txt
  templates/sitemap_children.xml
  templates/sitemap_index.xml
  templates/sitemap_tree.xml
  templates/templates/_contextual_footer.html
  templates/templates/docs/shared/_docs.html
  templates/templates/docs/shared/_search-results.html
  templates/templates/meta.html
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14770 chore: Remove robotics docs and redirect to readthedocs
  .github/workflows/robotics-docs-links.yaml
  ARCHITECTURE.md
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/robotics/docs/document.html
  templates/robotics/docs/search-results.html
  templates/robotics/index.html
  templates/sitemap_index.xml
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14952 Feat: Percy workflow for baseline build
  .github/workflows/percy-baseline.yaml
Labels: Review: QA needed, Review: Code needed

#14926 new pro/free-trial page
  navigation.yaml
  templates/pro/free-trial.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14954 Copy update on /download/iot/intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: QA +1, Review: QA needed, Review: Code needed, Review: Code +1

#14915 [K8s docs] Update version info on upgrading doc
  templates/kubernetes/charmed-k8s/docs/upgrading.md
Labels: Review: QA needed, Review: Code needed

#14958 copy update: [WD-20930] add copy for canonical ceph release cycle tab
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#14965 [WD-20898] Copy update /download/server/power
  templates/download/server/power.html
Labels: Review: QA +1, Review: Code +1

#14942 [WD-21032] Ubuntu 25.04 copy update - about/release-cycle
  static/js/src/chart-data.js
  templates/about/release_cycles/releases-table.html
  templates/shared/_kernel-release-diagram.html
Labels: Review: QA +1, Review: Code +1

#14967 Apply raspberry pi copy updates
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA needed, Review: Code needed

#14969 Revert "Apply raspberry pi copy updates"
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#14970 Apply copy update for /download/raspberry-pi
  releases.yaml
  templates/download/raspberry-pi/index.html
Labels: Review: QA +1, Review: Code +1

#14948 feat: /containers page refresh
  templates/containers/index.html
  templates/containers/shared/_container-portfolio-tabs.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14936 feat: Add a 'deprecated' warning notification to /landscape/docs
  templates/landscape/docs/document.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#14959 feat: Build /containers/container-build-service page
  navigation.yaml
  templates/containers/chiseled/index.html
  templates/containers/container-build-service.html
  templates/containers/form-data.json
  templates/containers/index.html
  templates/containers/what-are-containers.html
  templates/shared/forms/interactive/containers.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14961 copy update: links to marketplace listings
  templates/20-04/aws.html
Labels: Review: QA +1, Review: Code +1

#14963 Add 20-04/gcp page WD-20906
  navigation.yaml
  templates/20-04/gcp.html
Labels: Review: QA +1, Review: Design +1, Review: UX needed, Review: Code +1 (with changes)

#14973 feat: update ubuntu server cli cheatsheet
  templates/download/server/thank-you.html
  templates/download/shared/_server_weekly_news.html
Labels: Review: QA +1, Review: Code +1

#14925 copy update: [WD-20895] update download/server page
  releases.yaml
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Code +1

#14971 chore: Bump form-generator to 2.0.0
  requirements.txt
  templates/aws/index.html
  templates/aws/outposts.html
  templates/aws/pro.html
  templates/aws/support.html
  templates/download/renesas/index.html
  templates/embedded/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/form-data.json
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/management.html
  templates/internet-of-things/networking.html
  templates/internet-of-things/smart-city/form-data.json
  templates/internet-of-things/smart-city/index.html
  templates/internet-of-things/smart-displays.html
  templates/internet-of-things/smart-home/form-data.json
  templates/internet-of-things/smart-home/index.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/compare.html
  templates/kubernetes/documentation.html
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/resources.html
  templates/kubernetes/what-is-kubernetes.html
  templates/landscape/compare.html
  templates/landscape/features.html
  templates/landscape/form-data.json
  templates/landscape/index.html
  templates/landscape/managed/form-data.json
  templates/landscape/managed/index.html
  templates/security/form-data.json
  templates/security/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14977 feature: Refresh /containers
  navigation.yaml
  templates/containers/chiseled/index.html
  templates/containers/container-build-service.html
  templates/containers/form-data.json
  templates/containers/index.html
  templates/containers/shared/_container-portfolio-tabs.html
  templates/containers/what-are-containers.html
  templates/shared/forms/interactive/containers.html
Labels: Review: QA +1

#14960 feat: ceph pricing calculator
  package.json
  templates/ceph/pricing-calculator.html
  yarn.lock
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14956 WD-21345: usn.html: add FIPS and Realtime pockets
  templates/security/notices/usn.html
Labels: Review: QA +1, Review: Code +1

#14984 copy update: /desktop/wsl download links and hero image
  templates/desktop/wsl/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1, Review: PdM +1

#14989 chore: Fix broken links
  templates/robotics/index.html
Labels: Review: QA +1, Review: Code +1

#14982 feat: Use sitemap templates imported from parser module
  .github/workflows/sitemap.yaml
  requirements.txt
  templates/sitemap_children.xml
  templates/sitemap_template.xml
  templates/sitemap_tree.xml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14995 Dev - Refresh /download/desktop to show ARM build
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14997 Update /desktop/flavours for 25.04 release
  templates/desktop/flavours.html
Labels: Review: QA +1, Review: Code +1

#15003 releases: add plucky checksums
  releases.yaml
Labels: Review: QA +1, Review: Code +1

#15005 Final fixes
  meganav.yaml
  templates/download/desktop/index.html
  templates/download/raspberry-pi/index.html
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Code needed

#15006 Wd 20747: Add /download/renesas-iot page
  meganav.yaml
  static/files/sitemap.xml
  templates/download/contact-us.html
  templates/download/renesas-iot/index.html
  templates/download/renesas-iot/tab-1-renesas-rz-g2l.html
  templates/download/renesas/form-data.json
  templates/download/renesas/index.html
  templates/download/thank-you.html
  templates/shared/forms/interactive/renesas-iot.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15011 Fix download link
  templates/download/desktop/index.html
Labels: Review: QA +1, Review: Code +1

#15007 redirects: fix broken link in Focal eoss mailing list announcements
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#15001 test: Implement testing for sitemaps
  tests/test_sitemap.py
Labels: Review: QA +1, Review: Code +1

#14986 feat: Add 'aria-controls' attribute to the button element for generated forms
  static/js/src/dynamic-forms.js
  static/sass/_pattern_contact-modal.scss
  templates/16-04/azure.html
  templates/aws/form-data.json
  templates/aws/index.html
  templates/aws/outposts.html
  templates/aws/pro.html
  templates/aws/support.html
  templates/embedded/form-data.json
  templates/embedded/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/digital-signage.html
  templates/internet-of-things/form-data.json
  templates/internet-of-things/gateways.html
  templates/internet-of-things/index.html
  templates/internet-of-things/management.html
  templates/internet-of-things/networking.html
  templates/internet-of-things/smart-city/form-data.json
  templates/internet-of-things/smart-city/index.html
  templates/internet-of-things/smart-displays.html
  templates/internet-of-things/smart-home/form-data.json
  templates/internet-of-things/smart-home/index.html
  templates/kubernetes/charmed-k8s.html
  templates/kubernetes/compare.html
  templates/kubernetes/documentation.html
  templates/kubernetes/form-data.json
  templates/kubernetes/index.html
  templates/kubernetes/install.html
  templates/kubernetes/managed.html
  templates/kubernetes/resources.html
  templates/kubernetes/what-is-kubernetes.html
  templates/landscape/form-data.json
  templates/landscape/index.html
  templates/landscape/managed/form-data.json
  templates/landscape/managed/index.html
  templates/security/fips.html
  templates/security/form-data.json
  templates/security/index.html
  templates/shared/forms/form-template.html
Labels: Review: QA +1, Review: Code +1

#15018 [WD-21541] fix: Kubernetes LTS release chart showing incorrect color order
  static/js/src/chart-data.js
Labels: Review: QA +1, Review: Code +1

#15015 copy update firefighting-support
  templates/managed/firefighting-support.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#15019 remove unused initialization script from tag manager
  templates/templates/_tag_manager.html
Labels: Review: Code +1

#14826 feature branch: Sitemaps parser
  .dockerignore
  .github/workflows/pr.yaml
  .github/workflows/sitemap.yaml
  .gitignore
  Dockerfile
  requirements.txt
  templates/sitemap_index.xml
  templates/templates/_contextual_footer.html
  templates/templates/docs/shared/_docs.html
  templates/templates/docs/shared/_search-results.html
  templates/templates/meta.html
  tests/test_sitemap.py
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Don't merge

#15025 Copy update on /download/iot/intel-iot
  templates/download/iot/intel-iot.html
Labels: Review: QA needed, Review: Code needed

#14945 WD-14488 proctor360 integration
  konf/site.yaml
  static/js/src/advantage/credentials/dashboard/components/Sidebar/Sidebar.tsx
  templates/credentials/schedule-confirm.html
  templates/credentials/schedule.html
  webapp/shop/api/proctor360/api.py
  webapp/shop/cred/views.py
  webapp/shop/decorators.py
Labels: Review: QA needed, Review: Code needed, Commercial 🛒

#15020 chore: update k8s LTS support timelines
  static/js/src/chart-data.js
  static/js/src/release-chart-manager.js
  static/js/src/release-chart-old.js
Labels: Review: QA +1, Review: Code +1

#15021 feat: Link and copy update for pro/free-trial
  templates/pro/free-trial.html
Labels: Review: QA +1, Review: Code +1

#15032 Update live-links.yaml: make the name more specific
  .github/workflows/live-links.yaml
Labels: Review: Code +1

#14992 Set up core docs redirect and remove related stale code
  .github/workflows/core-docs-links.yaml
  .github/workflows/performance-check.yaml
  ARCHITECTURE.md
  konf/site.yaml
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/core/docs/document.html
  templates/core/docs/search-results.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#15037 WD-20477 - 20.04 EOL banner across static pages
  templates/core/index.html
  templates/core/services/index.html
  templates/embedded/index.html
  templates/internet-of-things/appstore.html
  templates/internet-of-things/index.html
  templates/internet-of-things/smart-displays.html
  templates/robotics/index.html
  templates/robotics/what-is-ros.html
  templates/shared/_20-04-eol-banner.html
Labels: Review: QA +1, Review: Code +1

#15044 [WD-21500] copy update /download/core
  templates/download/core/index.html
Labels: Review: QA +1, Review: Code +1

#15038 [WD-20510] fix: incorrect padding on search and close icon on medium screens
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1

#15026 feat: redesigned the confidential computing page
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14884 Fix: update deprecated link to SRU documentation
  templates/certified/index.html
Labels: Review: Code +1

#15014 copy: refresh /security/compliance-automation design. WD-19955
  meganav.yaml
  navigation.yaml
  redirects.yaml
  static/files/sitemap.xml
  templates/advantage/_table.html
  templates/base_index.html
  templates/cloud/hybrid-cloud.html
  templates/cloud/private-cloud.html
  templates/desktop/developers.html
  templates/download/cloud/index.html
  templates/download/shared/_secure-enterprise-management.html
  templates/financial-services/index.html
  templates/gov/index.html
  templates/openstack/consulting.html
  templates/openstack/support.html
  templates/pricing/desktop.html
  templates/pro/index.html
  templates/pro/why-pro.html
  templates/robotics/index.html
  templates/security/assurances.html
  templates/security/cis.html
  templates/security/compliance-automation.html
  templates/security/fedramp.html
  templates/security/form-data.json
  templates/security/index.html
  templates/security/security-standards.html
  templates/shared/_download-ubuntu-thank-you-pro-section.html
  templates/shared/_pro_strip.html
  templates/shared/_ubuntu-advantage-service-description-ja.html
  templates/shared/_ubuntu-pro-description.html
  templates/shared/pricing/_ua-for-infrastructure.html
  templates/telco/openran.html
  webapp/app.py
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#15031 feat: Refresh /security
  templates/security/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15045 copy: change FIPS notification link for /security/security-standards
  templates/security/security-standards.html
Labels: Review: QA +1, Review: Code +1

#15016 WD-21518: check if user is banned on your-exams page
  templates/credentials/your-exams.html
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#15054 [WD-21391] fix: scrolling issues when closing contact modal and add aria-expanded label to contact button
  static/js/src/dynamic-forms.js
Labels: Review: QA +1, Review: Code +1

#15058 Center search toggle icon in navigation dropdown
  static/sass/_pattern_navigation.scss
Labels: Review: QA +1, Review: Code +1, Bug 🐛

#15049 Update google clud logo in confidential computing WD-21719
  templates/confidential-computing/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#15053 feat: update core section links
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#15056 update ubuntu pro description pdf
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#15052 WD-21511 WD-21512: show correct exam names when scheduling
  templates/credentials/schedule.html
  webapp/shop/cred/constants.py
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#15061 WD-21716 - Copy Update - Add missing legacy date for kernel releases
  static/js/src/chart-data.js
  static/js/src/release-chart-old.js
  templates/shared/_kernel-release-diagram.html
Labels: Review: QA +1, Review: Code +1

#15066 Separate USN endpoint services
  konf/site.yaml
Labels: Review: Code +1

#15033 Update Qualcomm tabs content for 24.04 public beta
  templates/download/qualcomm-iot/index.html
  templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
  templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html
Labels: Review: QA +1, Review: Code +1, Review: UX +1
