Repository canonical/ubuntu.com, pull requests merged in 2025-03, with the labels that each got.

#14805 update CLA account choice message
  static/js/src/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
Labels: Review: Code +1

#14815 copy update security - FedRAMP
  templates/security/fedramp.html
Labels: Review: QA +1, Review: Code +1

#14802 copy update: authd section in desktop/organisations
  templates/desktop/organisations.html
Labels: Review: QA +1, Review: Code +1

#14817 feat: update openstack release cycle tab
  templates/about/release-cycle.html
Labels: Review: QA +1, Review: Code +1

#14808 fix(a11y): Refactor the HTML validator issues on the base templates
  templates/download/desktop/thank-you.html
  templates/templates/_getfeedback.html
  templates/templates/_navigation.html
  templates/templates/_notifications.html
  templates/templates/_tag_manager.html
  templates/templates/base.html
Labels: Review: QA +1, Review: Code +1

#14820 refactor: remove unused code from release cycle page
  static/js/src/release-chart-manager.js
  templates/about/release_cycles/microstack-eol.html
  templates/about/release_cycles/openstack-eol.html
Labels: Review: Code +1

#14789 Implement a specific cache policy for vulnerabilities & use latest discourse module branch
  requirements.txt
  templates/security/vulnerabilities/vulnerability-detailed.html
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14829 chore: Remove stale link from sitemap index
  templates/sitemap_index.xml
Labels: Review: QA +1, Review: Code +1

#14827 feat: Update requirements to import pypi package
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14833 feat: Add new resource type filter on /engage overview
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14834 WD-19956: update security copy
  templates/base_index.html
Labels: Review: QA needed, Review: Code needed

#14756 feat: refresh /pricing/pro
  templates/pricing/pro.html
Labels: Review: QA needed, Review: Design +1, Review: Code needed, Review: UX +1

#14835 chore: Bump vanilla version
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#14810 Refresh robotics/ros-esm WD-19398
  navigation.yaml
  package.json
  templates/robotics/base_robotics.html
  templates/robotics/ros-esm.html
  templates/robotics/shared/_learn-more-about-robotics.html
  templates/shared/contextual_footers/_further_reading.html
  templates/shared/contextual_footers/_robotics_further_reading.html
  templates/shared/contextual_footers/_robotics_newsletter_signup.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14839 fix(performance): Add API token for the perf-checks CI
  .github/workflows/performance-check.yaml
Labels: Review: Code +1

#14836 [WD-8780] fix: docs link scroll margin for same page links
  templates/templates/docs/shared/_docs.html
Labels: Review: QA +1, Review: Code +1

#14849 chore: Use image module on ubuntu home page
  templates/base_index.html
Labels: Review: QA +1, Review: Code +1

#14853 [WD-19716] fix: replace broken link
  templates/server/index.html
Labels: Review: QA +1, Review: Code +1

#14855 chore: fix broken links
  templates/containers/chiseled/index.html
Labels: Review: QA +1, Review: Code +1

#14848 [WD-19941] Exclude new(static) case-studies from engage page
  requirements.txt
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14842 feat: Build sitemaps template with directory parser
  .dockerignore
  Dockerfile
  requirements.txt
  static/files/sitemap_tree.xml
  templates/sitemap_children.xml
  templates/sitemap_template.xml
  webapp/app.py
  webapp/views.py
Labels: Review: QA +1, Review: Code +1

#14843 feat: Align fields with marketo for form 1251
  templates/openstack/contact-us.html
  templates/shared/_openstack_contact_us.html
  templates/shared/forms/_industry.html
  templates/training/contact-us.html
Labels: Review: QA +1, Review: Code +1

#14806 security web: add esm-infra-legacy pockets WD-17330 WD-19534
  templates/security/notices/usn.html
  webapp/security/views.py
Labels: Review: QA +1, Review: Code +1

#14856 [WD-16587] rebrand /appliance/adguard and other similar pages
  templates/appliance/adguard/index.md
  templates/appliance/lxd/index.md
  templates/appliance/mosquitto/index.md
  templates/appliance/nextcloud/index.md
  templates/appliance/openhab/index.md
  templates/appliance/plex/index.md
  templates/appliance/shared/_base_appliance_index.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)

#14846 feat: Remove '/appliance/tutorials' and set up redirect to '/core/docs/build-an-image'
  redirects.yaml
  templates/appliance/tutorials.html
Labels: Review: QA +1, Review: Code +1

#14861 chore: Refactor sitemap templates
  static/files/sitemap_tree.xml
  templates/sitemap_children.xml
  templates/sitemap_template.xml
Labels: Review: QA +1, Review: Code +1

#14865 fix: Swap frame and core images
  templates/internet-of-things/smart-displays.html
Labels: Review: QA +1, Review: Code +1

#14867 fix: Update chiseled doc link
  templates/containers/chiseled/index.html
Labels: Review: QA +1, Review: Code +1

#14868 feat: add more product cards
  templates/blog/product-cards.html
  templates/blog/product-cards/_IoT_appstore.html
  templates/blog/product-cards/_ai-solutions.html
  templates/blog/product-cards/_ceph.html
  templates/blog/product-cards/_ceph_guide-sds-for-ent.html
  templates/blog/product-cards/_ceph_optimise-storage-costs.html
  templates/blog/product-cards/_ceph_what-is-ceph.html
  templates/blog/product-cards/_charmed_mongodb.html
  templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
  templates/blog/product-cards/_desktop_ubuntu-for-desktops.html
  templates/blog/product-cards/_docker-security.html
  templates/blog/product-cards/_financialservices-awerness.html
  templates/blog/product-cards/_hybrid_cloud.html
  templates/blog/product-cards/_infrastructure_maximise-your-cloud-infrastructure.html
  templates/blog/product-cards/_infrastructure_optimised-costs-across-any-cloud.html
  templates/blog/product-cards/_kubeflow_deploy-tutorial.html
  templates/blog/product-cards/_kubeflow_jaas-bundle.html
  templates/blog/product-cards/_kubeflow_what-is-kubeflow.html
  templates/blog/product-cards/_kubernetes.html
  templates/blog/product-cards/_kubernetes_what-is-kubernetes.html
  templates/blog/product-cards/_lxd.html
  templates/blog/product-cards/_microcloud.html
  templates/blog/product-cards/_multi_cloud.html
  templates/blog/product-cards/_opensearch.html
  templates/blog/product-cards/_openstack.html
  templates/blog/product-cards/_private_cloud.html
  templates/blog/product-cards/_public_cloud.html
  templates/blog/product-cards/_raspberry-pi_2010-livestream.html
  templates/blog/product-cards/_server_scale-out-with-ubuntu-server.html.html
  templates/blog/product-cards/_services.html
  templates/blog/product-cards/_telco.html
  templates/blog/product-cards/_ubuntu_18.04_end_of_support.html
  templates/blog/product-cards/_wsl_ubuntu-on-windows.html
Labels: Review: QA +1, Review: Code +1

#14871 fix: Update broken link for chiseled docs
  templates/containers/chiseled/index.html
Labels: Review: QA +1

#14869 Update distributor offer table columns
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.test.tsx
  static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
  static/sass/_pattern_distributor.scss
Labels: Review: QA +1, Review: Code +1, Commercial 🛒

#14874 feat: Use form-generator Pypi package
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#14876 Add custom download URL for NVIDIA Jetson platforms
  webapp/certified/helpers.py
Labels: Review: QA +1, Review: Code +1

#14881 fix: update qualcomm links
  templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
  templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html
Labels: Review: QA +1, Review: Code +1

#14866 chore: Use git diff to get changed files
  .github/workflows/pr.yaml
Labels: Review: QA +1, Review: Code +1

#14722 chore: Update linkchecker to report 404 errors only
  .github/workflows/live-links.yaml
Labels: Review: QA +1, Review: Code +1

#14885 fix: Update AI datasheet link
  templates/ai/index.html
Labels: Review: QA +1

#14888 fix: Remove action trigger from PR
  .github/workflows/live-links.yaml
Labels: Review: Code needed

#14883 Add markdown support for certification notes and escape raw-html content
  requirements.txt
  templates/certified/model-details.html
  tests/cassettes/TestCertification.test_note_rendering.yaml
  tests/test_certification.py
  webapp/certified/helpers.py
  webapp/handlers.py
Labels: Review: QA +1, Review: Code +1

#14889 fix: Remove unexpected block
  templates/legal/data-privacy/enquiry.html
Labels: Review: Code +1

#14893 Update text on Pro pricing page
  templates/pricing/pro.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Commercial 🛒

#14891 Update solutions section of footer.
  templates/templates/footer.html
Labels: Review: QA +1, Review: Code +1

#14896 fix: Use standard jinja formatting on /training and fix lint-jinja
  .github/workflows/pr.yaml
  templates/training/index.html
Labels: Review: QA +1, Review: Code +1

#14886 WD-17875 Dev create /summit/call-for-collaboration
  meganav.yaml
  navigation.yaml
  static/sass/styles.scss
  templates/summit/_base_summit.html
  templates/summit/call-for-collaboration.html
  templates/summit/index.html
  templates/summit/shared/_latest-blogs_summit.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14895 Fixes /kubernetes/charmed-k8 returning a 404
  templates/kubernetes/charmed-k8s.html
Labels: Review: QA needed, Review: Code needed

#14894 chore: Add git diff-filter
  .github/workflows/pr.yaml
Labels: Review: Code +1

#14898 WD-20581 fix: contextual footer further reading section
  templates/legal/_base_legal_markdown.html
  templates/shared/contextual_footers/_further_reading.html
Labels: Review: QA +1, Review: Code +1

#14906 feat: Add preview image to /20years
  templates/20years/index.html
Labels: Review: QA +1, Review: Code +1

#14905 fix: Adjust spacing above footer headings
  templates/templates/footer.html
Labels: Review: QA +1, Review: Code +1

#14909 fix wrong path on retry for Trueability API
  webapp/shop/api/trueability/api.py
Labels: Review: QA needed, Review: Code needed, 🧊 Credentials, Commercial 🛒

#14901 Feat: Redesign /summit page and create /summit/call-for-collaboration
  meganav.yaml
  navigation.yaml
  static/sass/styles.scss
  templates/summit/_base_summit.html
  templates/summit/call-for-collaboration.html
  templates/summit/index.html
  templates/summit/shared/_latest-blogs_summit.html
Labels: Review: QA +1

#14903 Wd 20463 migrate app 3 trueablity com to app trueability com
  konf/site.yaml
Labels: Review: QA +1, Review: Code +1, 🧊 Credentials, Commercial 🛒

#14910 copy update: https://ubuntu.com/openstack
  templates/openstack/index.html
Labels: Review: Code +1

#14908 fix: Make sure button is reset to original state even when page is loaded from cache
  static/js/src/static-forms.js
Labels: Review: QA +1, Review: Code +1

#14913 Update partner logos on /pro/devices
  templates/certified/shared/_partners.html
  templates/pro/devices.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#14897 feat: Apply intel-nuc templates rebrand
  templates/appliance/_base-appliance.html
  templates/appliance/openhab/_next-steps.html
  templates/appliance/shared/_how-to-install.html
  templates/appliance/shared/_install_instructions_intel-nuc.html
  templates/appliance/shared/_intel-nuc.html
  templates/appliance/shared/_steps_install_openssh_windows.html
  templates/appliance/shared/_steps_nuc_first_boot.html
  templates/appliance/shared/_steps_nuc_flash_usb.html
  templates/appliance/shared/_steps_nuc_install_appliance.html
  templates/appliance/shared/_steps_nuc_thats-it.html
  templates/appliance/shared/_steps_ssh-keys_ubuntu.html
  templates/appliance/shared/_verify-checksums-pc.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#14914 feat: Apply design updates to rasp-pi appliance templates and remaining appliance footers
  templates/appliance/adguard/_next-steps.html
  templates/appliance/lxd/_next-steps.html
  templates/appliance/mosquitto/_next-steps.html
  templates/appliance/nextcloud/_next-steps.html
  templates/appliance/openhab/_next-steps.html
  templates/appliance/plex/_next-steps.html
  templates/appliance/shared/_appliance-os-tabs.html
  templates/appliance/shared/_install_instructions_raspberry-pi.html
  templates/appliance/shared/_raspberry-pi.html
  templates/appliance/shared/_steps_pi_imager_ubuntu.html
  templates/appliance/shared/_steps_pi_imager_windows.html
  templates/appliance/shared/_steps_pi_prep-sd-card.html
  templates/appliance/shared/_steps_pi_thats-it.html
  templates/appliance/shared/_what_you_will_need_pi.html
Labels: Review: QA needed, Review: Design +1, Review: Code needed, Review: UX +1

#14902 fix: Handle hitting '/download/server/thank-you' without a defined version
  templates/download/desktop/thank-you.html
  templates/download/raspberry-pi/thank-you.html
  templates/download/server/thank-you.html
Labels: Review: QA needed, Review: Code +1, Review: UX +1

#14917 feat: update remaining vm and rasp-2 appliance templates
  templates/appliance/_base-appliance.html
  templates/appliance/shared/_install_instructions_vm_macos.html
  templates/appliance/shared/_install_instructions_vm_ubuntu.html
  templates/appliance/shared/_install_instructions_vm_windows.html
  templates/appliance/shared/_intel-nuc.html
  templates/appliance/shared/_raspberry-pi2.html
  templates/appliance/shared/_steps-multipass-find-ip-macos.html
  templates/appliance/shared/_steps-multipass-find-ip-windows.html
  templates/appliance/shared/_steps_multipass_macos.html
  templates/appliance/shared/_steps_pi_imager_macos.html
  templates/appliance/shared/_steps_vm_intro.html
  templates/appliance/shared/_steps_vm_thats-it.html
  templates/appliance/shared/_verify-checksums.html
  templates/appliance/shared/_vm.html
  templates/appliance/shared/_what_you_will_need_pi2.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1
