Repository canonical/ubuntu.com, pull requests merged in 2025-10, with the labels that each got.

#15692 chore: remove broken link
  templates/openstack/index.html
Labels: Review: Code +1

#15694 chore(qualcomm-iot): adapted two links on the Rubik Pi3 tab
  templates/download/qualcomm-iot/tabs/development-board-tab.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#15693 copy: toolchains/java wording on ubuntu pro and support period
  templates/toolchains/java.html
Labels: Review: QA +1, Review: Code +1

#15687 refactor: Migrate /download/contact-us forms to form generator
  templates/download/contact-us.html
  templates/download/form-data.json
  tests/test_marketo.py
Labels: Review: QA +1, Review: Code +1

#15701 Copy update to /security/esm diagram legend
  static/js/src/release-chart-old.js
Labels: Review: QA +1, Review: Code +1

#15702 chore: add checks for blog author
  templates/blog/article.html
  templates/blog/author.html
Labels: Review: QA +1, Review: Code +1

#15703 fix: (WD-27722) Update u.com/download/server/thank-you-s390x for 25.10
  templates/download/server/thank-you-s390x.html
Labels: Review: QA +1, Review: Code +1, Copy update 📝

#15676 fix: robotics page image container class
  templates/robotics/index.html
Labels: Review: QA +1, Review: Code +1

#15679 copy: update ubuntu.com/core
  templates/core/index.html
  templates/core/tabs.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1, Review: UX +1

#15707 feat: Update Questing Quokka mascot image with black background version
  templates/download/server/manual.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#15710 WD-29304 (remove "cloud native operations report" from meganav)
  navigation.yaml
Labels: Review: QA +1, Review: Code +1

#15715 chore: Add release support tag to usn table
  templates/security/notices/usn.html
Labels: Review: QA +1, Review: Code +1

#15705 fix(WD-28107): redirect to P360 session when clicking "Take Exam" button
  webapp/shop/cred/views.py
Labels: Review: QA +1, Review: Code +1
